(()=>{
 'use strict';const toggle=document.getElementById('oneNotificationsToggle'),panel=document.getElementById('oneNotifications');if(!toggle||!panel)return;
 const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;},button=(text,fn)=>{const b=make('button',text);b.type='button';b.onclick=fn;return b;};
 const head=panel.firstElementChild;while(head.nextSibling)head.nextSibling.remove();head.querySelector('h2,h3')?.replaceChildren(document.createTextNode('Notifications'));const subtitle=make('p','Toute ta vie ONE, au même endroit.','hub-muted'),badge=make('span',undefined,'hub-notification-badge');badge.id='oneUnreadBadge';badge.hidden=true;toggle.append(badge);
 const nav=make('nav',undefined,'hub-notification-tabs');nav.setAttribute('aria-label','Filtrer les notifications');let filter='all';const filters=[['all','Toutes'],['friends','Amis'],['messages','Messages'],['creators','Créateurs']];for(const [key,label]of filters){const b=button(label,()=>{filter=key;draw();});b.dataset.filter=key;nav.append(b);}
 const actions=make('div',undefined,'hub-notification-tools'),refresh=button('↻ Actualiser',load),read=button('Tout lire',readAll),settings=button('⚙ Alertes téléphone',()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');window.ONEAccountUI?.show('alerts');window.ONEPush?.refresh();});actions.append(refresh,read,settings);
 const status=make('p',undefined,'hub-notification-status');status.setAttribute('role','status');const list=make('div');list.id='oneNotificationsList';panel.append(subtitle,nav,actions,status,list);
 let epoch=0,through=0,items=[],busy=false;const API='https://one-comments-api.moulinanthony60.workers.dev';
 async function api(path,method='GET'){window.ONEAPIBackoff?.check(method);const token=window.oneAccountToken?.();const res=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000)});const d=await res.json().catch(()=>({}));window.ONEAPIBackoff?.note(res,d);if(token!==window.oneAccountToken?.())throw Error('Le compte a changé.');if(!res.ok||!d.ok)throw Error(d.error||'Notifications indisponibles.');return d;}
 const category=n=>n.kind.startsWith('creator_')?'creators':['message','group_message','reply'].includes(n.kind)?'messages':'friends';
 const ago=at=>{const min=Math.max(0,Math.floor((Date.now()-at)/60000));return min<1?'À l’instant':min<60?'Il y a '+min+' min':min<1440?'Il y a '+Math.floor(min/60)+' h':new Date(at).toLocaleDateString('fr-FR',{day:'numeric',month:'short'});};
 function title(n){return ({friend:n.author+' souhaite devenir ton ami',party:n.author+' t’invite dans son salon',message:n.author+' t’a écrit',group_invite:n.author+' t’invite dans un groupe',group_saved:'Votre salon est enregistré',group_message:n.author+' a écrit au salon',creator_video:'Nouvelle vidéo de '+n.author,creator_live:n.author+' est en live',report:'Un commentaire a été signalé',reply:n.author+' a répondu à ton commentaire',test:'ONE · Notifications activées'})[n.kind]||'Une nouvelle pour toi';}
 function hide(){panel.hidden=true;toggle.setAttribute('aria-expanded','false');}
 async function act(path,buttons){if(busy)return;busy=true;let failure='';buttons.forEach(b=>b.disabled=true);status.textContent='';try{await api(path,'POST');await window.oneRefreshSalonState?.(true);if(path.startsWith('/friends/'))window.dispatchEvent(new Event('one-friends-refresh'));if(path.startsWith('/party/invitations/')&&path.endsWith('/accept')){hide();window.oneOpenSalon?.();}}catch(e){failure=e.message;}finally{busy=false;await load();if(failure)status.textContent=failure;}}
 function draw(){for(const b of nav.children)b.setAttribute('aria-pressed',String(b.dataset.filter===filter));list.replaceChildren();const visible=items.filter(n=>filter==='all'||category(n)===filter);if(!visible.length){const empty=make('section',undefined,'hub-notification-empty');empty.append(make('span','✦'),make('h3','Tu es à jour'),make('p','Les prochaines nouvelles apparaîtront ici.'));list.append(empty);window.dispatchEvent(new Event('one-notifications-rendered'));return;}
  for(const n of visible){const card=make('article',undefined,'hub-notification-card');card.dataset.unread=String(!n.read);card.dataset.notificationId=String(n.id);const media=window.onePrivateMediaInfo?.(n.text);if(media)card.dataset.oneMediaId=String(media.id);const face=window.ONEUI?.avatar({name:n.author||'ONE',accountId:n.accountId,avatarUrl:n.avatarUrl})||make('span','✦');face.classList.add('hub-notification-face');const text=make('div',undefined,'hub-notification-copy'),label=make('small',category(n)==='creators'?(n.kind==='creator_live'?'● EN LIVE':'NOUVELLE VIDÉO'):n.kind==='friend'?'DEMANDE D’AMI':n.kind==='group_message'?'TON SALON':category(n)==='messages'?'MESSAGE':'TES AMIS');label.className='hub-notification-kind';text.append(label,make('b',title(n)),make('p',media?(media.type==='video'?'Vidéo ONE reçue':'Photo ONE reçue'):n.text),make('time',ago(n.createdAt)));const row=make('div',undefined,'hub-notification-actions');
   if(n.kind==='friend'||n.kind==='party'||n.kind==='group_invite'){const id=n.kind==='friend'?n.context:n.kind==='party'?n.id.slice(6):n.context,path=n.kind==='friend'?'/friends/'+id:n.kind==='party'?'/party/invitations/'+id:'/social/groups/'+id,accept=button(n.kind==='party'?'Rejoindre':'Accepter',()=>act(path+'/accept',[accept,decline])),decline=button('Refuser',()=>act(path+'/decline',[accept,decline]));accept.className='hub-primary';row.append(accept,decline);}
   else if(['message','group_message','group_saved'].includes(n.kind)){row.append(button('Ouvrir la conversation',()=>{hide();window.oneOpenFriends?.(n.kind==='message'?n.context:'group:'+n.context);}));}
   else if(n.kind.startsWith('creator_')){try{const u=new URL(n.context);if(u.protocol==='https:'&&['www.youtube.com','www.twitch.tv'].includes(u.hostname)){const a=make('a',n.kind==='creator_live'?'Voir le live':'Voir la vidéo','hub-primary');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';row.append(a);}}catch{}}
   else if(n.kind==='report')row.append(button('Ouvrir la modération',()=>document.getElementById('oneModerationEntry')?.click()));
   if(n.kind==='reply'&&n.context)text.append(make('p','Ton commentaire : '+n.context,'hub-muted'));
   const dismiss=button('×',()=>act('/notifications/dismiss?id='+encodeURIComponent(n.id),[dismiss]));dismiss.className='hub-notification-dismiss';dismiss.setAttribute('aria-label','Retirer la notification : '+title(n));text.append(row);card.append(face,text,dismiss);list.append(card);
  }window.dispatchEvent(new Event('one-notifications-rendered'));
 }
 async function load(){if(busy)return;const own=++epoch;if(!window.oneAccountToken?.()){items=[];badge.hidden=true;status.textContent='Connecte-toi à ONE pour retrouver tes notifications.';draw();return;}try{const d=await api('/notifications');if(own!==epoch)return;items=ONEAudit.uniqueById(d.notifications);through=d.through;badge.textContent=d.unread>99?'99+':String(d.unread);badge.hidden=!d.unread;toggle.setAttribute('aria-label',d.unread?'Notifications : '+d.unread+' non lues':'Notifications');read.disabled=!d.unread;status.textContent='';draw();}catch(e){if(own===epoch)status.textContent=e.message;}}
 async function readAll(){if(busy||!through)return;await act('/notifications/read?through='+through,[read]);}
 toggle.addEventListener('click',()=>{if(!panel.hidden)load();});window.addEventListener('one-account-changed',()=>{epoch++;items=[];badge.hidden=true;load();});window.addEventListener('one-notifications-refresh',load);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(()=>{if(!document.hidden&&window.oneAccountToken?.())load();},30000);load();
})();
