/* Durable catalogue history. IndexedDB is authoritative; localStorage is only the legacy display mirror. */
(function(host){
 'use strict';
 const KEY='one_tiktok_external_v09',DB='one-catalogue-v1',LIMIT=5000,KEEP=12;
 const clone=x=>JSON.parse(JSON.stringify(x));
 function merge(...groups){const map=new Map();for(const group of groups){if(!Array.isArray(group))continue;for(const item of group){if(!item||typeof item!=='object')continue;const id=String(item.id||'');if(!/^\d{8,}$/.test(id))continue;const prior=map.get(id);map.set(id,prior?{...item,...prior,id}:{...item,id});}}return [...map.values()].sort((a,b)=>Number(b.addedAt||0)-Number(a.addedAt||0));}
 function suspicious(local,remote){return local.length>0&&(remote.length===0||remote.length<local.length*.7);}
 const policy={merge,suspicious,LIMIT,KEEP};if(typeof module!=='undefined'&&module.exports){module.exports=policy;return;}
 let dbPromise,queue=Promise.resolve(),error='',ready=Promise.resolve();
 const scope=()=>{try{return 'account:'+(JSON.parse(localStorage.getItem('one_account_v06')||'null')?.id||'guest');}catch{return 'account:guest';}};
 function readLegacy(){try{const raw=localStorage.getItem(KEY);if(raw===null)return [];const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw Error();return merge(parsed);}catch{throw Error('Catalogue local illisible : aucun remplacement automatique effectué.');}}
 function open(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore('vaults',{keyPath:'scope'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);req.onblocked=()=>reject(Error('Ferme les anciens onglets ONE pour ouvrir les sauvegardes.'));});return dbPromise;}
 async function load(id){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('vaults'),req=tx.objectStore('vaults').get(id);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>reject(req.error);});}
 async function persist(record){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('vaults','readwrite');tx.objectStore('vaults').put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Sauvegarde interrompue.'));});}
 function notify(message){error=message;host.dispatchEvent(new CustomEvent('one-catalogue-state',{detail:{error:message}}));}
 function mirror(record){if(record.scope!==scope())return;try{localStorage.setItem(KEY,JSON.stringify(record.entries));}catch{notify('Catalogue protégé dans la base locale, mais la copie de compatibilité est pleine.');}host.dispatchEvent(new CustomEvent('one-catalogue-state',{detail:{count:record.entries.length,last:record.history.at(-1)?.at,error}}));}
 function snapshot(record,reason){record.history.push({id:crypto.randomUUID(),at:Date.now(),reason,count:record.entries.length,entries:clone(record.entries)});record.history=record.history.slice(-KEEP);}
 async function initial(id){let record=await load(id);if(record)return record;const owner=await load('legacy-owner'),entries=!owner||owner.account===id?readLegacy():[];record={scope:id,entries,history:[],added:0,revision:0,updatedAt:Date.now()};if(entries.length)snapshot(record,'Migration de sécurité');await persist(record);if(!owner)await persist({scope:'legacy-owner',account:id});return record;}
 function transact(fn,{sync=true}={}){const id=scope();const work=async()=>{const run=async()=>{if(scope()!==id)throw Error('Le compte a changé. Réessaie depuis ton compte.');const record=await initial(id);const result=await fn(record);record.revision++;record.updatedAt=Date.now();await persist(record);if(scope()!==id)return result;mirror(record);if(sync)host.oneScheduleAutoSync?.();return result;};return navigator.locks? navigator.locks.request('one-catalogue:'+id,run):run();};const result=queue.then(work);queue=result.catch(e=>notify(e.message||'Sauvegarde indisponible : opération annulée.'));return result;}
 async function add(entries){return transact(r=>{const ids=new Set(r.entries.map(v=>v.id));let count=0;for(const v of merge(entries)){if(ids.has(v.id))continue;if(r.entries.length>=LIMIT)throw Error('Catalogue plein : aucune vidéo existante supprimée.');r.entries.unshift(v);ids.add(v.id);r.added++;count++;if(r.added%10===0)snapshot(r,'Automatique · '+r.added+' ajouts');}return count;});}
 async function update(entries,{reason='Fusion',remote=false}={}){return transact(r=>{const normalized=merge(entries);if(remote&&suspicious(r.entries,normalized)){snapshot(r,'Avant anomalie distante');notify('Le catalogue distant est vide ou fortement réduit. Tes vidéos sont conservées.');}r.entries=merge(r.entries,normalized);return clone(r.entries);},{sync:!remote});}
 async function remove(ids){return transact(r=>{snapshot(r,'Avant suppression');const set=new Set(ids.map(String));r.entries=r.entries.filter(v=>!set.has(v.id));return r.entries.length;});}
 async function restore(id){return transact(r=>{const snap=r.history.find(s=>s.id===id);if(!snap)throw Error('Sauvegarde introuvable.');const entries=clone(snap.entries);snapshot(r,'Avant restauration');r.entries=merge(r.entries,entries);return r.entries.length;});}
 async function importFile(data){if(data?.format!=='ONE-TIKTOK-CATALOGUE'||data.version!==1||!Array.isArray(data.entries))throw Error('Fichier de catalogue ONE invalide.');return transact(r=>{snapshot(r,'Avant import de catalogue');r.entries=merge(r.entries,data.entries);return r.entries.length;});}
 async function exportFile(){await ready;await queue;const r=await load(scope());return {format:'ONE-TIKTOK-CATALOGUE',version:1,exportedAt:new Date().toISOString(),entries:clone(r?.entries||[]),history:clone(r?.history||[])};}
 async function recoverGuest(){if(scope()==='account:guest')throw Error('Connecte-toi à ton compte pour récupérer le catalogue invité.');const guest=await load('account:guest');if(!guest?.entries?.length)throw Error('Aucun catalogue invité sur cet appareil.');return importFile({format:'ONE-TIKTOK-CATALOGUE',version:1,entries:guest.entries});}
 async function history(){await ready;const r=await load(scope());return {count:r?.entries.length||0,added:r?.added||0,items:(r?.history||[]).map(({entries,...meta})=>meta).reverse(),error};}
 async function cloud(){const data=await exportFile();data.history=data.history.slice(-6);const bytes=new TextEncoder().encode(JSON.stringify(data));if(!host.CompressionStream)return {encoding:'json',data};const compressed=await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();let binary='';const array=new Uint8Array(compressed);for(let i=0;i<array.length;i+=8192)binary+=String.fromCharCode(...array.subarray(i,i+8192));return {encoding:'gzip-base64',data:btoa(binary)};}
 async function acceptCloud(pack){if(!pack)return;let data;if(pack.encoding==='json')data=pack.data;else if(pack.encoding==='gzip-base64'&&host.DecompressionStream){const bytes=Uint8Array.from(atob(pack.data),c=>c.charCodeAt(0));data=JSON.parse(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text());}else throw Error('Format de sauvegarde cloud non pris en charge.');if(data?.format!=='ONE-TIKTOK-CATALOGUE'||!Array.isArray(data.entries))throw Error('Sauvegarde du catalogue invalide.');await update(data.entries,{remote:true});await transact(r=>{const ids=new Set(r.history.map(s=>s.id));for(const h of data.history||[]){if(!h||!Array.isArray(h.entries)||!Number.isFinite(h.at)||ids.has(h.id))continue;const entries=merge(h.entries);r.history.push({id:String(h.id),at:h.at,reason:String(h.reason||'Cloud'),count:entries.length,entries});ids.add(h.id);}r.history.sort((a,b)=>a.at-b.at);r.history=r.history.slice(-KEEP);},{sync:false});}
 async function initialize(){error='';ready=transact(r=>clone(r.entries),{sync:false});try{await ready;}catch(e){notify(e.message);}return ready;}
 host.ONECatalogue={...policy,initialize,add,update,remove,restore,importFile,exportFile,history,cloud,acceptCloud,recoverGuest,snapshot:reason=>transact(r=>{snapshot(r,reason||'Sauvegarde manuelle');}),get ready(){return ready;}};
 host.addEventListener('one-account-changed',()=>initialize().catch(()=>{}));host.addEventListener('storage',e=>{if(e.key===KEY)initialize().catch(()=>{});});
 initialize().catch(()=>{});
})(typeof window==='undefined'?globalThis:window);
