(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev';let dialog=null,dialogToken=null;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},button=(text,fn,label)=>{const b=el('button',text);b.type='button';b.onclick=fn;if(label){b.setAttribute('aria-label',label);b.title=label;}return b;},format=c=>c.slice(0,4)+'-'+c.slice(4);
 const params=new URLSearchParams(location.search),linkCode=params.get('friend');let resume=!!(linkCode&&/^[A-Z2-9]{8}$/i.test(linkCode));if(resume){sessionStorage.setItem('one_friend_pending',linkCode.toUpperCase());params.delete('friend');history.replaceState(history.state,'',location.pathname+(params.size?'?'+params:'')+location.hash);}
 const css=el('link');css.rel='stylesheet';css.href='ui/friends.css?v=014117';document.head.append(css);
 async function api(path,method='GET',body){const token=oneAccountToken();const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const data=await r.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé.');if(!r.ok||!data.ok)throw Error(data.error||'Service indisponible. Réessaie.');return data;}
 window.oneOpenFriends=(conversationId)=>{
  if(dialog?.open){if(typeof conversationId==='string')dialog.openThread?.(conversationId);dialog.focus();return;}dialogToken=oneAccountToken();let tab=typeof conversationId==='string'?'messages':resume?'add':'friends';if(oneAccountToken())resume=false;
  const d=el('dialog');dialog=d;d.className='oneModDialog oneFriendsDialog';d.setAttribute('aria-label','Amis ONE');let revision=0,state=null,selected=typeof conversationId==='string'?conversationId:null,timer=null,pending=null;const drafts=new Map();
  const header=el('header');header.append(el('h2','Amis ONE'),button('×',()=>d.close(),'Fermer les amis'));const nav=el('nav');nav.setAttribute('aria-label','Rubriques amis');const tabs=[];for(const [id,label]of [['friends','Mes amis'],['add','Ajouter'],['invitations','Invitations'],['messages','Messages']]){const b=button(label,()=>{tab=id;if(id==='messages')selected=null;render();});tabs.push([id,b]);nav.append(b);}const status=el('p');status.setAttribute('role','status');const content=el('div');content.className='friends-content';d.append(header,nav,status,content);document.body.append(d);
  d.openThread=id=>{selected=id;tab='messages';render();};
  const valid=()=>d.isConnected&&dialog===d;
  d.addEventListener('close',()=>{resume=false;revision++;clearInterval(timer);d.remove();if(dialog===d)dialog=null;});d.showModal();
  async function load(){const own=++revision;status.textContent='Chargement…';try{if(!oneAccountToken()){state=null;status.textContent='Connecte-toi à ONE pour retrouver tes amis.';render();return;}const fresh=await api('/friends/state');if(!valid()||own!==revision)return;state=fresh;status.textContent='';render();}catch(e){if(valid()&&own===revision){status.textContent=e.message;content.replaceChildren(button('Réessayer',load));}}}
  async function action(path,trigger,question){if(question&&!confirm(question))return;trigger.disabled=true;try{const result=await api(path,'POST');if(path.startsWith('/friends/request'))sessionStorage.removeItem('one_friend_pending');if(!valid())return;await load();status.textContent=path.startsWith('/party/invite')?(result.alreadyPending?'Invitation déjà en attente.':'Invitation envoyée à '+(result.recipient||'ton ami')+'.'):'Enregistré.';window.dispatchEvent(new Event('one-party-refresh'));}catch(e){if(valid())status.textContent=e.message;}finally{trigger.disabled=false;}}
  function actionButton(text,path,label,question){const b=button(text,()=>action(path,b,question),label);return b;}
  async function copy(value){try{await navigator.clipboard.writeText(value);status.textContent='Copié.';}catch{status.textContent='À copier : '+value;}}
  function openMessages(r){selected=r.id;tab='messages';render();}
  function render(){if(!valid())return;if(!state){for(const [id,b]of tabs)b.setAttribute('aria-current',id===tab?'page':'false');return;}revision++;clearInterval(timer);timer=null;content.replaceChildren();for(const [id,b]of tabs)b.setAttribute('aria-current',id===tab?'page':'false');if(!state)return;
   if(tab==='add')return renderAdd();if(tab==='messages')return renderMessages();
   const friends=state.relationships.filter(r=>r.status==='accepted').sort((a,b)=>Number(b.online)-Number(a.online)||a.name.localeCompare(b.name));const top=el('div');top.className='friends-list-head';top.append(el('p',friends.length+' ami'+(friends.length>1?'s':'')),button('↻',load,'Actualiser les amis'));if(tab==='friends')content.append(top);if(tab==='friends'&&!friends.length)content.append(el('p','Pas encore d’ami. Ouvre Ajouter pour partager ton code ou scanner un QR.'));
   const list=el('div');list.className='friend-list';if(tab==='friends'){const search=el('input');search.type='search';search.className='os-friends-search';search.placeholder='Rechercher un ami (pseudo ou ID ONE)';search.setAttribute('aria-label',search.placeholder);search.oninput=()=>{const q=search.value.toLocaleLowerCase();for(const row of list.children)row.hidden=!row.dataset.search.includes(q);};content.append(search,list,button('▦ Ajouter par ID ONE ou QR',()=>{tab='add';render();}));}for(const r of tab==='friends'?friends:[]){const row=el('article');row.dataset.search=(r.name+' '+(r.accountId||'')+' '+(r.code||'')).toLocaleLowerCase();row.append(ONEUI.avatar(r));row.className='friend-row';const who=el('div');who.className='friend-identity';const presence=el('small',r.online?'● En ligne':'● Hors ligne');presence.className='os-friend-status';presence.dataset.online=String(!!r.online);const salon=window.oneSocialRoom?.();if(salon?.members.some(m=>m.accountId===r.accountId))presence.textContent='● Dans ton salon';who.append(el('b',r.name),presence);who.title=r.accountId||'';const controls=el('div');controls.className='friend-actions';controls.append(button('Message',()=>openMessages(r),'Discuter avec '+r.name),actionButton('Inviter','/party/invite?recipient='+encodeURIComponent(r.accountId||r.code),'Inviter '+r.name+' dans mon salon'),actionButton('×','/friends/'+r.id+'/remove','Retirer '+r.name,'Retirer cet ami ? Votre historique de messages sera supprimé.'));const inviteButton=controls.children[1];const currentRoom=window.oneSocialRoom?.(),present=currentRoom?.members.some(m=>m.accountId===r.accountId);inviteButton.disabled=!currentRoom?.isHost||present;if(present)inviteButton.textContent='Dans ton salon';inviteButton.title=inviteButton.disabled?'Crée un salon pour inviter cet ami.':'Inviter dans ton salon';controls.lastChild.classList.add('friend-remove');const more=el('details');more.className='os-friend-more';more.append(el('summary','•••'));more.firstChild.setAttribute('aria-label','Autres actions pour '+r.name);more.append(controls.firstChild,controls.lastChild);row.append(who,inviteButton,more);inviteButton.classList.add('os-friend-primary');if(present){inviteButton.disabled=false;inviteButton.textContent='Voir';inviteButton.onclick=()=>{d.close();window.oneOpenSalon?.();};inviteButton.title='Voir votre salon';}list.append(row);}
   if(tab!=='invitations')return;if(!state.relationships.some(r=>r.status==='pending'))content.append(el('p','Aucune demande d’amis en attente.'));for(const [title,outgoing]of [['Demandes reçues',false],['Demandes envoyées',true]]){const rows=state.relationships.filter(r=>r.status==='pending'&&!!r.outgoing===outgoing);if(!rows.length)continue;content.append(el('h3',title));for(const r of rows){const row=el('article');row.className='friend-row';row.append(el('b',r.name));const controls=el('div');controls.className='friend-actions';if(!outgoing)controls.append(actionButton('✓','/friends/'+r.id+'/accept','Accepter '+r.name));controls.append(actionButton('×','/friends/'+r.id+(outgoing?'/remove':'/decline'),outgoing?'Annuler la demande':'Refuser la demande'));row.append(controls);content.append(row);}}
  }
  function renderAdd(){const url=new URL(location.pathname,location.origin);url.searchParams.set('friend',state.code);const code=el('strong',format(state.code));code.className='friend-share-code';content.append(el('h3','Mon code à partager'),code,button('Copier le code',()=>copy(format(state.code))),button('Copier le lien',()=>copy(url.href)));
   try{const q=qrcode(0,'M');q.addData(url.href);q.make();const canvas=el('canvas'),count=q.getModuleCount(),scale=4;canvas.width=canvas.height=(count+8)*scale;canvas.className='friend-qr';canvas.setAttribute('role','img');canvas.setAttribute('aria-label','QR pour ajouter mon compte ONE');const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let y=0;y<count;y++)for(let x=0;x<count;x++)if(q.isDark(y,x))ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);content.append(canvas);}catch{content.append(el('p','QR indisponible : utilise le code ou le lien.'));}
   const label=el('label','Code ONE de ton ami'),input=el('input');input.maxLength=16;input.placeholder='ABCD-EFGH';input.value=sessionStorage.getItem('one_friend_pending')||'';label.append(input);content.append(el('p','Ton ami peut scanner ce QR avec son téléphone.'),button('Scanner un QR code',()=>window.oneScanFriendQR?.(value=>{if(!valid())return;input.value=format(value);sessionStorage.setItem('one_friend_pending',value);status.textContent='Code lu. Confirme avec Envoyer une demande.';})),label);const send=button('Envoyer une demande',()=>action('/friends/request?code='+encodeURIComponent(input.value),send,'Envoyer une demande à ce code ONE ?'));content.append(send);
  }

  function renderInbox(){const own=revision;let loading=false;const list=el('div');list.className='friend-inbox';content.append(el('h3','Toutes les conversations'),list);async function poll(){if(loading||!valid()||revision!==own||document.hidden)return;loading=true;try{const result=await api('/friends/inbox');if(!valid()||revision!==own)return;list.replaceChildren();if(!result.conversations.length)list.append(el('p','Ajoute un ami pour discuter.'));for(const c of result.conversations){const row=button('',()=>openMessages(c),'Conversation avec '+c.name+(c.unread?', '+c.unread+' message(s) non lu(s)':''));row.className='friend-conversation';const title=el('b',c.name),preview=el('span',c.lastText||'Commencer la discussion'),meta=el('small',c.lastAt?new Date(c.lastAt).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'');row.append(title,preview,meta);if(c.unread){const badge=el('strong',c.unread>99?'99+':String(c.unread));badge.className='friend-unread';row.append(badge);}list.append(row);}}catch(e){if(valid()&&revision===own)status.textContent=e.message;}finally{loading=false;}}poll();timer=setInterval(poll,4000);}
  function renderMessages(){const friends=state.relationships.filter(r=>r.status==='accepted');if(!friends.some(r=>r.id===selected))selected=null;if(!selected){renderInbox();return;}
   content.append(button('← Toutes les conversations',()=>{selected=null;render();}));
   const friend=friends.find(r=>r.id===selected),thread=selected,own=revision;let messageBusy=false,messageKey='',readThrough=0;content.append(el('h3',friend.name));const log=el('div');log.className='friend-message-log';log.setAttribute('role','log');log.setAttribute('aria-label','Conversation avec '+friend.name);const label=el('label','Ton message'),input=el('textarea');input.maxLength=1000;input.rows=2;input.placeholder='Écris à '+friend.name;input.value=drafts.get(thread)||'';label.append(input);const send=button('Envoyer',sendMessage),msgStatus=el('p');msgStatus.setAttribute('role','status');content.append(log,label,send,msgStatus);
   const current=()=>valid()&&tab==='messages'&&selected===thread&&revision===own;
   input.oninput=()=>{drafts.set(thread,input.value);pending=null;};
   async function poll(){if(!current()||messageBusy||document.hidden)return;messageBusy=true;try{const result=await api('/friends/'+thread+'/messages');if(!current())return;const key=JSON.stringify(result.messages);if(key!==messageKey){const near=log.scrollHeight-log.scrollTop-log.clientHeight<50;log.replaceChildren();for(const m of result.messages){const item=el('article');item.className=m.isYou?'mine':'theirs';item.append(el('small',(m.isYou?'Toi':friend.name)+' · '+new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})),el('p',m.text));log.append(item);}if(!result.messages.length)log.append(el('p','Votre conversation commence ici.'));if(near||!messageKey)log.scrollTop=log.scrollHeight;messageKey=key;}const through=result.messages.at(-1)?.createdAt;if(through>readThrough&&document.visibilityState==='visible'){await api('/friends/'+thread+'/messages/read?through='+through,'POST');readThrough=through;if(current())window.dispatchEvent(new Event('one-notifications-refresh'));}}catch(e){if(current())msgStatus.textContent=e.message;}finally{messageBusy=false;}}
   async function sendMessage(){if(send.disabled||!input.value.trim())return;const draft=input.value;pending=pending&&pending.thread===thread&&pending.text===draft.trim()?pending:{id:crypto.randomUUID(),text:draft.trim(),thread};const message=pending;send.disabled=true;try{await api('/friends/'+thread+'/messages','POST',{id:message.id,text:message.text});if(!current())return;if(input.value===draft){input.value='';drafts.delete(thread);}if(pending===message)pending=null;msgStatus.textContent='Message envoyé.';await poll();}catch(e){if(current())msgStatus.textContent=e.message;}finally{send.disabled=false;}}
   poll();timer=setInterval(poll,4000);
  }
  load();
 };
 const entry=button('Amis · Mon code et mon QR',window.oneOpenFriends);document.getElementById('oneAuthLoggedIn')?.append(entry);
 window.addEventListener('one-account-changed',()=>{if(dialog?.open&&dialogToken===oneAccountToken())return;const reopen=resume;dialog?.close();if(oneAccountToken()&&reopen){resume=true;window.oneOpenFriends();}});
 const headerButton=button('',window.oneOpenFriends,'Amis');headerButton.id='oneFriendsToggle';headerButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v2"/></svg>';(document.getElementById('oneSalonsToggle')||document.getElementById('oneNotificationsToggle'))?.before(headerButton);
 if(resume)window.oneOpenFriends();
})();
