(()=>{
const API='https://one-comments-api.moulinanthony60.workers.dev';const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
window.ONEPokerMount=async(host,onBalance)=>{const token=window.oneAccountToken?.(),root=el('div',undefined,'onePoker');host.replaceChildren(root);let table=null,busy=false,buyin=100,error='',key='',pending=null,offer=null,code='',raise=4;const current=()=>host.contains(root)&&host.isConnected&&token===window.oneAccountToken?.();
const button=(label,fn,disabled=false)=>{const b=el('button',label);b.type='button';b.disabled=disabled||busy;b.onclick=fn;return b;};
async function api(path,body){if(!token)throw Error('Connecte-toi à ONE.');const r=await fetch(API+'/points/poker/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const d=await r.json();if(!r.ok){const e=Error(d.error||'Poker indisponible.');e.definitive=r.status>=400&&r.status<500;throw e;}return d;}
function save(){try{localStorage.setItem(key,JSON.stringify({code:table?.code||code,pending}));}catch{}}
async function run(path,body){if(busy)return;busy=true;error='';if(path==='create'){pending=body;save();}render();try{const d=await api(path,body);if(!current())return;table=d.table;code=table?.code||'';pending=null;offer=null;save();onBalance(d.balance);raise=table?.minRaise||4;}catch(e){error=e.message;if(path==='create'&&e.definitive){pending=null;save();}if(path!=='create')await load(false);}finally{busy=false;if(current())render();}}
async function load(draw=true){try{const d=await api('state'+(code?'?code='+encodeURIComponent(code):''));if(!current())return;const changed=table?.revision!==d.table?.revision||table?.code!==d.table?.code;table=d.table;code=table?.code||'';onBalance(d.balance);if(changed&&draw){raise=table?.minRaise||4;render();}save();}catch(e){if(current()){error=e.message;if(draw)render();}}}
function cards(list){const row=el('div',undefined,'onePokerCards');for(const c of list){const n=el('span',undefined,'onePokerCard');if(c===null){n.classList.add('isBack');n.textContent='ONE';}else{const rank=['A','2','3','4','5','6','7','8','9','10','V','D','R'][c%13],suit=['♠','♥','♦','♣'][Math.floor(c/13)];n.classList.toggle('isRed',[1,2].includes(Math.floor(c/13)));n.append(el('small',rank+suit),el('b',suit));n.setAttribute('aria-label',rank+suit);}row.append(n);}return row;}
function render(){root.replaceChildren();root.append(el('h3','ONE · Texas Hold’em'),el('p','Tête-à-tête · Blindes 1 / 2 Points ONE','onePokerHelp'));
if(!table){const amount=el('select');amount.setAttribute('aria-label','Points à apporter à la table');for(const n of [100,500,1000]){const o=el('option',n+' Points ONE');o.value=n;amount.append(o);}amount.value=buyin;amount.disabled=busy||!!pending;amount.onchange=()=>buyin=+amount.value;root.append(el('p','Les points apportés sont réservés à la table. Chaque mise est prélevée sur cette réserve. Le reste et les gains reviennent au solde à la fin de la main.'),amount);
if(pending)root.append(button('Retrouver ma table',()=>run('create',pending)));else{root.append(button('Jouer contre l’ordinateur',()=>run('create',{id:crypto.randomUUID(),mode:'bot',buyin})),el('p','Pour jouer avec tes amis, retrouve ONE Poker dans les salons Party.'));}}
else if(table.street==='waiting'){root.append(el('div','CODE : '+table.code,'onePokerCode'),el('p','En attente d’un ami · '+table.buyin+' points par joueur.'),el('p','Partage ce code à ton ami. Il choisira Poker → Vérifier la table.'),button('Annuler et récupérer mes points',()=>run('leave',{code:table.code,revision:table.revision})));}
else{const felt=el('section',undefined,'onePokerFelt'),other=table.players.find(p=>!p.isYou),me=table.players.find(p=>p.isYou);felt.append(el('strong',other.name+' · '+other.stack+' pts'),cards(other.hole),el('p',other.bet?'Mise : '+other.bet+' pts':'','onePokerBet'),el('div','POT · '+(table.pot||table.wonPot)+' pts','onePokerPot'));const board=[...table.board];while(board.length<5)board.push(null);felt.append(cards(board),el('small',{preflop:'PRÉFLOP',flop:'FLOP',turn:'TURN',river:'RIVER',finished:'MAIN TERMINÉE'}[table.street]),cards(me.hole),el('strong','Toi · '+me.stack+' pts'),el('p','Mise : '+me.bet+' pts','onePokerBet'));root.append(felt,el('p',table.last,'onePokerMessage'));
if(table.street==='finished'){root.append(el('p','Ta réserve restante et tes gains ont été reversés sur ton compte.'),button('Nouvelle table',()=>{table=null;code='';error='';save();render();}));}else{root.append(el('p',table.isTurn?'À toi de jouer · 2 minutes maximum.':'Ton adversaire joue…'));const actions=el('div',undefined,'onePokerActions');actions.append(button('Se coucher',()=>run('action',{code:table.code,revision:table.revision,action:'fold'}),!table.isTurn),button(table.call?'Suivre · '+table.call+' pts':'Parole',()=>run('action',{code:table.code,revision:table.revision,action:'call'}),!table.isTurn));const amount=el('input');amount.type='number';amount.min=table.minRaise;amount.max=table.maxRaise;amount.step=1;amount.value=raise;amount.setAttribute('aria-label','Montant total de la relance');amount.disabled=!table.canRaise||busy;amount.oninput=()=>raise=+amount.value;actions.append(amount,button('Relancer',()=>run('action',{code:table.code,revision:table.revision,action:'raise',amount:raise}),!table.canRaise),button('Tapis · '+table.maxRaise+' pts',()=>run('action',{code:table.code,revision:table.revision,action:table.canRaise?'raise':'call',amount:table.maxRaise}),!table.isTurn));root.append(actions,button('Quitter et se coucher',()=>run('leave',{code:table.code,revision:table.revision})));}}
const status=el('p',error,'onePokerError');status.setAttribute('role','status');root.append(status,el('p','Une table joue une main. Les cartes adverses restent cachées jusqu’à l’abattage. Après 2 minutes sans action, le joueur se couche. Points virtuels sans valeur monétaire.','onePokerHelp'));}
render();if(token){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));key='one-poker-'+Array.from(new Uint8Array(hash)).map(n=>n.toString(16).padStart(2,'0')).join('');try{const saved=JSON.parse(localStorage.getItem(key)||'null');code=saved?.code||'';pending=saved?.pending||null;}catch{}}
await load();if(current())render();async function poll(){if(!current())return;if(!busy&&table&&table.street!=='finished')await load();if(current())setTimeout(poll,3000);}setTimeout(poll,3000);
};
const s=el('style');s.textContent=`#onePointsPanel .onePoker{display:grid;gap:14px}#onePointsPanel .onePoker h3{text-align:center;color:#f2d28b}#onePointsPanel .onePokerFelt{display:grid;gap:10px;justify-items:center;text-align:center;padding:22px 10px;border:6px solid #805839;outline:1px solid #dfba6c;border-radius:60px;background:radial-gradient(ellipse,#196b63,#103c38);box-shadow:inset 0 0 0 2px #bc9a5677,inset 0 0 50px #0008,0 12px 24px #0005}#onePointsPanel .onePokerCards{display:flex;gap:5px;justify-content:center;width:100%}#onePointsPanel .onePokerCard{width:42px;height:62px;display:flex;flex-direction:column;box-sizing:border-box;padding:4px;color:#162034;background:linear-gradient(120deg,#fffdf4,#eae4d3);border-radius:5px;border:1px solid #fff5bd;box-shadow:0 4px 4px #0006}#onePointsPanel .onePokerCard small{align-self:flex-start;font:bold 10px Georgia}#onePointsPanel .onePokerCard b{font-size:25px}#onePointsPanel .onePokerCard.isRed{color:#c12847}#onePointsPanel .onePokerCard.isBack{align-items:center;justify-content:center;font:bold 9px Georgia;color:#ddc698;background:repeating-linear-gradient(135deg,#7361c922 0 2px,transparent 2px 8px),#262040;box-shadow:inset 0 0 0 3px #181530,0 4px 4px #0005}#onePointsPanel .onePokerPot{padding:8px 16px;border:1px solid #ecd39988;border-radius:30px;color:#fff0bb;background:#072d2e;font-weight:bold}#onePointsPanel .onePokerActions{display:flex;gap:8px;flex-wrap:wrap}#onePointsPanel .onePokerActions button{flex:1;min-width:100px}#onePointsPanel .onePokerHelp{font-size:11px;color:#b6a9ca}#onePointsPanel .onePokerMessage{color:#ffe4ab;font-weight:bold;text-align:center}#onePointsPanel .onePokerError{color:#ffbead}#onePointsPanel .onePokerCode{font:bold 21px monospace;text-align:center;letter-spacing:3px;padding:20px;border:1px dashed #c4a477;border-radius:12px}#onePointsPanel .onePoker input:not([type=number]){width:100%;box-sizing:border-box}#onePointsPanel .onePokerBet{font-size:11px}`;document.head.append(s);
})();



