(()=>{
 'use strict';const {el,button,api,avatar}=ONEUI,modal=document.getElementById('accountModal'),sheet=modal?.querySelector('.sheet');if(!sheet)return;
 const header=sheet.querySelector('header'),summary=sheet.querySelector('.accountSummary'),logged=document.getElementById('oneAuthLoggedIn'),out=document.getElementById('oneAuthLoggedOut'),platforms=sheet.querySelector('.platformList'),manage=document.getElementById('managePlatforms')?.parentElement;
 header.querySelector('h3').textContent='Compte ONE';const profile=el('section',undefined,'hub-account-section'),connections=el('section',undefined,'hub-account-section'),alerts=el('section',undefined,'hub-account-section'),advanced=el('details',undefined,'hub-account-advanced');advanced.append(el('summary','Sauvegarde et réglages avancés'));
 const intro=sheet.querySelector('header+p');intro?.remove();profile.append(out,logged);connections.append(el('h3','Tes plateformes'),el('p','Retrouve tes contenus avec tes comptes connectés.','hub-muted'),platforms);if(manage)connections.append(manage);
 for(const node of [...sheet.childNodes])if(node!==header&&node!==summary)advanced.append(node);
 connections.append(advanced);const nav=el('nav',undefined,'hub-account-tabs');nav.setAttribute('aria-label','Rubriques du compte');const sections={profile,connections,alerts},buttons={};
 function show(key){for(const [id,section]of Object.entries(sections)){section.hidden=id!==key;buttons[id]?.setAttribute('aria-current',id===key?'page':'false');}}
 for(const [id,label]of [['profile','Mon profil'],['connections','Connexions'],['alerts','Notifications']]){const b=button(label,()=>show(id));buttons[id]=b;nav.append(b);}sheet.append(header,summary,nav,profile,connections,alerts);show('profile');
 const photoPanel=el('section',undefined,'hub-photo-editor'),preview=el('div',undefined,'hub-photo-preview'),photoActions=el('div',undefined,'hub-actions'),picker=el('input');picker.type='file';picker.accept='image/jpeg,image/png,image/webp';picker.hidden=true;picker.setAttribute('aria-label','Choisir une photo de profil');const choose=button('Choisir une photo',()=>picker.click()),save=button('Enregistrer la photo',storePhoto),remove=button('Retirer la photo',()=>storePhoto(null)),status=el('p',undefined,'hub-muted');status.setAttribute('role','status');save.hidden=true;save.className='hub-primary';photoActions.append(choose,save,remove,picker);photoPanel.append(preview,photoActions,el('small','Visible par tes amis et les membres de tes salons.'),status);logged.prepend(photoPanel);
 const identityFacts=el('dl',undefined,'hub-identity-facts'),idRow=el('div'),idLabel=el('dt','ID ONE'),idValue=el('dd','—'),mailRow=el('div'),mailLabel=el('dt','E-mail'),mailValue=el('dd','—');idRow.append(idLabel,idValue);mailRow.append(mailLabel,mailValue);identityFacts.append(idRow,mailRow);logged.append(identityFacts);
 let ownToken='',serial=0,profileData=null,draft=undefined,busy=false;
 const account=()=>window.oneAccountLocal?.()||{};
 function paint(){const a=account(),me={accountId:a.id,name:a.displayName||'ONE',avatarUrl:draft===undefined?profileData?.avatarUrl:draft};idValue.textContent=a.id||'—';mailValue.textContent=a.email||'—';preview.replaceChildren(avatar({...me,avatarUrl:undefined}));if(me.avatarUrl){const img=el('img');img.src=me.avatarUrl;img.alt='Aperçu de ta photo';preview.append(img);}const summaryFace=summary.querySelector('.accountAvatar');summaryFace?.replaceChildren(avatar({...me,avatarUrl:profileData?.avatarUrl}));const entry=document.getElementById('accountBtn');entry?.querySelector('.hub-header-avatar')?.remove();if(profileData?.avatarUrl&&entry){const face=avatar({...me,avatarUrl:profileData.avatarUrl});face.classList.add('hub-header-avatar');entry.prepend(face);}remove.hidden=!profileData?.avatarUrl;save.hidden=draft===undefined;choose.disabled=save.disabled=remove.disabled=busy;}
 async function load(){const token=window.oneAccountToken?.(),own=++serial;if(token!==ownToken){profileData=null;draft=undefined;ownToken=token;}paint();if(!token)return;try{const d=await api('/social/profile');if(own!==serial||token!==window.oneAccountToken?.())return;profileData=d;paint();}catch(e){if(own===serial)status.textContent=e.message;}}
 picker.onchange=async()=>{const f=picker.files?.[0];picker.value='';if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>12*1024*1024){status.textContent='Choisis une photo JPEG, PNG ou WebP de moins de 12 Mo.';return;}const token=window.oneAccountToken?.();busy=true;paint();let bitmap;try{bitmap=await createImageBitmap(f);if(token!==window.oneAccountToken?.())return;const canvas=el('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d'),side=Math.min(bitmap.width,bitmap.height);ctx.fillStyle='#221735';ctx.fillRect(0,0,256,256);ctx.drawImage(bitmap,(bitmap.width-side)/2,(bitmap.height-side)/2,side,side,0,0,256,256);draft=canvas.toDataURL('image/jpeg',.82);if(draft.length>90000)draft=canvas.toDataURL('image/jpeg',.6);status.textContent='Aperçu prêt. Enregistre pour appliquer ta photo.';}catch{status.textContent='Cette photo ne peut pas être ouverte. Essaie une autre image.';}finally{bitmap?.close();busy=false;paint();}};
 async function storePhoto(value){if(busy)return;const photo=value===null?null:draft;if(photo===undefined)return;busy=true;paint();try{const d=await api('/social/profile','POST',{avatar:photo});profileData=d;draft=undefined;status.textContent=photo?'Photo enregistrée sur ton compte ONE.':'Photo retirée.';await window.oneRefreshSalonState?.(true);window.dispatchEvent(new Event('one-profile-photo-changed'));}catch(e){status.textContent=e.message;}finally{busy=false;paint();}}
 const identityInput=document.getElementById('oneDisplayName');identityInput?.setAttribute('aria-label','Ton nom dans ONE');const legacyIdentity=document.getElementById('oneIdentityStatus');if(legacyIdentity)legacyIdentity.classList.add('hub-legacy-identity');
 const friendsEntry=button('♧ Mes amis et mes salons',()=>{modal.classList.remove('show');window.oneOpenFriends?.();});friendsEntry.className='hub-profile-friends';logged.append(friendsEntry);
 // Reuse the same vector platform marks as Together.
 const marks={Youtube:'<rect x="1" y="5" width="22" height="15" rx="5" fill="#ff0033"/><path d="m10 9 6 3.5-6 3.5Z" fill="#fff"/>',Twitch:'<path d="M4 2h18v13l-6 6h-5l-4 3v-3H2V6Z" fill="#9146ff"/><path d="M6 4h14v10l-4 4h-5l-3 3v-3H6Z" fill="#fff"/><path d="M10 7v6m6-6v6" stroke="#9146ff" stroke-width="2"/>',TikTok:'<path d="M14 3v12a5 5 0 1 1-5-5" fill="none" stroke="#25f4ee" stroke-width="4" transform="translate(-1 1)"/><path d="M14 3c0 4 3 6 6 6M14 3v12a5 5 0 1 1-5-5" fill="none" stroke="#fe2c55" stroke-width="3" transform="translate(1 0)"/><path d="M14 3c0 4 3 6 6 6M14 3v12a5 5 0 1 1-5-5" fill="none" stroke="#fff" stroke-width="2.5"/>'};for(const [id,paths]of Object.entries(marks)){const icon=document.getElementById('account'+id+'Text')?.closest('.platformRow')?.querySelector('.platformIcon');if(icon)icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+paths+'</svg>';}
 window.ONEAccountUI={alerts,show:(key='profile')=>{modal.classList.add('show');show(key);load();}};
 document.getElementById('accountBtn')?.addEventListener('click',()=>{show('profile');load();});window.addEventListener('one-account-changed',load);load();
})();
