/* Frontend content preparation; no shared playback or publication is fabricated. */
(()=>{
 const {el,button,icon,avatar,dialog}=ONEUI;const previews=[];let selected=null,source='one',activeMedia=[];
 const sources=[['one','ONE'],['tiktok','TikTok'],['youtube','YouTube'],['twitch','Twitch'],['music','Musique']];
 function chooseNative(onChoose){const d=dialog('Choisir une création ONE');d.append(el('p','Créations locales de cette session. La publication du Feed ONE n’est pas encore reliée.','os-muted'));for(const item of previews){const b=button(item.title,()=>{d.close();onChoose(item);},'os-button os-wide');d.append(b);}const file=el('input');file.type='file';file.accept='video/*';file.setAttribute('aria-label','Prévisualiser une vidéo locale');const label=el('label','Ajouter une vidéo locale à prévisualiser');label.append(file);d.append(label);file.onchange=()=>{const f=file.files?.[0];if(!f)return;if(!f.type.startsWith('video/')){d.append(el('p','Choisis un fichier vidéo.'));return;}const item={id:crypto.randomUUID(),title:f.name,creator:'Toi',url:URL.createObjectURL(f),file:f,source:'one',local:true};previews.push(item);d.close();onChoose(item);};if(!previews.length)d.append(el('p','Aucune création disponible pour le moment.'));
 }
 function watch(item){selected=item;source=item.source;window.oneShowSpace?.('together');}
 function parseLink(value,kind){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('Utilise un lien HTTPS de la source sélectionnée.');let embed=null;
  if(kind==='youtube'){let id;if(u.hostname==='youtu.be')id=u.pathname.slice(1);else if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([\w-]+)/)?.[1];if(!/^[\w-]{11}$/.test(id||''))throw Error('Lien YouTube non reconnu.');embed='https://www.youtube-nocookie.com/embed/'+id;}
  else if(kind==='twitch'){if(!['twitch.tv','www.twitch.tv','m.twitch.tv'].includes(u.hostname)||!/^\/[\w]{2,25}\/?$/.test(u.pathname))throw Error('Utilise le lien d’une chaîne Twitch.');embed='https://player.twitch.tv/?channel='+encodeURIComponent(u.pathname.replaceAll('/',''))+'&parent='+encodeURIComponent(location.hostname)+'&autoplay=false';}
  else if(kind==='tiktok'){if(!['tiktok.com','www.tiktok.com','m.tiktok.com','vm.tiktok.com','vt.tiktok.com'].includes(u.hostname))throw Error('Utilise un lien TikTok.');const id=u.pathname.match(/\/video\/(\d+)/)?.[1];if(id)embed='https://www.tiktok.com/player/v1/'+id;}
  return {id:crypto.randomUUID(),title:u.hostname+u.pathname,source:kind,url:u.href,embed,local:false};
 }
 function contentLink(){const d=dialog('Choisir le contenu'),label=el('label','Lien '+(sources.find(s=>s[0]===source)?.[1]||'')),input=el('input');input.type='url';input.placeholder='https://…';label.append(input);const status=el('p');status.setAttribute('role','status');d.append(label,button('Préparer ce contenu',()=>{try{selected=parseLink(input.value.trim(),source);d.close();const shell=document.getElementById('oneFoundation');renderTogether(shell);}catch(e){status.textContent=e.message;}},'os-primary'),status);}
 function choose(){if(source==='one')chooseNative(item=>{selected=item;renderTogether(document.getElementById('oneFoundation'));});else contentLink();}
 function renderPreview(parent,item){parent.replaceChildren();if(!item){parent.append(icon(source),el('h2','Choisis votre prochain moment'),el('p','Prépare une vidéo ou un lien à regarder ensemble.'));return;}if(item.local){const video=el('video');video.src=item.url;video.controls=true;video.playsInline=true;video.preload='metadata';video.setAttribute('aria-label',item.title);parent.append(video);activeMedia.push(video);}else if(item.embed){const frame=el('iframe');frame.src=item.embed;frame.title='Aperçu personnel · '+item.title;frame.allow='fullscreen; encrypted-media; picture-in-picture';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;parent.append(frame);activeMedia.push(frame);}else{parent.append(icon(item.source),el('h2','Lien sélectionné'),el('p','Ce contenu ne propose pas de lecteur intégré ici.'));const a=el('a','Ouvrir la source');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.className='os-button';parent.append(a);}}
 function stopPreview(){for(const node of activeMedia){if(node.tagName==='VIDEO')node.pause();else node.remove();}activeMedia=[];document.querySelectorAll('.os-watch-player video,.os-native-video').forEach(v=>v.pause());document.querySelectorAll('.os-watch-player iframe').forEach(f=>f.remove());}
 function roomMembers(target){window.dispatchEvent(new Event('one-salon-before-render'));target.replaceChildren();const room=window.oneSocialRoom?.();if(room){for(const m of room.members)target.append(ONEUI.player(m));}else target.append(button('Créer ou rejoindre un salon',()=>window.oneOpenSalon?.(),'os-primary'));window.dispatchEvent(new Event('one-salon-rendered'));}
 function renderTogether(shell){stopPreview();window.dispatchEvent(new Event('one-salon-before-render'));shell.replaceChildren();const head=el('div',undefined,'os-page-head');head.append(el('h1','Together'),button('Voir le salon',()=>window.oneOpenSalon?.()));shell.append(head);const player=el('section',undefined,'os-watch-player');renderPreview(player,selected);shell.append(player,el('span','APERÇU PERSONNEL · NON SYNCHRONISÉ','os-eyebrow'));const title=el('h2',selected?.title||'Aucun contenu sélectionné','os-selected-title');shell.append(title);const platforms=el('nav',undefined,'os-platforms');platforms.setAttribute('aria-label','Sources Together');for(const [id,name]of sources){const b=button('',()=>{source=id;selected=null;renderTogether(shell);});b.append(icon(id),el('span',name));b.setAttribute('aria-pressed',String(id===source));platforms.append(b);}shell.append(platforms,button(source==='one'?'Choisir dans le Feed ONE':'Ajouter une vidéo ou un lien',choose,'os-button os-wide'));const room=window.oneSocialRoom?.();shell.append(el('h3','Dans le salon'));const members=el('div',undefined,'os-members os-together-members');members.id='oneTogetherMembers';roomMembers(members);shell.append(members,el('p','Ces membres ne sont pas encore participants à Together.','os-muted'));const launch=button('Démarrer Together',null,'os-primary os-wide');launch.disabled=true;launch.title='La session partagée doit être prise en charge par le service';shell.append(launch,el('p','Le lecteur ci-dessus reste personnel. Rejoindre, synchroniser et démarrer la session seront disponibles après l’adaptation du service.','os-blocked'));const tools=el('div',undefined,'os-room-tools');const feedback=el('p');feedback.setAttribute('role','status');for(const [kind,label]of [['mic','🎤 Micro'],['camera','▣ Caméra']])tools.append(button(label,async()=>{try{await window.ONEPartyMedia?.toggle?.(kind);}catch(e){feedback.textContent=e.message;}}));tools.append(button('☏ Chat',()=>{window.oneOpenSalon?.();const chat=document.getElementById('onePartyChat');if(chat){chat.hidden=false;chat.scrollIntoView({block:'nearest'});}}));shell.append(tools,feedback);const queue=el('details',undefined,'os-pending');queue.append(el('summary','File d’attente commune'),el('p','L’ajout et l’ordre partagé attendent le service Together. Aucun contenu n’est envoyé aux autres membres.'));shell.append(queue);window.dispatchEvent(new Event('one-salon-rendered'));}
 function renderFeed(shell){stopPreview();shell.replaceChildren();const head=el('div',undefined,'os-page-head');head.append(el('h1','Feed ONE'),button('＋ Créer',()=>window.openOneStudio?.(),'os-primary'));shell.append(head);const tabs=el('nav',undefined,'os-tabs'),list=el('div',undefined,'os-native-list');let tab='Pour toi';function draw(){stopPreview();list.replaceChildren();const items=tab==='Abonnements'?[]:previews;for(const item of items){const card=el('article',undefined,'os-native-card'),video=el('video',undefined,'os-native-video');video.src=item.url;video.controls=true;video.playsInline=true;video.preload='metadata';video.setAttribute('aria-label',item.title);activeMedia.push(video);const creator=el('div',undefined,'os-native-creator');creator.append(avatar({name:item.creator}),el('b',item.creator+' · aperçu local'));const follow=button('Suivre',null);follow.disabled=true;creator.append(follow);const actions=el('div',undefined,'os-native-actions');for(const label of ['♡ J’aime','☏ Commentaires']){const b=button(label,null);b.disabled=true;b.title='Disponible après connexion du Feed ONE au service';actions.append(b);}actions.append(button('↗ Partager',async()=>{const status=card.querySelector('[role=status]');try{if(navigator.canShare?.({files:[item.file]}))await navigator.share({files:[item.file],title:item.title});else status.textContent='Le partage de fichiers n’est pas disponible dans ce navigateur.';}catch(e){if(e.name!=='AbortError')status.textContent='Le partage n’a pas abouti.';}}));const save=el('a','↓ Sauvegarder');save.href=item.url;save.download=item.file.name;save.className='os-button';actions.append(save);const status=el('p');status.setAttribute('role','status');card.append(video,creator,el('p',item.title),actions,button('Regarder avec mon salon',()=>watch(item),'os-primary os-wide'),status);list.append(card);}if(!items.length){const empty=el('section',undefined,'os-feed-empty os-native-skeleton');empty.append(icon('one'),el('h2','Vos créations, plein écran.'),el('p',tab==='Abonnements'?'Les vidéos des comptes suivis apparaîtront ici.':'Aucune vidéo native publiée pour le moment.'),el('small','La publication, les likes et les commentaires attendent le service Feed ONE.'),button('Prévisualiser une vidéo locale',()=>chooseNative(()=>draw()),'os-primary'));list.append(empty);}}for(const name of ['Pour toi','Abonnements','Découvrir']){const b=button(name,()=>{tab=name;for(const x of tabs.children)x.setAttribute('aria-pressed',String(x===b));draw();});b.setAttribute('aria-pressed',String(name===tab));tabs.append(b);}shell.append(tabs,el('p','Les aperçus locaux restent dans cette session. Ils ne sont pas publiés.','os-muted'),list);draw();}
 document.getElementById('chips')?.addEventListener('click',stopPreview,true);window.ONEContent={renderTogether,renderFeed,watchWithSalon:watch,parseLink};
 window.addEventListener('one-party-state',()=>{const target=document.getElementById('oneTogetherMembers');if(target?.isConnected)roomMembers(target);});
 window.addEventListener('one-space-open',e=>{if(e.detail!=='together'&&e.detail!=='one')stopPreview();});
 window.addEventListener('one-account-changed',()=>{stopPreview();for(const item of previews)URL.revokeObjectURL(item.url);previews.length=0;selected=null;source='one';if(window.oneCurrentSpace?.()==='together')renderTogether(document.getElementById('oneFoundation'));if(window.oneCurrentSpace?.()==='one')renderFeed(document.getElementById('oneFoundation'));});
 window.addEventListener('pagehide',()=>{stopPreview();for(const item of previews)URL.revokeObjectURL(item.url);});
})();
