(()=>{
 const {el,button,tile,icon,avatar,activity,games}=ONEUI;const css=el('link');css.rel='stylesheet';css.href='ui/social.css?v=014116';document.head.append(css);
 let room=window.oneSocialRoom?.()||null,filter='Tous',selected='bluff';
 const capsule=button('',()=>window.oneOpenSalon?.(),'os-capsule');capsule.hidden=true;capsule.id='oneRoomCapsule';document.querySelector('.topbar .brandrow').after(capsule);
 function syncRoom(){capsule.hidden=!room;capsule.replaceChildren();if(room){capsule.append(el('span','● Salon · '+room.members.length));const faces=el('span',undefined,'os-mini-avatars');room.members.slice(0,3).forEach(m=>faces.append(avatar(m)));capsule.append(faces);capsule.setAttribute('aria-label',room.name+', '+room.members.length+' membres. Ouvrir le salon.');}const banner=document.getElementById('oneRoomBanner');if(banner){banner.replaceChildren();banner.hidden=!room;if(room){banner.append(el('b','Toujours ensemble'),el('p','Tu es dans le salon « '+room.name+' ». Navigue librement avec ton groupe.'),button('Voir le salon',()=>window.oneOpenSalon?.()));}}}
 function home(shell){shell.replaceChildren();const hero=el('section',undefined,'os-home-hero');hero.append(el('span','À PLUSIEURS, PARTOUT DANS ONE','os-eyebrow'),el('h1','Les mêmes moments.\nEnsemble.'),el('p','Ton salon, tes amis et les contenus que vous aimez.'),button('Ouvrir les salons',()=>window.oneOpenSalon?.(),'os-primary'));shell.append(hero);const banner=el('section',undefined,'os-room-banner');banner.id='oneRoomBanner';shell.append(banner);const strip=el('div',undefined,'os-home-links');strip.append(button('♧ Amis ONE',()=>window.oneOpenFriends?.()),button('＋ Créer une vidéo',()=>window.openOneStudio?.()));shell.append(strip,el('p','UNE SEULE APPLICATION. TOUS VOS MOMENTS.','os-home-signature'));syncRoom();}
 function nativeFeed(shell){window.ONEContent.renderFeed(shell);}
 function together(shell){window.ONEContent.renderTogether(shell);}
 function partyCatalog(parent,currentRoom=room){const box=el('section',undefined,'os-party-catalog');box.append(el('span','DES JEUX, UN SEUL GROUPE','os-eyebrow'),el('h2','Party'),el('p','Choisis ce que tu aimerais proposer à ton salon.','os-muted'));const tabs=el('nav',undefined,'os-tabs');tabs.setAttribute('aria-label','Catégories des jeux');const list=el('div',undefined,'os-game-grid'),detail=el('div');function draw(){list.replaceChildren();for(const g of games().filter(g=>filter==='Tous'||g.category===filter)){const b=button('',()=>{selected=g.id;draw();ONEUI.propose(g);},'os-game-card');b.setAttribute('aria-pressed',String(g.id===selected));b.append(window.ONEGameArt(g.id),el('b',g.name),el('small',g.min+'–'+g.max+' joueurs'));list.append(b);}}for(const name of ['Tous','Cartes','Ambiance']){const b=button(name,()=>{filter=name;for(const t of tabs.children)t.setAttribute('aria-pressed',String(t===b));draw();});b.setAttribute('aria-pressed',String(filter===name));tabs.append(b);}box.append(tabs,list,detail);parent.append(box);draw();}
 // Only the pre-game lobby changes. Existing running-game renderers remain intact.
 window.renderONELobby=({body,room})=>partyCatalog(body,room);
 if(window.ONEPublicRooms)window.ONEPublicRooms.catalog=body=>partyCatalog(body,null);
 function render(space){document.body.dataset.oneSocialSpace=space||'';const shell=document.getElementById('oneFoundation');if(!shell||shell.hidden)return;if(space==='home')home(shell);if(space==='one')nativeFeed(shell);if(space==='together')together(shell);if(space==='social'){shell.replaceChildren(el('h1','Amis ONE'),button('Retrouver mes amis',()=>window.oneOpenFriends?.(),'os-primary'));}}
 window.addEventListener('one-space-open',e=>render(e.detail));window.addEventListener('one-party-state',e=>{room=e.detail;syncRoom();});window.addEventListener('one-account-changed',()=>{room=null;syncRoom();document.querySelectorAll('.os-dialog').forEach(d=>d.close());});render(window.oneCurrentSpace?.());syncRoom();
})();
