function oneAmazonSearchHtml(query){const terms=String(query||'').trim().replace(/\s+/g,' ').slice(0,300);if(!terms)return '';const url='https://www.amazon.fr/s?k='+encodeURIComponent(terms);return '<section class="oneAmazonResults"><article class="oneAmazonCard"><small>RECHERCHE AMAZON.FR</small><strong>'+v17Escape(terms)+'</strong><p>Résultats de recherche, pas une fiche produit confirmée. Vérifie le modèle et la compatibilité avant achat.</p><a href="'+v17Escape(url)+'" target="_blank" rel="noopener noreferrer">Rechercher sur Amazon ↗</a></article></section>';}
function oneProductRequest(q){return /(?:ryzen|radeon|geforce|rtx|gtx|intel|amd|logitech|razer|steelseries|corsair|hyperx|playstation|xbox|nintendo|\bcore i[3579]\b|\b\d{4,5}x3d\b|casque|clavier|souris|micro|écran|ecran|setup|acheter|achat|prix|produit|manette|chaise|webcam|ordinateur|carte graphique|processeur|téléphone|smartphone|chaussure|veste|maillot|écouteur|ecouteur|pi[eè]ces?|accessoires?|batterie|chargeur|câble|cable|console|\bjeux?\b|\bssd\b|\bram\b|\bgpu\b|\bcpu\b|\bpc\b)/i.test(q);}
/* Amazon-only purchase results. Source evidence and purchase availability are separate. */
function oneAmazonProductUrl(value){try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||!(u.hostname==='amazon.fr'||u.hostname.endsWith('.amazon.fr')))return '';const m=u.pathname.match(/\/(?:dp|gp\/product)\/([A-Z0-9]{10})(?:\/|$)/i);return m?u.href:'';}catch{return '';}}
function oneAmazonRows(results,model){const seen=new Set();return (Array.isArray(results)?results:[]).flatMap(r=>{const url=oneAmazonProductUrl(r.url);if(!url||seen.has(url)||!oneOfferModelMatch(r.title||'',model)||oneOfferAccessory(r.title||'',model)||v1845VariantConflict((r.title||'').replace(/([0-9])([a-z])/gi,'$1 $2'),model.replace(/([0-9])([a-z])/gi,'$1 $2'))||v1839IsSecondHand(r))return [];seen.add(url);return [{title:r.title||model,_evidence:[r.content,r.snippet,r._evidence].filter(Boolean).join(' '),_merchantUrl:url,shop:'Amazon.fr',model}];}).slice(0,3);}
async function v1833ShopSearch(model){const spaced=model.replace(/([0-9])([a-z])/gi,'$1 $2');const queries=[spaced+' site:amazon.fr/dp/',model+' Amazon.fr fiche produit',model.replace(/\bTKL\b/gi,'Tenkeyless')+' site:amazon.fr'];const results=[];for(const q of [...new Set(queries)]){const data=await v1841WebResearch(q);results.push(...(Array.isArray(data?.results)?data.results:[]));const rows=oneAmazonRows(results,model);if(rows.length)return rows;}return [];}
function v1833ShopLiveHtml(offers,model=''){const rows=oneAmazonRows((offers||[]).map(o=>({url:o._merchantUrl,title:o.title,_evidence:o._evidence})),model);if(!rows.length)return oneAmazonSearchHtml(model);return '<section class="oneAmazonResults"><h4>Piste Amazon · à confirmer</h4><p class="aiProductNote">Le titre trouvé mentionne le modèle demandé. Vérifie aussi la variante sélectionnée sur Amazon. L’usage actuel par le créateur reste à confirmer.</p>'+rows.map(o=>'<article class="oneAmazonCard"><small>AMAZON.FR</small><strong>'+v17Escape(model)+'</strong><p>'+v17Escape(o.title)+'</p><span>Prix et disponibilité à vérifier sur Amazon.</span><a href="'+v17Escape(o._merchantUrl)+'" target="_blank" rel="noopener noreferrer">Voir le produit sur Amazon ↗</a></article>').join('')+'</section>';}
function oneAiProductsHtml(){return '';}
(()=>{const extract=v1841ExtractModel;v1841ExtractModel=function(q,data){const answer=String(data?.answer||'');const model=extract(q,{answer,results:[]});if(!model)return '';const evidence=(data?.results||[]).some(r=>oneOfferModelMatch((r.title||'')+' '+(r.content||r.snippet||''),model));return evidence?model:'';};})();
