import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {clone} from './vendor/SkeletonUtils.js';
const cache=new Map(),loader=new GLTFLoader();
const asset=name=>{if(!cache.has(name))cache.set(name,loader.loadAsync(new URL('../assets/bluff/'+name+'.glb',import.meta.url).href).catch(e=>{cache.delete(name);throw e;}));return cache.get(name);};
const ranks={A:'AS',K:'ROI',Q:'DAME',J:'JOKER'},symbols={A:'♠',K:'♚',Q:'♛',J:'✦'};
function cardTexture(rank){const c=document.createElement('canvas');c.width=256;c.height=384;const x=c.getContext('2d');x.fillStyle=rank?'#efe1c5':'#33192b';x.fillRect(0,0,256,384);x.strokeStyle='#ab824b';x.lineWidth=8;x.strokeRect(12,12,232,360);x.lineWidth=2;x.strokeRect(22,22,212,340);x.textAlign='center';x.fillStyle=rank?'#30201f':'#dcb778';x.font='bold 110px Georgia';x.fillText(rank?symbols[rank]:'✦',128,225);x.font='bold 27px Georgia';x.fillText(rank?ranks[rank]:'ONE',128,295);if(rank){x.font='bold 40px Georgia';x.fillText(rank,45,68);x.save();x.translate(256,384);x.rotate(Math.PI);x.fillText(rank,45,68);x.restore();}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function cardMesh(rank,textures){const front=cardTexture(rank),back=cardTexture(null);textures.push(front,back);const group=new T.Group();const geo=new T.BoxGeometry(.37,.56,.012);const edge=new T.MeshStandardMaterial({color:0xbda785,roughness:.8});const fm=new T.MeshStandardMaterial({map:front,roughness:.8}),bm=new T.MeshStandardMaterial({map:back,roughness:.8});const mesh=new T.Mesh(geo,[edge,edge,edge,edge,fm,bm]);mesh.castShadow=true;group.add(mesh);group.userData.face=fm;return group;}
export async function mount(host,players,pending,game,slots,isCancelled,eventStarted,eventKind){
 const [room,...loaded]=await Promise.all(['salon',...players.filter(p=>!p.isYou).map((p,i)=>['croupier','renard','corbeau'][i]),'main','revolver'].map(asset));
 if(isCancelled())return()=>{};
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;
 const canvas=renderer.domElement;canvas.className='bluff-canvas bluff-model-canvas';canvas.setAttribute('aria-label','Table de bluff 3D : cliquer une carte pour la sélectionner');host.prepend(canvas);
 const scene=new T.Scene();scene.background=new T.Color(0x160e13);scene.fog=new T.Fog(0x160e13,8,18);const camera=new T.PerspectiveCamera(43,1,.05,40);
 scene.add(new T.HemisphereLight(0xffddb1,0x342436,.9));const light=new T.DirectionalLight(0xffc584,2.7);light.position.set(-3,6,4);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:18});light.shadow.bias=-.001;scene.add(light);
 const fill=new T.PointLight(0x799bc9,30,10);fill.position.set(3,3,-2);scene.add(fill);
 const woodCanvas=document.createElement('canvas');woodCanvas.width=512;woodCanvas.height=512;const wx=woodCanvas.getContext('2d');wx.fillStyle='#684022';wx.fillRect(0,0,512,512);let seed=41;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<1400;i++){const y=random()*512;wx.strokeStyle=i%3?'#49291830':'#b5834630';wx.lineWidth=.5+random();wx.beginPath();wx.moveTo(0,y);wx.bezierCurveTo(170,y+random()*15,320,y-10,512,y+random()*8);wx.stroke();}const woodMap=new T.CanvasTexture(woodCanvas);woodMap.colorSpace=T.SRGBColorSpace;woodMap.wrapS=woodMap.wrapT=T.RepeatWrapping;woodMap.repeat.set(2,2);const woodMat=new T.MeshStandardMaterial({map:woodMap,roughness:.6,color:0xa37750});
 const world=room.scene.clone(true);scene.add(world);world.traverse(o=>{if(o.isMesh){o.receiveShadow=true;if(o.material.name.startsWith('Bois'))o.material=woodMat;}if(o.name.startsWith('Table_ronde'))o.visible=false;else if(o.name==='Table'||o.name==='Torus')o.position.y+=.8;if(o.name.startsWith('Plancher'))o.position.y+=.8;});
 const rivals=players.filter(p=>!p.isYou),actors=[],textures=[],owned=[];
 const positions=rivals.length===1?[[0,-1.9]]:rivals.length===2?[[-1.0,-1.6],[1.0,-1.6]]:[[-1.32,-1.5],[0,-2.0],[1.32,-1.5]];
 for(let i=0;i<rivals.length;i++){const model=clone(loaded[i].scene);model.position.set(positions[i][0],.12,positions[i][1]);model.scale.setScalar(.9);model.rotation.y=-positions[i][0]*.12;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const mixer=new T.AnimationMixer(model);loaded[i].animations.forEach(c=>mixer.clipAction(c).play());actors.push({model,mixer,head:model.getObjectByName("tete"),p:rivals[i],slot:slots[i]});}
 const handAsset=loaded.at(-2),hand=clone(handAsset.scene);hand.scale.setScalar(.60);hand.position.set(-.5,.35,2.38);scene.add(hand);const handMixer=new T.AnimationMixer(hand);for(const clip of handAsset.animations){const tracks=clip.tracks.filter(t=>!t.name.startsWith('Carte_'));if(tracks.length)handMixer.clipAction(new T.AnimationClip('Main',clip.duration,tracks)).play();}hand.traverse(o=>{if(o.name.startsWith('Carte_'))o.visible=false;if(o.isMesh)o.castShadow=true;});
 const right=new T.Group(),rightHand=clone(handAsset.scene),revolver=loaded.at(-1).scene.clone(true);rightHand.scale.set(-.45,.45,.45);rightHand.traverse(o=>{if(o.name.startsWith('Carte_'))o.visible=false;});const rightMixer=new T.AnimationMixer(rightHand);for(const clip of handAsset.animations){const tracks=clip.tracks.filter(t=>!t.name.startsWith('Carte_'));if(tracks.length)rightMixer.clipAction(new T.AnimationClip('Grip',clip.duration,tracks)).play();}rightMixer.setTime(0);revolver.position.set(0,.64,.12);right.add(rightHand);scene.add(revolver);right.position.set(.8,.45,1.9);scene.add(right);
 const own=[];for(let i=0;i<game.hand.length;i++){const c=cardMesh(game.hand[i].rank,textures),offset=i-(game.hand.length-1)/2;c.position.set(-.52+offset*.23,1.35,2.60+Math.abs(offset)*.015);c.rotation.set(-.12,0,-offset*.16);c.userData.id=game.hand[i].id;c.userData.baseY=c.position.y;c.userData.home=c.position.clone();c.userData.fan=c.rotation.z;c.userData.lift=0;scene.add(c);own.push(c);owned.push(c);}
 // Only the public count is used for opponents' backs; other players' ranks never enter this scene.
 for(const a of actors)for(let i=0;i<Math.min(5,a.p.count);i++){const c=cardMesh(null,textures);c.scale.setScalar(.44);c.position.set(a.model.position.x+(i-2)*.10,.96,a.model.position.z+.9);c.rotation.x=-Math.PI/2;scene.add(c);owned.push(c);}
 const thrown=[];for(let i=0;i<(pending?.count||0);i++){const c=cardMesh(null,textures);c.scale.setScalar(.65);c.rotation.x=-Math.PI/2;scene.add(c);thrown.push(c);owned.push(c);}
 const revealed=[];if(game.reveal)for(let i=0;i<game.reveal.cards.length;i++){const c=cardMesh(game.reveal.cards[i],textures);c.scale.setScalar(.68);c.position.set((i-(game.reveal.cards.length-1)/2)*.29,.975,0);scene.add(c);revealed.push(c);owned.push(c);}
 const started=eventStarted??-100000,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let dead=false,frame=0,last=0,w=0,h=0,yaw=0,drag=null;
 const ray=new T.Raycaster(),pointer=new T.Vector2();
 function down(e){drag={x:e.clientX,y:e.clientY,yaw};canvas.setPointerCapture(e.pointerId);}
 function move(e){if(drag)yaw=T.MathUtils.clamp(drag.yaw+(e.clientX-drag.x)/900,-.18,.18);}
 function up(e){if(!drag)return;const was=drag;drag=null;if(Math.hypot(e.clientX-was.x,e.clientY-was.y)>8)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(own,true)[0];if(hit){let obj=hit.object;while(obj&&!obj.userData.id)obj=obj.parent;const i=game.hand.findIndex(c=>c.id===obj?.userData.id);host.querySelectorAll('.bluff-card')[i]?.click();}}
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);
 function render(now){if(dead||!host.isConnected)return;frame=requestAnimationFrame(render);if(document.hidden||now-last<40)return;const dt=Math.min(.1,Math.max(.001,(now-last)/1000));last=now;const r=host.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;
  if(w!==host.clientWidth||h!==host.clientHeight){w=host.clientWidth;h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}

  const elapsed=(now-started)/1000,age=game.reveal?(Date.now()-game.reveal.at)/1000:999;const shot=game.rules==='roulette'&&age>=0&&age<3.2;
  const mine=players.find(p=>p.isYou),victim=actors.find(a=>a.p.accountId===game.reveal?.accountId),distance=w/h<.85?7.9:5.7,view=new T.Vector3(0,.85,0);camera.position.set(Math.sin(yaw)*distance,3.25,distance*Math.cos(yaw));
  let tableFocus=0,weaponFocus=0,collapse=0;if(shot&&!reduced){tableFocus=(1-T.MathUtils.smoothstep(age,.70,1.15))*T.MathUtils.smoothstep(age,0,.20);weaponFocus=T.MathUtils.smoothstep(age,.85,1.35)*(1-T.MathUtils.smoothstep(age,2.65,3.2));view.lerp(new T.Vector3(0,.93,0),tableFocus);camera.position.y+=tableFocus*.48;camera.position.z-=tableFocus*(w/h<.85?.55:.9);const aim=victim?new T.Vector3(victim.model.position.x,1.75,victim.model.position.z+.2):new T.Vector3(.8,1.65,1.65);view.lerp(aim,weaponFocus*.55);if(game.reveal.eliminated&&game.reveal.accountId===mine?.accountId){collapse=T.MathUtils.smoothstep(age,1.9,2.8);camera.position.y-=collapse*.8;}}
  camera.lookAt(view);if(collapse)camera.rotateZ(-collapse*.14);
  hand.position.y=.35-tableFocus*.55;
  for(const a of actors){let time=reduced?0:(now/1000)%1.95;if(shot&&a.p.accountId===game.reveal.accountId)time=a.p.eliminated&&age>2.1?6.67+(age-2.1)*1.18:3.56+(reduced?2.9:age);else if(a.p.eliminated)time=7.97;else if(pending?.accountId===a.p.accountId&&elapsed<1.3)time=2+elapsed;a.mixer.setTime(time);a.model.updateMatrixWorld(true);const pos=(a.head?a.head.localToWorld(new T.Vector3(0,.35,0)):new T.Vector3(0,1.95,0).applyMatrix4(a.model.matrixWorld)).project(camera);a.slot.style.left=(pos.x*.5+.5)*w+'px';a.slot.style.top=(-pos.y*.5+.5)*h+'px';a.slot.style.setProperty('--face',Math.max(24,42*h/500)+'px');}
  const throwing=pending?.accountId===mine?.accountId&&elapsed<2.6;handMixer.setTime(throwing&&!reduced?elapsed:0);
  for(let i=0;i<own.length;i++){const c=own[i],selected=host.querySelectorAll('.bluff-card')[i]?.getAttribute('aria-pressed')==='true';c.userData.lift=T.MathUtils.damp(c.userData.lift,selected?.13:0,18,dt);const deal=eventKind==='deal'&&!reduced?T.MathUtils.clamp((elapsed-2.2-i*.10)/.52,0,1):1,ease=1-Math.pow(1-deal,3);c.position.lerpVectors(new T.Vector3(0,.96,0),c.userData.home,ease);c.position.y+=c.userData.lift+Math.sin(deal*Math.PI)*.25-tableFocus*.7;c.rotation.set(T.MathUtils.lerp(-Math.PI/2,-.12,ease),0,c.userData.fan*ease);c.userData.face.emissive.setHex(selected?0x44300a:0);c.visible=deal>0;}
  revealed.forEach((c,i)=>{const t=reduced?1:T.MathUtils.clamp((age-i*.12)/.65,0,1);c.rotation.x=Math.PI/2+Math.PI*t;c.position.y=.975+Math.sin(t*Math.PI)*.18;});
  const source=actors.find(a=>a.p.accountId===pending?.accountId)?.model.position||new T.Vector3(0,0,1.4),t=reduced?1:Math.min(1,elapsed/.65);thrown.forEach((c,i)=>{const stagger=reduced?1:T.MathUtils.clamp((elapsed-i*.09)/.65,0,1),flight=1-Math.pow(1-stagger,2);c.position.set(T.MathUtils.lerp(source.x,-.18+i*.17,flight),.96+Math.sin(stagger*Math.PI)*.55+i*.012,T.MathUtils.lerp(source.z,0,flight));c.rotation.z=(1-stagger)*.7;c.rotation.y=Math.sin(stagger*Math.PI)*.25;});
  const ownShot=shot&&game.reveal.accountId===mine?.accountId;let reach=0,lift=0;if(ownShot&&!reduced){reach=Math.min(1,age/.6)*(1-T.MathUtils.smoothstep(age,2.75,3.2));lift=age>.6?Math.sin(Math.min(1,(age-.6)/2.6)*Math.PI):0;}right.position.set(.8+reach*.05,.45+lift*.8-tableFocus*.25,1.9-reach);right.rotation.x=-lift*.45;right.updateMatrixWorld(true);if(ownShot&&!reduced&&age>.55&&age<2.85){revolver.position.copy(new T.Vector3(0,.64,.12).applyMatrix4(right.matrixWorld));revolver.quaternion.copy(right.quaternion);revolver.rotateZ((1-Math.min(1,(age-.55)/.25))*Math.PI/2);}else{revolver.position.set(.85,1.01,1.02);revolver.rotation.set(0,0,Math.PI/2);}window.ONEBluffSound?.effect(game,reduced?1:age/3.2);
  renderer.render(scene,camera);
 }
 host.classList.add('bluff-model-ready');host.querySelector('.bluff-loading')?.remove();host.querySelector('.bluff-look').textContent='Clique les cartes · glisse pour regarder';frame=requestAnimationFrame(render);
 const onLost=e=>{e.preventDefault();dead=true;cancelAnimationFrame(frame);host.classList.remove('bluff-model-ready');host.dataset.modelError='La 3D a été interrompue. Les cartes restent accessibles.';};canvas.addEventListener('webglcontextlost',onLost);
 return()=>{dead=true;cancelAnimationFrame(frame);actors.forEach(a=>a.mixer.stopAllAction());handMixer.stopAllAction();rightMixer.stopAllAction();textures.forEach(t=>t.dispose());woodMap.dispose();woodMat.dispose();for(const group of owned)group.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of new Set(Array.isArray(o.material)?o.material:[o.material]))m.dispose();}});renderer.dispose();renderer.forceContextLoss();canvas.remove();host.classList.remove('bluff-model-ready');};
}

