import * as T from './vendor/three.module.js';
import {GLTFLoader} from './vendor/GLTFLoader.js';
import {clone} from './vendor/SkeletonUtils.js';
const cache=new Map(),loader=new GLTFLoader();
const asset=name=>{if(!cache.has(name))cache.set(name,loader.loadAsync(new URL('../assets/bluff/'+name+'.glb',import.meta.url).href).catch(e=>{cache.delete(name);throw e;}));return cache.get(name);};
const ranks={A:'AS',K:'ROI',Q:'DAME',J:'JOKER'},symbols={A:'♠',K:'♚',Q:'♛',J:'✦'};
function cardTexture(rank){const c=document.createElement('canvas');c.width=256;c.height=384;const x=c.getContext('2d');x.fillStyle=rank?'#efe1c5':'#33192b';x.fillRect(0,0,256,384);x.strokeStyle='#ab824b';x.lineWidth=8;x.strokeRect(12,12,232,360);x.lineWidth=2;x.strokeRect(22,22,212,340);x.textAlign='center';x.fillStyle=rank?'#30201f':'#dcb778';x.font='bold 110px Georgia';x.fillText(rank?symbols[rank]:'✦',128,225);x.font='bold 27px Georgia';x.fillText(rank?ranks[rank]:'ONE',128,295);if(rank){x.font='bold 40px Georgia';x.fillText(rank,45,68);x.save();x.translate(256,384);x.rotate(Math.PI);x.fillText(rank,45,68);x.restore();}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function cardMesh(rank,textures){const front=cardTexture(rank),back=cardTexture(null);textures.push(front,back);const group=new T.Group();const geo=new T.BoxGeometry(.37,.56,.012);const edge=new T.MeshStandardMaterial({color:0xbda785,roughness:.8});const fm=new T.MeshStandardMaterial({map:front,roughness:.8}),bm=new T.MeshStandardMaterial({map:back,roughness:.8});const mesh=new T.Mesh(geo,[edge,edge,edge,edge,fm,bm]);mesh.castShadow=true;group.add(mesh);group.userData.face=fm;return group;}
export async function mount(host,players,pending,game,slots,isCancelled,eventStarted,eventKind){
 const [room,...loaded]=await Promise.all(['salon',...players.filter(p=>!p.isYou).map(p=>['croupier','renard','corbeau','chasseur'].includes(p.avatar)?p.avatar:'croupier'),'main','revolver'].map(asset));
 if(isCancelled())return()=>{};
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;
 const canvas=renderer.domElement;canvas.className='bluff-canvas bluff-model-canvas';canvas.setAttribute('aria-label','Table de bluff 3D : cliquer une carte pour la sélectionner');host.prepend(canvas);
 const scene=new T.Scene();scene.background=new T.Color(0x160e13);scene.fog=new T.Fog(0x160e13,8,18);const camera=new T.PerspectiveCamera(43,1,.05,40);
 scene.add(new T.HemisphereLight(0xffddb1,0x342436,.9));const light=new T.DirectionalLight(0xffc584,2.7);light.position.set(-3,6,4);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:18});light.shadow.bias=-.001;scene.add(light);
 const fill=new T.PointLight(0x799bc9,30,10);fill.position.set(3,3,-2);scene.add(fill);
 const woodCanvas=document.createElement('canvas');woodCanvas.width=512;woodCanvas.height=512;const wx=woodCanvas.getContext('2d');wx.fillStyle='#684022';wx.fillRect(0,0,512,512);let seed=41;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<1400;i++){const y=random()*512;wx.strokeStyle=i%3?'#49291830':'#b5834630';wx.lineWidth=.5+random();wx.beginPath();wx.moveTo(0,y);wx.bezierCurveTo(170,y+random()*15,320,y-10,512,y+random()*8);wx.stroke();}const woodMap=new T.CanvasTexture(woodCanvas);woodMap.colorSpace=T.SRGBColorSpace;woodMap.wrapS=woodMap.wrapT=T.RepeatWrapping;woodMap.repeat.set(2,2);const woodMat=new T.MeshStandardMaterial({map:woodMap,roughness:.6,color:0xa37750});
 const emblemCanvas=document.createElement('canvas');emblemCanvas.width=1024;emblemCanvas.height=512;const ex=emblemCanvas.getContext('2d');ex.fillStyle='#120e14';ex.fillRect(0,0,1024,512);ex.strokeStyle='#ac8950';ex.lineWidth=7;ex.strokeRect(22,22,980,468);ex.lineWidth=2;ex.strokeRect(37,37,950,438);ex.textAlign='center';ex.fillStyle='#d9b77a';ex.font='bold 170px Georgia';ex.fillText('ONE',512,282);ex.font='26px Georgia';ex.fillStyle='#a98c60';ex.fillText('LE SALON DES OMBRES',512,350);const emblemMap=new T.CanvasTexture(emblemCanvas);emblemMap.colorSpace=T.SRGBColorSpace;const emblemGeometry=new T.BoxGeometry(2.0,1,.06),emblemMaterial=new T.MeshStandardMaterial({map:emblemMap,roughness:.6,emissive:0xb78d42,emissiveMap:emblemMap,emissiveIntensity:.35});const emblem=new T.Mesh(emblemGeometry,emblemMaterial);emblem.position.set(0,2.25,-3.6);scene.add(emblem);const ambience=new T.PointLight(0xff8c32,18,6);ambience.position.set(0,3,-2.6);scene.add(ambience);
 const world=room.scene.clone(true);scene.add(world);world.traverse(o=>{if(o.isMesh){o.receiveShadow=true;if(o.material.name.startsWith('Bois'))o.material=woodMat;}if(o.name.startsWith('Table_ronde'))o.visible=false;else if(o.name==='Table'||o.name==='Torus')o.position.y+=.8;if(o.name.startsWith('Plancher'))o.position.y+=.8;});
 const rivals=players.filter(p=>!p.isYou),actors=[],textures=[],owned=[];
 const positions=rivals.length===1?[[0,-1.9]]:rivals.length===2?[[-1.0,-1.6],[1.0,-1.6]]:[[-1.32,-1.5],[0,-2.0],[1.32,-1.5]];
 for(let i=0;i<rivals.length;i++){const model=clone(loaded[i].scene);model.position.set(positions[i][0],.12,positions[i][1]);const real=!!model.getObjectByName("mixamorigHead");model.scale.setScalar(real?1.5:.9);model.position.y=real?-.45:.12;model.rotation.y=-positions[i][0]*.12;scene.add(model);model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});const mixer=new T.AnimationMixer(model);loaded[i].animations.forEach(c=>mixer.clipAction(c).play());actors.push({model,mixer,head:model.getObjectByName("tete")||model.getObjectByName("mixamorigHead"),real:!!model.getObjectByName("mixamorigHead"),p:rivals[i],slot:slots[i]});}
 for(const a of actors.filter(a=>a.real)){a.weapon=loaded.at(-1).scene.clone(true);a.weapon.visible=false;scene.add(a.weapon);a.grip=a.model.getObjectByName('mixamorigRightHand');}
 const handAsset=loaded.at(-2),hand=clone(handAsset.scene);hand.scale.setScalar(.60);hand.position.set(-.5,.35,2.38);scene.add(hand);const handMixer=new T.AnimationMixer(hand);for(const clip of handAsset.animations){const tracks=clip.tracks.filter(t=>!t.name.startsWith('Carte_'));if(tracks.length)handMixer.clipAction(new T.AnimationClip('Main',clip.duration,tracks)).play();}hand.traverse(o=>{if(o.name.startsWith('Carte_'))o.visible=false;if(o.isMesh)o.castShadow=true;});
 const right=new T.Group(),rightHand=clone(handAsset.scene),revolver=loaded.at(-1).scene.clone(true);rightHand.scale.set(-.45,.45,.45);rightHand.traverse(o=>{if(o.name.startsWith('Carte_'))o.visible=false;});const rightMixer=new T.AnimationMixer(rightHand);for(const clip of handAsset.animations){const tracks=clip.tracks.filter(t=>!t.name.startsWith('Carte_'));if(tracks.length)rightMixer.clipAction(new T.AnimationClip('Grip',clip.duration,tracks)).play();}rightMixer.setTime(0);revolver.position.set(0,.64,.12);right.add(rightHand);scene.add(revolver);right.position.set(.8,.45,1.9);scene.add(right);const flash=new T.PointLight(0xffc678,0,4);scene.add(flash);const bloodGeometry=new T.BufferGeometry(),bloodPositions=new Float32Array(42*3);bloodGeometry.setAttribute('position',new T.BufferAttribute(bloodPositions,3));const bloodMaterial=new T.PointsMaterial({color:0xb91427,size:.11,toneMapped:false,transparent:true,opacity:0,depthWrite:false});const blood=new T.Points(bloodGeometry,bloodMaterial);blood.frustumCulled=false;scene.add(blood);
 handMixer.setTime(0);hand.updateMatrixWorld(true);const gripBone=hand.getObjectByName('poignet'),gripRest=gripBone?.matrixWorld.clone().invert(),gripDelta=new T.Matrix4();
 const own=[];for(let i=0;i<game.hand.length;i++){const c=cardMesh(game.hand[i].rank,textures),offset=i-(game.hand.length-1)/2;c.position.set(-.52+offset*.23,1.42,2.60+Math.abs(offset)*.015);c.rotation.set(-.12,0,-offset*.16);c.userData.id=game.hand[i].id;c.userData.baseY=c.position.y;c.userData.home=c.position.clone();c.userData.fan=c.rotation.z;c.userData.lift=0;scene.add(c);own.push(c);owned.push(c);}
 // Only the public count is used for opponents' backs; other players' ranks never enter this scene.
 for(const a of actors)for(let i=0;i<Math.min(5,a.p.count);i++){const c=cardMesh(null,textures);c.scale.setScalar(.44);c.position.set(a.model.position.x+(i-2)*.10,.96,a.model.position.z+.9);c.rotation.x=-Math.PI/2;scene.add(c);owned.push(c);}
 const thrown=[];for(let i=0;i<(pending?.count||0);i++){const c=cardMesh(null,textures);c.scale.setScalar(.65);c.rotation.x=-Math.PI/2;scene.add(c);thrown.push(c);owned.push(c);}
 const revealed=[];if(game.reveal)for(let i=0;i<game.reveal.cards.length;i++){const c=cardMesh(game.reveal.cards[i],textures);c.scale.setScalar(.68);c.position.set((i-(game.reveal.cards.length-1)/2)*.29,.975,0);scene.add(c);revealed.push(c);owned.push(c);}
 const lens=document.createElement('div');lens.className='bluff-blood-lens';lens.setAttribute('aria-hidden','true');const svgNS='http://www.w3.org/2000/svg',splatter=document.createElementNS(svgNS,'svg');splatter.setAttribute('viewBox','0 0 1000 600');splatter.setAttribute('preserveAspectRatio','none');for(let i=0;i<22;i++){const left=i%2===0,x=left?25+(i*37)%170:805+(i*29)%175,y=20+(i*79)%540,r=8+(i*11)%30;const spot=document.createElementNS(svgNS,'path');const points=[];for(let k=0;k<16;k++){const angle=k*Math.PI/8,rr=r*(.65+((k*7+i*3)%9)*.065);points.push([x+Math.cos(angle)*rr,y+Math.sin(angle)*rr*.8]);}let d='M'+(points[15][0]+points[0][0])/2+' '+(points[15][1]+points[0][1])/2;for(let k=0;k<16;k++){const cur=points[k],next=points[(k+1)%16];d+='Q'+cur[0]+' '+cur[1]+' '+(cur[0]+next[0])/2+' '+(cur[1]+next[1])/2;}spot.setAttribute('d',d+'Z');spot.setAttribute('fill',i%3?'#a30c21':'#690516');spot.setAttribute('opacity',String(.52+(i%3)*.12));splatter.append(spot);const drip=document.createElementNS(svgNS,'path');drip.setAttribute('d','M'+x+' '+y+' Q'+(x-5)+' '+(y+r*1.6)+' '+(x+2)+' '+(y+r*2.5));drip.setAttribute('stroke','#800819');drip.setAttribute('stroke-width',String(3+i%5));drip.setAttribute('stroke-linecap','round');drip.setAttribute('fill','none');splatter.append(drip);}lens.append(splatter);host.append(lens);
 const proof=document.createElement('div');proof.className='bluff-proof';proof.setAttribute('role','status');if(game.reveal){const names=game.reveal.cards.map(r=>ranks[r]).join(' · ');proof.textContent=(game.reveal.honest?'ANNONCE VRAIE':'BLUFF DÉCOUVERT')+' — '+names+' / demandé : '+ranks[game.reveal.target];host.append(proof);}let replayAt=-100000;const replay=()=>{replayAt=performance.now();};host.addEventListener('one-review-proof',replay);
 const stains=[],stainGeo=new T.CircleGeometry(1,14),stainMat=new T.MeshBasicMaterial({color:0x840d20,transparent:true,opacity:.88,depthWrite:false,side:T.DoubleSide,toneMapped:false});for(const player of players.filter(p=>p.eliminated)){const a=actors.find(a=>a.p.accountId===player.accountId),x=a?a.model.position.x*.72:.45,z=a?a.model.position.z+.8:1.05;for(let i=0;i<12;i++){const mark=new T.Mesh(stainGeo,stainMat),angle=i*2.399,r=i===0?.16:.025+((i*7)%5)*.016;mark.position.set(x+Math.cos(angle)*i*.014,1.006,z+Math.sin(angle)*i*.012);mark.rotation.x=-Math.PI/2;mark.scale.set(r,r*.7,1);mark.userData.player=player.accountId;scene.add(mark);stains.push(mark);}}
 const started=eventStarted??-100000,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let dead=false,frame=0,last=0,w=0,h=0,yaw=0,drag=null;
 const ray=new T.Raycaster(),pointer=new T.Vector2();
 function down(e){drag={x:e.clientX,y:e.clientY,yaw};canvas.setPointerCapture(e.pointerId);}
 function move(e){if(drag)yaw=T.MathUtils.clamp(drag.yaw+(e.clientX-drag.x)/900,-.18,.18);}
 function up(e){if(!drag)return;const was=drag;drag=null;if(Math.hypot(e.clientX-was.x,e.clientY-was.y)>8)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(own,true)[0];if(hit){let obj=hit.object;while(obj&&!obj.userData.id)obj=obj.parent;const i=game.hand.findIndex(c=>c.id===obj?.userData.id);host.querySelectorAll('.bluff-card')[i]?.click();}}
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);
 function render(now){if(dead||!host.isConnected)return;frame=requestAnimationFrame(render);if(document.hidden||now-last<40)return;const dt=Math.min(.1,Math.max(.001,(now-last)/1000));last=now;const r=host.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;
  if(w!==host.clientWidth||h!==host.clientHeight){w=host.clientWidth;h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}

  const elapsed=(now-started)/1000,age=game.reveal?(Date.now()-game.reveal.at)/1000:999;const shot=game.rules==='roulette'&&age>=0&&age<5.8;
  const mine=players.find(p=>p.isYou),victim=actors.find(a=>a.p.accountId===game.reveal?.accountId),distance=w/h<.85?7.9:5.7,view=new T.Vector3(0,.85,0);camera.position.set(Math.sin(yaw)*distance,3.25,distance*Math.cos(yaw));
  const reviewAge=(now-replayAt)/1000,reviewing=reviewAge>=0&&reviewAge<2.8,proofAge=reviewing?reviewAge:age,proofActive=!!game.reveal&&(reviewing||age>=0&&age<2.6),shotAge=Math.max(0,age-2.6);
  let tableFocus=0,weaponFocus=0,collapse=0;
  if(proofActive){const end=reviewing?2.8:2.6;tableFocus=reduced?0:T.MathUtils.smoothstep(proofAge,0,.25)*(1-T.MathUtils.smoothstep(proofAge,end-.30,end));}
  proof.hidden=!proofActive;host.classList.toggle('bluff-show-proof',proofActive);
  if(tableFocus){camera.position.lerp(new T.Vector3(0,2.35,1.15),tableFocus);view.lerp(new T.Vector3(0,.975,0),tableFocus);}
  if(shot&&!reviewing&&!reduced&&age>=2.6){weaponFocus=T.MathUtils.smoothstep(shotAge,0,.5)*(1-T.MathUtils.smoothstep(shotAge,2.65,3.2));const aim=victim?new T.Vector3(victim.model.position.x,1.75,victim.model.position.z+.2):new T.Vector3(.85,1.65,1.45);view.lerp(aim,weaponFocus*.55);if(game.reveal.eliminated&&game.reveal.accountId===mine?.accountId){collapse=T.MathUtils.smoothstep(shotAge,1.9,2.8);camera.position.y-=collapse*.8;}}
  camera.lookAt(view);if(collapse)camera.rotateZ(-collapse*.14);
  hand.position.y=.35-tableFocus*.55;
  for(const a of actors){let time=reduced?0:(now/1000)%1.95;if(shot&&a.p.accountId===game.reveal.accountId)time=age<2.6?0:a.p.eliminated&&shotAge>2.1?6.67+(shotAge-2.1)*1.18:3.56+(reduced?2.9:shotAge);else if(a.p.eliminated)time=7.97;else if(pending?.accountId===a.p.accountId&&elapsed<1.3)time=2+elapsed;a.mixer.setTime(Math.min(time,7.94));const dying=shot&&a.p.accountId===game.reveal.accountId&&game.reveal.eliminated;const fall=a.p.eliminated?(dying?T.MathUtils.smoothstep(shotAge,1.85,3.1):1):0;a.model.rotation.z=-fall*.12;a.model.position.y=(a.real?-.45:.12)+fall*.10;a.model.updateMatrixWorld(true);if(a.weapon&&a.grip){a.weapon.visible=shot&&age>=2.6&&a===victim&&!proofActive;a.weapon.position.copy(a.grip.getWorldPosition(new T.Vector3()));a.weapon.rotation.set(-.3,0,Math.PI/2*(1-Math.min(1,shotAge)));}const pos=(a.head?a.head.getWorldPosition(new T.Vector3()).add(new T.Vector3(0,a.real?.16:.3,0)):new T.Vector3(0,1.95,0).applyMatrix4(a.model.matrixWorld)).project(camera);a.slot.style.left=(pos.x*.5+.5)*w+'px';a.slot.style.top=(-pos.y*.5+.5)*h+'px';a.slot.style.setProperty('--face',Math.max(24,42*h/500)+'px');}
  const throwing=pending?.accountId===mine?.accountId&&elapsed<2.6;handMixer.setTime(throwing&&!reduced?elapsed:0);hand.updateMatrixWorld(true);if(gripBone)gripDelta.multiplyMatrices(gripBone.matrixWorld,gripRest);
  for(let i=0;i<own.length;i++){const c=own[i],selected=host.querySelectorAll('.bluff-card')[i]?.getAttribute('aria-pressed')==='true';c.userData.lift=T.MathUtils.damp(c.userData.lift,selected?.13:0,18,dt);const deal=eventKind==='deal'&&!reduced?T.MathUtils.clamp((elapsed-5.3-i*.10)/.52,0,1):1,ease=1-Math.pow(1-deal,3);c.position.lerpVectors(new T.Vector3(0,.96,0),gripBone?c.userData.home.clone().applyMatrix4(gripDelta):c.userData.home,ease);c.position.y+=c.userData.lift+Math.sin(deal*Math.PI)*.25-tableFocus*.7;c.rotation.set(T.MathUtils.lerp(-Math.PI/2,-.12,ease),0,c.userData.fan*ease);c.userData.face.emissive.setHex(selected?0x44300a:0);c.visible=deal>0;}
  revealed.forEach((c,i)=>{c.visible=proofActive||!pending;c.userData.face.emissive.setHex(proofActive?(game.reveal.cards[i]===game.reveal.target||game.reveal.cards[i]==='J'?0x15330a:0x66100a):0);const t=reduced||reviewing?1:T.MathUtils.clamp((age-i*.12)/.65,0,1);c.rotation.x=Math.PI/2+Math.PI*t;c.position.y=.975+Math.sin(t*Math.PI)*.18;});
  const source=actors.find(a=>a.p.accountId===pending?.accountId)?.model.position||new T.Vector3(0,0,1.4),t=reduced?1:Math.min(1,elapsed/.65);thrown.forEach((c,i)=>{c.visible=!proofActive;const stagger=reduced?1:T.MathUtils.clamp((elapsed-i*.09)/.65,0,1),flight=1-Math.pow(1-stagger,2);c.position.set(T.MathUtils.lerp(source.x,-.18+i*.17,flight),.96+Math.sin(stagger*Math.PI)*.55+i*.012,T.MathUtils.lerp(source.z,0,flight));c.rotation.z=(1-stagger)*.7;c.rotation.y=Math.sin(stagger*Math.PI)*.25;});
  const ownShot=shot&&age>=2.6&&!reviewing&&game.reveal.accountId===mine?.accountId;let reach=0,lift=0;if(ownShot&&!reduced){reach=Math.min(1,shotAge/.6)*(1-T.MathUtils.smoothstep(shotAge,2.75,3.2));lift=shotAge>.6?Math.sin(Math.min(1,(shotAge-.6)/2.6)*Math.PI):0;}right.position.set(.8+reach*.05,.45+lift*.8-tableFocus*.25,1.9-reach);right.rotation.x=-lift*.45;right.updateMatrixWorld(true);if(ownShot&&!reduced&&shotAge>.55&&shotAge<2.85){revolver.position.copy(new T.Vector3(0,.64,.12).applyMatrix4(right.matrixWorld));revolver.quaternion.copy(right.quaternion);revolver.rotateZ((1-Math.min(1,(shotAge-.55)/.25))*Math.PI/2);revolver.rotateY(-.35*Math.min(1,(shotAge-.55)/.5));}else{revolver.position.set(.85,1.01,1.02);revolver.rotation.set(0,0,Math.PI/2);}window.ONEBluffSound?.effect(game,reduced?1:shotAge/3.2);
  const fired=shot&&game.reveal.eliminated&&shotAge>1.76&&shotAge<2.0;flash.intensity=fired&&!reduced?8*(1-(shotAge-1.76)/.24):0;flash.position.copy(victim?new T.Vector3(victim.model.position.x,1.8,victim.model.position.z+.2):revolver.position);if(fired&&!reduced)camera.rotateX(Math.sin((shotAge-1.76)/.24*Math.PI)*.025);
  revolver.visible=!proofActive;hand.visible=!proofActive&&(!mine?.eliminated||shot);right.visible=hand.visible;if(mine?.eliminated&&shot){hand.position.y-=collapse*1.2;right.position.y-=collapse*1.2;}own.forEach(c=>{if(mine?.eliminated)c.visible=false;});own.forEach(c=>{if(proofActive)c.visible=false;});
  const lensAge=age-4.36;lens.style.opacity=game.reveal?.eliminated&&lensAge>=0&&lensAge<3.6&&!reviewing?String(Math.min(1,lensAge/.08)*(1-T.MathUtils.smoothstep(lensAge,1.7,3.6))):'0';
  const bloodAge=shotAge-1.76,bloodOn=shot&&game.reveal.eliminated&&bloodAge>=0&&bloodAge<1.4&&!reduced;blood.visible=bloodOn;if(bloodOn){const origin=victim?(victim.head?victim.head.getWorldPosition(new T.Vector3()).add(new T.Vector3(0,.15,0)):new T.Vector3(victim.model.position.x,1.8,victim.model.position.z)).add(new T.Vector3(0,0,.2)):new T.Vector3(.35,1.85,1.9);for(let i=0;i<42;i++){const a=i*2.399;bloodPositions[i*3]=origin.x+Math.cos(a)*bloodAge*(.3+i*.009);bloodPositions[i*3+1]=origin.y+Math.sin(a)*bloodAge*.45-bloodAge*bloodAge*.55;bloodPositions[i*3+2]=origin.z+bloodAge*(.25+(i%4)*.12);}bloodGeometry.attributes.position.needsUpdate=true;bloodMaterial.opacity=.95*(1-bloodAge/1.4);}
  for(const mark of stains)mark.visible=!proofActive&&(mark.userData.player!==game.reveal?.accountId||age>=4.36);
  renderer.render(scene,camera);
 }
 host.classList.add('bluff-model-ready');host.querySelector('.bluff-loading')?.remove();host.querySelector('.bluff-look').textContent='Clique les cartes · glisse pour regarder';frame=requestAnimationFrame(render);
 const onLost=e=>{e.preventDefault();dead=true;cancelAnimationFrame(frame);host.classList.remove('bluff-model-ready');host.dataset.modelError='La 3D a été interrompue. Les cartes restent accessibles.';};canvas.addEventListener('webglcontextlost',onLost);
 return()=>{host.removeEventListener('one-review-proof',replay);proof.remove();lens.remove();host.classList.remove('bluff-show-proof');dead=true;cancelAnimationFrame(frame);actors.forEach(a=>a.mixer.stopAllAction());handMixer.stopAllAction();rightMixer.stopAllAction();stainGeo.dispose();stainMat.dispose();bloodGeometry.dispose();bloodMaterial.dispose();emblemMap.dispose();emblemGeometry.dispose();emblemMaterial.dispose();textures.forEach(t=>t.dispose());woodMap.dispose();woodMat.dispose();for(const group of owned)group.traverse(o=>{if(o.isMesh){o.geometry.dispose();for(const m of new Set(Array.isArray(o.material)?o.material:[o.material]))m.dispose();}});renderer.dispose();renderer.forceContextLoss();canvas.remove();host.classList.remove('bluff-model-ready');};
}

