/* Original low-poly room, generated locally. WebGL 1, no external assets. */
(()=>{
 let stop=()=>{},lastAction='',actionStarted=0;
 window.addEventListener('one-game-before-render',()=>stop());
 window.addEventListener('pagehide',()=>stop());window.addEventListener('one-account-changed',()=>stop());window.addEventListener('one-party-state',e=>{if(!e.detail)stop();});
 window.ONEBluffScene=(host,players,pending,game)=>{const signature=game.id+':'+game.revision;if(signature!==lastAction){lastAction=signature;actionStarted=performance.now();}
  stop();const canvas=document.createElement('canvas');canvas.className='bluff-canvas';canvas.setAttribute('aria-label','Salon de bluff en trois dimensions');host.prepend(canvas);
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'low-power'});
  if(!gl){canvas.remove();host.classList.add('bluff-fallback');return;}
  const vs=`attribute vec3 pos;attribute vec3 normal;attribute vec3 color;attribute float motion;uniform float progress;uniform float clock;uniform float shot;uniform vec3 lift;uniform vec3 origin;uniform float aspect;uniform float yaw;uniform float pull;varying vec3 shade;
  void main(){float c=cos(yaw),s=sin(yaw);vec3 point=pos;if(motion>0.5&&motion<1.5){point+=origin*(1.0-progress);point.y+=sin(progress*3.14159)*.65;}if(motion>1.5&&motion<2.5){point.y+=sin(progress*3.14159)*.16;point.z-=sin(progress*3.14159)*.22;}if(motion>2.5&&motion<3.5){point.y+=sin(clock*1.7+pos.x)*.014;}if(motion>3.5&&motion<4.5){float raise=smoothstep(0.,.3,shot)*(1.-smoothstep(.75,1.,shot));point+=lift*raise;point.x+=sin(shot*50.)*.018*step(.55,shot)*(1.-step(.65,shot));}if(motion>4.5){point.y-=smoothstep(.62,.95,shot)*.7;}vec3 p=vec3(c*point.x+s*point.z,point.y,-s*point.x+c*point.z);float y=.954*(p.y-3.0)-.300*(p.z-7.0);float d=-.300*(p.y-3.0)-.954*(p.z-7.0)+pull;gl_Position=vec4(p.x*2.8/aspect,y*2.8,d*1.002-0.2002,d);float light=.32+.68*max(dot(normal,normalize(vec3(-.45,1.,.55))),0.);shade=color*light;}`;
  const fs=`precision mediump float;varying vec3 shade;void main(){gl_FragColor=vec4(shade,1.);}`;
  let observer,frame=0,dead=false,onVisibility=null;const shaders=[],buffers=[];
  stop=()=>{dead=true;cancelAnimationFrame(frame);if(onVisibility)document.removeEventListener('visibilitychange',onVisibility);observer?.disconnect();for(const b of buffers)gl.deleteBuffer(b);for(const s of shaders)gl.deleteShader(s);if(program)gl.deleteProgram(program);canvas.remove();};
  let program=null;
  try{
   const shader=(type,source)=>{const s=gl.createShader(type);shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Shader unavailable');return s;};
   program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Scene unavailable');gl.useProgram(program);
   let motion=0;const vertices=[];const tri=(a,b,c,n,col)=>{for(const p of [a,b,c])vertices.push(...p,...n,...col,motion);};
   function box(x,y,z,w,h,d,col){const v=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y+h,z-d/2],[x-w/2,y+h,z-d/2],[x-w/2,y,z+d/2],[x+w/2,y,z+d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];for(const [a,b,c,e,n]of [[0,1,2,3,[0,0,-1]],[4,7,6,5,[0,0,1]],[0,4,5,1,[0,-1,0]],[3,2,6,7,[0,1,0]],[0,3,7,4,[-1,0,0]],[1,5,6,2,[1,0,0]]]){tri(v[a],v[b],v[c],n,col);tri(v[a],v[c],v[e],n,col);}}
   function cylinder(x,y,z,r,h,col,segments=40){for(let i=0;i<segments;i++){const a=i*2*Math.PI/segments,b=(i+1)*2*Math.PI/segments,p=(t,dy)=>[x+r*Math.cos(t),y+dy,z+r*Math.sin(t)];tri([x,y+h,z],p(a,h),p(b,h),[0,1,0],col);const n=[Math.cos((a+b)/2),0,Math.sin((a+b)/2)];tri(p(a,0),p(b,0),p(b,h),n,col);tri(p(a,0),p(b,h),p(a,h),n,col);}}
   function sphere(x,y,z,rx,ry,rz,col){const p=(a,b)=>[x+rx*Math.sin(a)*Math.cos(b),y+ry*Math.cos(a),z+rz*Math.sin(a)*Math.sin(b)];for(let i=0;i<8;i++)for(let j=0;j<12;j++){const a=i*Math.PI/8,b=j*Math.PI/6,c=(i+1)*Math.PI/8,d=(j+1)*Math.PI/6;const n=[Math.sin((a+c)/2)*Math.cos((b+d)/2),Math.cos((a+c)/2),Math.sin((a+c)/2)*Math.sin((b+d)/2)];tri(p(a,b),p(c,b),p(c,d),n,col);tri(p(a,b),p(c,d),p(a,d),n,col);}}
   // Floorboards, back wall, pillars, shelves, bottles and warm lamps.
   for(let i=-7;i<7;i++)box(i,-1.18,0,.96,.12,18,[.14+(i%2)*.015,.09,.075]);
   box(0,-1.1,-5.2,16,7,.2,[.115,.075,.09]);for(let i=-7;i<=7;i+=2)box(i,-1,-5,.13,6,.2,[.22,.12,.10]);
   for(const x of [-4,4]){box(x,.6,-4.8,2.4,.14,.7,[.23,.13,.09]);box(x,2,-4.8,2.4,.14,.7,[.23,.13,.09]);for(let k=0;k<5;k++){const xx=x-.8+k*.4;cylinder(xx,2.14,-4.65,.10,.38,[.07,.23+k*.015,.16],8);cylinder(xx,2.5,-4.65,.047,.16,[.13,.24,.16],8);}cylinder(x,3.7,-4.3,.45,.1,[.75,.42,.13]);sphere(x,3.6,-4.3,.15,.24,.15,[1,.70,.26]);}
   // Thick wooden tabletop, inset velvet and supporting pedestal.
   cylinder(0,-1.1,0,.65,1.1,[.18,.09,.065]);cylinder(0,0,0,2.55,.20,[.30,.14,.095],80);cylinder(0,.20,0,2.48,.025,[.54,.30,.16],80);cylinder(0,.226,0,2.28,.015,[.18,.24,.22],80);
   const rivals=players.filter(p=>!p.isYou);const angles=rivals.length===1?[Math.PI]:rivals.length===2?[-2.12,2.12]:[-1.97,Math.PI,1.97];
   const slots=[];let gunLift=[0,0,0];const recentShot=game.rules==='roulette'&&game.reveal&&Date.now()-game.reveal.at<3400;const loserId=recentShot?game.reveal.accountId:null;
   function revolver(x,y,z){box(x,y,z,.12,.13,.45,[.25,.27,.29]);sphere(x,y+.07,z+.05,.10,.09,.13,[.34,.35,.36]);box(x,y-.15,z+.17,.11,.21,.12,[.29,.14,.08]);box(x,y+.13,z-.15,.04,.025,.045,[.53,.49,.38]);}
   rivals.forEach((p,i)=>{const angle=angles[i],x=Math.sin(angle)*2.9,z=Math.cos(angle)*2.9;const cloth=p.eliminated?[.15,.15,.17]:[[.28,.19,.35],[.19,.29,.30],[.34,.20,.16]][i];
    motion=0;box(x,-.5,z,.9,1.7,.45,[.16,.08,.06]);motion=p.eliminated?5:3;sphere(x,1.02,z,.47,.67,.29,cloth);sphere(x,1.98,z,.29,.36,.26,[.59,.39,.29]);cylinder(x,2.20,z,.36,.075,[.11,.09,.12],12);cylinder(x,2.26,z,.26,.22,cloth,12);
    // Coat lapels, buttons and facial details on the original characters.
    box(x-.13,.72,z+.29,.1,.65,.025,[.10,.09,.12]);box(x+.13,.72,z+.29,.1,.65,.025,[.10,.09,.12]);for(let b=0;b<3;b++)sphere(x,.86+b*.14,z+.31,.025,.025,.025,[.68,.52,.25]);sphere(x,1.92,z+.26,.06,.075,.08,[.65,.44,.32]);for(const eye of [-1,1]){sphere(x+eye*.105,2.04,z+.235,.048,.034,.025,[.10,.08,.07]);box(x+eye*.105,2.10,z+.24,.1,.018,.03,[.17,.10,.07]);}box(x,1.83,z+.25,.14,.025,.035,[.24,.11,.08]);
    for(const side of [-1,1]){sphere(x+side*.38,.83,z*.88,.17,.40,.22,cloth);sphere(x+side*.36,.41,z*.70,.18,.10,.22,[.59,.39,.29]);}
    motion=p.accountId===loserId?4:0;const gx=x+.5,gz=z*.67;revolver(gx,.34,gz);if(p.accountId===loserId)gunLift=[-.25,1.4,z+.1-gz];motion=0;
    for(let k=0;k<Math.min(p.count,5);k++)box(x+(k-2)*.10,.27,z*.72,.16,.014,.28,[.43,.24,.21]);
    slots.push({p,x,y:1.99,z:z+.27});
   });
   // First-person hands and facedown cards on the central pile.
   motion=2;sphere(-1.10,.39,2.28,.21,.11,.37,[.60,.40,.29]);sphere(1.10,.39,2.28,.21,.11,.37,[.60,.40,.29]);
   motion=players.find(p=>p.isYou)?.accountId===loserId?4:0;revolver(.8,.30,1.9);if(players.find(p=>p.isYou)?.accountId===loserId)gunLift=[.25,.7,.3];motion=1;for(let i=0;i<(pending?.count||0);i++)box(-.18+i*.14,.26+i*.014,.10,.36,.01,.53,[.57,.31,.18]);
   const buffer=gl.createBuffer();buffers.push(buffer);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);['pos','normal','color'].forEach((name,i)=>{const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,40,i*12);});const motionLoc=gl.getAttribLocation(program,'motion');gl.enableVertexAttribArray(motionLoc);gl.vertexAttribPointer(motionLoc,1,gl.FLOAT,false,40,36);gl.enable(gl.DEPTH_TEST);
   const overlays=slots.map(({p})=>{const node=document.createElement('div');node.className='bluff-person'+(p.isTurn?' active':'')+(p.faults>=3?' eliminated':'');const face=document.createElement('div');face.className='cg-face';face.dataset.cameraSeat=p.accountId;const initial=document.createElement('span');initial.className='cg-avatar';initial.textContent=p.name.slice(0,1).toUpperCase();initial.textContent='';initial.setAttribute('aria-label',p.name);face.style.background='transparent';face.style.borderColor='transparent';face.append(initial);const label=document.createElement('b');label.textContent=p.name;const info=document.createElement('small');info.textContent=p.faults>=3?'Éliminé':p.count+' cartes · '+(game.rules==='roulette'?(p.shots||0)+'/6':p.faults+'/3 erreurs');node.append(face,label,info);host.append(node);return node;});
   let yaw=0;const aspectLoc=gl.getUniformLocation(program,'aspect'),yawLoc=gl.getUniformLocation(program,'yaw'),pullLoc=gl.getUniformLocation(program,'pull');
   const clockLoc=gl.getUniformLocation(program,'clock'),shotLoc=gl.getUniformLocation(program,'shot'),liftLoc=gl.getUniformLocation(program,'lift');let lastFrame=0;
   const progressLoc=gl.getUniformLocation(program,'progress'),originLoc=gl.getUniformLocation(program,'origin');const source=slots.find(s=>s.p.accountId===pending?.accountId);const from=source?[source.x*.7,.15,source.z*.7]:[0,.2,2];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
   function draw(){if(dead)return;if(document.hidden)return;const now=performance.now();if(now-lastFrame<32){frame=requestAnimationFrame(draw);return;}lastFrame=now;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;const ratio=Math.min(devicePixelRatio||1,1.5),aspect=w/h,pull=Math.max(0,(1.3-aspect)*5);if(canvas.width!==Math.round(w*ratio)||canvas.height!==Math.round(h*ratio)){canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.038,.025,.047,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(aspectLoc,aspect);gl.uniform1f(yawLoc,yaw);gl.uniform1f(pullLoc,pull);const progress=reduced||document.hidden||!pending?1:Math.min(1,(performance.now()-actionStarted)/650);const shot=reduced?1:game.reveal?Math.min(1,Math.max(0,(Date.now()-game.reveal.at)/3200)):0;gl.uniform1f(clockLoc,reduced?0:now/1000);gl.uniform1f(shotLoc,shot);gl.uniform3fv(liftLoc,gunLift);gl.uniform1f(progressLoc,progress);gl.uniform3fv(originLoc,from);gl.drawArrays(gl.TRIANGLES,0,vertices.length/10);if(!reduced&&host.isConnected&&host.getBoundingClientRect().bottom>0){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);}
    slots.forEach((s,i)=>{const headY=s.y+(s.p.eliminated?-.7*Math.min(1,shot/.95):reduced?0:Math.sin(now/1000*1.7+s.x)*.014);const x=Math.cos(yaw)*s.x+Math.sin(yaw)*s.z,z=-Math.sin(yaw)*s.x+Math.cos(yaw)*s.z,y=.954*(headY-3)-.300*(z-7),d=-.300*(headY-3)-.954*(z-7)+pull;const n=overlays[i];n.style.left=(.5+x*2.8/aspect/d/2)*w+'px';n.style.top=(.5-y*2.8/d/2)*h+'px';n.style.setProperty('--face',Math.max(28,.54*2.8/d*h/2)+'px');});
   }
   let drag=null;canvas.onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX,start:yaw};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;yaw=Math.max(-.18,Math.min(.18,drag.start+(e.clientX-drag.x)/1200));cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
   canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();stop();overlays.forEach(n=>{n.style.left='';n.style.top='';});host.classList.add('bluff-fallback');});observer=new ResizeObserver(draw);observer.observe(host);onVisibility=()=>{if(!document.hidden)draw();};document.addEventListener('visibilitychange',onVisibility);draw();
  }catch(e){stop();host.classList.add('bluff-fallback');const p=document.createElement('p');p.textContent='La 3D est indisponible sur cet appareil. Les commandes du jeu restent accessibles.';host.append(p);}
 };
})();
