/* Original low-poly room, generated locally. WebGL 1, no external assets. */
(()=>{
 let stop=()=>{},lastAction='',actionStarted=0,audio=null,muted=false;const heard=new Set();
 function unlock(){if(muted)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
 document.addEventListener('pointerdown',e=>{if(e.target.closest('#onePartyGame')&&!e.target.closest('.bluff-sound'))unlock();},{passive:true});
 window.ONEBluffSound={enabled:()=>!muted&&audio?.state==='running',toggle:()=>{if(audio?.state==='running'&&!muted)muted=true;else{muted=false;unlock();}return !muted;}};
 function effect(game,phase,cinematic=false){if(window.ONEPremiumTables&&!cinematic)return;if(!game.reveal||game.rules!=='roulette'||phase<.55||Date.now()-game.reveal.at>(cinematic?20000:6200))return;const key=game.id+':'+game.reveal.at;if(heard.has(key))return;heard.add(key);if(heard.size>100)heard.delete(heard.values().next().value);if(muted||audio?.state!=='running'||document.hidden)return;const t=audio.currentTime;for(const delay of [0,.045]){const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(delay?870:1850,t+delay);osc.frequency.exponentialRampToValueAtTime(260,t+delay+.035);gain.gain.setValueAtTime(.0001,t+delay);gain.gain.exponentialRampToValueAtTime(.10,t+delay+.002);gain.gain.exponentialRampToValueAtTime(.0001,t+delay+.045);osc.connect(gain);gain.connect(audio.destination);osc.start(t+delay);osc.stop(t+delay+.05);}if(game.reveal.eliminated){const buffer=audio.createBuffer(1,Math.ceil(audio.sampleRate*.22),audio.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*Math.exp(-i/(audio.sampleRate*.045));const burst=audio.createBufferSource(),filter=audio.createBiquadFilter(),level=audio.createGain();burst.buffer=buffer;filter.type='lowpass';filter.frequency.value=4200;level.gain.value=.24;burst.connect(filter);filter.connect(level);level.connect(audio.destination);burst.start(t+.065);const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.setValueAtTime(95,t+.07);osc.frequency.exponentialRampToValueAtTime(38,t+.25);gain.gain.setValueAtTime(.12,t+.07);gain.gain.exponentialRampToValueAtTime(.0001,t+.32);osc.connect(gain);gain.connect(audio.destination);osc.start(t+.07);osc.stop(t+.33);}}

 window.ONEBluffSound.effect=effect;
 window.addEventListener('one-game-before-render',()=>stop());
 window.addEventListener('pagehide',()=>stop());window.addEventListener('one-account-changed',()=>stop());window.addEventListener('one-party-state',e=>{if(!e.detail)stop();});
 window.ONEBluffScene=(host,players,pending,game)=>{const signature=game.id+':'+game.revision;if(signature!==lastAction){lastAction=signature;actionStarted=performance.now();}
  stop();const canvas=document.createElement('canvas');canvas.className='bluff-canvas';canvas.setAttribute('aria-label','Salon de bluff en trois dimensions');host.prepend(canvas);
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false,powerPreference:'low-power'});
  if(!gl){canvas.remove();host.classList.add('bluff-fallback');return;}
  const vs=`attribute vec3 pos;attribute vec3 normal;attribute vec3 color;attribute float motion;uniform float progress;uniform float clock;uniform float shot;uniform vec3 lift;uniform vec3 origin;uniform float aspect;uniform float yaw;uniform float pull;varying vec3 shade;varying vec3 world;varying vec3 surface;
  void main(){float c=cos(yaw),s=sin(yaw);vec3 point=pos;if(motion>0.5&&motion<1.5){point+=origin*(1.0-progress);point.y+=sin(progress*3.14159)*.65;}if(motion>1.5&&motion<2.5){point.y+=sin(progress*3.14159)*.16;point.z-=sin(progress*3.14159)*.22;}if(motion>2.5&&motion<3.5){point.y+=sin(clock*1.7+pos.x)*.014;}if(motion>3.5&&motion<4.5){float raise=smoothstep(0.,.3,shot)*(1.-smoothstep(.75,1.,shot));point+=lift*raise;point.x+=sin(shot*50.)*.018*step(.55,shot)*(1.-step(.65,shot));}if(motion>4.5){point.y-=smoothstep(.62,.95,shot)*.7;}vec3 p=vec3(c*point.x+s*point.z,point.y,-s*point.x+c*point.z);float y=.954*(p.y-3.0)-.300*(p.z-7.0);float d=-.300*(p.y-3.0)-.954*(p.z-7.0)+pull;gl_Position=vec4(p.x*2.8/aspect,y*2.8,d*1.002-0.2002,d);world=point;surface=normal;shade=color;}`;
  const fs=`precision mediump float;varying vec3 shade;varying vec3 world;varying vec3 surface;
float hash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453);}
void main(){vec3 n=normalize(surface),base=shade;float grain=hash(floor(world*190.));
// Warm varnished wood, woven cloth and a soft skin response, lit per pixel.
if(base.r>base.g*1.35&&base.g>base.b*1.15){float veins=sin(world.x*39.+sin(world.z*4.)*3.+sin(world.x*7.+world.z)*2.);base*=.94+.035*veins+.025*grain;}else{base*=.94+.10*grain;}
vec3 l=normalize(vec3(-2.,4.5,2.)-world),r=normalize(vec3(3.,2.8,-2.)-world),v=normalize(vec3(0.,3.,7.)-world);
float diffuse=max(dot(n,l),0.),rim=max(dot(n,r),0.);float spec=pow(max(dot(n,normalize(l+v)),0.),40.);
float tabletop=1.-.26*exp(-dot(world.xz,world.xz)*.7);vec3 lit=base*(vec3(.21,.19,.23)+vec3(1.15,.79,.46)*diffuse+vec3(.28,.32,.42)*rim)*tabletop+vec3(.29,.20,.11)*spec;
float fog=smoothstep(5.,12.,length(world-vec3(0.,2.,4.)));lit=mix(lit,vec3(.035,.024,.033),fog*.66);gl_FragColor=vec4(pow(lit,vec3(.85)),1.);}`;
  let observer,frame=0,dead=false,onVisibility=null;let disposeGrip=()=>{},drawGrip=()=>{};const shaders=[],buffers=[];
  stop=()=>{dead=true;disposeGrip();cancelAnimationFrame(frame);if(onVisibility)document.removeEventListener('visibilitychange',onVisibility);observer?.disconnect();for(const b of buffers)gl.deleteBuffer(b);for(const s of shaders)gl.deleteShader(s);if(program)gl.deleteProgram(program);canvas.remove();};
  let program=null;
  try{
   const shader=(type,source)=>{const s=gl.createShader(type);shaders.push(s);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('Shader unavailable');return s;};
   program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('Scene unavailable');gl.useProgram(program);
   let motion=0;const vertices=[];const tri=(a,b,c,n,col)=>{for(const p of [a,b,c])vertices.push(...p,...n,...col,motion);};
   function box(x,y,z,w,h,d,col){const v=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y+h,z-d/2],[x-w/2,y+h,z-d/2],[x-w/2,y,z+d/2],[x+w/2,y,z+d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];for(const [a,b,c,e,n]of [[0,1,2,3,[0,0,-1]],[4,7,6,5,[0,0,1]],[0,4,5,1,[0,-1,0]],[3,2,6,7,[0,1,0]],[0,3,7,4,[-1,0,0]],[1,5,6,2,[1,0,0]]]){tri(v[a],v[b],v[c],n,col);tri(v[a],v[c],v[e],n,col);}}
   function cylinder(x,y,z,r,h,col,segments=40){for(let i=0;i<segments;i++){const a=i*2*Math.PI/segments,b=(i+1)*2*Math.PI/segments,p=(t,dy)=>[x+r*Math.cos(t),y+dy,z+r*Math.sin(t)];tri([x,y+h,z],p(a,h),p(b,h),[0,1,0],col);const n=[Math.cos((a+b)/2),0,Math.sin((a+b)/2)];tri(p(a,0),p(b,0),p(b,h),n,col);tri(p(a,0),p(b,h),p(a,h),n,col);}}
   function sphere(x,y,z,rx,ry,rz,col){const p=(a,b)=>[x+rx*Math.sin(a)*Math.cos(b),y+ry*Math.cos(a),z+rz*Math.sin(a)*Math.sin(b)];const emit=(a,b)=>{const n=[Math.sin(a)*Math.cos(b)/rx,Math.cos(a)/ry,Math.sin(a)*Math.sin(b)/rz],d=Math.hypot(...n);vertices.push(...p(a,b),...n.map(v=>v/d),...col,motion);};for(let i=0;i<14;i++)for(let j=0;j<24;j++){const a=i*Math.PI/14,b=j*Math.PI/12,c=(i+1)*Math.PI/14,d=(j+1)*Math.PI/12;for(const [u,v]of [[a,b],[c,b],[c,d],[a,b],[c,d],[a,d]])emit(u,v);}}
   function limb(a,b,r1,r2,col){const axis=b.map((v,i)=>v-a[i]),len=Math.hypot(...axis),w=axis.map(v=>v/len),u=Math.abs(w[1])<.9?[w[2],0,-w[0]]:[1,0,0],ul=Math.hypot(...u);u.forEach((v,i)=>u[i]=v/ul);const v=[w[1]*u[2]-w[2]*u[1],w[2]*u[0]-w[0]*u[2],w[0]*u[1]-w[1]*u[0]];const emit=(t,end)=>{const n=u.map((q,i)=>q*Math.cos(t)+v[i]*Math.sin(t)),pos=(end?b:a).map((q,i)=>q+n[i]*(end?r2:r1));vertices.push(...pos,...n,...col,motion);};for(let k=0;k<16;k++){const t=k*Math.PI/8,q=(k+1)*Math.PI/8;for(const [angle,end]of [[t,0],[q,0],[q,1],[t,0],[q,1],[t,1]])emit(angle,end);}}
   function hand(x,y,z,side=1,grip=false){const skin=[.56,.32,.20];sphere(x,y,z,.14,.075,.20,skin);for(let f=0;f<4;f++){const fx=x+(f-1.5)*.064,tip=z-(grip?.11:.30)+Math.abs(f-1.5)*.025;limb([fx,y,z-.09],[fx,y+(grip?.08:0),tip],.036,.028,skin);sphere(fx,y+(grip?.08:0),tip,.029,.033,.05,skin);sphere(fx,y+.065,z-.075,.039,.025,.045,[.61,.36,.23]);}limb([x+side*.12,y,z+.06],[x+side*.18,y+.035,z-.075],.049,.034,skin);}
   // Floorboards, back wall, pillars, shelves, bottles and warm lamps.
   for(let i=-7;i<7;i++)box(i,-1.18,0,.96,.12,18,[.14+(i%2)*.015,.09,.075]);
   box(0,-1.1,-5.2,16,7,.2,[.115,.075,.09]);for(let i=-7;i<=7;i+=2)box(i,-1,-5,.13,6,.2,[.22,.12,.10]);
   for(const x of [-4,4]){box(x,.6,-4.8,2.4,.14,.7,[.23,.13,.09]);box(x,2,-4.8,2.4,.14,.7,[.23,.13,.09]);for(let k=0;k<5;k++){const xx=x-.8+k*.4;cylinder(xx,2.14,-4.65,.10,.38,[.07,.23+k*.015,.16],8);cylinder(xx,2.5,-4.65,.047,.16,[.13,.24,.16],8);}cylinder(x,3.7,-4.3,.45,.1,[.75,.42,.13]);sphere(x,3.6,-4.3,.15,.24,.15,[1,.70,.26]);box(x,3.35,-4.48,.42,.58,.08,[.47,.26,.10]);}
   // Wall panels, brass rails, upholstery and framed art give the room depth.
   for(let k=-6;k<=6;k++){box(k,-.95,-4.96,.93,1.25,.09,[.20,.10,.075]);box(k,-.90,-4.88,.72,1.09,.05,[.12,.055,.038]);}
   box(0,.36,-4.84,14,.08,.17,[.44,.25,.12]);box(0,3.8,-4.89,2.5,.10,.10,[.55,.35,.14]);box(0,2.5,-4.89,2.5,.10,.10,[.55,.35,.14]);for(const x of [-1.2,1.2])box(x,2.5,-4.89,.09,1.4,.10,[.55,.35,.14]);box(0,2.57,-4.96,2.3,1.21,.03,[.10,.17,.17]);sphere(0,3.15,-4.88,.32,.43,.04,[.32,.22,.13]);
   // Thick wooden tabletop, inset velvet and supporting pedestal.
   cylinder(0,-1.1,0,.65,1.1,[.18,.09,.065]);cylinder(0,0,0,2.55,.20,[.30,.14,.095],80);cylinder(0,.20,0,2.48,.025,[.54,.30,.16],80);cylinder(0,.226,0,2.28,.015,[.43,.19,.10],96);cylinder(0,.243,0,1.27,.006,[.43,.58,.42],96);cylinder(0,.250,0,1.24,.006,[.43,.19,.10],96);
   const rivals=players.filter(p=>!p.isYou);const angles=rivals.length===1?[Math.PI]:rivals.length===2?[-2.12,2.12]:[-2.48,Math.PI,2.48];
   const slots=[];let gunLift=[0,0,0];const recentShot=game.rules==='roulette'&&game.reveal&&Date.now()-game.reveal.at<3400;const loserId=recentShot?game.reveal.accountId:null;
   function revolver(x,y,z){box(x,y,z,.12,.13,.45,[.25,.27,.29]);sphere(x,y+.07,z+.05,.10,.09,.13,[.34,.35,.36]);box(x,y-.15,z+.17,.11,.21,.12,[.29,.14,.08]);box(x,y+.13,z-.15,.04,.025,.045,[.53,.49,.38]);limb([x,y+.065,z-.42],[x,y+.065,z-.12],.043,.052,[.36,.38,.40]);sphere(x,y+.065,z-.42,.028,.028,.008,[.025,.025,.028]);if(motion===4){hand(x,y-.12,z+.20,1,true);limb([x+.06,y-.12,z+.32],[x+.18,y-.30,z+.72],.075,.12,[.25,.17,.12]);}}
   rivals.forEach((p,i)=>{const angle=angles[i],x=Math.sin(angle)*2.9,z=Math.cos(angle)*2.9;const cloth=p.eliminated?[.15,.15,.17]:[[.28,.19,.35],[.19,.29,.30],[.34,.20,.16]][i];
    const skin=[[.57,.34,.22],[.67,.43,.29],[.40,.25,.19]][i],shirt=[.62,.54,.40],dark=[.075,.055,.046];
    motion=0;box(x,-.5,z,.96,1.9,.35,[.16,.07,.045]);sphere(x,.92,z-.19,.48,.64,.12,[.26,.10,.065]);for(const dx of [-.48,.48])cylinder(x+dx,-.45,z,.065,1.92,[.37,.20,.09],16);
    motion=p.eliminated?5:3;
    // Shaped shoulders, waistcoat, collar, neck and articulated arms.
    sphere(x,1.03,z,.44,.57,.27,cloth);sphere(x,1.40,z,.53,.24,.28,cloth);sphere(x,1.14,z+.24,.27,.41,.085,shirt);
    cylinder(x,1.53,z,.135,.22,skin,24);sphere(x,1.97,z,.285,.355,.255,skin);sphere(x,1.77,z+.045,.23,.14,.20,skin);
    sphere(x,2.14,z-.09,.29,.23,.23,dark);for(const side of [-1,1]){sphere(x+side*.275,1.97,z,.060,.10,.055,skin);sphere(x+side*.12,1.92,z+.19,.12,.09,.09,skin);sphere(x+side*.105,2.045,z+.23,.071,.043,.034,[.75,.69,.55]);sphere(x+side*.105,2.045,z+.26,.026,.029,.014,[.065,.08,.065]);limb([x+side*.05,2.115,z+.24],[x+side*.17,2.12,z+.21],.022,.014,dark);}
    sphere(x,1.985,z+.26,.053,.085,.077,skin);sphere(x,1.86,z+.235,.12,.025,.023,[.24,.095,.06]);sphere(x,1.79,z+.21,.15,.065,.04,[.21,.14,.10]);
    if(i!==1){cylinder(x,2.22,z,.36,.055,dark,48);cylinder(x,2.26,z,.25,.22,cloth,48);cylinder(x,2.27,z,.256,.055,[.12,.065,.04],48);}
    for(const side of [-1,1]){limb([x+side*.15,1.52,z+.21],[x+side*.08,1.1,z+.30],.075,.025,dark);const shoulder=[x+side*.43,1.38,z],elbow=[x+side*.60,.67,z+.22],wrist=[x+side*.36,.40,z*.70+.12];limb(shoulder,elbow,.19,.135,cloth);sphere(...elbow,.14,.14,.14,cloth);limb(elbow,wrist,.135,.082,cloth);cylinder(wrist[0],wrist[1]-.03,wrist[2],.10,.055,shirt,24);hand(wrist[0],wrist[1],wrist[2]-.13,side);}
    for(let b=0;b<4;b++)sphere(x,.87+b*.13,z+.32,.020,.021,.014,[.70,.51,.22]);
    motion=p.accountId===loserId?4:0;const gx=x+.5,gz=z*.67;revolver(gx,.34,gz);if(p.accountId===loserId)gunLift=[-.25,1.4,z+.1-gz];motion=0;
    for(let k=0;k<Math.min(p.count,5);k++)box(x+(k-2)*.10,.27,z*.72,.16,.014,.28,[.43,.24,.21]);
    slots.push({p,x,y:1.99,z:z+.27});
   });
   // First-person hands and facedown cards on the central pile.
   const gripStart=vertices.length/10;motion=2;limb([-.70,-1.41,4.4],[-.25,-.68,3.35],.19,.10,[.24,.16,.11]);hand(-.25,-.65,3.22,-1,true);const gripCount=vertices.length/10-gripStart;limb([1.25,-.10,3.5],[1.0,.33,2.5],.19,.10,[.24,.16,.11]);hand(1,.36,2.4,1);
   motion=players.find(p=>p.isYou)?.accountId===loserId?4:0;revolver(.8,.30,1.9);if(players.find(p=>p.isYou)?.accountId===loserId)gunLift=[.25,.7,.3];motion=1;for(let i=0;i<(pending?.count||0);i++)box(-.18+i*.14,.26+i*.014,.10,.36,.01,.53,[.57,.31,.18]);
   const buffer=gl.createBuffer();buffers.push(buffer);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);['pos','normal','color'].forEach((name,i)=>{const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,40,i*12);});const motionLoc=gl.getAttribLocation(program,'motion');gl.enableVertexAttribArray(motionLoc);gl.vertexAttribPointer(motionLoc,1,gl.FLOAT,false,40,36);gl.enable(gl.DEPTH_TEST);

   // A transparent foreground pass places the modelled thumb over the clickable cards.
   const gripCanvas=document.createElement('canvas');gripCanvas.className='bluff-grip';gripCanvas.setAttribute('aria-hidden','true');host.append(gripCanvas);const gg=gripCanvas.getContext('webgl',{alpha:true,antialias:true,powerPreference:'low-power'});
   if(gg){const pp=gg.createProgram(),ss=[];for(const [type,src]of [[gg.VERTEX_SHADER,vs],[gg.FRAGMENT_SHADER,fs]]){const sh=gg.createShader(type);gg.shaderSource(sh,src);gg.compileShader(sh);ss.push(sh);gg.attachShader(pp,sh);}gg.linkProgram(pp);if(gg.getProgramParameter(pp,gg.LINK_STATUS)){gg.useProgram(pp);const bb=gg.createBuffer();gg.bindBuffer(gg.ARRAY_BUFFER,bb);gg.bufferData(gg.ARRAY_BUFFER,new Float32Array(vertices.slice(gripStart*10,(gripStart+gripCount)*10)),gg.STATIC_DRAW);for(const [i,name]of ['pos','normal','color','motion'].entries()){const l=gg.getAttribLocation(pp,name);gg.enableVertexAttribArray(l);gg.vertexAttribPointer(l,i===3?1:3,gg.FLOAT,false,40,i*12);}gg.enable(gg.DEPTH_TEST);const u={};for(const name of ['aspect','yaw','pull','progress','clock','shot','lift','origin'])u[name]=gg.getUniformLocation(pp,name);drawGrip=(w,h,a,y,p,progress)=>{if(gripCanvas.width!==w||gripCanvas.height!==h){gripCanvas.width=w;gripCanvas.height=h;}gg.viewport(0,0,w,h);gg.clearColor(0,0,0,0);gg.clear(gg.COLOR_BUFFER_BIT|gg.DEPTH_BUFFER_BIT);for(const [name,value]of Object.entries({aspect:a,yaw:y,pull:p,progress,clock:0,shot:0}))gg.uniform1f(u[name],value);gg.uniform3fv(u.lift,[0,0,0]);gg.uniform3fv(u.origin,[0,0,0]);gg.drawArrays(gg.TRIANGLES,0,gripCount);};disposeGrip=()=>{gg.deleteBuffer(bb);ss.forEach(sh=>gg.deleteShader(sh));gg.deleteProgram(pp);gripCanvas.remove();};}else{ss.forEach(sh=>gg.deleteShader(sh));gg.deleteProgram(pp);gripCanvas.remove();}}else gripCanvas.remove();
   const overlays=slots.map(({p})=>{const node=document.createElement('div');node.className='bluff-person'+(p.isTurn?' active':'')+(p.eliminated?' eliminated':'');const face=document.createElement('div');face.className='cg-face';face.dataset.cameraSeat=p.accountId;const initial=document.createElement('span');initial.className='cg-avatar';initial.textContent=p.name.slice(0,1).toUpperCase();initial.textContent='';initial.setAttribute('aria-label',p.name);face.style.background='transparent';face.style.borderColor='transparent';face.append(initial);const label=document.createElement('b');label.textContent=p.name;const info=document.createElement('small');info.textContent=p.eliminated?'Éliminé':p.count+' cartes · '+(game.rules==='roulette'?(p.shots||0)+'/6':p.faults+'/3 erreurs');node.append(face,label,info);host.append(node);return node;});
   let yaw=0;const aspectLoc=gl.getUniformLocation(program,'aspect'),yawLoc=gl.getUniformLocation(program,'yaw'),pullLoc=gl.getUniformLocation(program,'pull');
   const clockLoc=gl.getUniformLocation(program,'clock'),shotLoc=gl.getUniformLocation(program,'shot'),liftLoc=gl.getUniformLocation(program,'lift');let lastFrame=0;
   const progressLoc=gl.getUniformLocation(program,'progress'),originLoc=gl.getUniformLocation(program,'origin');const source=slots.find(s=>s.p.accountId===pending?.accountId);const from=source?[source.x*.7,.15,source.z*.7]:[0,.2,2];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
   function draw(){if(dead)return;if(document.hidden)return;const now=performance.now();if(now-lastFrame<32){frame=requestAnimationFrame(draw);return;}lastFrame=now;const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;const ratio=Math.min(devicePixelRatio||1,1.5),aspect=w/h,pull=Math.max(0,(1.3-aspect)*5);if(canvas.width!==Math.round(w*ratio)||canvas.height!==Math.round(h*ratio)){canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);}gl.viewport(0,0,canvas.width,canvas.height);gl.clearColor(.038,.025,.047,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(aspectLoc,aspect);gl.uniform1f(yawLoc,yaw);gl.uniform1f(pullLoc,pull);const progress=reduced||document.hidden||!pending?1:Math.min(1,(performance.now()-actionStarted)/650);const shot=reduced?1:game.reveal?Math.min(1,Math.max(0,(Date.now()-game.reveal.at)/3200)):0;effect(game,shot);gl.uniform1f(clockLoc,reduced?0:now/1000);gl.uniform1f(shotLoc,shot);gl.uniform3fv(liftLoc,gunLift);gl.uniform1f(progressLoc,progress);gl.uniform3fv(originLoc,from);gl.drawArrays(gl.TRIANGLES,0,vertices.length/10);drawGrip(canvas.width,canvas.height,aspect,yaw,pull,progress);if(!reduced&&host.isConnected&&host.getBoundingClientRect().bottom>0){cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);}
    slots.forEach((s,i)=>{const headY=s.y+(s.p.eliminated?-.7*Math.min(1,shot/.95):reduced?0:Math.sin(now/1000*1.7+s.x)*.014);const x=Math.cos(yaw)*s.x+Math.sin(yaw)*s.z,z=-Math.sin(yaw)*s.x+Math.cos(yaw)*s.z,y=.954*(headY-3)-.300*(z-7),d=-.300*(headY-3)-.954*(z-7)+pull;const n=overlays[i];n.style.left=(.5+x*2.8/aspect/d/2)*w+'px';n.style.top=(.5-y*2.8/d/2)*h+'px';n.style.setProperty('--face',Math.max(28,.54*2.8/d*h/2)+'px');});
   }
   let drag=null;canvas.onpointerdown=e=>{drag={id:e.pointerId,x:e.clientX,start:yaw};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;yaw=Math.max(-.18,Math.min(.18,drag.start+(e.clientX-drag.x)/1200));cancelAnimationFrame(frame);frame=requestAnimationFrame(draw);};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
   canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();stop();overlays.forEach(n=>{n.style.left='';n.style.top='';});host.classList.add('bluff-fallback');});observer=new ResizeObserver(draw);observer.observe(host);onVisibility=()=>{if(!document.hidden)draw();};document.addEventListener('visibilitychange',onVisibility);draw();
  }catch(e){stop();host.classList.add('bluff-fallback');const p=document.createElement('p');p.textContent='La 3D est indisponible sur cet appareil. Les commandes du jeu restent accessibles.';host.append(p);}
 };
})();
