/* The same published catalogue powers Boutique and product requests in ONE IA. */
(()=>{
 const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 let items=[],loaded=false,pending=null;
 async function load(){if(loaded)return items;if(pending)return pending;pending=(async()=>{const r=await fetch('ui/boutique-catalog.json?v=118b1',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Catalogue indisponible');const data=await r.json();if(!Array.isArray(data.items))throw Error('Catalogue invalide');items=data.items.filter(p=>p&&p.status==='published'&&typeof p.id==='string'&&typeof p.title==='string'&&p.title.trim()&&['new','used'].includes(p.market)&&['creator','business','private'].includes(p.sellerType)&&Number.isFinite(p.price)&&p.price>0&&p.currency==='EUR');loaded=true;return items;})();try{return await pending;}finally{pending=null;}}
 function parse(query){const q=normalize(query),budget=q.match(/(?:moins de|maximum|max(?:i)?|budget(?: de)?|jusqu.?a|sous)\s*(\d+(?:[.,]\d+)?)/);const market=/\b(occasion|seconde main|vinted)\b/.test(q)?'used':/\b(neuf|neuve|neufs|neuves)\b/.test(q)?'new':null;const sellerType=/\b(particulier|particuliers)\b/.test(q)?'private':/\b(createur|createurs)\b/.test(q)?'creator':/\b(entreprise|entreprises)\b/.test(q)?'business':null;
  const stop=new Set('je j tu il elle on nous vous cherche cherches chercher recherche recherches rechercher trouve trouver moi voudrais veux souhaite acheter achat acheter acheter un une des de du le la les en et ou avec pour qui que quoi quel quelle quels quelles a au aux d l sur mon ma mes dans boutique catalogue one ia neuf neuve neufs neuves occasion seconde main vinted moins maximum maxi max budget jusqu sous euros euro prix produits produit article articles particulier particuliers createur createurs entreprise entreprises'.split(' '));
  const cleaned=q.replace(/(?:moins de|maximum|max(?:i)?|budget(?: de)?|jusqu.?a|sous)\s*\d+(?:[.,]\d+)?\s*(?:€|euros?)?/g,'');const words=cleaned.match(/[a-z0-9]+/g)||[];return{market,sellerType,maxPrice:budget?Number(budget[1].replace(',','.')):null,words:words.filter(w=>!stop.has(w)&&w.length>1)};
 }
 function filter(list,query='',options={}){const p=parse(query),market=options.market||p.market,seller=options.seller==='all'?p.sellerType:options.seller||p.sellerType;return list.filter(item=>{if(market&&item.market!==market)return false;if(seller&&item.sellerType!==seller)return false;if(options.category&&options.category!=='Tout'&&item.category!==options.category)return false;if(options.condition&&options.condition!=='Tous les états'&&item.condition!==options.condition)return false;if(p.maxPrice!==null&&item.price>p.maxPrice)return false;const text=normalize([item.title,item.brand,item.description,item.category,item.size,item.sellerName,...(Array.isArray(item.tags)?item.tags:[])].join(' '));return p.words.every(w=>text.includes(w)||w.length>3&&w.endsWith('s')&&text.includes(w.slice(0,-1)));});}
 const search=async(query,options)=>filter(await load(),query,options);
 const handles=q=>window.oneCurrentSpace?.()==='shop'||window.oneProductRequest?.(q)||/\b(boutique|catalogue|occasion|vinted|acheter|robe|pantalon|sac|sneakers|meuble|bijou)\b/i.test(q);
 async function answer(q,host){host.replaceChildren();const line=document.createElement('p');line.textContent='Recherche dans le catalogue ONE…';host.append(line);try{const found=await search(q);line.textContent=found.length?found.length+' article'+(found.length>1?'s':'')+' trouvé'+(found.length>1?'s':'')+' dans la Boutique ONE.':'Aucun article correspondant dans le catalogue ONE pour le moment.';for(const item of found.slice(0,5)){const p=document.createElement('p');p.textContent=item.title+' · '+new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(item.price)+' · '+(item.market==='used'?'Occasion':'Neuf');host.append(p);}const note=document.createElement('small');note.textContent='Résultats issus uniquement des annonces publiées dans ONE. Aucun résultat Web ajouté.';host.append(note);const open=document.createElement('button');open.type='button';open.className='oneShopAiLink';open.textContent='Voir la Boutique →';open.onclick=()=>{document.getElementById('closeAi')?.click();document.getElementById('videoAiClose')?.click();window.dispatchEvent(new CustomEvent('one-shop-search',{detail:q}));};host.append(open);}catch{line.textContent='Le catalogue ONE est momentanément indisponible. Réessaie dans quelques instants.';}}
 window.ONEBoutiqueCatalog={load,search,filter,parse,handles,answer};
})();
