/* Boutique entry and private listing drafts. No checkout or public publishing yet. */
(()=>{
 const style=document.createElement('link');style.rel='stylesheet';style.href='ui/boutique.css?v=118b1';document.head.append(style);
 const e=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
 const button=(text,fn,cls='')=>{const n=e('button',cls,text);n.type='button';n.onclick=fn;return n;};
 const bag='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></svg>';
 const entry=button('',()=>window.oneShowSpace?.('shop'));entry.id='oneShopToggle';entry.setAttribute('aria-label','Boutique');entry.setAttribute('aria-controls','oneShop');entry.innerHTML=bag+'<span>Boutique</span>';
 (document.getElementById('onePointsToggle')||document.getElementById('oneSearchToggle'))?.after(entry);
 const categories=['Tout','Mode','Beauté','Maison','High-tech','Jeux & loisirs'];
 const sellers={all:'Tous les vendeurs',creator:'Créateurs',business:'Entreprises',private:'Particuliers'};
 let market='new',category='Tout',seller='all',query='',view='catalog',dialog=null,conditionFilter='Tous les états',resultEpoch=0;
 const draftKey=()=>'one_shop_drafts_118:'+String(window.oneAccountLocal?.()?.id||'visitor');
 function readDrafts(){try{const v=JSON.parse(localStorage.getItem(draftKey())||'[]');return Array.isArray(v)?v.filter(d=>d&&typeof d.title==='string'):[];}catch{return [];}}
 function storeDraft(draft){const list=readDrafts(),index=list.findIndex(d=>d.id===draft.id);if(index<0)list.unshift(draft);else list[index]=draft;localStorage.setItem(draftKey(),JSON.stringify(list));}
 function openDraft(existing){
  const accountKey=draftKey(),origin=document.activeElement;dialog?.close();const box=e('dialog','oneShopEditor');dialog=box;box.setAttribute('aria-labelledby','oneShopEditorTitle');
  const head=e('header'),title=e('h2','',existing?'Modifier le brouillon':'Préparer une annonce');title.id='oneShopEditorTitle';const close=button('×',()=>box.close(),'shop-close');close.setAttribute('aria-label','Fermer le brouillon');head.append(title,close);
  const form=e('form'),notice=e('p','shop-form-note','Ton brouillon reste privé sur cet appareil. La publication et les achats seront disponibles à l’ouverture de la Boutique.');
  function field(label,name,type,value,options){const wrap=e('label','shop-field',label),input=e(options?'select':'input');input.name=name;if(options){for(const [key,text]of options){const opt=e('option','',text);opt.value=key;input.append(opt);}}else input.type=type;input.value=value||'';wrap.append(input);form.append(wrap);return input;}
  const audience=field('Je vends en tant que','seller','',existing?.seller||'private',Object.entries(sellers).filter(([k])=>k!=='all'));
  const area=field('Rubrique','market','',existing?.market||market,[['new','Neuf'],['used','Occasion']]);
  const name=field('Titre de l’annonce','title','text',existing?.title);name.required=true;name.maxLength=90;name.placeholder='Ex. : veste en jean, taille M';
  const cat=field('Catégorie','category','',existing?.category||'Mode',categories.slice(1).map(c=>[c,c]));
  const price=field('Prix en euros','price','number',existing?.price);price.required=true;price.min='0.01';price.max='999999';price.step='0.01';price.inputMode='decimal';price.placeholder='0,00';
  const condition=field('État','condition','',existing?.condition||'Très bon état',[['Neuf avec étiquette','Neuf avec étiquette'],['Neuf sans étiquette','Neuf sans étiquette'],['Très bon état','Très bon état'],['Bon état','Bon état'],['État satisfaisant','État satisfaisant']]);
  const size=field('Taille ou dimensions (facultatif)','size','text',existing?.size);size.maxLength=50;size.placeholder='Ex. : M, 38, 120 × 60 cm';
  const descLabel=e('label','shop-field','Description'),desc=e('textarea');desc.name='description';desc.maxLength=1500;desc.rows=4;desc.value=existing?.description||'';desc.placeholder='Décris ton article et ses éventuels défauts.';descLabel.append(desc);form.append(descLabel);
  const syncCondition=()=>{condition.disabled=area.value==='new';condition.parentElement.hidden=area.value==='new';};area.onchange=syncCondition;syncCondition();
  const feedback=e('p','shop-form-feedback');feedback.setAttribute('role','status');const save=e('button','shop-primary','Enregistrer le brouillon');save.type='submit';
  form.onsubmit=event=>{event.preventDefault();if(draftKey()!==accountKey){feedback.textContent='Le compte a changé. Rouvre ton brouillon.';return;}if(!form.reportValidity())return;if(!name.value.trim()){feedback.textContent='Ajoute un titre à ton annonce.';return;}try{storeDraft({id:existing?.id||crypto.randomUUID(),title:name.value.trim(),seller:audience.value,market:area.value,category:cat.value,price:Number(price.value),condition:area.value==='new'?'Neuf':condition.value,size:size.value.trim(),description:desc.value.trim(),updatedAt:Date.now()});view='drafts';box.close();render();}catch{feedback.textContent='Le brouillon n’a pas pu être enregistré. Garde cette fenêtre ouverte et réessaie.';}};
  form.append(feedback,save);box.append(head,notice,form);document.body.append(box);box.addEventListener('close',()=>{if(dialog===box)dialog=null;box.remove();if(origin?.isConnected)origin.focus({preventScroll:true});},{once:true});box.showModal();
 }
 function render(){
  const root=document.getElementById('oneShop');if(!root||window.oneCurrentSpace?.()!=='shop')return;root.replaceChildren();
  const heading=e('header','shop-heading'),word=e('div');word.append(e('span','shop-eyebrow','ONE · BOUTIQUE'),e('h1','','À chacun sa trouvaille.'));const actions=e('div','shop-actions');actions.append(button('Mes brouillons'+(readDrafts().length?' · '+readDrafts().length:''),()=>{view=view==='drafts'?'catalog':'drafts';render();},'shop-secondary'),button('＋ Vendre',()=>openDraft(),'shop-primary'));heading.append(word,actions);root.append(heading);
  const tabs=e('nav','shop-market-tabs');tabs.setAttribute('aria-label','Rayons de la Boutique');for(const [id,label,detail]of [['new','Neuf','Créateurs & marques'],['used','Occasion','La seconde main']]){const b=button('',()=>{market=id;view='catalog';render();});b.setAttribute('aria-pressed',String(market===id));b.dataset.market=id;b.append(e('b','',label),e('span','',detail));tabs.append(b);}root.append(tabs);
  if(view==='drafts'){
   const row=e('div','shop-section-heading');row.append(e('h2','','Mes brouillons'),button('Retour aux annonces',()=>{view='catalog';render();},'shop-text-button'));root.append(row,e('p','shop-muted','Privés, enregistrés sur cet appareil. Aucune annonce n’est publiée.'));
   const drafts=readDrafts();if(!drafts.length){root.append(empty('Ton prochain article commence ici.','Prépare le titre, le prix et l’état de ton article.'));return;}
   const list=e('div','shop-drafts');for(const d of drafts){const card=button('',()=>openDraft(d),'shop-draft');card.append(e('span','shop-draft-badge','BROUILLON · '+(d.market==='new'?'NEUF':'OCCASION')),e('h3','',d.title),e('b','shop-price',new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(d.price)),e('small','',d.condition+(d.size?' · '+d.size:'')),e('span','shop-edit-link','Modifier →'));list.append(card);}root.append(list);return;
  }
  const hero=e('section','shop-hero');hero.dataset.market=market;const art=e('div','shop-hero-art');art.setAttribute('aria-hidden','true');art.innerHTML='<i></i><div>'+bag+'</div><span>✦</span>';
  const heroText=e('div','shop-hero-text');heroText.append(e('span','shop-eyebrow',market==='used'?'UNE NOUVELLE VIE, UN NOUVEAU COUP DE CŒUR':'LES NOUVEAUTÉS DE TA COMMUNAUTÉ'),e('h2','',market==='used'?'Déjà aimé.\nPrêt à te plaire.':'Des créations.\nDes découvertes.'),e('p','',market==='used'?'Mode, objets et belles trouvailles de seconde main.':'Les produits neufs des créateurs, des entreprises et des particuliers.'));hero.append(heroText,art);root.append(hero);
  const search=e('form','shop-search');search.setAttribute('role','search');const input=e('input');input.type='search';input.placeholder=market==='used'?'Une marque, une taille, une envie…':'Rechercher un produit, une marque…';input.setAttribute('aria-label','Rechercher dans la Boutique');input.value=query;const submit=e('button','','Rechercher');submit.type='submit';search.append(input,submit);search.onsubmit=event=>{event.preventDefault();query=input.value.trim();renderResults();};root.append(search);
  const cats=e('div','shop-categories');cats.setAttribute('role','group');cats.setAttribute('aria-label','Catégories de produits');for(const c of categories){const b=button(c,()=>{category=c;for(const n of cats.children)n.setAttribute('aria-pressed',String(n===b));renderResults();});b.setAttribute('aria-pressed',String(category===c));cats.append(b);}root.append(cats);
  const filters=e('div','shop-filters'),sellerLabel=e('label','','Vendeurs'),select=e('select');select.setAttribute('aria-label','Type de vendeur');for(const [id,text]of Object.entries(sellers)){const o=e('option','',text);o.value=id;select.append(o);}select.value=seller;select.onchange=()=>{seller=select.value;renderResults();};sellerLabel.append(select);filters.append(sellerLabel);if(market==='used'){const stateLabel=e('label','','État'),state=e('select');state.setAttribute('aria-label','État des articles');for(const t of ['Tous les états','Neuf avec étiquette','Neuf sans étiquette','Très bon état','Bon état','État satisfaisant'])state.append(e('option','',t));state.value=conditionFilter;state.onchange=()=>{conditionFilter=state.value;renderResults();};stateLabel.append(state);filters.append(stateLabel);}root.append(filters);
  const results=e('section','shop-results');results.setAttribute('aria-live','polite');root.append(results);
  async function renderResults(){const own=++resultEpoch;results.replaceChildren(e('p','shop-muted','Chargement du catalogue…'));try{const items=await window.ONEBoutiqueCatalog.search(query,{market,category,seller,condition:market==='used'?conditionFilter:null});if(own!==resultEpoch||!results.isConnected)return;results.replaceChildren();const active=!!query||category!=='Tout'||seller!=='all'||market==='used'&&conditionFilter!=='Tous les états';const row=e('div','shop-section-heading');row.append(e('h2','',market==='used'?'Les dernières annonces':'À découvrir'),e('span','shop-muted',items.length+' article'+(items.length>1?'s':'')));results.append(row);if(items.length){const grid=e('div','shop-drafts');for(const item of items){const card=e('article','shop-draft');card.append(e('span','shop-draft-badge',item.market==='used'?'OCCASION':'NEUF'),e('h3','',item.title),e('b','shop-price',new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(item.price)),e('small','',item.condition+(item.size?' · '+item.size:'')),e('small','',item.sellerName||sellers[item.sellerType]));if(item.description)card.append(e('p','shop-muted',item.description));if(item.offerUrl){try{const url=new URL(item.offerUrl);if(url.protocol==='https:'&&!url.username&&!url.password){const link=e('a','shop-edit-link','Voir l’offre ↗');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer sponsored';card.append(link);}}catch{}}grid.append(card);}results.append(grid);}else results.append(empty(active?'Aucun article pour le moment.':'Les premières annonces arrivent bientôt.',query?'Aucun résultat pour « '+query+' ».':'La Boutique se prépare. Tu peux déjà préparer ton annonce en brouillon.'));if(active)results.append(button('Effacer les filtres',()=>{query='';category='Tout';seller='all';conditionFilter='Tous les états';render();},'shop-text-button'));}catch{if(own===resultEpoch&&results.isConnected){results.replaceChildren(empty('Le catalogue est indisponible.','Réessaie dans quelques instants.'),button('Réessayer',renderResults,'shop-text-button'));}}}renderResults();
  root.append(e('p','shop-opening-note','Créateurs · Entreprises · Particuliers'));
 }
 function empty(title,copy){const box=e('div','shop-empty'),icon=e('span','shop-empty-icon');icon.innerHTML=bag;box.append(icon,e('h3','',title),e('p','',copy));return box;}
 function sync(){const active=window.oneCurrentSpace?.()==='shop';if(active)entry.setAttribute('aria-current','page');else entry.removeAttribute('aria-current');document.body.classList.toggle('oneShopOpen',active);if(active)render();}
 window.addEventListener('one-shop-search',event=>{query=String(event.detail||'');const parsed=window.ONEBoutiqueCatalog.parse(query);market=parsed.market||'new';seller=parsed.sellerType||'all';category='Tout';conditionFilter='Tous les états';view='catalog';window.oneShowSpace?.('shop');render();});
 window.addEventListener('one-space-open',sync);window.addEventListener('one-account-changed',()=>{dialog?.close();sync();});sync();
})();
