/* Catalogue controls use persistent IDs; no owner media URLs or provider credentials. */
(()=>{
 const store=window.ONECatalogue;if(!store)return;const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 const style=el('link');style.rel='stylesheet';style.href='ui/catalog-manager.css?v=014117';document.head.append(style);
 const section=el('section');section.className='one-catalogue';section.setAttribute('aria-label','Catalogue TikTok et sauvegardes');const title=el('h3','Catalogue TikTok'),status=el('p','Ouverture des sauvegardes…'),actions=el('div'),history=el('details'),summary=el('summary','Historique des sauvegardes'),list=el('div'),search=el('input'),entriesList=el('div');status.setAttribute('role','status');actions.className='one-catalogue-actions';history.append(summary,list);search.type='search';search.placeholder='Rechercher une vidéo ou un créateur';search.setAttribute('aria-label','Rechercher dans le catalogue');section.append(title,status,actions,history,search,entriesList);document.getElementById('tiktokExternalStatus')?.after(section);
 function button(text,fn,parent=actions){const b=el('button',text);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();await paint();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}};parent.append(b);return b;}
 function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 button('Exporter une sauvegarde',async()=>download(await store.exportFile(),'ONE-TikTok-'+new Date().toISOString().slice(0,10)+'.json'));
 const input=el('input');input.type='file';input.accept='.json,application/json';input.hidden=true;section.append(input);button('Importer un catalogue',()=>input.click());input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());await store.importFile(data);refresh();await paint();status.textContent='Catalogue importé. Les vidéos déjà présentes ont été conservées.';}catch(e){status.textContent=e.message;}finally{input.value='';}};
 button('Récupérer le catalogue invité',async()=>{if(confirm('Ajouter à ce compte les vidéos importées sans connexion sur cet appareil ?')){await store.recoverGuest();refresh();}});
 button('Sauvegarder maintenant',()=>store.snapshot('Sauvegarde manuelle'));
 button('Protéger sur cet appareil',async()=>{const ok=await navigator.storage?.persist?.();alert(ok?'Stockage persistant accordé. Exporte aussi une copie indépendante.':'Le navigateur n’a pas accordé le stockage persistant. Exporte une copie indépendante.');});
 const note=el('p','Sauvegarde automatique tous les 10 nouveaux TikTok. Historique local dans la base du navigateur, inclus dans le profil cloud chiffré quand la synchronisation réussit. Exporte un fichier pour garder une copie indépendante de cet appareil.');note.className='one-catalogue-note';section.append(note);
 const shareNote=el('p','Pour un autre compte ou appareil : exporte le catalogue puis importe ce fichier dans ONE. Les liens publics utilisent le même lecteur TikTok officiel. Aucun catalogue privé n’est publié automatiquement.');shareNote.className='one-catalogue-note';section.append(shareNote);
 let data=[];function refresh(){window.loadTikTokLocal?.();window.renderTikTokExternalManager?.();window.render?.();}
 function play(item){const d=el('dialog');d.className='one-catalogue-player';const close=el('button','Fermer'),heading=el('h3',item.title||'TikTok'),message=el('p','Appuie sur Lecture dans le lecteur TikTok.'),frame=el('iframe'),external=el('a','Ouvrir sur TikTok');frame.title='TikTok '+item.id;frame.src='https://www.tiktok.com/player/v1/'+encodeURIComponent(item.id)+'?autoplay=0&controls=1&description=1&rel=0';frame.allow='autoplay; fullscreen; encrypted-media; picture-in-picture';frame.referrerPolicy='strict-origin-when-cross-origin';external.href='https://www.tiktok.com/@'+'_'+'/video/'+encodeURIComponent(item.id);external.target='_blank';external.rel='noopener noreferrer';d.append(close,heading,frame,message,external);document.body.append(d);function remove(){window.removeEventListener('message',listen);frame.src='about:blank';d.remove();}close.onclick=()=>d.close();d.addEventListener('close',remove,{once:true});d.addEventListener('click',e=>{if(e.target===d)d.close();});function listen(e){if(e.origin!=='https://www.tiktok.com'||e.source!==frame.contentWindow||!e.data?.['x-tiktok-player'])return;if(e.data.type==='onStateChange'&&e.data.value===1)message.textContent='Lecture en cours';if(e.data.type==='onPlayerError'){const code=e.data.value?.errorCode;message.textContent=code===3002?'Lecture automatique bloquée : appuie sur Lecture.':code===1001?'Cette vidéo n’est plus disponible dans le lecteur. Ouvre-la sur TikTok.':'Le lecteur rencontre un problème. Réessaie ou ouvre TikTok.';}}window.addEventListener('message',listen);d.showModal();}
 function rows(){entriesList.replaceChildren();const q=search.value.trim().toLocaleLowerCase(),visible=data.filter(v=>(v.title+' '+v.creator).toLocaleLowerCase().includes(q));let shown=0;function more(){for(const item of visible.slice(shown,shown+30)){const row=el('article'),text=el('div');text.append(el('b',item.title||'TikTok'),el('small',item.creator||'Créateur TikTok'));row.append(text);button('Lire',()=>play(item),row);entriesList.append(row);}shown+=30;next.hidden=shown>=visible.length;}const next=el('button','Afficher la suite');next.type='button';next.onclick=()=>{next.remove();more();entriesList.append(next);};more();entriesList.append(next);if(!visible.length)entriesList.prepend(el('p','Aucune vidéo correspondante.'));}search.oninput=rows;
 async function paint(){const info=await store.history(),payload=await store.exportFile();data=payload.entries;status.textContent=info.error||info.count+' vidéos · '+info.added+' nouveaux ajouts protégés'+(info.items[0]?' · dernière sauvegarde '+new Date(info.items[0].at).toLocaleString():' · premier snapshot au 10e ajout');list.replaceChildren();for(const item of info.items){const row=el('article');row.append(el('span',new Date(item.at).toLocaleString()+' · '+item.count+' vidéos · '+item.reason));button('Restaurer',async()=>{if(!confirm('Restaurer cette sauvegarde en conservant les vidéos actuelles ?'))return;await store.restore(item.id);refresh();},row);list.append(row);}rows();}
 window.addEventListener('one-catalogue-state',()=>paint().catch(e=>status.textContent=e.message));store.ready.then(()=>{refresh();return paint();}).catch(e=>status.textContent=e.message);
})();
