/* ONE 0.14.104: provider credentials never enter browser storage. */
(()=>{
 'use strict';
 const API='https://one-connections-api.moulinanthony60.workers.dev';
 const nativeFetch=window.fetch.bind(window), names={youtube:'YouTube',twitch:'Twitch',tiktok:'TikTok'}, ids={youtube:'Youtube',twitch:'Twitch',tiktok:'TikTok'};
 let status={},owner='',loaded=false,busy='',error='',loading=null,epoch=0,lastRefresh=0;
 const token=()=>localStorage.getItem('one_account_token_v06')||'';
 const notify=m=>window.toast?window.toast(m):console.info(m);
 const cleanLegacy=()=>['one_youtube_api_key','one_twitch_client_id','one_twitch_token','one_tiktok_data','one_tiktok_connected','one_twitch_oauth_state','one_tiktok_oauth_state'].forEach(k=>localStorage.removeItem(k));
 const current=()=>owner===token()&&!!owner;
 window.oneProviderReady=p=>current()&&status[p]?.connected===true;
 async function api(path,body,signal){const captured=token();if(!captured)throw Error('Connecte-toi à ton compte ONE.');const r=await nativeFetch(API+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+captured,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:signal||AbortSignal.timeout(20000)});if(captured!==token())throw Error('Le compte ONE a changé.');const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false){const e=Error(d.error||'Connexions momentanément indisponibles.');e.status=r.status;throw e;}return d;}
 function paint(){if(!document.getElementById('accountYoutubeStatus'))return;let count=0;for(const p of Object.keys(names)){const button=document.getElementById('account'+ids[p]+'Status'),text=document.getElementById('account'+ids[p]+'Text');if(!button||!text)continue;const ready=window.oneProviderReady(p),s=current()?status[p]:null;if(ready)count++;button.textContent=busy===p?'Patiente…':ready?'Déconnecter':s?.reconnect?'Reconnecter':'Connecter';button.disabled=!!busy||!!token()&&!loaded&&!error;button.classList.toggle('on',ready);button.setAttribute('aria-label',button.textContent+' '+names[p]);text.textContent=!token()?'Connecte-toi à ONE pour continuer':error||(!loaded?'Vérification…':ready?'Connecté'+(p==='tiktok'?' · compte de test':''):s?.reconnect?'Autorisation à renouveler':s?.configured===false?'Connexion bientôt disponible':p==='tiktok'?'Réservé aux comptes de test':'Non connecté');}
 const counter=document.getElementById('accountConnectedCount');if(counter)counter.textContent=token()?count+' plateforme'+(count>1?'s':'')+' connectée'+(count>1?'s':''):'Connecte-toi à ton compte ONE';
 }
 function clearPrivate(){window.ONEConnections.tiktokData=null;try{youtubeItems=[];ytBaseItems=[];twitchItems=[];twitchVodItems=[];twitchClipItems=[];followingItems=[];loadTikTokLocal();render();}catch{}}
 async function loadTikTok(){const captured=token(),generation=epoch;try{const d=await api('/api/tiktok/feed');if(captured!==token()||generation!==epoch||!window.oneProviderReady('tiktok'))return;window.ONEConnections.tiktokData=d;window.loadTikTokLocal?.();window.render?.();}catch(e){if(captured!==token()||generation!==epoch)return;if(e.status===409){status.tiktok={...status.tiktok,connected:false,reconnect:true};paint();}notify(e.message);}}
 function loadContent(before={}){if(window.oneProviderReady('youtube')&&!before.youtube?.connected)window.youtubeSearch?.('',false,false);if(window.oneProviderReady('twitch')&&!before.twitch?.connected)window.loadTwitch?.(false);if(window.oneProviderReady('tiktok')&&(!before.tiktok?.connected||!window.ONEConnections.tiktokData))loadTikTok();}
 async function refresh(){if(loading)return loading;const captured=token(),generation=epoch;if(!captured){status={};owner='';loaded=true;paint();return;}loading=(async()=>{try{const d=await api('/connections');if(captured!==token()||generation!==epoch)return;const before=status;status=d.providers;owner=captured;loaded=true;error='';lastRefresh=Date.now();paint();loadContent(before);}catch(e){if(captured!==token()||generation!==epoch)return;error=e.message;paint();}finally{if(generation===epoch)loading=null;}})();return loading;}
 async function connect(p){if(busy)return;if(!token()){document.getElementById('accountModal')?.classList.add('show');document.getElementById('oneAuthEmail')?.focus();notify('Connecte-toi à ONE avant de connecter '+names[p]+'.');return;}busy=p;paint();try{const captured=token();const verifier=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');const proof=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))),v=>v.toString(16).padStart(2,'0')).join('');const d=await api('/connections/'+p+'/begin',{proof});if(captured!==token())return;sessionStorage.setItem('one_connection_pending',JSON.stringify({provider:p,state:d.state,verifier}));location.assign(d.url);}catch(e){notify(e.message);}finally{busy='';paint();}}
 async function disconnect(p){if(busy)return;busy=p;paint();try{await api('/connections/'+p+'/disconnect',{});epoch++;loading=null;status[p]={...status[p],connected:false,reconnect:false};cleanLegacy();clearPrivate();paint();loadContent();notify(names[p]+' déconnecté de ONE.');}catch(e){notify(e.message);}finally{busy='';paint();}}
 function bind(){for(const p of Object.keys(names)){const b=document.getElementById('account'+ids[p]+'Status');if(b)b.onclick=()=>window.oneProviderReady(p)?disconnect(p):connect(p);}paint();}
 async function returned(){const u=new URL(location.href),p=u.searchParams.get('one_connection');if(!Object.hasOwn(names,p))return;const state=u.searchParams.get('state'),result=u.searchParams.get('result');for(const k of ['one_connection','state','result'])u.searchParams.delete(k);history.replaceState(null,'',u.pathname+u.search+u.hash);document.getElementById('accountModal')?.classList.add('show');let pending;try{pending=JSON.parse(sessionStorage.getItem('one_connection_pending')||'null');}catch{}if(!pending||pending.state!==state||pending.provider!==p){notify('Connexion non reconnue dans cet onglet. Recommence depuis ton compte ONE.');return;}sessionStorage.removeItem('one_connection_pending');if(result!=='ready'){notify('Connexion '+names[p]+' refusée ou interrompue. Réessaie depuis ton compte ONE.');return;}busy=p;paint();try{await api('/connections/'+p+'/complete',{state,verifier:pending.verifier});epoch++;loading=null;loaded=false;status={};notify(names[p]+' connecté.');}catch(e){notify(e.message);}finally{busy='';paint();}}
 window.oneConnectedFetch=async(input,options={})=>{
  const url=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url,location.href);
  const p=url.origin==='https://www.googleapis.com'&&url.pathname.startsWith('/youtube/v3/')?'youtube':url.origin==='https://api.twitch.tv'&&url.pathname.startsWith('/helix/')?'twitch':null;
  if(!p)return nativeFetch(input,options);
  if(!loaded)await refresh();const captured=token(),generation=epoch;if(!window.oneProviderReady(p))return new Response(JSON.stringify({error:{message:'Connecte '+names[p]+' depuis ton compte ONE.'}}),{status:409,headers:{'Content-Type':'application/json'}});
  const path=url.pathname.slice(p==='youtube'?12:7);for(const k of ['key','access_token','oauth_token','client_id'])url.searchParams.delete(k);
  const r=await nativeFetch(API+'/api/'+p+'/'+path+url.search,{method:'GET',headers:{Authorization:'Bearer '+captured},signal:options.signal||AbortSignal.timeout(20000)});
  const responseBody=await r.text();if(captured!==token()||generation!==epoch)throw new DOMException('Compte modifié','AbortError');
  if(r.status===409){status[p]={...status[p],connected:false,reconnect:true};paint();}return new Response(responseBody,{status:r.status,headers:{'Content-Type':'application/json'}});
 };
 window.ONEConnections={connect,disconnect,refresh,paint,bind,tiktokData:null};
 function accountChanged(){if(owner===token())return;epoch++;loading=null;status={};owner=token();loaded=false;error='';cleanLegacy();clearPrivate();paint();refresh();}
 window.addEventListener('one-account-changed',accountChanged);
 window.addEventListener('storage',e=>{if(e.key==='one_account_token_v06')accountChanged();});
 window.addEventListener('focus',()=>{if(Date.now()-lastRefresh>60000)refresh();});
 document.addEventListener('DOMContentLoaded',async()=>{cleanLegacy();bind();document.getElementById('accountBtn')?.addEventListener('click',()=>{paint();refresh();});await returned();await refresh();});
})();
