(()=>{
 let busy=false,start=null,pulled=false;
 const button=document.createElement('button');button.type='button';button.id='oneRefreshContent';button.textContent='↻';button.setAttribute('aria-label','Actualiser le contenu');const search=document.getElementById('oneSearchToggle');search?.before(button);
 async function refresh(){if(busy)return;if(document.getElementById('vfeed').classList.contains('show')&&verticalFeedMode==='tiktok'){document.getElementById('oneRefreshTikTok').click();return;}busy=true;button.disabled=true;button.setAttribute('aria-busy','true');const platform=state.filter;try{if(platform==='twitch')await twitchStreams(false,state.query);else if(platform==='youtube'){await youtubeSearch(state.query||'gaming france',false,false);if(window.oneYoutubeTab==='following')await window.oneRefreshFollowedPriority?.();}else if(platform==='tiktok'){oneTikTokSession=null;loadTikTokLocal();render();}else await loadUnifiedFeed();}catch{toast('Actualisation indisponible. Réessaie dans un instant.');}finally{busy=false;button.disabled=false;button.removeAttribute('aria-busy');}}
 button.onclick=refresh;
 document.addEventListener('touchstart',e=>{const blocked=e.target.closest('iframe,.modal.show,#vfeed.show,#videoAiPanel:not([hidden]),input,textarea');start=!blocked&&window.scrollY<=0&&e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null;pulled=false;},{passive:true});
 document.addEventListener('touchmove',e=>{if(!start||e.touches.length!==1)return;const dx=e.touches[0].clientX-start.x,dy=e.touches[0].clientY-start.y;if(dy>15&&Math.abs(dx)<dy){if(e.cancelable)e.preventDefault();pulled=dy>80;}},{passive:false});
 document.addEventListener('touchend',()=>{if(pulled)refresh();start=null;pulled=false;},{passive:true});document.addEventListener('touchcancel',()=>{start=null;pulled=false;},{passive:true});
})();
