(()=>{
 const header=document.querySelector('.topbar'),app=document.querySelector('.app');
 const nav=document.createElement('nav');nav.className='oneMainNav';nav.setAttribute('aria-label','Espaces ONE');
 nav.innerHTML='<button data-one-space="one"><span class="symbol">▣</span><span><b>ONE</b><small>Vidéos & créations</small></span></button><button data-one-space="together"><span class="symbol">♧</span><span><b>Together</b><small>Regarder ensemble</small></span></button><button data-one-space="party"><span class="symbol">✦</span><span><b>Party</b><small>Jouer ensemble</small></span></button>';
 header.querySelector('.brandrow').after(nav);
 const label=document.createElement('p');label.className='oneSourcesLabel';label.textContent='Sources de contenu';header.querySelector('.tabsRail').before(label);
 for(const filter of ['all','one','cinema']){const b=document.querySelector('#chips [data-filter="'+filter+'"]');if(b)b.hidden=true;}
 const more=document.createElement('button');more.className='chip';more.type='button';more.textContent='Plus';more.onclick=e=>{e.stopPropagation();show('sources');};document.getElementById('chips').appendChild(more);
 const shell=document.createElement('section');shell.className='oneShell';shell.id='oneFoundation';shell.hidden=true;shell.setAttribute('aria-label','Espace ONE');header.after(shell);
 const social=document.createElement('button');social.type='button';social.className='nav oneSocialNav';social.innerHTML='<span class="ico">☏</span>Social';social.onclick=()=>show('social');social.className='oneSecondary oneSocialEntry';social.innerHTML='Social · Amis et messages';
 const home=document.createElement('button');home.type='button';home.className='nav';home.id='oneHomeNav';home.innerHTML='<span class="ico">⌂</span>Accueil';home.onclick=()=>show('one');document.querySelector('.bottom').prepend(home);
 const sourceGrid='<div class="oneSourceGrid"><button data-source="tiktok"><span>♪</span>TikTok</button><button data-source="youtube"><span>▶</span>YouTube</button><button data-source="twitch"><span>▣</span>Twitch</button><button data-source="music"><span>♫</span>Musique</button></div>';
 const screens={
 one:'<span class="oneEyebrow">Ton espace de création</span><h1 class="oneShellTitle">Bienvenue sur ONE.</h1><p class="oneShellLead">Regarde, crée et partage. Un espace pour tes vidéos et celles de la communauté.</p><div class="oneHeroCard"><span class="oneSmallTag">Contenu natif ONE</span><h2>Les premières créations<br>commencent avec toi.</h2><p>Prépare ta vidéo dans le Studio. La publication sur le feed ONE sera ouverte dans une prochaine étape.</p><button class="onePrimary" data-action="studio">Préparer une création ＋</button></div><div class="oneEmpty"><span>✦</span><strong>Le feed ONE arrive bientôt</strong>Aucune publication native pour le moment.</div>',
 together:'<span class="oneEyebrow">À plusieurs, partout dans ONE</span><h1 class="oneShellTitle">Together</h1><p class="oneShellLead">Un salon, jusqu’à quatre personnes et les contenus que vous aimez.</p><div class="oneHeroCard"><span class="symbol">♧</span><h2>Les mêmes moments.<br>Ensemble.</h2><p>Les salons et les invitations seront disponibles une fois le service Together connecté.</p><span class="oneSmallTag">En préparation</span></div><div class="oneFeatureGrid"><div class="oneFeature"><span class="symbol">▶</span><h3>Regarder ensemble</h3><p>Une lecture partagée entre les participants.</p></div><div class="oneFeature"><span class="symbol">☏</span><h3>Garder le contact</h3><p>Retrouver ses amis et ses invitations dans Social.</p></div></div>',
 party:'<span class="oneEyebrow">La prochaine aventure</span><h1 class="oneShellTitle">Party</h1><p class="oneShellLead">Des jeux à partager avec ton groupe Together.</p><div class="oneHeroCard"><span class="oneSmallTag">À venir</span><h2>Le Blind Test<br>ouvrira la partie.</h2><p>Party sera développé après la lecture persistante et les salons Together.</p></div><div class="oneFeatureGrid"><div class="oneFeature"><span class="symbol">♫</span><h3>Blind Test</h3><p>Reconnaître, buzzer et marquer des points.</p></div><div class="oneFeature"><span class="symbol">✦</span><h3>Défis de groupe</h3><p>De nouveaux jeux viendront ensuite.</p></div></div>',
 social:'<span class="oneEyebrow">Tes proches dans ONE</span><h1 class="oneShellTitle">Social</h1><p class="oneShellLead">Amis, conversations, groupes et invitations, au même endroit.</p><div class="oneEmpty"><span>☏</span><strong>Les conversations arrivent bientôt</strong>Le service de messages n’est pas encore connecté.</div><div class="oneFeatureGrid"><div class="oneFeature"><h3>Conversations</h3><p>Échanger et partager des contenus.</p></div><div class="oneFeature"><h3>Invitations</h3><p>Rejoindre un salon Together depuis une conversation.</p></div></div>',
 sources:'<span class="oneEyebrow">Tes contenus externes</span><h1 class="oneShellTitle">Sources</h1><p class="oneShellLead">Retrouve les lecteurs et tes playlists.</p>'+sourceGrid+'<p class="oneShellLead">Les connexions aux plateformes se gèrent dans Réglages.</p><button class="oneSecondary" data-action="settings">Ouvrir les réglages</button>'
 };
 let current=null;
 function mark(space){nav.querySelectorAll('button').forEach(b=>{if(b.dataset.oneSpace===space)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});social.classList.toggle('active',space==='social');home.classList.toggle('active',space==='one');}
 function show(space,push=true){if(!screens[space])return;if(current===space&&!shell.hidden)return;closeVerticalFeed();v1815StopAllPlayers();current=space;document.body.classList.add('oneShellOpen');shell.innerHTML=screens[space];if(space==='one')shell.appendChild(social);shell.hidden=false;mark(space);if(push)history.pushState({...history.state,oneSpace:space},'');window.scrollTo({top:0,behavior:'auto'});}
 function leave(){current=null;shell.hidden=true;document.body.classList.remove('oneShellOpen');mark(null);}
 nav.onclick=e=>{const b=e.target.closest('[data-one-space]');if(b)show(b.dataset.oneSpace);};
 shell.onclick=e=>{const source=e.target.closest('[data-source]');if(source){leave();document.querySelector('#chips [data-filter="'+source.dataset.source+'"]').click();return;}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='studio'){openOneStudio();}if(action==='settings')document.getElementById('profile').click();};
 document.getElementById('chips').addEventListener('click',e=>{if(e.target.closest('[data-filter]'))leave();},true);
 document.getElementById('chips').addEventListener('click',e=>{if(e.target.closest('[data-filter]')?.dataset.filter!=='tiktok')return;if(!document.getElementById('vfeed').classList.contains('show'))openVerticalFeed('tiktok');});
 document.getElementById('discover').addEventListener('click',e=>{e.stopImmediatePropagation();openOneStudio();},true);
 document.getElementById('savedNav').addEventListener('click',leave,true);
 document.getElementById('oneHome').addEventListener('click',e=>{e.stopImmediatePropagation();show('one');},true);
 document.getElementById('oneHome').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopImmediatePropagation();show('one');}},true);
 window.addEventListener('popstate',e=>{if(e.state?.oneSpace)show(e.state.oneSpace,false);else leave();});
 show('one',false);history.replaceState({...history.state,oneSpace:'one'},'');
})();
