(()=>{
 const header=document.querySelector('.topbar'),app=document.querySelector('.app');

 const brandrow=header.querySelector('.brandrow'),searchBox=header.querySelector('.search'),searchInput=document.getElementById('search');
 const tools=document.createElement('div');tools.className='oneHeaderTools';tools.innerHTML='<button type="button" id="oneSearchToggle" aria-label="Rechercher" aria-expanded="false" aria-controls="oneHeaderSearch"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg></button><button type="button" id="oneNotificationsToggle" aria-label="Notifications" aria-expanded="false" aria-controls="oneNotifications"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5Zm5 3h4M12 2v2"/></svg></button>';
 brandrow.insertBefore(tools,document.getElementById('accountBtn'));searchBox.id='oneHeaderSearch';searchBox.hidden=true;
 const notices=document.createElement('section');notices.id='oneNotifications';notices.hidden=true;notices.setAttribute('aria-label','Notifications');notices.innerHTML='<div class="oneNoticeHead"><b>Notifications</b><button type="button" aria-label="Fermer les notifications">×</button></div><p>Aucune notification pour le moment.</p><small>Les invitations et l’activité Social apparaîtront ici lorsque ces services seront disponibles.</small>';header.appendChild(notices);
 const searchToggle=document.getElementById('oneSearchToggle'),noticeToggle=document.getElementById('oneNotificationsToggle');
 function closeNotices(){notices.hidden=true;noticeToggle.setAttribute('aria-expanded','false');}
 function setSearch(open){searchBox.hidden=!open;header.classList.toggle('oneSearchOpen',open);searchToggle.setAttribute('aria-expanded',String(open));if(open){closeNotices();searchInput.focus({preventScroll:true});}else searchInput.blur();}
 searchToggle.onclick=()=>setSearch(searchBox.hidden);
 noticeToggle.onclick=()=>{const open=notices.hidden;setSearch(false);notices.hidden=!open;noticeToggle.setAttribute('aria-expanded',String(open));};notices.querySelector('button').onclick=()=>{closeNotices();noticeToggle.focus();};
 header.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!notices.hidden){closeNotices();noticeToggle.focus();}else if(!searchBox.hidden){setSearch(false);searchToggle.focus();}}});
 document.addEventListener('click',e=>{if(!header.contains(e.target))closeNotices();});
 // Search from the native home uses the existing all-source search flow.
 document.getElementById('searchBtn').addEventListener('click',()=>{if(document.body.classList.contains('oneShellOpen')){leave();state.filter='all';state.mode=null;}},true);

 const nav=document.createElement('nav');nav.className='oneMainNav';nav.setAttribute('aria-label','Espaces ONE');
 nav.innerHTML='<button data-one-space="one"><span class="symbol">▣</span><span><b>ONE</b><small>Vidéos & créations</small></span></button><button data-one-space="together"><span class="symbol">♧</span><span><b>Together</b><small>Regarder ensemble</small></span></button><button data-one-space="party"><span class="symbol">✦</span><span><b>Party</b><small>Jouer ensemble</small></span></button>';
 header.querySelector('.brandrow').after(nav);
 const label=document.createElement('p');label.className='oneSourcesLabel';label.textContent='Sources de contenu';header.querySelector('.tabsRail').before(label);
 for(const filter of ['all','one','cinema']){const b=document.querySelector('#chips [data-filter="'+filter+'"]');if(b)b.hidden=true;}
 const more=document.createElement('button');more.className='chip';more.type='button';more.textContent='Plus';more.onclick=e=>{e.stopPropagation();show('sources');};document.getElementById('chips').appendChild(more);
 const shell=document.createElement('section');shell.className='oneShell';shell.id='oneFoundation';shell.hidden=true;shell.setAttribute('aria-label','Espace ONE');header.after(shell);
 const social=document.createElement('button');social.type='button';social.className='nav oneSocialNav';social.innerHTML='<span class="ico">☏</span>Social';social.onclick=()=>show('social');social.className='oneSecondary oneSocialEntry';social.innerHTML='Social · Amis et messages';
 const home=document.createElement('button');home.type='button';home.className='nav';home.id='oneHomeNav';home.innerHTML='<span class="ico">⌂</span>Accueil';home.onclick=()=>show('one');document.querySelector('.bottom').prepend(home);
 const sourceGrid='<div class="oneSourceGrid"><button data-source="tiktok"><span>♪</span>TikTok</button><button data-source="youtube"><span>▶</span>YouTube</button><button data-source="twitch"><span>▣</span>Twitch</button><button data-source="music"><span>♫</span>Musique</button></div>';
 const screens={
 one:'<span class="oneEyebrow">Ton espace de création</span><h1 class="oneShellTitle">Bienvenue sur ONE.</h1><p class="oneShellLead">Regarde, crée et partage. Un espace pour tes vidéos et celles de la communauté.</p><div class="oneHeroCard"><span class="oneSmallTag">Contenu natif ONE</span><h2>Les premières créations<br>commencent avec toi.</h2><p>Prépare ta vidéo dans le Studio. La publication sur le feed ONE sera ouverte dans une prochaine étape.</p><button class="onePrimary" data-action="studio">Préparer une création ＋</button></div><div class="oneEmpty"><span>✦</span><strong>Le feed ONE arrive bientôt</strong>Aucune publication native pour le moment.</div>',
 together:'<span class="oneEyebrow">À plusieurs, partout dans ONE</span><h1 class="oneShellTitle">Together</h1><p class="oneShellLead">Un salon, jusqu’à quatre personnes et les contenus que vous aimez.</p><div class="oneHeroCard"><span class="symbol">♧</span><h2>Les mêmes moments.<br>Ensemble.</h2><p>Les salons et les invitations seront disponibles une fois le service Together connecté.</p><span class="oneSmallTag">En préparation</span></div><div class="oneFeatureGrid"><div class="oneFeature"><span class="symbol">▶</span><h3>Regarder ensemble</h3><p>Une lecture partagée entre les participants.</p></div><div class="oneFeature"><span class="symbol">☏</span><h3>Garder le contact</h3><p>Retrouver ses amis et ses invitations dans Social.</p></div></div>',
 party:'<span class="oneEyebrow">La prochaine aventure</span><h1 class="oneShellTitle">Party</h1><p class="oneShellLead">Des jeux à partager avec ton groupe Together.</p><div class="oneHeroCard"><span class="oneSmallTag">À venir</span><h2>Le Blind Test<br>ouvrira la partie.</h2><p>Party sera développé après la lecture persistante et les salons Together.</p></div><div class="oneFeatureGrid"><div class="oneFeature"><span class="symbol">♫</span><h3>Blind Test</h3><p>Reconnaître, buzzer et marquer des points.</p></div><div class="oneFeature"><span class="symbol">✦</span><h3>Défis de groupe</h3><p>De nouveaux jeux viendront ensuite.</p></div></div>',
 social:'<span class="oneEyebrow">Tes proches dans ONE</span><h1 class="oneShellTitle">Social</h1><p class="oneShellLead">Amis, conversations, groupes et invitations, au même endroit.</p><div class="oneEmpty"><span>☏</span><strong>Les conversations arrivent bientôt</strong>Le service de messages n’est pas encore connecté.</div><div class="oneFeatureGrid"><div class="oneFeature"><h3>Conversations</h3><p>Échanger et partager des contenus.</p></div><div class="oneFeature"><h3>Invitations</h3><p>Rejoindre un salon Together depuis une conversation.</p></div></div>',
 sources:'<span class="oneEyebrow">Tes contenus externes</span><h1 class="oneShellTitle">Sources</h1><p class="oneShellLead">Retrouve les lecteurs et tes playlists.</p>'+sourceGrid+'<p class="oneShellLead">Les connexions aux plateformes se gèrent dans Réglages.</p><button class="oneSecondary" data-action="settings">Ouvrir les réglages</button>'
 };
 let current=null;
 function mark(space){if(space){document.querySelectorAll('#chips [data-filter]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false');});document.querySelectorAll('.bottom .nav').forEach(b=>b.classList.remove('active'));document.body.classList.remove('oneTwToolsOpen');}nav.querySelectorAll('button').forEach(b=>{if(b.dataset.oneSpace===space)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});social.classList.toggle('active',space==='social');home.classList.toggle('active',space==='one');}
 function show(space,push=true){if(!screens[space])return;if(current===space&&!shell.hidden)return;closeVerticalFeed();v1815StopAllPlayers();current=space;document.body.classList.add('oneShellOpen');shell.innerHTML=screens[space];if(space==='one')shell.appendChild(social);shell.hidden=false;mark(space);window.dispatchEvent(new CustomEvent("one-space-open",{detail:space}));if(push)history.pushState({...history.state,oneSpace:space},'');window.scrollTo({top:0,behavior:'auto'});}
 function leave(){current=null;shell.hidden=true;document.body.classList.remove('oneShellOpen');mark(null);}
 nav.onclick=e=>{const b=e.target.closest('[data-one-space]');if(b)show(b.dataset.oneSpace);};
 shell.onclick=e=>{const source=e.target.closest('[data-source]');if(source){leave();document.querySelector('#chips [data-filter="'+source.dataset.source+'"]').click();return;}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='studio'){openOneStudio();}if(action==='settings')document.getElementById('profile').click();};
 document.getElementById('chips').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;const fromShell=!shell.hidden;if(fromShell&&state.filter===b.dataset.filter)state.filter='';leave();document.querySelectorAll('#chips [data-filter]').forEach(c=>{c.classList.toggle('active',c===b);c.setAttribute('aria-pressed',String(c===b));});if(b.dataset.filter!=='tiktok')return;e.preventDefault();e.stopImmediatePropagation();if(document.getElementById('vfeed').classList.contains('show')&&verticalFeedMode==='tiktok')return;window.oneTTTrace?.('clic source TikTok',null,null);state.filter='tiktok';state.mode=null;state.query='';ytLastQuery='';document.getElementById('search').value='';document.querySelectorAll('#chips [data-filter]').forEach(c=>c.classList.toggle('active',c===b));loadTikTokLocal();creatorResults=[];openVerticalFeed('tiktok');},true);
 document.getElementById('chips').addEventListener('click',e=>{if(e.target.closest('[data-filter]')?.dataset.filter!=='tiktok')return;if(!document.getElementById('vfeed').classList.contains('show'))openVerticalFeed('tiktok');});
 document.getElementById('discover').addEventListener('click',e=>{e.stopImmediatePropagation();openOneStudio();},true);
 document.getElementById('savedNav').addEventListener('click',leave,true);
 document.getElementById('oneHome').addEventListener('click',e=>{e.stopImmediatePropagation();show('one');},true);
 document.getElementById('oneHome').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopImmediatePropagation();show('one');}},true);
 window.addEventListener('popstate',e=>{if(e.state?.oneSpace)show(e.state.oneSpace,false);else leave();});

 const twTools=document.createElement('button');twTools.id='oneTwitchTools';twTools.type='button';twTools.hidden=true;twTools.setAttribute('aria-label','Afficher les filtres Twitch');twTools.setAttribute('aria-expanded','false');twTools.setAttribute('aria-controls','twitchFilters');twTools.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg>';document.getElementById('feedTitle').after(twTools);twTools.onclick=()=>{const open=document.body.classList.toggle('oneTwToolsOpen');twTools.setAttribute('aria-expanded',String(open));};
 const previousRender=render;render=function(){const tw=state.filter==='twitch'&&state.mode===null;twTools.hidden=!tw;document.body.classList.toggle('oneYoutubeBrowse',state.filter==='youtube'&&state.mode===null);return previousRender.apply(this,arguments);};window.render=render;

 window.oneCurrentSpace=()=>current;
 const exit=document.getElementById('closeVFeed');exit.onclick=()=>{const tik=verticalFeedMode==='tiktok';closeVerticalFeed();if(tik)show('one');};
 const refresh=document.createElement('button');refresh.type='button';refresh.id='oneRefreshTikTok';refresh.className='vexit';refresh.textContent='↻';refresh.setAttribute('aria-label','Actualiser le feed TikTok');document.querySelector('.vfeedTop').appendChild(refresh);refresh.onclick=()=>{if(verticalFeedMode!=='tiktok'||refresh.disabled)return;refresh.disabled=true;try{v17Observer?.disconnect();v1815StopAllPlayers();v17ActiveId='';oneTikTokSession=null;loadTikTokLocal();const root=document.getElementById('vfeedScroller');root.replaceChildren();root.scrollTop=0;renderVerticalFeed();oneCommitTikTokHead(oneMixCreators(tiktokItems,'tiktok'));}finally{setTimeout(()=>{refresh.disabled=false},500);}};
 const syncRefresh=()=>{refresh.hidden=verticalFeedMode!=='tiktok';};new MutationObserver(syncRefresh).observe(document.getElementById('vfeed'),{attributes:true,attributeFilter:['class']});syncRefresh();
 if(oneReloadRoute&&!oneReloadRoute.shell&&['youtube','twitch','tiktok','music'].includes(oneReloadRoute.filter)){leave();history.replaceState({...history.state,oneSpace:null},'');}else{show(oneReloadRoute?.shell||'one',false);history.replaceState({...history.state,oneSpace:current},'');}

})();

(()=>{window.oneYoutubeTab=oneReloadRoute?.youtubeTab==='following'?'following':'home';const title=document.getElementById('feedTitle'),tabs=document.createElement('div');tabs.id='oneYoutubeTabs';tabs.hidden=true;tabs.setAttribute('role','group');tabs.setAttribute('aria-label','Vidéos YouTube');tabs.innerHTML='<button type="button" data-yt-view="home" aria-pressed="true">Pour toi</button><button type="button" data-yt-view="following" aria-pressed="false" aria-label="Deux dernières vidéos par chaîne suivie">♧ Abonnements</button>';title.after(tabs);tabs.onclick=e=>{const b=e.target.closest('[data-yt-view]');if(!b)return;window.oneYoutubeTab=b.dataset.ytView;state.query='';document.getElementById('search').value='';render();};const prev=render;render=function(){const yt=state.filter==='youtube'&&state.mode===null;tabs.hidden=!yt;title.hidden=yt&&!state.query;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ytView===window.oneYoutubeTab)));const result=prev.apply(this,arguments);if(yt&&window.oneYoutubeTab==='following'&&!state.query&&!filtered().length){const empty=document.querySelector('#feed .empty');if(empty)empty.textContent='Aucune vidéo disponible pour tes chaînes suivies. Ajoute des abonnements ou réessaie après le chargement YouTube.';}return result;};window.render=render;})();

(()=>{const modal=document.getElementById('playerModal');document.getElementById('feed').addEventListener('click',e=>{const media=e.target.closest('.youtube-card .media');if(!media)return;const item=v17ItemById(media.closest('.card').dataset.id);if(!item?.videoId)return;e.preventDefault();e.stopImmediatePropagation();v1815StopAllPlayers();openItem(item.id);modal.classList.add('oneYoutubeFullscreen');if(modal.requestFullscreen&&!document.fullscreenElement)modal.requestFullscreen().catch(()=>{});},true);const close=document.getElementById('closePlayer'),previous=close.onclick;close.onclick=e=>{previous?.call(close,e);modal.classList.remove('oneYoutubeFullscreen');if(document.fullscreenElement===modal)document.exitFullscreen?.().catch(()=>{});};})();
/* Preserve the same iframe when Android Back exits native fullscreen. */
(()=>{
 const modal=document.getElementById('playerModal'),bar=modal.querySelector('.playerTop'),close=document.getElementById('closePlayer');let wasFullscreen=false,drag=null;
 const expand=document.createElement('button');expand.type='button';expand.id='oneMiniExpand';expand.textContent='⛶';expand.setAttribute('aria-label','Remettre la vidéo en plein écran');bar.insertBefore(expand,close);
 function restore(){modal.classList.remove('oneYoutubeMini');modal.style.removeProperty('left');modal.style.removeProperty('top');modal.classList.add('oneYoutubeFullscreen');modal.requestFullscreen?.().catch(()=>{});}
 expand.onclick=restore;
 close.addEventListener('click',e=>{if(!modal.classList.contains('oneYoutubeFullscreen'))return;e.preventDefault();e.stopImmediatePropagation();modal.classList.remove('oneYoutubeFullscreen');modal.classList.add('oneYoutubeMini');if(document.fullscreenElement===modal)document.exitFullscreen?.().catch(()=>{});},true);
 close.addEventListener('click',()=>{modal.classList.remove('oneYoutubeMini');modal.style.removeProperty('left');modal.style.removeProperty('top');});
 bar.addEventListener('pointerdown',e=>{if(!modal.classList.contains('oneYoutubeMini')||e.target.closest('button'))return;const r=modal.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};bar.setPointerCapture(e.pointerId);e.preventDefault();});
 bar.addEventListener('pointermove',e=>{if(!drag)return;const r=modal.getBoundingClientRect();modal.style.left=Math.max(0,Math.min(innerWidth-r.width,e.clientX-drag.x))+'px';modal.style.top=Math.max(0,Math.min(innerHeight-r.height,e.clientY-drag.y))+'px';});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])bar.addEventListener(event,()=>drag=null);
 window.addEventListener('resize',()=>{if(!modal.classList.contains('oneYoutubeMini'))return;const r=modal.getBoundingClientRect();modal.style.left=Math.max(0,Math.min(innerWidth-r.width,r.left))+'px';modal.style.top=Math.max(0,Math.min(innerHeight-r.height,r.top))+'px';});
})();
