(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev';let dialog=null;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
 const format=c=>c.slice(0,4)+'-'+c.slice(4);
 const params=new URLSearchParams(location.search),linkCode=params.get('friend');if(linkCode&&/^[A-Z2-9]{8}$/i.test(linkCode)){sessionStorage.setItem('one_friend_pending',linkCode.toUpperCase());params.delete('friend');history.replaceState(history.state,'',location.pathname+(params.size?'?'+params:'')+location.hash);}
 async function api(path,method='GET'){const token=oneAccountToken(),controller=new AbortController();let timer;try{return await Promise.race([(async()=>{const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token},signal:controller.signal});const data=await r.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé. Réessaie.');if(!r.ok||!data.ok)throw Error(data.error||'Service indisponible.');return data;})(),new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(Error('Le service met trop de temps à répondre. Appuie sur Réessayer.'));},12000);})]);}finally{clearTimeout(timer);}}

 async function copy(text,status){try{await navigator.clipboard.writeText(text);status.textContent='Copié.';}catch{status.textContent='Copie ce texte : '+text;}}
 window.oneOpenFriends=()=>{
  if(dialog?.open){dialog.focus();return;}let revision=0;const d=el('dialog');dialog=d;d.className='oneModDialog';d.setAttribute('aria-label','Amis ONE');const header=el('header'),close=button('×',()=>d.close());close.setAttribute('aria-label','Fermer les amis');header.append(el('h2','Amis ONE'),close);const status=el('p'),content=el('div');status.setAttribute('role','status');d.append(header,button('Réessayer',()=>load()),status,content);document.body.append(d);d.addEventListener('close',()=>{revision++;d.remove();if(dialog===d)dialog=null;});d.showModal();
  async function action(path,message){if(message&&!confirm(message))return;const own=revision;d.querySelectorAll('button').forEach(b=>b.disabled=true);try{const result=await api(path,'POST');if(path.startsWith('/friends/request'))sessionStorage.removeItem('one_friend_pending');if(!d.isConnected||own!==revision)return;await load();status.textContent=path.startsWith('/party/invite')?(result.alreadyPending?'Invitation déjà en attente pour ':'Invitation envoyée à ')+(result.recipient||'ce membre')+'.':'Action enregistrée.';window.dispatchEvent(new Event('one-party-refresh'));}catch(e){if(d.isConnected)status.textContent=e.message;}finally{if(d.isConnected)d.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  async function load(){const own=++revision;if(!oneAccountToken()){status.textContent='';content.replaceChildren(el('p','Connecte-toi à ONE, puis ouvre Amis pour envoyer la demande.'));return;}status.textContent='Chargement…';try{const data=await api('/friends/state');if(!d.isConnected||own!==revision)return;content.replaceChildren();status.textContent='';const shareURL=new URL(location.pathname,location.origin);shareURL.searchParams.set('friend',data.code);const code=el('strong',format(data.code));code.style.cssText='display:block;font-size:24px;letter-spacing:3px;margin:12px 0';content.append(el('h3','Mon code ONE'),code,button('Copier le code',()=>copy(format(data.code),status)),button('Copier le lien',()=>copy(shareURL.href,status)));
   const qr=el('div');try{const q=qrcode(0,'M');q.addData(shareURL.href);q.make();const canvas=el('canvas'),count=q.getModuleCount(),scale=4;canvas.width=canvas.height=(count+8)*scale;canvas.style.cssText='max-width:100%;height:auto;display:block;margin:12px auto';canvas.setAttribute('role','img');canvas.setAttribute('aria-label','QR code de demande d’ami ONE');const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';for(let y=0;y<count;y++)for(let x=0;x<count;x++)if(q.isDark(y,x))ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);qr.append(canvas);}catch{qr.textContent='QR indisponible : utilise le code ou le lien.';}content.append(qr,el('p','Ton ami peut scanner ce QR avec l’appareil photo de son téléphone, puis ouvrir ONE. Vous devrez confirmer la demande.'));
   const label=el('label','Code ONE de ton ami'),input=el('input');input.maxLength=16;input.placeholder='ABCD-EFGH';input.value=sessionStorage.getItem('one_friend_pending')||'';input.style.cssText='width:100%;box-sizing:border-box;padding:12px;margin:8px 0;background:#090d19;color:white;border-radius:10px';label.append(input);content.append(button('Scanner un QR code',()=>window.oneScanFriendQR?.(code=>{if(!d.isConnected)return;input.value=format(code);sessionStorage.setItem('one_friend_pending',code);status.textContent='Code lu. Vérifie-le puis appuie sur Envoyer une demande.';input.focus();})),label,button('Envoyer une demande',()=>action('/friends/request?code='+encodeURIComponent(input.value),'Envoyer une demande d’ami à ce code ONE ?')),button('Actualiser',load));
   for(const [title,filter]of [['Demandes reçues',r=>r.status==='pending'&&!r.outgoing],['Mes amis',r=>r.status==='accepted'],['Demandes envoyées',r=>r.status==='pending'&&r.outgoing]]){content.append(el('h3',title));const rows=data.relationships.filter(filter);if(!rows.length)content.append(el('small','Aucun membre pour le moment.'));for(const r of rows){const card=el('article');card.append(el('b',r.name),el('p',format(r.code)));if(r.status==='pending'&&!r.outgoing)card.append(button('Accepter',()=>action('/friends/'+r.id+'/accept')),button('Refuser',()=>action('/friends/'+r.id+'/decline')));if(r.status==='accepted')card.append(button('Inviter dans mon salon Party',()=>action('/party/invite?recipient='+encodeURIComponent(r.code))));card.append(button(r.status==='accepted'?'Retirer cet ami':'Annuler / retirer',()=>action('/friends/'+r.id+'/remove','Retirer cette relation ou demande ?')));content.append(card);}}
  }catch(e){if(d.isConnected&&own===revision)status.textContent=e.message;}}
  load();
 };
 const entry=button('Amis · Mon code et mon QR',window.oneOpenFriends);document.getElementById('oneAuthLoggedIn')?.append(entry);
 window.addEventListener('one-account-changed',()=>{dialog?.close();if(oneAccountToken()&&sessionStorage.getItem('one_friend_pending'))window.oneOpenFriends();});
 const headerButton=button('',window.oneOpenFriends);headerButton.id='oneFriendsToggle';headerButton.setAttribute('aria-label','Amis');headerButton.title='Amis';headerButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="7" r="3"/><path d="M3 20v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 4v2"/></svg>';document.getElementById('oneNotificationsToggle')?.before(headerButton);
 if(linkCode)window.oneOpenFriends();
})();
