(()=>{
 function codeFrom(value){try{const url=new URL(value);if(url.origin!==location.origin||url.pathname!==location.pathname||url.username||url.password)return '';const code=url.searchParams.get('friend')||'';return /^[A-Z2-9]{8}$/i.test(code)?code.toUpperCase():'';}catch{return '';}}
 window.oneFriendCodeFromQR=codeFrom;
 window.oneScanFriendQR=(onCode,options={})=>{
  const d=document.createElement('dialog');d.className='oneModDialog';d.setAttribute('aria-label','Scanner un QR ONE');const title=document.createElement('h2');title.textContent=options.title||'Scanner un QR ONE';const close=document.createElement('button');close.type='button';close.textContent='Fermer le scanner';const video=document.createElement('video');video.muted=true;video.playsInline=true;video.autoplay=true;video.style.cssText='width:100%;max-height:55dvh;object-fit:cover;border-radius:12px';const status=document.createElement('p');status.setAttribute('role','status');status.textContent=options.hint||'Autorise la caméra puis vise le QR de ton ami.';d.append(title,close,video,status);document.body.append(d);d.showModal();let stream=null,timer=null,stopped=false;const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
  function stop(){stopped=true;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());video.srcObject=null;document.removeEventListener('visibilitychange',hidden);window.removeEventListener('pagehide',closeScan);window.removeEventListener('one-account-changed',closeScan);}
  function closeScan(){stop();if(d.open)d.close();d.remove();}
  function hidden(){if(document.hidden)closeScan();}
  close.onclick=closeScan;d.addEventListener('close',()=>{stop();d.remove();});document.addEventListener('visibilitychange',hidden);window.addEventListener('pagehide',closeScan);window.addEventListener('one-account-changed',closeScan);
  function scan(){if(stopped)return;try{if(video.readyState>=2&&video.videoWidth){const ratio=Math.min(1,640/video.videoWidth);canvas.width=Math.round(video.videoWidth*ratio);canvas.height=Math.round(video.videoHeight*ratio);ctx.drawImage(video,0,0,canvas.width,canvas.height);const frame=ctx.getImageData(0,0,canvas.width,canvas.height),found=jsQR(frame.data,frame.width,frame.height,{inversionAttempts:'dontInvert'});if(found){const code=(options.parse||codeFrom)(found.data);if(code){closeScan();onCode(code);return;}status.textContent=(options.parse?'Ce QR ne correspond pas à un salon ONE.':'Ce QR ne correspond pas à un profil ami ONE.');}}}catch{status.textContent='Lecture impossible. Utilise le code écrit sous le profil de ton ami.';}timer=setTimeout(scan,250);}
  (async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw Error('La caméra n’est pas disponible ici. Utilise le code ONE.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:640}},audio:false});if(stopped){stream.getTracks().forEach(t=>t.stop());return;}video.srcObject=stream;await video.play();scan();}catch(e){stream?.getTracks().forEach(t=>t.stop());if(!stopped)status.textContent=e.name==='NotAllowedError'?'Accès caméra refusé. Autorise-le dans le navigateur ou utilise le code ONE.':e.name==='NotReadableError'?'Caméra déjà utilisée. Coupe la caméra Party avant de scanner.':e.message;}})();
 };
})();
