/* Presentation of public game snapshots only. No game, wallet or membership writes. */
(()=>{
 const cinemaStyle=document.createElement('style');cinemaStyle.textContent=`#onePartyGame .bf-cinema{background:radial-gradient(ellipse at 50% 42%,#65205b99,#060711f5 70%)!important;backdrop-filter:blur(9px)!important;gap:10px;padding:24px;box-sizing:border-box;isolation:isolate}#onePartyGame .bf-cinema:before{content:'';position:absolute;inset:8%;border:1px solid #c9945933;border-radius:50%;box-shadow:0 0 70px #ad37e322;pointer-events:none;z-index:-1}#onePartyGame .bf-cinema h3{font-size:clamp(28px,7vw,48px)!important;letter-spacing:.06em;text-shadow:0 0 26px #ef306277;margin:0;text-align:center}#onePartyGame .bf-cinema p{margin:0;color:#f8ddaa;font-size:18px!important}#onePartyGame .bf-cinema .bf-cinema-face{width:72px;height:72px;border-radius:50%;overflow:hidden;border:2px solid #e4ba6c;box-shadow:0 0 26px #d48b4855;display:grid;place-items:center}#onePartyGame .bf-cinema-face>*{width:100%;height:100%;object-fit:cover}#onePartyGame .bf-cinema video{width:min(78vw,300px)!important;height:min(38dvh,300px)!important;object-fit:cover;border-radius:50%!important;border:1px solid #ad825c!important;box-shadow:0 0 50px #b66a3933!important}#onePartyGame .bf-cinema .bf-cinema-cards span{width:60px;height:84px;border:2px solid #dfc593;border-radius:9px;box-shadow:0 9px 24px #0009;transform:rotate(var(--tilt,0deg))}#onePartyGame .bf-cinema .bf-cinema-cards span:nth-child(1){--tilt:-9deg}#onePartyGame .bf-cinema .bf-cinema-cards span:nth-child(3){--tilt:9deg}#onePartyGame .bf-cinema strong{font-size:24px;text-align:center;text-shadow:0 0 20px currentColor}#onePartyGame .bf-cinema button{margin-top:10px;min-height:44px;padding:10px 24px;background:linear-gradient(135deg,#6b2ec9,#231334);border:1px solid #a778d9;border-radius:12px}#onePartyGame .bf-cinema [hidden]{display:none!important}@media(prefers-reduced-motion:no-preference){#onePartyGame .bf-cinema{animation:bfArrival .25s ease-out}#onePartyGame .bf-cinema video{animation:bfTension 2.4s ease-in-out both}#onePartyGame .bf-cinema strong:not([hidden]){animation:bfArrival .3s ease-out}@keyframes bfArrival{from{opacity:0;transform:scale(.94)}to{opacity:1;transform:scale(1)}}@keyframes bfTension{from{transform:scale(.85) rotate(-9deg)}to{transform:scale(1.04) rotate(3deg)}}}`;document.head.append(cinemaStyle);
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/game-tables.css?v=014117';document.head.append(css);const bluffCss=document.createElement('link');bluffCss.rel='stylesheet';bluffCss.href='ui/bluff-table-structure.css?v=014117';document.head.append(bluffCss);
 const cinemaModule=import('./bluff-cinematic.js?v=117h');cinemaModule.then(m=>m.preload()).catch(()=>{});
 const frozen=new Map(),seen=new Set();let gameId='',lastPoker=null,cinema=null;
 function avatar(face,p){const member=window.oneSocialRoom?.()?.members?.find(m=>m.accountId===p.accountId)||p;if(window.ONEUI)face.append(ONEUI.avatar(member));else face.textContent=p.name.slice(0,1);}
 function capture(p){const owner=p.isYou?'local':p.accountId,b=[...document.querySelectorAll('.oneCamBubble')].find(n=>n.dataset.cameraOwner===owner),v=b?.querySelector('video');if(!v||v.classList.contains('off')||v.readyState<2)return null;try{const c=document.createElement('canvas');c.width=c.height=160;const w=v.videoWidth,h=v.videoHeight,k=Math.min(w,h);if(!k)return null;c.getContext('2d').drawImage(v,(w-k)/2,(h-k)/2,k,k,0,0,160,160);return c.toDataURL('image/jpeg',.75);}catch{return null;}}
 function portrait(p,el){const face=el('div');face.className='gt-portrait';if(p.eliminated){if(!frozen.has(p.accountId))frozen.set(p.accountId,capture(p));const image=frozen.get(p.accountId);if(image){const img=el('img');img.src=image;img.alt=p.name;face.append(img);}else avatar(face,p);face.classList.add('gt-eliminated');face.append(el('b','×'));}else{face.dataset.cameraSeat=p.isYou?'local':p.accountId;avatar(face,p);}return face;}
 function media(){document.querySelectorAll('.gt-mic').forEach(n=>{const m=window.ONEPartyMedia?.memberStatus?.(n.dataset.owner);n.textContent=m?.mic===true?'🎤':m?.mic===false?'🔇':'·';n.title=m?.mic===undefined?'État du micro indisponible':m.mic?'Micro actif':'Micro coupé';});const visible=!!document.querySelector('#onePartyGame .bf-premium')&&window.onePartyGameVisible?.()&&!window.oneSalonIsOpen?.();document.querySelectorAll('.oneCamBubble').forEach(b=>{const eliminated=visible&&[...document.querySelectorAll('.bf-player[data-eliminated=true]')].some(p=>p.dataset.owner===b.dataset.cameraOwner);b.classList.toggle('gt-camera-hidden',!!eliminated);});}
 ['one-media-state','one-game-rendered','one-space-open','one-salon-visibility'].forEach(e=>window.addEventListener(e,()=>queueMicrotask(media)));
 function reset(){frozen.clear();seen.clear();gameId='';cinema?.remove();cinema=null;document.querySelectorAll('.gt-camera-hidden').forEach(n=>n.classList.remove('gt-camera-hidden'));}
 window.addEventListener('one-account-changed',reset);window.addEventListener('one-party-state',e=>{if(!e.detail)reset();});window.addEventListener('one-game-rendered',()=>{if(!document.querySelector('.bf-premium')){cinema?.remove();cinema=null;}});
 function proof(scene,r,el){scene.querySelector('.bf-proof')?.remove();const box=el('section');box.className='bf-proof';box.setAttribute('aria-label','Cartes révélées par le serveur');box.append(el('b',r.name+' · '+(r.honest?'Annonce vraie':'BLUFF !')));const cards=el('div');for(const rank of r.cards){const c=el('span',rank==='J'?'★':rank);c.className='bf-proof-card';cards.append(c);}box.append(cards,el('small',r.penalized+' · '+(r.eliminated?'Éliminé':'Toujours en jeu')));scene.append(box);return box;}
 function reveal(g,el){
  const r=g.reveal;if(!r)return;const key=g.id+':'+r.at;if(seen.has(key))return;seen.add(key);
  if(Date.now()-r.at>7000)return;
  const panel=document.getElementById('onePartyGame');if(!panel)return;cinema?.remove();
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const overlay=el('section');cinema=overlay;overlay.className='bf-cinema bf-verdict';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-label','Résultat de l’accusation');
  const title=el('h3',r.honest?'ANNONCE VRAIE':'BLUFF !'),who=el('p',r.penalized),face=el('div');face.className='bf-cinema-face';const victim=g.players.find(p=>p.accountId===r.penalizedAccountId)||g.players.find(p=>p.name===r.penalized);if(victim)avatar(face,victim);
  let preview=null,previewFrozen=false;
  function syncPreview(){
   if(!victim||!overlay.isConnected||previewFrozen)return;
   const owner=victim.isYou?'local':victim.accountId;
   const source=[...document.querySelectorAll('.oneCamBubble')].find(n=>n.dataset.cameraOwner===owner)?.querySelector('video');
   const stream=source?.srcObject,track=stream?.getVideoTracks?.().find(t=>t.readyState==='live'&&t.enabled&&!t.muted);
   if(!track){if(preview){preview.srcObject=null;preview.remove();preview=null;avatar(face,victim);}return;}
   if(!preview){preview=el('video');preview.autoplay=true;preview.playsInline=true;preview.muted=true;preview.setAttribute('aria-label','Caméra de '+victim.name);face.replaceChildren(preview);}
   if(preview.srcObject!==stream){preview.srcObject=stream;preview.play().catch(()=>{});}
  }

  function freezePreview(){
   previewFrozen=true;
   if(!victim)return;
   let image=frozen.get(victim.accountId);
   if(preview?.readyState>=2&&preview.videoWidth&&preview.videoHeight){try{
    const canvas=document.createElement('canvas');canvas.width=480;canvas.height=Math.round(480*preview.videoHeight/preview.videoWidth);
    canvas.getContext('2d').drawImage(preview,0,0,canvas.width,canvas.height);image=canvas.toDataURL('image/jpeg',.88);frozen.set(victim.accountId,image);
   }catch{}}
   if(preview)preview.srcObject=null;
   if(image){const still=el('img');still.src=image;still.alt='Dernière image de '+victim.name;face.replaceChildren(still);}
   face.dataset.frozen='true';
   for(const seat of document.querySelectorAll('.bf-player')){if(seat.dataset.owner===(victim.isYou?'local':victim.accountId)&&image){const portrait=seat.querySelector('.gt-portrait');if(portrait){const still=el('img');still.src=image;still.alt='Dernière image de '+victim.name;portrait.replaceChildren(still);portrait.classList.add('gt-eliminated');}}}
  }
  const cards=el('div');cards.className='bf-verdict-cards';for(const rank of r.cards){const card=el('span',rank==='J'?'★':rank);cards.append(card);}
  const drum=el('div');drum.className='bf-drum';drum.setAttribute('aria-hidden','true');for(let i=0;i<6;i++){const chamber=el('i');chamber.style.setProperty('--chamber',i);drum.append(chamber);}const hub=el('b','ONE');drum.append(hub);
  const result=el('strong','');result.setAttribute('role','status');const close=el('button','Retour à la table');close.type='button';
  let timer,previewTimer,disposeScene;const finish=()=>{disposeScene?.();clearTimeout(timer);clearInterval(previewTimer);if(preview)preview.srcObject=null;overlay.remove();if(cinema===overlay)cinema=null;};close.onclick=finish;
  overlay.append(title,face,who,cards,drum,result,close);panel.append(overlay);syncPreview();previewTimer=setInterval(()=>{if(!overlay.isConnected){clearInterval(previewTimer);if(preview)preview.srcObject=null;return;}syncPreview();},200);
  const verdict=()=>{if(!overlay.isConnected)return;if(r.eliminated)freezePreview();overlay.classList.add(r.eliminated?'bf-lost':'bf-saved','bf-resolved');title.textContent=r.eliminated?'ÉLIMINÉ':'SAUVÉ';result.textContent=r.eliminated?'Fin de manche pour '+r.penalized:'CLIC · '+r.penalized+' reste en jeu';window.ONEBluffSound?.effect?.(g,1,true);timer=setTimeout(finish,1500);};
  if(reduced){verdict();return;}
  cards.animate([{opacity:0,transform:'perspective(500px) rotateY(90deg) translateY(20px)'},{opacity:1,transform:'perspective(500px) rotateY(0deg) translateY(0)'}],{duration:550,easing:'ease-out'});
  drum.className='bf-revolver-stage';drum.replaceChildren(el('small','Préparation de la scène…'));
  cinemaModule.then(m=>m.mount(drum,{eliminated:r.eliminated,onImpact:verdict,getTargetRect:()=>face.getBoundingClientRect(),onPhase:text=>{if(overlay.isConnected)title.textContent=text;},isCancelled:()=>!overlay.isConnected})).then(dispose=>{disposeScene=dispose;if(!overlay.isConnected)disposeScene?.();}).catch(()=>{if(overlay.isConnected){drum.replaceChildren(el('small','Scène 3D indisponible sur cet appareil'));verdict();}});


 }
 function bluff(scene,g,el){
  if(gameId!==g.id){reset();gameId=g.id;}
  scene.setAttribute('aria-label','Table ONE Bluff');let seats=scene.__oneBluffSeats;
  if(!seats){seats=new Map();scene.__oneBluffSeats=seats;}
  const rivals=g.players.filter(p=>!p.isYou),layouts={1:[[50,6,1]],2:[[22,13,1],[78,13,1]],3:[[50,3,1],[16,23,1],[84,23,1]],4:[[32,20,.78],[68,20,.78],[16,36,.84],[84,36,.84]],5:[[50,17,.72],[17,26,.78],[83,26,.78],[16,41,.82],[84,41,.82]]},slots=layouts[rivals.length]||layouts[5];
  for(const [i,p]of rivals.entries()){
   const id=String(p.accountId||p.name),[x,y,scale]=slots[i];let seat=seats.get(id);
   if(!seat){seat=el('article');seat.className='bf-player';seat.dataset.owner=id;const face=el('div');face.className='gt-portrait';face.dataset.cameraSeat=p.accountId||'';avatar(face,p);const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=id;const name=el('b'),count=el('small');count.className='bf-count';const backs=el('div');backs.className='bf-backs';seat.append(face,mic,name,count,backs);scene.append(seat);seats.set(id,seat);}
   seat.classList.toggle('bf-current',!!p.isTurn);if(p.eliminated&&seat.dataset.wasEliminated!=='true'){const oldFace=seat.querySelector('.gt-portrait'),frozenFace=portrait(p,el),mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=id;frozenFace.append(mic);oldFace.replaceWith(frozenFace);}seat.dataset.wasEliminated=String(!!p.eliminated);seat.dataset.eliminated=String(!!p.eliminated);if(seat.dataset.layoutId!==id){seat.style.setProperty('--seat-x',x+'%');seat.style.setProperty('--seat-y',y+'%');seat.style.setProperty('--seat-scale',scale);seat.dataset.layoutId=id;}seat.querySelector('b').textContent=p.name;seat.querySelector('.bf-count').textContent=p.eliminated?'ÉLIMINÉ':p.count+' cartes';
   const backs=seat.querySelector('.bf-backs'),amount=Math.min(5,Math.max(0,p.count));while(backs.children.length>amount)backs.lastElementChild.remove();while(backs.children.length<amount){const card=el('i','ONE');backs.append(card);}for(const [n,card]of [...backs.children].entries())card.style.setProperty('--i',n-(amount-1)/2);
  }
  for(const [id,node]of seats)if(!rivals.some(p=>String(p.accountId||p.name)===id)){node.remove();seats.delete(id);}
  const center=scene.querySelector('.bf-center'),pending=center.querySelector('.bf-pending'),played=center.querySelector('.bf-played-cards'),backsToShow=g.pending?.count||0,source=Array.from({length:Math.min(3,backsToShow)},()=>({rank:null})),target=pending;center.querySelector('.bf-deck').hidden=!!g.pending;
  const nextKey=g.id+':'+g.revision+':'+(g.pending?.accountId||g.pending?.name||'')+':'+(g.reveal?.at||'');if(scene.dataset.centerState!==nextKey){const from=scene.dataset.centerOrigin?JSON.parse(scene.dataset.centerOrigin):[scene.getBoundingClientRect().left+scene.clientWidth/2,scene.getBoundingClientRect().top+scene.clientHeight*.44];const oldNodes=[...pending.children,...played.children].map(n=>n.getBoundingClientRect());pending.replaceChildren();played.replaceChildren();source.forEach((card,i)=>{const node=el('span',card.rank?(card.rank==='J'?'★':card.rank):'ONE');node.className=card.rank?'bf-proof-card':'bf-card-back';node.style.setProperty('--i',i-(source.length-1)/2);target.append(node);const rect=node.getBoundingClientRect();if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const origin=oldNodes.shift()||{left:from[0],top:from[1],width:rect.width,height:rect.height};node.animate([{transform:'translate3d('+((origin.left-rect.left)||0)+'px,'+((origin.top-rect.top)||0)+'px,0) scale(.82) rotate(-6deg)',opacity:.55},{transform:'translate3d(0,0,0) scale(1) rotate(0)',opacity:1}],{duration:360,delay:i*55,easing:'cubic-bezier(.2,.75,.25,1)'});}});scene.dataset.centerState=nextKey;scene.dataset.centerOrigin=JSON.stringify([scene.getBoundingClientRect().left+scene.clientWidth/2,scene.getBoundingClientRect().top+scene.clientHeight*.52]);}

  if(g.reveal)scene.dataset.revealKey=String(g.reveal.at);else delete scene.dataset.revealKey;media();if(g.reveal)reveal(g,el);
 }
 window.ONEPremiumTables={bluff,proof,portrait};
 const original=window.renderONEPartyPoker;
 window.renderONEPartyPoker=args=>{original(args);const {g,body,el}=args,root=body.querySelector('.onePartyPoker');if(!root)return;root.classList.add('gt-poker');const old=lastPoker?.id===g.id?lastPoker:null;const seats=[...root.querySelectorAll('.ppSeat')];g.players.forEach((p,i)=>{const seat=seats[i];if(!seat)return;seat.dataset.player=p.accountId;const dealer=g.players.findIndex(x=>x.accountId===g.dealer);if(dealer>=0){const sb=g.players.length===2?dealer:(dealer+1)%g.players.length,bb=(sb+1)%g.players.length;if(i===sb||i===bb){const badge=el('span',i===sb?'SB':'BB');badge.className='gt-blind';badge.title=i===sb?'Petite blinde':'Grosse blinde';seat.append(badge);}}const own=Math.max(0,g.players.findIndex(x=>x.isYou)),slot=(i-own+g.players.length)%g.players.length;seat.style.top=(50+30*Math.cos(slot/g.players.length*Math.PI*2))+'%';const face=portrait(p,el);face.classList.add('ppAvatar');seat.querySelector('.ppAvatar').replaceWith(face);const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=p.isYou?'local':p.accountId;face.append(mic);if((g.winners||[]).some(w=>(typeof w==='string'?w:w.accountId||w.id)===p.accountId))seat.classList.add('gt-winner');if(!old||old.handNumber!==g.handNumber)seat.querySelectorAll('.ppCard').forEach(c=>c.classList.add('gt-card-reveal'));const before=old?.players.find(x=>x.accountId===p.accountId);if(before&&!before.folded&&p.folded)seat.classList.add('gt-fold');if(before&&p.bet>before.bet)seat.querySelector('.ppBet')?.classList.add('gt-bet-in');});
  root.querySelectorAll('.ppCommunity .ppCard').forEach((c,i)=>{if(g.board[i]!=null&&(!old||old.board[i]!==g.board[i]))c.classList.add('gt-card-reveal');});const chips=el('div');chips.className='gt-chips';chips.setAttribute('aria-hidden','true');if(g.pot||g.wonPot)for(let i=0;i<5;i++){const stack=el('i');stack.style.setProperty('--i',i);chips.append(stack);}root.querySelector('.ppPot').after(chips);const mark=el('div','♛\nONE');mark.className='gt-felt-mark';root.querySelector('.ppFelt').append(mark);
  const amount=root.querySelector('.ppAmount'),raise=root.querySelector('.ppActions button:last-child');if(amount&&raise){const sync=()=>{const value=Math.min(g.maxRaise,Math.max(g.minRaise,Math.round(Number(amount.value)||g.minRaise)));raise.textContent='Relancer · '+value;};root.querySelector('.ppControls').addEventListener('input',sync);root.querySelector('.ppControls').addEventListener('change',sync);root.querySelector('.ppPresets').addEventListener('click',sync);sync();}if(old&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const pot=root.querySelector('.ppPot'),dest=pot.getBoundingClientRect();function fly(from,to){const chip=el('i');chip.className='gt-flying-chip';Object.assign(chip.style,{position:'fixed',left:from.left+from.width/2+'px',top:from.top+from.height/2+'px'});document.body.append(chip);chip.animate([{transform:'translate3d(0,0,0)',opacity:1},{transform:'translate3d('+((to.left+to.width/2)-(from.left+from.width/2))+'px,'+((to.top+to.height/2)-(from.top+from.height/2))+'px,0)',opacity:.3}],{duration:550,easing:'ease-out'}).finished.finally(()=>chip.remove());}g.players.forEach((p,i)=>{const before=old.players.find(x=>x.accountId===p.accountId);if(before&&p.bet>before.bet)fly(seats[i].getBoundingClientRect(),dest);});if(old.status==='playing'&&g.status==='finished')root.querySelectorAll('.gt-winner').forEach(n=>fly(dest,n.getBoundingClientRect()));}lastPoker=JSON.parse(JSON.stringify(g));media();
 };
})();

/* One timeline owns both the verdict and its sound. */
(()=>{const s=document.createElement('style');s.textContent=`#onePartyGame .bf-verdict{gap:12px;background:radial-gradient(ellipse at center,#321642ed,#050611fa 75%)!important}#onePartyGame .bf-verdict .bf-cinema-face{width:86px;height:86px;transition:filter .3s,box-shadow .3s}#onePartyGame .bf-verdict-cards{display:flex;gap:9px;min-height:88px;align-items:center;transition:opacity .3s}#onePartyGame .bf-verdict-cards span{display:grid;place-items:center;width:52px;height:76px;border-radius:8px;border:2px solid #efcf90;background:linear-gradient(135deg,#fff8e8,#ccbb9c);color:#171220;font:700 30px Georgia;box-shadow:0 8px 25px #0009}#onePartyGame .bf-drum{position:relative;width:180px;height:180px;flex-shrink:0;border-radius:50%;border:5px solid #b89962;background:repeating-conic-gradient(#6b6153 0deg 8deg,#3b3735 8deg 60deg);box-shadow:inset 0 0 0 7px #19171c,inset 0 0 22px #fff5,0 0 45px #bd6ffa33}#onePartyGame .bf-drum i{position:absolute;left:calc(50% - 20px);top:calc(50% - 20px);width:40px;height:40px;border-radius:50%;background:radial-gradient(circle,#07070b 45%,#211e26 65%,#a18b68 70%,#18151a 79%);transform:rotate(calc(var(--chamber)*60deg)) translateY(-57px)}#onePartyGame .bf-drum b{position:absolute;inset:65px;display:grid;place-items:center;color:#e5c083;font-size:10px;border-radius:50%;background:#17151a;border:1px solid #a28b65}#onePartyGame .bf-verdict strong{min-height:30px;font-size:18px!important}#onePartyGame .bf-saved .bf-cinema-face{box-shadow:0 0 35px #41ddaa;border-color:#41ddaa}#onePartyGame .bf-lost .bf-cinema-face{filter:grayscale(1);border-color:#ff3264;box-shadow:0 0 35px #ff3264}#onePartyGame .bf-resolved .bf-drum{opacity:.45}#onePartyGame .bf-verdict button{margin:0}@media(max-height:650px){#onePartyGame .bf-verdict{gap:7px;padding:12px}#onePartyGame .bf-verdict .bf-cinema-face{width:52px;height:52px}#onePartyGame .bf-verdict-cards{min-height:60px}#onePartyGame .bf-verdict-cards span{width:36px;height:52px;font-size:24px}#onePartyGame .bf-drum{zoom:.75}}`;document.head.append(s);})();

(()=>{const s=document.createElement('style');s.textContent='#onePartyGame .bf-verdict .bf-cinema-face video{width:100%!important;height:100%!important;min-height:0!important;max-height:none!important;border:0!important;border-radius:0!important;object-fit:cover!important;animation:none!important;transform:none!important;box-shadow:none!important}';document.head.append(s);})();

(()=>{const s=document.createElement('style');s.textContent='#onePartyGame .bf-revolver-stage{width:min(90vw,620px);height:clamp(160px,32dvh,320px);display:grid;place-items:center;background:radial-gradient(ellipse,#71433733,transparent 70%)}#onePartyGame .bf-revolver-stage canvas{width:100%;height:100%;display:block}#onePartyGame .bf-verdict .bf-cinema-face{width:clamp(80px,16dvh,140px);height:clamp(80px,16dvh,140px)}#onePartyGame .bf-verdict{gap:8px}';document.head.append(s);})();

(()=>{const style=document.createElement('style');style.textContent=`
#onePartyGame .bf-verdict{display:block!important;padding:0!important;background:linear-gradient(#080411b8,#08041166 50%,#080411e8),url('ui/game-lounge-109.webp') center/cover!important;overflow:hidden;min-height:0}
#onePartyGame .bf-verdict:before{inset:0;border:0;border-radius:0;box-shadow:inset 0 0 130px 35px #05040ce0;z-index:0}
#onePartyGame .bf-verdict h3{position:absolute;top:5%;left:5%;right:5%;font-size:clamp(20px,4vw,32px)!important;z-index:3;color:#f5dbaa;text-transform:uppercase;letter-spacing:.08em}
#onePartyGame .bf-verdict .bf-cinema-face{position:absolute;top:13%;left:50%;transform:translateX(-50%);width:clamp(110px,24vw,210px);height:clamp(90px,18dvh,150px);border-radius:18px;background:#171022;z-index:3;border:1px solid #b18b53;box-shadow:0 8px 40px #0008}
#onePartyGame .bf-verdict>p{position:absolute;top:calc(13% + clamp(90px,18dvh,150px));left:10%;right:10%;text-align:center;padding-top:6px;z-index:3;font-weight:700}
#onePartyGame .bf-verdict .bf-revolver-stage{position:absolute;inset:28% 0 8%;width:100%;height:auto;background:transparent}
#onePartyGame .bf-verdict .bf-verdict-cards{position:absolute;left:4%;top:40%;z-index:3;gap:5px;transform:scale(.75);transform-origin:left center}
#onePartyGame .bf-verdict strong{position:absolute;bottom:13%;left:6%;right:6%;z-index:3;text-align:center;padding:12px;background:#08071199;border-radius:12px;pointer-events:none}
#onePartyGame .bf-verdict strong:empty{display:none}
#onePartyGame .bf-verdict>button{position:absolute;bottom:4%;left:50%;transform:translateX(-50%);z-index:4;white-space:nowrap}
#onePartyGame .bf-verdict.bf-resolved .bf-verdict-cards{opacity:0}
@media(max-width:500px){#onePartyGame .bf-verdict .bf-verdict-cards{top:37%;left:2%;transform:scale(.6)}#onePartyGame .bf-verdict .bf-revolver-stage{inset:30% -12% 8%;width:124%}}
`;document.head.append(style);})();
