/* Presentation of public game snapshots only. No game, wallet or membership writes. */
(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/game-tables.css?v=014109';document.head.append(css);
 const frozen=new Map(),seen=new Set();let gameId='',lastPoker=null,cinema=null;
 function avatar(face,p){const member=window.oneSocialRoom?.()?.members?.find(m=>m.accountId===p.accountId)||p;if(window.ONEUI)face.append(ONEUI.avatar(member));else face.textContent=p.name.slice(0,1);}
 function capture(p){const owner=p.isYou?'local':p.accountId,b=[...document.querySelectorAll('.oneCamBubble')].find(n=>n.dataset.cameraOwner===owner),v=b?.querySelector('video');if(!v||v.classList.contains('off')||v.readyState<2)return null;try{const c=document.createElement('canvas');c.width=c.height=160;const w=v.videoWidth,h=v.videoHeight,k=Math.min(w,h);if(!k)return null;c.getContext('2d').drawImage(v,(w-k)/2,(h-k)/2,k,k,0,0,160,160);return c.toDataURL('image/jpeg',.75);}catch{return null;}}
 function portrait(p,el){const face=el('div');face.className='gt-portrait';if(p.eliminated){if(!frozen.has(p.accountId))frozen.set(p.accountId,capture(p));const image=frozen.get(p.accountId);if(image){const img=el('img');img.src=image;img.alt=p.name;face.append(img);}else avatar(face,p);face.classList.add('gt-eliminated');face.append(el('b','×'));}else{face.dataset.cameraSeat=p.isYou?'local':p.accountId;avatar(face,p);}return face;}
 function media(){document.querySelectorAll('.gt-mic').forEach(n=>{const m=window.ONEPartyMedia?.memberStatus?.(n.dataset.owner);n.textContent=m?.mic===true?'🎤':m?.mic===false?'🔇':'·';n.title=m?.mic===undefined?'État du micro indisponible':m.mic?'Micro actif':'Micro coupé';});const visible=!!document.querySelector('#onePartyGame .bf-premium')&&window.onePartyGameVisible?.()&&!window.oneSalonIsOpen?.();document.querySelectorAll('.oneCamBubble').forEach(b=>{const eliminated=visible&&[...document.querySelectorAll('.bf-player[data-eliminated=true]')].some(p=>p.dataset.owner===b.dataset.cameraOwner);b.classList.toggle('gt-camera-hidden',!!eliminated);});}
 ['one-media-state','one-game-rendered','one-space-open','one-salon-visibility'].forEach(e=>window.addEventListener(e,()=>queueMicrotask(media)));
 function reset(){frozen.clear();seen.clear();gameId='';cinema?.remove();cinema=null;document.querySelectorAll('.gt-camera-hidden').forEach(n=>n.classList.remove('gt-camera-hidden'));}
 window.addEventListener('one-account-changed',reset);window.addEventListener('one-party-state',e=>{if(!e.detail)reset();});window.addEventListener('one-game-rendered',()=>{if(!document.querySelector('.bf-premium')){cinema?.remove();cinema=null;}});
 function proof(scene,r,el){scene.querySelector('.bf-proof')?.remove();const box=el('section');box.className='bf-proof';box.setAttribute('aria-label','Cartes révélées par le serveur');box.append(el('b',r.name+' · '+(r.honest?'Annonce vraie':'BLUFF !')));const cards=el('div');for(const rank of r.cards){const c=el('span',rank==='J'?'★':rank);c.className='bf-proof-card';cards.append(c);}box.append(cards,el('small',r.penalized+' · '+(r.eliminated?'Éliminé':'Toujours en jeu')));scene.append(box);return box;}
 function reveal(g,el){const r=g.reveal;if(!r)return;const key=g.id+':'+r.at;if(seen.has(key))return;seen.add(key);if(Date.now()-r.at>7000||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const panel=document.getElementById('onePartyGame');if(!panel)return;cinema?.remove();const overlay=el('section');cinema=overlay;overlay.className='bf-cinema';overlay.setAttribute('aria-label','Résultat de l’accusation');const title=el('h3',r.honest?'ANNONCE VRAIE':'BLUFF !'),who=el('p',r.penalized),cards=el('div');cards.className='bf-cinema-cards';r.cards.forEach(rank=>cards.append(el('span',rank==='J'?'★':rank)));const video=el('video');video.muted=true;video.playsInline=true;video.preload='auto';video.src='ui/bluff-'+(r.eliminated?'shot':'click')+'-109.webm';video.poster='ui/bluff-cinema-109.webp';video.hidden=true;const result=el('strong',r.eliminated?'ÉLIMINÉ':'CLIC · ENCORE EN JEU');result.hidden=true;const close=el('button','Retour à la table');close.type='button';close.onclick=()=>{video.pause();overlay.remove();if(cinema===overlay)cinema=null;};overlay.append(title,who,cards,video,result,close);panel.append(overlay);
  const later=(fn,ms)=>setTimeout(()=>{if(overlay.isConnected)fn();},ms);later(()=>{cards.hidden=true;video.hidden=false;video.play().catch(()=>{video.hidden=true;result.hidden=false;});},850);video.onended=()=>{video.hidden=true;result.hidden=false;overlay.classList.toggle('bf-lost',r.eliminated);};video.onerror=()=>{video.hidden=true;result.hidden=false;};later(()=>{video.pause();overlay.remove();if(cinema===overlay)cinema=null;},Math.max(3000,Math.min(5800,(g.resumeAt||Date.now()+5800)-Date.now())));
 }
 function bluff(scene,g,el){if(gameId!==g.id){reset();gameId=g.id;}scene.setAttribute('aria-label','Table ONE Bluff');const opponents=g.players.filter(p=>!p.isYou),positions=opponents.length===1?[[50,20]]:opponents.length===2?[[19,85],[81,85]]:opponents.length===3?[[50,12],[16,155],[84,155]]:[[50,12],[15,100],[85,100],[15,260],[85,260]];
  g.players.forEach(p=>{const own=p.isYou,i=opponents.indexOf(p),seat=el('article');seat.className='bf-player'+(p.isTurn?' bf-current':'')+(own?' bf-own':'');seat.dataset.owner=own?'local':p.accountId;seat.dataset.eliminated=String(!!p.eliminated);seat.style.left=(own?50:positions[i][0])+'%';seat.style.top=(own?430:positions[i][1])+'px';const face=portrait(p,el),mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=seat.dataset.owner;face.append(mic);seat.append(face,el('b',own?'Toi':p.name),el('small',p.eliminated?'ÉLIMINÉ':p.count+' cartes'));if(!own&&!p.eliminated){const backs=el('div');backs.className='bf-backs';for(let n=0;n<p.count;n++){const c=el('i','ONE');c.style.setProperty('--i',n-(p.count-1)/2);backs.append(c);}seat.append(backs);}scene.append(seat);});
  const center=el('div');center.className='bf-center';const deck=el('div','✦\nONE');deck.className='bf-deck';center.append(deck,el('small','Dernière annonce'),el('b',g.pending?g.pending.name+' · '+g.pending.count+' '+({A:'As',K:'Rois',Q:'Dames'}[g.target]||g.target):'À toi de faire parler les cartes'));if(g.resumeAt>Date.now()){const pause=el('small','Nouvelle manche après la révélation');center.append(pause);}scene.append(center);if(g.reveal)reveal(g,el);media();
 }
 window.ONEPremiumTables={bluff,proof};
 const original=window.renderONEPartyPoker;
 window.renderONEPartyPoker=args=>{original(args);const {g,body,el}=args,root=body.querySelector('.onePartyPoker');if(!root)return;root.classList.add('gt-poker');const old=lastPoker?.id===g.id?lastPoker:null;const seats=[...root.querySelectorAll('.ppSeat')];g.players.forEach((p,i)=>{const seat=seats[i];if(!seat)return;seat.dataset.player=p.accountId;const own=Math.max(0,g.players.findIndex(x=>x.isYou)),slot=(i-own+g.players.length)%g.players.length;seat.style.top=(50+30*Math.cos(slot/g.players.length*Math.PI*2))+'%';const face=portrait(p,el);face.classList.add('ppAvatar');seat.querySelector('.ppAvatar').replaceWith(face);const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=p.isYou?'local':p.accountId;face.append(mic);if((g.winners||[]).some(w=>(typeof w==='string'?w:w.accountId||w.id)===p.accountId))seat.classList.add('gt-winner');const before=old?.players.find(x=>x.accountId===p.accountId);if(before&&!before.folded&&p.folded)seat.classList.add('gt-fold');if(before&&p.bet>before.bet)seat.querySelector('.ppBet')?.classList.add('gt-bet-in');});
  root.querySelectorAll('.ppCommunity .ppCard').forEach((c,i)=>{if(g.board[i]!=null&&(!old||old.board[i]!==g.board[i]))c.classList.add('gt-card-reveal');});const chips=el('div');chips.className='gt-chips';chips.setAttribute('aria-hidden','true');if(g.pot||g.wonPot)for(let i=0;i<5;i++){const stack=el('i');stack.style.setProperty('--i',i);chips.append(stack);}root.querySelector('.ppPot').after(chips);const mark=el('div','♛\nONE');mark.className='gt-felt-mark';root.querySelector('.ppFelt').append(mark);
  const amount=root.querySelector('.ppAmount'),raise=root.querySelector('.ppActions button:last-child');if(amount&&raise){const sync=()=>{const value=Math.min(g.maxRaise,Math.max(g.minRaise,Math.round(Number(amount.value)||g.minRaise)));raise.textContent='Relancer · '+value;};root.querySelector('.ppControls').addEventListener('input',sync);root.querySelector('.ppControls').addEventListener('change',sync);root.querySelector('.ppPresets').addEventListener('click',sync);sync();}lastPoker=JSON.parse(JSON.stringify(g));media();
 };
})();
