/* Common game presentation only. No game state, wallet or membership mutations. */
(()=>{
 const {el,button}=ONEUI,css=el('link');css.rel='stylesheet';css.href='ui/game-shell.css?v=014109';document.head.append(css);
 let nativeArmedUntil=0,nativeSeen=false;
 const names={bluff:'ONE Bluff',poker:'ONE Poker',douze:'ONE Douze'};
 function hero(kind,name){const box=el('div',undefined,'ogl-hero');box.dataset.kind=kind;box.append(window.ONEGameArt?.(kind)||el('span'));const title=el('div',undefined,'ogl-hero-title');title.append(el('small','À TA TABLE, TES AMIS'),el('h3',name||names[kind]||'Party'),el('p',({bluff:'Bluffe. Observe. Survis.',poker:'Les cartes en main. Le salon ensemble.',douze:'Douze cartes. Chaque choix compte.'})[kind]||'Votre prochaine partie commence ici.'));box.append(title);return box;}
 async function native(panel){window.onePartyImmersive?.(true);try{if(document.fullscreenElement!==panel&&panel.requestFullscreen)await panel.requestFullscreen();}catch{/* Native fullscreen is optional; internal immersive mode is already active. */}}
 function exitNative(){if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});}
 document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement)nativeSeen=true;else if(nativeSeen){nativeSeen=false;window.onePartyImmersive?.(false);}});
 function closeMenus(){document.querySelectorAll('.ogm-menu[open]').forEach(m=>m.open=false);}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.ogm-menu[open]')){closeMenus();e.stopImmediatePropagation();e.preventDefault();}},true);
 function mediaState(){document.querySelectorAll('.ogm-media').forEach(b=>{const m=window.ONEPartyMedia?.memberStatus?.('local')||{},key=b.dataset.media,on=key==='voice'?!!m.connected:key==='camera'?window.ONEPartyMedia?.status?.().camera:window.ONEPartyMedia?.status?.().mic;b.setAttribute('aria-pressed',String(!!on));b.querySelector('small').textContent=key==='voice'?(on?'Connecté':'Rejoindre'):(on?'ON':'OFF');});document.querySelectorAll('.ogl-media').forEach(n=>{const m=window.ONEPartyMedia?.memberStatus?.(n.dataset.you==='true'?'local':n.dataset.account)||{};n.textContent=(m.mic===true?'🎤':m.mic===false?'🔇':'🎤 ·')+' '+(m.camera===true?'📹':'▣');n.title='Micro : '+(m.mic===undefined?'inconnu':m.mic?'actif':'coupé')+' · caméra : '+(m.camera===undefined?'inconnue':m.camera?'active':'coupée');});}
 window.addEventListener('one-media-state',mediaState);window.addEventListener('one-salon-rendered',mediaState);window.addEventListener('one-game-rendered',mediaState);
 function mount({panel,menu,tools,g,room,fullscreen,returnToGames,rules}){
  if(!g)return;menu.classList.add('ogm-menu');const summary=menu.querySelector('summary');summary.textContent='⋮';summary.setAttribute('aria-label','Menu du jeu');summary.setAttribute('aria-haspopup','dialog');tools.hidden=true;tools.classList.add('ogm-legacy');const backdrop=button('',()=>{menu.open=false;},'ogm-backdrop');backdrop.setAttribute('aria-label','Fermer le menu');const card=el('section',undefined,'ogm-panel');card.setAttribute('role','dialog');card.setAttribute('aria-label','Menu '+(names[g.kind]||window.ONEPartyCatalog?.[g.kind]?.name||'ONE Couleurs'));const title=names[g.kind]||window.ONEPartyCatalog?.[g.kind]?.name||'ONE Couleurs';const header=el('header');header.append(el('b','Menu'),el('small',title));card.append(header);const feedback=el('p',undefined,'ogm-feedback');feedback.setAttribute('role','status');
  function group(name){const n=el('section');n.append(el('h4',name));card.append(n);return n;}
  function action(parent,label,fn,cls=''){const b=button(label,fn,'ogm-action '+cls);parent.append(b);return b;}
  const part=group('PARTIE');action(part,'⛶ Plein écran',()=>{menu.open=false;native(panel);});action(part,'↔ Réduire le jeu',()=>{menu.open=false;exitNative();fullscreen(false);window.oneShowSpace?.('home');});action(part,'← Retour au Salon',()=>{menu.open=false;exitNative();fullscreen(false);window.oneOpenSalon?.();});
  const social=group('SOCIAL');for(const [label,key]of [['🎤 Micro','mic'],['▣ Caméra','camera'],['🎧 Vocal','voice']]){const b=action(social,label,async()=>{b.disabled=true;feedback.textContent='';try{if(key==='voice')document.getElementById('oneGameVoiceJoin')?.click();else await window.ONEPartyMedia?.toggle?.(key);}catch(e){feedback.textContent=e.message;}finally{b.disabled=false;mediaState();}});b.classList.add('ogm-media');b.dataset.media=key;b.append(el('small','OFF'));}action(social,'☏ Chat',()=>{menu.open=false;exitNative();fullscreen(false);window.oneOpenSalon?.();const chat=document.getElementById('onePartyChat');if(chat){chat.hidden=false;chat.scrollIntoView({block:'nearest'});}});
  const gameplay=group('JEU');function sub(title,fill){const view=el('div',undefined,'ogm-sub');view.append(button('← '+title,()=>view.remove(),'ogm-action'));fill(view);card.append(view);view.querySelector('button').focus();}action(gameplay,'▤ Règles de '+title,()=>sub('Règles',v=>v.append(el('h3',title),el('p',rules))));action(gameplay,'⚙ Préférences',()=>sub('Préférences',v=>{if(g.kind==='bluff'&&window.ONEBluffSound){const b=button('',()=>{window.ONEBluffSound.toggle();sync();},'ogm-action');function sync(){const on=window.ONEBluffSound.enabled();b.textContent='Son : '+(on?'activé':'coupé');b.setAttribute('aria-pressed',String(on));}sync();v.append(b);}else v.append(el('p','Aucun réglage local supplémentaire disponible pour ce jeu.'));v.append(el('p','Les animations respectent le réglage « Réduire les animations » de ton appareil.'));}));
  const sensitive=group('ACTIONS');action(sensitive,'↪ Quitter la partie',()=>{menu.open=false;returnToGames();},'ogm-danger');action(sensitive,'↪ Quitter le Salon',()=>{menu.open=false;exitNative();fullscreen(false);window.oneAskLeaveSalon?.();},'ogm-danger-secondary');card.append(feedback);menu.append(backdrop,card);menu.addEventListener('toggle',()=>{summary.setAttribute('aria-expanded',String(menu.open));if(menu.open)mediaState();});mediaState();
 }
 window.ONEGameMenu={mount,hero,arm:()=>{nativeArmedUntil=Date.now()+12000;},cancelArm:()=>{nativeArmedUntil=0;},enter(panel,g){const armed=Date.now()<nativeArmedUntil;nativeArmedUntil=0;const old=panel.querySelector('.ogm-enter');old?.remove();if(!matchMedia('(prefers-reduced-motion: reduce)').matches){const cover=el('div',undefined,'ogm-enter');cover.setAttribute('aria-hidden','true');cover.append(hero(g.kind,names[g.kind]||window.ONEPartyCatalog?.[g.kind]?.name));panel.append(cover);setTimeout(()=>cover.remove(),650);}if(armed)native(panel);},exitNative};
})();
