/* Presentation of public game snapshots only. No game, wallet or membership writes. */
(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/game-tables.css?v=014110';document.head.append(css);const bluffCss=document.createElement('link');bluffCss.rel='stylesheet';bluffCss.href='ui/bluff-table-structure.css?v=014110';document.head.append(bluffCss);
 const frozen=new Map(),seen=new Set();let gameId='',lastPoker=null,cinema=null;
 function avatar(face,p){const member=window.oneSocialRoom?.()?.members?.find(m=>m.accountId===p.accountId)||p;if(window.ONEUI)face.append(ONEUI.avatar(member));else face.textContent=p.name.slice(0,1);}
 function capture(p){const owner=p.isYou?'local':p.accountId,b=[...document.querySelectorAll('.oneCamBubble')].find(n=>n.dataset.cameraOwner===owner),v=b?.querySelector('video');if(!v||v.classList.contains('off')||v.readyState<2)return null;try{const c=document.createElement('canvas');c.width=c.height=160;const w=v.videoWidth,h=v.videoHeight,k=Math.min(w,h);if(!k)return null;c.getContext('2d').drawImage(v,(w-k)/2,(h-k)/2,k,k,0,0,160,160);return c.toDataURL('image/jpeg',.75);}catch{return null;}}
 function portrait(p,el){const face=el('div');face.className='gt-portrait';if(p.eliminated){if(!frozen.has(p.accountId))frozen.set(p.accountId,capture(p));const image=frozen.get(p.accountId);if(image){const img=el('img');img.src=image;img.alt=p.name;face.append(img);}else avatar(face,p);face.classList.add('gt-eliminated');face.append(el('b','×'));}else{face.dataset.cameraSeat=p.isYou?'local':p.accountId;avatar(face,p);}return face;}
 function media(){document.querySelectorAll('.gt-mic').forEach(n=>{const m=window.ONEPartyMedia?.memberStatus?.(n.dataset.owner);n.textContent=m?.mic===true?'🎤':m?.mic===false?'🔇':'·';n.title=m?.mic===undefined?'État du micro indisponible':m.mic?'Micro actif':'Micro coupé';});const visible=!!document.querySelector('#onePartyGame .bf-premium')&&window.onePartyGameVisible?.()&&!window.oneSalonIsOpen?.();document.querySelectorAll('.oneCamBubble').forEach(b=>{const eliminated=visible&&[...document.querySelectorAll('.bf-player[data-eliminated=true]')].some(p=>p.dataset.owner===b.dataset.cameraOwner);b.classList.toggle('gt-camera-hidden',!!eliminated);});}
 ['one-media-state','one-game-rendered','one-space-open','one-salon-visibility'].forEach(e=>window.addEventListener(e,()=>queueMicrotask(media)));
 function reset(){frozen.clear();seen.clear();gameId='';cinema?.remove();cinema=null;document.querySelectorAll('.gt-camera-hidden').forEach(n=>n.classList.remove('gt-camera-hidden'));}
 window.addEventListener('one-account-changed',reset);window.addEventListener('one-party-state',e=>{if(!e.detail)reset();});window.addEventListener('one-game-rendered',()=>{if(!document.querySelector('.bf-premium')){cinema?.remove();cinema=null;}});
 function proof(scene,r,el){scene.querySelector('.bf-proof')?.remove();const box=el('section');box.className='bf-proof';box.setAttribute('aria-label','Cartes révélées par le serveur');box.append(el('b',r.name+' · '+(r.honest?'Annonce vraie':'BLUFF !')));const cards=el('div');for(const rank of r.cards){const c=el('span',rank==='J'?'★':rank);c.className='bf-proof-card';cards.append(c);}box.append(cards,el('small',r.penalized+' · '+(r.eliminated?'Éliminé':'Toujours en jeu')));scene.append(box);return box;}
 function reveal(g,el){const r=g.reveal;if(!r)return;const key=g.id+':'+r.at;if(seen.has(key))return;seen.add(key);if(Date.now()-r.at>7000||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const panel=document.getElementById('onePartyGame');if(!panel)return;cinema?.remove();const overlay=el('section');cinema=overlay;overlay.className='bf-cinema';overlay.setAttribute('aria-label','Résultat de l’accusation');const title=el('h3',r.honest?'ANNONCE VRAIE':'BLUFF !'),who=el('p',r.penalized),cards=el('div');cards.className='bf-cinema-cards';r.cards.forEach(rank=>cards.append(el('span',rank==='J'?'★':rank)));const video=el('video');video.muted=true;video.playsInline=true;video.preload='auto';video.src='ui/bluff-'+(r.eliminated?'shot':'click')+'-109.webm';video.poster='ui/bluff-cinema-109.webp';video.hidden=true;const result=el('strong',r.eliminated?'ÉLIMINÉ':'CLIC · ENCORE EN JEU');result.hidden=true;const close=el('button','Retour à la table');close.type='button';close.onclick=()=>{video.pause();overlay.remove();if(cinema===overlay)cinema=null;};overlay.append(title,who,cards,video,result,close);panel.append(overlay);
  const later=(fn,ms)=>setTimeout(()=>{if(overlay.isConnected)fn();},ms);later(()=>{cards.hidden=true;video.hidden=false;video.play().catch(()=>{video.hidden=true;result.hidden=false;});},850);video.onended=()=>{video.hidden=true;result.hidden=false;overlay.classList.toggle('bf-lost',r.eliminated);};video.onerror=()=>{video.hidden=true;result.hidden=false;};later(()=>{video.pause();overlay.remove();if(cinema===overlay)cinema=null;},Math.max(3000,Math.min(5800,(g.resumeAt||Date.now()+5800)-Date.now())));
 }
 function bluff(scene,g,el){
  if(gameId!==g.id){reset();gameId=g.id;}
  scene.setAttribute('aria-label','Table ONE Bluff');let seats=scene.__oneBluffSeats;
  if(!seats){seats=new Map();scene.__oneBluffSeats=seats;}
  const rivals=g.players.filter(p=>!p.isYou),layouts={1:[[50,17,.72]],2:[[24,30,.80],[76,30,.80]],3:[[50,14,.70],[18,32,.82],[82,32,.82]],4:[[35,13,.68],[65,13,.68],[16,30,.80],[84,30,.80]],5:[[50,10,.62],[19,20,.74],[81,20,.74],[15,36,.84],[85,36,.84]]},slots=layouts[rivals.length]||layouts[5];
  for(const [i,p]of rivals.entries()){
   const id=String(p.accountId||p.name),[x,y,scale]=slots[i];let seat=seats.get(id);
   if(!seat){seat=el('article');seat.className='bf-player';seat.dataset.owner=id;const face=el('div');face.className='gt-portrait';face.dataset.cameraSeat=p.accountId||'';avatar(face,p);const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=id;const name=el('b'),count=el('small');count.className='bf-count';const backs=el('div');backs.className='bf-backs';seat.append(face,mic,name,count,backs);scene.append(seat);seats.set(id,seat);}
   seat.classList.toggle('bf-current',!!p.isTurn);if(p.eliminated&&seat.dataset.wasEliminated!=='true'){const oldFace=seat.querySelector('.gt-portrait'),frozenFace=portrait(p,el),mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=id;frozenFace.append(mic);oldFace.replaceWith(frozenFace);}seat.dataset.wasEliminated=String(!!p.eliminated);seat.dataset.eliminated=String(!!p.eliminated);seat.style.setProperty('--seat-x',x+'%');seat.style.setProperty('--seat-y',y+'%');seat.style.setProperty('--seat-scale',scale);seat.querySelector('b').textContent=p.name;seat.querySelector('.bf-count').textContent=p.eliminated?'ÉLIMINÉ':p.count+' cartes';
   const backs=seat.querySelector('.bf-backs'),amount=Math.min(5,Math.max(0,p.count));while(backs.children.length>amount)backs.lastElementChild.remove();while(backs.children.length<amount){const card=el('i','ONE');backs.append(card);}for(const [n,card]of [...backs.children].entries())card.style.setProperty('--i',n-(amount-1)/2);
  }
  for(const [id,node]of seats)if(!rivals.some(p=>String(p.accountId||p.name)===id)){node.remove();seats.delete(id);}
  const center=scene.querySelector('.bf-center'),pending=center.querySelector('.bf-pending'),played=center.querySelector('.bf-played-cards'),backsToShow=g.pending?.count||0,revealed=g.reveal?.cards||[],source=revealed.length?revealed.map(rank=>({rank})):Array.from({length:Math.min(3,backsToShow)},()=>({rank:null})),target=revealed.length?played:pending;center.querySelector('.bf-deck').hidden=!!g.pending||!!g.reveal;
  pending.replaceChildren();played.replaceChildren();source.forEach((card,i)=>{const node=el('span',card.rank?(card.rank==='J'?'★':card.rank):'ONE');node.className=card.rank?'bf-proof-card':'bf-card-back';node.style.setProperty('--i',i-(source.length-1)/2);target.append(node);if(card.rank&&scene.dataset.revealKey!==String(g.reveal.at))node.animate([{transform:'rotateY(90deg) translateY(-8px)',opacity:.2},{transform:'rotateY(0) translateY(0)',opacity:1}],{duration:420,delay:i*70,easing:'ease-out'});});
  if(g.reveal)scene.dataset.revealKey=String(g.reveal.at);else delete scene.dataset.revealKey;media();if(g.reveal)reveal(g,el);
 }
 window.ONEPremiumTables={bluff,proof};
 const original=window.renderONEPartyPoker;
 window.renderONEPartyPoker=args=>{original(args);const {g,body,el}=args,root=body.querySelector('.onePartyPoker');if(!root)return;root.classList.add('gt-poker');const old=lastPoker?.id===g.id?lastPoker:null;const seats=[...root.querySelectorAll('.ppSeat')];g.players.forEach((p,i)=>{const seat=seats[i];if(!seat)return;seat.dataset.player=p.accountId;const own=Math.max(0,g.players.findIndex(x=>x.isYou)),slot=(i-own+g.players.length)%g.players.length;seat.style.top=(50+30*Math.cos(slot/g.players.length*Math.PI*2))+'%';const face=portrait(p,el);face.classList.add('ppAvatar');seat.querySelector('.ppAvatar').replaceWith(face);const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner=p.isYou?'local':p.accountId;face.append(mic);if((g.winners||[]).some(w=>(typeof w==='string'?w:w.accountId||w.id)===p.accountId))seat.classList.add('gt-winner');const before=old?.players.find(x=>x.accountId===p.accountId);if(before&&!before.folded&&p.folded)seat.classList.add('gt-fold');if(before&&p.bet>before.bet)seat.querySelector('.ppBet')?.classList.add('gt-bet-in');});
  root.querySelectorAll('.ppCommunity .ppCard').forEach((c,i)=>{if(g.board[i]!=null&&(!old||old.board[i]!==g.board[i]))c.classList.add('gt-card-reveal');});const chips=el('div');chips.className='gt-chips';chips.setAttribute('aria-hidden','true');if(g.pot||g.wonPot)for(let i=0;i<5;i++){const stack=el('i');stack.style.setProperty('--i',i);chips.append(stack);}root.querySelector('.ppPot').after(chips);const mark=el('div','♛\nONE');mark.className='gt-felt-mark';root.querySelector('.ppFelt').append(mark);
  const amount=root.querySelector('.ppAmount'),raise=root.querySelector('.ppActions button:last-child');if(amount&&raise){const sync=()=>{const value=Math.min(g.maxRaise,Math.max(g.minRaise,Math.round(Number(amount.value)||g.minRaise)));raise.textContent='Relancer · '+value;};root.querySelector('.ppControls').addEventListener('input',sync);root.querySelector('.ppControls').addEventListener('change',sync);root.querySelector('.ppPresets').addEventListener('click',sync);sync();}lastPoker=JSON.parse(JSON.stringify(g));media();
 };
})();
