(()=>{
 const toggle=document.getElementById('oneNotificationsToggle'),panel=document.getElementById('oneNotifications');if(!toggle||!panel)return;
 const head=panel.firstElementChild;while(head.nextSibling)head.nextSibling.remove();
 const badge=document.createElement('span');badge.id='oneUnreadBadge';badge.hidden=true;toggle.append(badge);
 const status=document.createElement('p');status.setAttribute('role','status');const actions=document.createElement('div'),list=document.createElement('div');list.id='oneNotificationsList';
 const refresh=document.createElement('button');refresh.type='button';refresh.textContent='Actualiser';const read=document.createElement('button');read.type='button';read.textContent='Tout marquer comme lu';read.disabled=true;actions.append(refresh,read);panel.append(actions,status,list);
 const css=document.createElement('style');css.textContent='#oneNotificationsToggle{position:relative}#oneUnreadBadge{position:absolute;top:-3px;right:-5px;min-width:15px;padding:2px 4px;border-radius:12px;background:#a855f7;color:white;font:700 10px sans-serif}#oneUnreadBadge[hidden]{display:none}#oneNotifications{max-height:75dvh;overflow:auto}#oneNotificationsList article{border-top:1px solid #443751;padding:12px 8px;text-align:left}#oneNotificationsList article[data-unread="true"]{border-left:3px solid #af7bff;background:#a855f710}#oneNotificationsList p{white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}#oneNotificationsList small{color:#bbb0cb}#oneNotifications button{margin:3px;padding:7px;border-radius:9px;background:#302342;color:white;border:1px solid #65517e}#oneNotifications button:disabled{opacity:.5}';document.head.append(css);
 const API='https://one-comments-api.moulinanthony60.workers.dev';let revision=0,through=0,busyRead=false;
 function clear(){list.replaceChildren();badge.hidden=true;badge.textContent='';read.disabled=true;through=0;toggle.setAttribute('aria-label','Notifications');}
 async function request(path,method='GET'){const token=oneAccountToken();const response=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token}});const data=await response.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé.');if(!response.ok||!data.ok)throw Error(data.error||'Notifications momentanément indisponibles.');return data;}
 async function load(){const own=++revision;if(!oneAccountToken()){clear();status.textContent='Connecte-toi à ONE pour voir tes notifications.';return;}try{const data=await request('/notifications');if(own!==revision)return;through=data.through;badge.textContent=data.unread>99?'99+':String(data.unread);badge.hidden=!data.unread;toggle.setAttribute('aria-label',data.unread?'Notifications : '+data.unread+' non lues':'Notifications');read.disabled=busyRead||!data.unread;status.textContent=data.notifications.length?'Tes 50 dernières notifications au maximum.':'Aucune notification pour le moment.';list.replaceChildren();for(const n of data.notifications){const article=document.createElement('article');article.dataset.unread=String(!n.read);const title=document.createElement('b'),body=document.createElement('p'),date=document.createElement('small');title.textContent=n.kind==='party'?n.author+' t’invite dans Party':n.kind==='report'?'Un commentaire a été signalé':n.author+' a répondu à ton commentaire';body.textContent=n.text;date.textContent=new Date(n.createdAt).toLocaleString('fr-FR');article.append(title,date,body);if(n.context){const quote=document.createElement('small');quote.textContent='Ton commentaire : '+n.context;article.append(quote);}if(n.kind==='party'){const join=document.createElement('button');join.type='button';join.textContent='Voir l’invitation';join.onclick=()=>{panel.hidden=true;toggle.setAttribute('aria-expanded','false');document.querySelector('[data-one-space=party]')?.click();window.dispatchEvent(new Event('one-party-refresh'));};article.append(join);}if(n.kind==='report'){const mod=document.createElement('button');mod.textContent='Ouvrir la modération';mod.type='button';mod.onclick=()=>document.getElementById('oneModerationEntry')?.click();article.append(mod);}list.append(article);}}catch(e){if(own===revision){status.textContent=e.message;read.disabled=true;}}}
 read.onclick=async()=>{if(!through||busyRead)return;busyRead=true;read.disabled=true;const own=revision;let success=false;try{await request('/notifications/read?through='+through,'POST');success=true;}catch(e){if(own===revision)status.textContent=e.message;}finally{busyRead=false;if(success&&own===revision)load();else if(own===revision)read.disabled=false;}};
 refresh.onclick=load;toggle.addEventListener('click',()=>{if(!panel.hidden)load();});
 window.addEventListener('one-account-changed',()=>{++revision;clear();load();});window.addEventListener('one-notifications-refresh',load);
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)load();});setInterval(()=>{if(!document.hidden&&oneAccountToken())load();},60000);load();
})();
