(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev';
 const css=document.createElement('style');css.textContent=`#onePointsPanel .casino{display:grid;gap:16px;text-align:left}#onePointsPanel .casino button{font-size:14px;width:auto;padding:10px 16px}#onePointsPanel .casino button:disabled{opacity:.45;cursor:default}#onePointsPanel .casino input{width:65px;background:#21172c;color:#fff;border:1px solid #987ab0;border-radius:9px;padding:10px;font-size:16px}#onePointsPanel .casino select{background:#21172c;color:#fff;border:1px solid #987ab0;border-radius:9px;padding:10px;font-size:16px}#onePointsPanel .casinoToolbar{display:flex;flex-wrap:wrap;align-items:center;gap:10px}#onePointsPanel .casinoBalance{font-size:22px;color:#f3d58b}#onePointsPanel .casinoTable{border:1px solid #a38955;border-radius:18px;padding:20px 12px;background:radial-gradient(ellipse at center,#245344,#112c26);text-align:center;min-height:180px}#onePointsPanel .casinoReels{display:flex;justify-content:center;gap:8px;margin:20px 0;font-size:34px}#onePointsPanel .casinoReel{border:1px solid #d9bc77;padding:10px;background:#fff4d5;color:#241c32;border-radius:9px}#onePointsPanel .casinoCards{display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin:12px 0}#onePointsPanel .casinoCard{background:#fff5e1;border:1px solid #d1bc81;color:#282335;padding:16px 9px;border-radius:7px;min-width:26px;font-size:21px}#onePointsPanel .casinoCard.red{color:#b32442}#onePointsPanel .rouletteBall{margin:15px auto;border:4px solid #dfc581;border-radius:50%;width:95px;height:95px;display:grid;place-items:center;font-size:42px;background:#172c24}#onePointsPanel .rouletteBall.red{background:#9e2940}#onePointsPanel .rouletteBall.black{background:#17141c}#onePointsPanel .casinoResult{font-size:20px;color:#f3d58b;margin:15px 0}#onePointsPanel .casinoNotice{min-height:24px;color:#f0d48e}#onePointsPanel .casinoTable.reveal{animation:oneReveal .3s ease-out}@keyframes oneReveal{from{opacity:.4;transform:translateY(6px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){#onePointsPanel .casinoTable.reveal{animation:none}}`;document.head.append(css);
 window.ONECasinoMount=async host=>{
  let data={balance:0,dailyClaimed:false,round:null},kind='roulette',busy=false,alive=true,loaded=false,pending=null,stake=10,choice='red',selectedNumber=0;const token=window.oneAccountToken?.();
  const current=()=>alive&&host.isConnected&&host.contains(root)&&token===window.oneAccountToken?.();
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};host.replaceChildren();const root=el('div',undefined,'casino');host.append(root);const msg=el('p','','casinoNotice');msg.setAttribute('role','status');
  let storageKey='';if(token){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));storageKey='one-casino-'+Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');try{pending=JSON.parse(localStorage.getItem(storageKey)||'null');}catch{}}
  async function api(path,body){if(!token)throw Error('Connecte-toi à ton compte ONE pour jouer.');const r=await fetch(API+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const d=await r.json();if(token!==window.oneAccountToken?.())throw Error('Le compte a changé. Rouvre Points ONE.');if(!r.ok){const e=Error(d.error||'Action indisponible.');e.definitive=r.status>=400&&r.status<500;throw e;}return d;}
  const save=()=>{try{if(pending)localStorage.setItem(storageKey,JSON.stringify(pending));else localStorage.removeItem(storageKey);}catch{}};
  async function run(path,body,retry=false){if(busy)return;busy=true;if(!retry&&path!=='/points/daily'){pending={path,body};save();}render();msg.textContent='Validation…';try{const d=await api(path,body);if(!current())return;const old=data.round;data=d;if(path==='/points/daily')data.round=old;pending=null;save();if(data.round)kind=data.round.kind;loaded=true;msg.textContent=path==='/points/daily'?'Récompense quotidienne récupérée.':'';}catch(e){if(e.definitive){pending=null;save();}if(current()){msg.textContent=e.message+(pending?' Réessaie pour retrouver le résultat, sans nouvelle mise.':'');}}finally{busy=false;if(current()){const message=msg.textContent;render();msg.textContent=message;}}}
  function button(label,fn,disabled=false){const b=el('button',label);b.type='button';b.disabled=disabled||busy;b.onclick=fn;return b;}
  function total(cards){let t=cards.filter(c=>c!==null).reduce((n,c)=>n+Math.min(c%13+1,10),0);for(const c of cards)if(c!==null&&c%13===0&&t+10<=21)t+=10;return t;}
  function cards(parent,cards){const row=el('div',undefined,'casinoCards');for(const c of cards){const rank=c===null?'?':['A','2','3','4','5','6','7','8','9','10','V','D','R'][c%13],suit=c===null?'':['♠','♥','♦','♣'][Math.floor(c/13)];const tile=el('span',undefined,'casinoCard'+(c===null?' back':'')+(c!==null&&[1,2].includes(Math.floor(c/13))?' red':''));tile.append(el('span',rank+suit));if(c!==null)tile.append(el('small',c%13===0?'1 ou 11':Math.min(c%13+1,10)+' pts','casinoCardValue'));row.append(tile);}parent.append(row);}

  function render(){root.replaceChildren();const bar=el('div',undefined,'casinoToolbar');bar.append(el('strong',data.balance.toLocaleString('fr-FR')+' Points ONE','casinoBalance'),button(data.dailyClaimed?'100 points récupérés':'Récupérer 100 points',()=>run('/points/daily',{}),!loaded||data.dailyClaimed||!!pending));root.append(bar);const tabs=el('div',undefined,'casinoToolbar');for(const [id,name]of [['roulette','Roulette'],['blackjack','Blackjack'],['slots','Machine à sous']]){const b=button(name,()=>{kind=id;render();},!!pending||!!(data.round&&!data.round.settled));b.setAttribute('aria-pressed',String(kind===id));tabs.append(b);}root.append(tabs);const controls=el('div',undefined,'casinoToolbar');const label=el('label','Mise : '),select=el('select');select.setAttribute('aria-label','Mise en Points ONE');for(const n of [10,25,50,100]){const o=el('option',n+' points');o.value=n;select.append(o);}select.value=stake;select.disabled=busy||!!pending||!!(data.round&&!data.round.settled);select.onchange=()=>{stake=+select.value;render();};label.append(select);controls.append(label);if(kind==='roulette'){const colors=el('select');colors.setAttribute('aria-label','Type de pari');for(const [id,name]of [['red','Rouge'],['black','Noir'],['number','Numéro']]){const o=el('option',name);o.value=id;colors.append(o);}colors.value=choice;colors.disabled=select.disabled;colors.onchange=()=>{choice=colors.value;render();};controls.append(colors);if(choice==='number'){const label=el('label','Numéro : '),number=el('input');number.type='number';number.min='0';number.max='36';number.step='1';number.value=selectedNumber;number.setAttribute('aria-label','Numéro de roulette de 0 à 36');number.disabled=select.disabled;number.oninput=()=>{selectedNumber=number.value===''?NaN:Number(number.value);};label.append(number);controls.append(label);}}root.append(controls);
   const table=el('div',undefined,'casinoTable reveal'),r=data.round?.kind===kind?data.round:null;table.dataset.game=kind;if(kind==='roulette'){table.append(window.ONECasinoWheel(r));}else if(kind==='slots'){table.append(el('div','ONE • LUCKY','slotMarquee'));const reels=el('div',undefined,'casinoReels');for(const n of r?.reels||[0,1,2])reels.append(el('span',['🍒','🍋','🔔','⭐','💎','7'][n],'casinoReel'));table.append(reels);}else{table.append(el('p',r?'Croupier · '+total(r.dealer)+(r.settled?' points':' visibles'):'Croupier'));cards(table,r?.dealer||[null,null]);table.append(el('p',r?'Ta main · '+total(r.player)+' points':'Ta main'));cards(table,r?.player||[null,null]);}if(r?.settled)table.append(el('div',r.result+' · '+(r.payout?'Retour : '+r.payout+' points':'Mise perdue'),'casinoResult'));root.append(table);
   if(pending)root.append(button('Retrouver mon résultat',()=>run(pending.path,pending.body,true)));else if(r&&!r.settled){const actions=el('div',undefined,'casinoToolbar');for(const [action,label]of [['hit','Carte'],['stand','Rester']])actions.append(button(label,()=>run('/points/blackjack',{id:r.id,version:r.version,action})));root.append(actions);}else root.append(button(kind==='blackjack'?'Distribuer':'Jouer',()=>{if(kind==='roulette'&&choice==='number'&&(!Number.isInteger(selectedNumber)||selectedNumber<0||selectedNumber>36)){msg.textContent='Choisis un numéro entier entre 0 et 36.';return;}run('/points/play',{id:crypto.randomUUID(),kind,stake,choice:choice==='number'?'n:'+selectedNumber:choice});},!loaded||data.balance<stake));
   const rules=kind==='roulette'?'Roulette européenne : rouge/noir = retour de 2 × la mise ; numéro exact (0 à 36) = 36 × la mise. Le zéro fait perdre les paris rouge/noir.':kind==='slots'?'3 symboles identiques : retour de 10 × la mise. Une paire : mise remboursée. Sinon : mise perdue.':'Atteins 21 sans dépasser. Le croupier tire jusqu’à 17. Victoire : retour de 2 × la mise ; égalité : mise remboursée. As : 1 ou 11. Pas de double, split ni bonus blackjack.';root.append(el('p',rules),el('p','Points virtuels, sans valeur monétaire. Les retours indiqués comprennent la mise.'),msg);
  }
  if(!current())return;render();try{const d=await api('/points/state');if(!current())return;data=d;loaded=true;if(data.round)kind=data.round.kind;render();if(pending)msg.textContent='Une demande attend sa confirmation. Retrouve son résultat avant de rejouer.';}catch(e){if(current())msg.textContent=e.message;}
  window.addEventListener('one-account-changed',()=>{alive=false;if(!host.contains(root))return;host.replaceChildren(el('p','Le compte a changé. Sélectionne à nouveau Jeux.'));},{once:true});
 };
})();
