(()=>{
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let selected=10;const revealed=new Set();
const symbolFor=v=>({10:'🍒',20:'🔔',50:'⭐',100:'💎',500:'7️⃣'}[Number(v)]||'🪙');const games={10:['Trésor ONE','✦','Chaque montant présent au moins 3 fois est gagné. Les montants gagnants se cumulent.'],50:['Numéros chance','7','Compare tes 12 numéros aux 3 numéros gagnants. Chaque correspondance rapporte son gain ; les gains se cumulent.'],100:['Temple des gemmes','◆','Trouve 3 gemmes identiques dans chaque mission. Les gains se cumulent. Trois clés ouvrent le coffre bonus.']};
window.ONEScratchMount=(host,{data,busy,serverVersion=0,pending,token,buy,retry})=>{
 const select=el('div',undefined,'oneScratchChoices');for(const [price,[name,icon]] of Object.entries(games)){const b=el('button',icon+' '+name+' · '+price+' pts');b.type='button';b.disabled=busy||!!pending;b.setAttribute('aria-pressed',String(selected===+price));b.onclick=()=>{selected=+price;window.ONEScratchMount(host,{data,busy,serverVersion,pending,token,buy,retry});};select.append(b);}host.replaceChildren(select);
 const [name,icon,rule]=games[selected],ticket=el('section',undefined,'oneScratchTicket');ticket.dataset.price=selected;ticket.append(el('small','COLLECTION À GRATTER'),el('h3',icon+' '+name),el('p',rule));
 const saved=data.scratchTickets?.find(t=>t.stake===selected),r=saved&&(selected===10||saved.scratchVersion===2)?saved:null,key=r?token+':'+r.id:'',done=r&&revealed.has(key),board=el('div',undefined,'oneScratchBoard');
 if(selected===50&&(!r||r.scratchVersion===2)){const lucky=el('div',undefined,'oneLuckyNumbers');for(const n of (r?.luckyNumbers||["?","?","?"]))lucky.append(el('b',n));ticket.append(el('p','TES 3 NUMÉROS CHANCE'),lucky);board.classList.add('isNumbers');for(const c of (r?.numberCells||Array.from({length:12},()=>({number:"?",prize:"—"})))){const cell=el('div',undefined,'oneScratchCell');cell.append(el('b',c.number),el('small',c.prize+' pts'));board.append(cell);}}
 else if(selected===100&&(!r||r.scratchVersion===2)){board.classList.add('isTemple');const icons=['Rubis rouge','Diamant bleu','Émeraude verte','Cœur violet'];const gemIcon=n=>{const icon=el('span',undefined,'oneGemArt98');icon.dataset.kind=n;icon.setAttribute('role','img');icon.setAttribute('aria-label',icons[n]);return icon;};for(const [i,m]of (r?.missions||Array.from({length:3},(_,i)=>({target:i,prize:'—',gems:[0,1,2,3]}))).entries()){const row=el('div',undefined,'oneGemMission');row.dataset.gem=i;const caption=el('small',undefined,'oneGemCaption98');caption.append(gemIcon(m.target),el('span',icons[m.target]+' ×3 · '+m.prize+' pts'));row.append(caption);const cells=el('div');for(const gem of m.gems){const cell=el('b',undefined,'oneGemCell98');cell.dataset.gem=gem;cell.append(gemIcon(gem));cells.append(cell);}row.append(cells);board.append(row);}const bonus=el('div',undefined,'oneGemBonus');bonus.append(el('small','COFFRE BONUS · '+(r?.bonusPrize||'—')+' pts'),el('strong',(r?.bonusSymbols||['key','key','key']).map(x=>x==='key'?'🔑':'☾').join('   ')));board.append(bonus);}
 else{if(selected===50)ticket.append(el('strong',r?'Numéro chance : '+r.lucky:'3 numéros chance à découvrir','oneLuckyNumber'));const gems=['◆','✦','⬟','●','★'],amounts=[selected,selected*2,selected*5,selected*10,selected*50];for(let i=0;i<(r?6:selected===50?12:6);i++){const cell=el('div',undefined,'oneScratchCell');if(r){if(selected===50)cell.append(el('b',String(r.numbers[i])),el('small',r.prizes[i]+' pts'));else if(selected===100)cell.append(el('b',gems[amounts.indexOf(r.symbols[i])]),el('small',r.symbols[i]+' pts'));else cell.append(el('b',symbolFor(r.symbols[i])),el('small',r.symbols[i]+' pts'));}else cell.append(el('b',selected===100?['♦','◆','⬟'][i%3]:'?'));board.append(cell);}}
 const balanceLabel=host.closest('.casino')?.querySelector('.casinoBalance');if(balanceLabel)balanceLabel.textContent=r&&!done?'Ticket à révéler':data.balance.toLocaleString('fr-FR')+' Points ONE';ticket.append(board);if(saved&&!r)ticket.append(el('p','Ancien ticket terminé · '+saved.payout+' points. Le prochain achat utilise le nouveau jeu.','oneArchivedTicket'));const status=el('p',r?(done?(r.payout?'Gagné : '+r.payout+' Points ONE':'Ce ticket ne rapporte pas de points.'):'Gratte la surface pour découvrir ton ticket.'):'Choisis ton ticket et commence à gratter.','oneScratchStatus');status.setAttribute('role','status');ticket.append(status);host.append(ticket);
 const reveal=()=>{if(!r||revealed.has(key))return;revealed.add(key);if(balanceLabel)balanceLabel.textContent=data.balance.toLocaleString('fr-FR')+' Points ONE';board.removeAttribute('aria-hidden');canvas?.remove();buyButton.disabled=serverVersion<36||busy||data.balance<selected;status.textContent=r.payout?'Gagné : '+r.payout+' Points ONE':'Ce ticket ne rapporte pas de points.';ticket.classList.toggle('isWinner',r.payout>0);revealButton?.remove();};let canvas=null,revealButton=null;
 if(r&&!done){board.setAttribute('aria-hidden','true');canvas=el('canvas',undefined,'oneScratchCoating');canvas.width=600;canvas.height=360;canvas.setAttribute('aria-hidden','true');board.append(canvas);const ctx=canvas.getContext('2d'),g=ctx.createLinearGradient(0,0,600,360);g.addColorStop(0,'#f4db99');g.addColorStop(.4,'#a5b3d0');g.addColorStop(.65,'#e6edf9');g.addColorStop(1,'#82709f');ctx.fillStyle=g;ctx.fillRect(0,0,600,360);ctx.fillStyle='#ffffff40';for(let x=-360;x<600;x+=24){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+360,360);ctx.strokeStyle='#ffffff40';ctx.stroke();}for(let y=0;y<360;y+=3){for(let x=0;x<600;x+=3){ctx.fillStyle=((x*7+y*13)%19<8)?'#ffffff35':'#554e5c16';ctx.fillRect(x,y,1,1);}}ctx.strokeStyle='#fff6';ctx.lineWidth=3;ctx.strokeRect(9,9,582,342);ctx.fillStyle='#313251';ctx.font='bold 27px system-ui';ctx.textAlign='center';ctx.fillText('ONE · GRATTE ICI',300,185);ctx.font='18px system-ui';ctx.fillText('Révèle chaque symbole',300,220);const visited=new Set();let active=false,last=null;
 const scratch=e=>{if(!active)return;const box=canvas.getBoundingClientRect(),x=(e.clientX-box.left)*600/box.width,y=(e.clientY-box.top)*360/box.height;ctx.globalCompositeOperation='destination-out';ctx.lineWidth=56;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last?.x??x,last?.y??y);ctx.lineTo(x,y);ctx.stroke();last={x,y};visited.add(Math.floor(x/30)+','+Math.floor(y/30));};
 canvas.onpointerdown=e=>{active=true;last=null;canvas.setPointerCapture(e.pointerId);scratch(e);};canvas.onpointermove=scratch;canvas.onpointerup=canvas.onpointercancel=()=>{active=false;last=null;const pixels=ctx.getImageData(0,0,600,360).data;let clear=0;for(let i=3;i<pixels.length;i+=4)if(pixels[i]<32)clear++;if(clear/(600*360)>.995)reveal();};revealButton=el('button','Révéler le ticket');revealButton.type='button';revealButton.onclick=()=>{board.removeAttribute('aria-hidden');reveal();};host.append(revealButton);}
 const buyButton=el('button',pending?'Retrouver mon ticket':'Acheter · '+selected+' Points ONE','oneScratchBuy');buyButton.type='button';buyButton.disabled=serverVersion<36||busy||(!pending&&(data.balance<selected||!!r&&!done));buyButton.onclick=()=>pending?retry():buy(selected);host.append(buyButton);if(serverVersion<36)host.append(el('p','Le serveur des jeux doit être mis à jour (version 36). Installe le nouveau Worker avant de lancer un ticket.','oneScratchServerError')); 
 // Enable the next purchase only once the current ticket has been revealed.
 const update=()=>{if(r&&revealed.has(key)&&!busy)buyButton.disabled=serverVersion<36||data.balance<selected;};ticket.addEventListener('pointerup',update);revealButton?.addEventListener('click',update);
 host.append(el('p','Gains possibles : ×1 (25 %), ×2 (15,8 %), ×5 (3 %), ×10 (1 %), ×50 (0,2 %). Sans gain : 55 %. Les gains comprennent le prix du ticket. Points virtuels sans valeur monétaire.','oneScratchRules'));
};
const s=el('style');s.textContent=`#onePointsPanel .oneScratchChoices{display:grid;gap:8px;margin-bottom:18px}#onePointsPanel .oneScratchChoices button{text-align:left}#onePointsPanel .oneScratchChoices [aria-pressed=true]{border-color:#fbd677;background:#8968bf44}#onePointsPanel .oneScratchTicket{padding:20px 12px;border:2px solid #e3b864;border-radius:22px;text-align:center;background:radial-gradient(ellipse at top,#cc7d284d,transparent),linear-gradient(140deg,#553179,#22133c);box-shadow:inset 0 0 0 5px #ffffff0a,0 12px 28px #0005}#onePointsPanel .oneScratchTicket[data-price="50"]{background:radial-gradient(ellipse at top,#26cfea66,transparent),linear-gradient(140deg,#154d86,#231b52)}#onePointsPanel .oneScratchTicket[data-price="100"]{background:radial-gradient(ellipse at top,#f655b555,transparent),linear-gradient(140deg,#a0277d,#382267)}#onePointsPanel .oneScratchTicket>small{font-size:9px;letter-spacing:3px;color:#ffe3a9}#onePointsPanel .oneScratchTicket h3{font-size:26px;color:#ffde85}#onePointsPanel .oneScratchBoard{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:18px 0;position:relative;overflow:hidden;border-radius:12px;height:180px;background:#170e2c;padding:8px;box-sizing:border-box}#onePointsPanel .oneScratchCell{display:grid;align-content:center;gap:5px;border:1px solid #f4cf7855;border-radius:7px;color:#ffe1a4;background:#ffffff09}#onePointsPanel .oneScratchCell b{font-size:18px}#onePointsPanel .oneScratchCell small{font-size:12px}#onePointsPanel .oneScratchCoating{position:absolute;inset:0;width:100%;height:100%;touch-action:none;cursor:crosshair}#onePointsPanel .oneScratchStatus{min-height:46px;color:#ffeba3}#onePointsPanel .oneScratchBuy{display:block;width:100%;margin:14px 0;background:linear-gradient(#ebbd66,#ac692b);color:#251328;font-weight:bold}#onePointsPanel .oneScratchRules{font-size:11px;margin-top:16px}#onePointsPanel .oneLuckyNumber{display:block;margin-top:12px;color:#ffe298}#onePointsPanel .oneScratchTicket.isWinner{box-shadow:0 0 25px #ebc37566,inset 0 0 0 5px #fff2}`;document.head.append(s);
})();


(()=>{const s=document.createElement('style');s.textContent=`
#onePointsPanel .oneScratchTicket{position:relative;background:radial-gradient(circle at 20% 0,#fca75a55,transparent 40%),linear-gradient(135deg,#712fa0,#271242);border:2px solid #f3c66d;box-shadow:inset 0 0 0 4px #fff1,0 14px 35px #0006}
#onePointsPanel .oneScratchTicket[data-price="50"]{background:radial-gradient(circle at 80% 0,#7be6ff66,transparent 50%),repeating-linear-gradient(135deg,transparent 0 20px,#ffffff06 20px 21px),linear-gradient(135deg,#1b79a6,#20164f)}
#onePointsPanel .oneScratchTicket[data-price="100"]{background:radial-gradient(circle at 50% 0,#e15ffb66,transparent 50%),repeating-linear-gradient(45deg,transparent 0 18px,#fff1 18px 19px),linear-gradient(140deg,#60258b,#171840)}
#onePointsPanel .oneLuckyNumbers{display:flex;justify-content:center;gap:14px;margin-top:12px}#onePointsPanel .oneLuckyNumbers b{width:42px;height:42px;border:2px solid #efdb99;background:radial-gradient(circle at 30% 25%,#fef1c2,#cca65b);color:#21325a;display:grid;place-items:center;border-radius:50%;font-size:20px;box-shadow:0 4px 0 #8a6b39}
#onePointsPanel .oneScratchBoard.isNumbers{height:285px;grid-template-columns:repeat(3,1fr)}#onePointsPanel .oneScratchBoard.isTemple{height:365px;display:flex;flex-direction:column;gap:8px;background:#130c27}
#onePointsPanel .oneGemMission{padding:6px;border:1px solid #fff2;border-radius:7px}#onePointsPanel .oneGemMission>small{display:block;text-align:left;color:#e1c3f5;font-size:10px;margin-bottom:4px}#onePointsPanel .oneGemMission>div{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}#onePointsPanel .oneGemMission b{background:linear-gradient(135deg,#fff2,#ffffff05);border:1px solid #fff2;border-radius:6px;font:30px Georgia;padding:4px;text-shadow:0 0 10px currentColor}#onePointsPanel [data-gem="0"]{color:#ff669b}#onePointsPanel [data-gem="1"]{color:#66d6ff}#onePointsPanel [data-gem="2"]{color:#7dffb1}#onePointsPanel [data-gem="3"]{color:#e5b7ff}#onePointsPanel .oneGemBonus{display:grid;gap:6px;color:#f1d181;border:1px solid #ecc57e77;border-radius:9px;padding:7px;background:#71502133}#onePointsPanel .oneGemBonus small{font-size:10px}#onePointsPanel .oneGemBonus strong{font-size:24px}#onePointsPanel .oneScratchServerError{margin:12px 0;color:#ffd39a;font-size:13px}
`;document.head.append(s);})();

(()=>{const s=document.createElement('style');s.textContent='.oneScratchTicket .oneScratchCell{background:linear-gradient(145deg,#ffffff12,#00000022),radial-gradient(circle at 25% 10%,#fff3,transparent 35%);box-shadow:inset 0 1px #fff2,0 3px 8px #0005}.oneScratchTicket[data-price="10"] .oneScratchCell b{font-size:31px;filter:drop-shadow(0 2px 2px #0008)}.oneScratchCoating{background:transparent!important;box-shadow:inset 0 0 0 5px #ffffff55!important}.oneScratchStatus{font-weight:650}.oneScratchTicket.isWinner{animation:oneScratchWin 1.2s ease-in-out 2}@keyframes oneScratchWin{50%{transform:translateY(-3px);filter:saturate(1.25)}}';document.head.append(s)})();

(()=>{const style=document.createElement('style');style.textContent="\n@media(max-width:560px){\n #onePointsPanel .oneScratchChoices{gap:6px;margin-bottom:12px}\n #onePointsPanel .oneScratchChoices button{min-height:38px;padding:8px 10px;font-size:12px;border-radius:9px}\n #onePointsPanel .oneScratchTicket{padding:15px 9px;border-radius:17px}\n #onePointsPanel .oneScratchTicket>small{font-size:8px;letter-spacing:2px}\n #onePointsPanel .oneScratchTicket h3{font-size:22px;margin:9px 0}\n #onePointsPanel .oneScratchTicket>p{font-size:12px;line-height:1.45;margin:7px 3px}\n #onePointsPanel .oneScratchBoard{margin:12px 0;height:166px;padding:7px;gap:5px}\n #onePointsPanel .oneScratchBoard.isNumbers{height:246px}\n #onePointsPanel .oneScratchBoard.isTemple{height:285px;padding:6px;gap:6px}\n #onePointsPanel .oneScratchCell{min-width:0}\n #onePointsPanel .oneScratchCell b{font-size:16px}\n #onePointsPanel .oneScratchCell small{font-size:10px}\n #onePointsPanel .oneScratchTicket[data-price=\"10\"] .oneScratchCell b{font-size:25px}\n #onePointsPanel .oneScratchCoating{border-radius:8px}\n #onePointsPanel .oneScratchStatus{font-size:12px;min-height:35px;margin:8px 0}\n #onePointsPanel .oneScratchBuy{font-size:13px;padding:10px;margin:10px 0}\n #onePointsPanel .oneScratchRules{font-size:10px;line-height:1.35;margin-top:10px}\n}\n";document.head.append(style)})();
