(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev',rarities={normal:'Normale',rare:'Rare',epic:'Épique',legendary:'Légendaire'};
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 function card(c,quantity){const a=el('article',undefined,'oneCollectible');a.dataset.rarity=c.rarity;const locked=quantity===0;const image=el('div',undefined,'oneCardImage');image.setAttribute('aria-hidden','true');if(locked){a.classList.add('isMissing');image.classList.add('oneCardBack');image.textContent='?';}else{const row=Math.floor((c.number-1)/10),col=(c.number-1)%10,xs=[0,157,313,470,627,784,941,1098,1255,1515,1672],ys=[0,190,364,538,714,941];let h=ys[row+1]-ys[row]-4,w=Math.min(xs[col+1]-xs[col]-4,h*.8),x=xs[col]+(xs[col+1]-xs[col]-w)/2,y=ys[row]+2;if(c.number===9){w=150;x=1258;}image.style.aspectRatio=w+'/'+h;image.style.backgroundImage='url("ui/one-collection-art-hd.png?v=01484")';image.style.backgroundSize=1672/w*100+'% '+941/h*100+'%';image.style.backgroundPosition=x/(1672-w)*100+'% '+y/(941-h)*100+'%';}a.append(image,el('h4',locked?'Carte à découvrir':c.name),el('small','#'+c.number+' · '+(locked?'Non trouvée':rarities[c.rarity]+(quantity===undefined?'':' · ×'+quantity))));return window.ONECard3D?window.ONECard3D(a,c,locked):a;}

 const css=document.createElement('style');css.textContent='#onePointsPanel .onePackList{display:grid;gap:16px;margin-top:20px}#onePointsPanel .onePackBox{border:1px solid #bfa065;border-radius:15px;padding:18px;background:#23172e}#onePointsPanel .onePackBox button,#onePointsPanel .onePackAction{width:auto;font-size:14px;padding:10px 16px;margin:12px 0}#onePointsPanel button:disabled{opacity:.45;cursor:default}#onePointsPanel .onePackStatus{margin:14px 0;color:#f0d088}';document.head.append(css);
 const animationReady=window.ONECard3D?Promise.resolve():new Promise(resolve=>{const script=document.createElement('script');script.src='ui/one-cards-3d.js?v=01484c';script.onload=resolve;script.onerror=resolve;document.head.append(script);});
 window.ONEPacksMount=async(host,which)=>{
  const token=window.oneAccountToken?.(),root=el('div');host.replaceChildren(root);let state=null,pending=null,busy=false,key='',filter='',results=[],collectionOpen=false;const notice=el('p','','onePackStatus');notice.setAttribute('role','status');const current=()=>host.contains(root)&&token===window.oneAccountToken?.();
  async function api(path,post=false){if(!token)throw Error('Connecte-toi à ton compte ONE.');const r=await fetch(API+path,{method:post?'POST':'GET',headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(15000)});const d=await r.json();if(token!==window.oneAccountToken?.())throw Error('Le compte a changé. Rouvre Points ONE.');if(!r.ok){const e=Error(d.error||'Service indisponible.');e.definitive=r.status>=400&&r.status<500;throw e;}return d;}
  function save(){try{pending?localStorage.setItem(key,JSON.stringify(pending)):localStorage.removeItem(key);}catch{}}
  async function open(pack){if(busy)return;if(!pending){pending={pack:pack.id,id:crypto.randomUUID()};save();}busy=true;render();notice.textContent='Ouverture…';try{const [d]=await Promise.all([api('/collection/open?pack='+encodeURIComponent(pending.pack)+'&request='+encodeURIComponent(pending.id),true),new Promise(resolve=>setTimeout(resolve,1100))]);if(!current())return;results=d.cards;state=await api('/collection/state');pending=null;save();notice.textContent='Tes 5 cartes ont rejoint ta collection.';}catch(e){if(e.definitive){pending=null;save();}notice.textContent=e.message+(pending?' Réessaie pour retrouver les mêmes cartes, sans nouveau débit.':'');}finally{busy=false;if(current()){const message=notice.textContent;render();notice.textContent=message;}}}
  function render(){root.replaceChildren();root.append(el('h3',which==='packs'?'Les packs ONE':'Ta collection'));if(!state){root.append(notice);return;}root.append(el('p',state.balance.toLocaleString('fr-FR')+' Points ONE'));if(which==='packs'){if(busy){const opening=el('div',undefined,'onePackOpening');opening.append(el('div','ONE','oneOpeningEnvelope'),el('p','Ouverture de tes 5 cartes…'));root.append(opening);}if(results.length&&!busy){const reveal=el('section',undefined,'onePackReveal');reveal.append(el('h3','Tes nouvelles cartes'));const grid=el('div',undefined,'oneCollectionGrid');results.forEach((id,i)=>{const c=window.ONECollectionCards.find(c=>c.id===id);if(c){const tile=card(c);tile.style.setProperty('--reveal-delay',i*.22+'s');grid.append(tile);}});reveal.append(grid);root.append(reveal);}if(pending){const b=el('button','Retrouver mon ouverture','onePackAction');b.disabled=busy;b.onclick=()=>open();root.append(b);}const list=el('div',undefined,'onePackList');for(const p of state.packs){const a=el('article',undefined,'onePackBox');a.append(el('h3',p.name),el('p',p.cost+' points · 5 cartes'),el('p',Object.entries(p.chances).map(([r,n])=>rarities[r]+' : '+n+' %').join(' · ')));const b=el('button','Ouvrir · '+p.cost+' points');b.type='button';b.disabled=busy||!!pending||state.balance<p.cost;b.onclick=()=>open(p);a.append(b);list.append(a);}root.append(list,el('p','Chances par carte. Les doublons sont possibles et conservés.'));}
   else{if(!collectionOpen){root.append(el('p','Catalogue des collections'));const catalogue=el('button',undefined,'oneCollectionCover');catalogue.type='button';catalogue.append(el('span','✦','oneCoverStar'),el('strong','Collection ONE · Série 1'),el('span',state.owned.length+' / 50 cartes trouvées'),el('span','Afficher ma collection →'));catalogue.onclick=()=>{collectionOpen=true;render();};root.append(catalogue,el('p','De nouvelles collections arriveront prochainement.'),notice);return;}const back=el('button','← Catalogue','onePackAction');back.onclick=()=>{collectionOpen=false;render();};root.append(back,el('p',state.owned.length+' / 50 cartes obtenues'));const filters=el('div',undefined,'oneCardFilters');for(const [id,label]of [['','Toutes'],...Object.entries(rarities)]){const b=el('button',label);b.type='button';b.setAttribute('aria-pressed',String(filter===id));b.onclick=()=>{filter=id;render();};filters.append(b);}const grid=el('div',undefined,'oneCollectionGrid');for(const c of window.ONECollectionCards||[]){if(filter&&c.rarity!==filter)continue;grid.append(card(c,state.owned.find(o=>o.id===c.id)?.quantity||0));}root.append(filters,grid);}root.append(notice);
  }
  render();notice.textContent='Chargement…';try{await animationReady;if(token){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));key='one-pack-'+Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');try{pending=JSON.parse(localStorage.getItem(key)||'null');}catch{}}state=await api('/collection/state');if(current()){render();notice.textContent='';}}catch(e){if(current())notice.textContent=e.message;}
  window.addEventListener('one-account-changed',()=>{if(host.contains(root))host.replaceChildren(el('p','Le compte a changé. Sélectionne à nouveau cet onglet.'));},{once:true});
 };
})();
