(()=>{
 const search=document.getElementById('oneSearchToggle');if(!search)return;
 const css=document.createElement('style');css.textContent='#onePointsToggle{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:1px;width:40px;min-width:32px;height:40px;padding:3px!important;color:#e5c77f;background:transparent;border:0}#onePointsToggle svg{width:21px;height:21px;fill:none;stroke:currentColor;stroke-width:1.6}#onePointsToggle span{font-size:9px;line-height:10px}#onePointsPanel{box-sizing:border-box;width:min(460px,calc(100vw - 24px));max-height:calc(100dvh - 32px);padding:0;border:1px solid #92744f;border-radius:20px;background:linear-gradient(145deg,#30213c,#141020);color:#f5edff;box-shadow:0 25px 80px #0009}#onePointsPanel::backdrop{background:#080611bd}#onePointsPanel header{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #d8b77833}#onePointsPanel h2{margin:0;font-size:22px;color:#efd392}#onePointsPanel button{width:40px;min-height:40px;border:1px solid #9476a6;background:#ffffff08;color:#fff;border-radius:10px;font-size:25px;cursor:pointer}#onePointsPanel .onePointsBody{padding:35px 24px;text-align:center}#onePointsPanel .onePointsEmblem{font-size:38px;color:#e3c178}#onePointsPanel h3{font-size:18px;margin:14px 0 8px}#onePointsPanel p{font-size:14px;line-height:1.6;color:#cabed5;margin:0}#onePointsPanel button:focus-visible,#onePointsToggle:focus-visible{outline:2px solid #efd392;outline-offset:3px}';document.head.append(css);
 const button=document.createElement('button');button.type='button';button.id='onePointsToggle';button.setAttribute('aria-label','Points ONE');button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-controls','onePointsPanel');button.setAttribute('aria-expanded','false');button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9.5"/><path d="m12 6 1.9 3.8 4.2.6-3 3 .7 4.2-3.8-2-3.8 2 .7-4.2-3-3 4.2-.6Z"/></svg><span>Points</span>';search.before(button);
 const balance=document.createElement('span');balance.className='oneHeaderBalance';balance.textContent='…';button.append(balance);
 window.ONEUpdateBalance=value=>{if(!Number.isFinite(value))return;balance.textContent=value.toLocaleString('fr-FR');button.setAttribute('aria-label','Points ONE : '+value.toLocaleString('fr-FR')+' points');};
 let refreshing=false;
 async function refreshBalance(){const token=window.oneAccountToken?.();if(!token){balance.textContent='—';button.setAttribute('aria-label','Points ONE · Se connecter');return;}if(refreshing)return;refreshing=true;try{const r=await fetch('https://one-comments-api.moulinanthony60.workers.dev/points/state',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});const d=await r.json();if(r.ok&&token===window.oneAccountToken?.())window.ONEUpdateBalance(d.balance);}catch{}finally{refreshing=false;}}
 window.addEventListener('one-account-changed',()=>{balance.textContent='…';refreshBalance();});window.addEventListener('focus',refreshBalance);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshBalance();});setInterval(()=>{if(!document.hidden)refreshBalance();},30000);refreshBalance();

 const panel=document.createElement('dialog');panel.id='onePointsPanel';panel.setAttribute('aria-labelledby','onePointsTitle');panel.innerHTML='<header><h2 id="onePointsTitle">Points ONE</h2><button type="button" aria-label="Fermer Points ONE">×</button></header><nav class="onePointsTabs" aria-label="Points ONE"><button type="button" aria-pressed="true" data-points-view="packs">Packs</button><button type="button" aria-pressed="false" data-points-view="collection">Collection</button><button type="button" aria-pressed="false" data-points-view="games">Jeux</button></nav><section class="onePointsBody" id="onePointsContent"></section>';document.body.append(panel);
 const extra=document.createElement('style');extra.textContent='#onePointsPanel:has(.oneCollectionGrid){width:min(780px,calc(100vw - 24px))}#onePointsPanel .oneCollectionGrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;text-align:left;margin-top:18px}#onePointsPanel .oneCardImage{background-repeat:no-repeat;width:100%;border-radius:6px;height:auto}#onePointsPanel .oneCollectible{min-width:0;padding:6px;border:1px solid #85778e;border-radius:10px;background:#18141f}#onePointsPanel .oneCollectible[data-rarity=rare]{border-color:#52b8f2}#onePointsPanel .oneCollectible[data-rarity=epic]{border-color:#b36be5}#onePointsPanel .oneCollectible[data-rarity=legendary]{border-color:#e5bd65}#onePointsPanel .oneCollectible h4{font-size:12px;margin:8px 0 4px;overflow-wrap:anywhere}#onePointsPanel .oneCollectible small{font-size:10px;color:#cbbfd6}#onePointsPanel .oneCardFilters{display:flex;flex-wrap:wrap;gap:6px;margin-top:18px}#onePointsPanel .oneCardFilters button{width:auto;font-size:12px;padding:8px;min-height:40px}#onePointsPanel .oneCardFilters [aria-pressed=true]{border-color:#e2c27b;background:#a4813933}@media(max-width:560px){#onePointsPanel .oneCollectionGrid{grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}#onePointsPanel .onePointsBody{padding:22px 12px}} #onePointsPanel .onePointsGames{display:grid;gap:12px;margin-top:20px}#onePointsPanel .onePointsGames article{padding:16px;border:1px solid #d8b77855;border-radius:14px;background:#100b19}#onePointsPanel .onePointsTabs{display:flex;gap:8px;padding:14px 20px 0}#onePointsPanel .onePointsTabs button{width:auto;flex:1;font-size:14px;min-height:44px}#onePointsPanel .onePointsTabs [aria-pressed=true]{border-color:#e5c57d;color:#f2dca8;background:#dfb96d18}#onePointsPanel .onePackPreview{width:112px;height:148px;border:1px solid #c9a367;border-radius:12px;margin:0 auto 20px;display:grid;place-items:center;background:linear-gradient(145deg,#61416f,#251830);box-shadow:0 9px 25px #0006;font-size:36px;color:#e5c57d}';document.head.append(extra);
 const content=panel.querySelector('#onePointsContent');function view(which){panel.querySelectorAll('[data-points-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pointsView===which)));if(which==='games')window.ONECasinoMount(content);else window.ONEPacksMount(content,which);}
panel.querySelectorAll('[data-points-view]').forEach(b=>b.onclick=()=>view(b.dataset.pointsView));
 button.onclick=()=>{if(!panel.open){panel.showModal();view('packs');button.setAttribute('aria-expanded','true');}};panel.querySelector('button').onclick=()=>panel.close();panel.addEventListener('close',()=>{button.setAttribute('aria-expanded','false');button.focus({preventScroll:true});});panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)panel.close();}});
})();
