(()=>{
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};let selected=10;const revealed=new Set();
const games={10:['Trésor ONE','✦','Trouve 3 montants identiques pour gagner ce montant.'],50:['Numéro chance','7','Retrouve le numéro chance parmi 12 cases et complète les 3 numéros bonus.'],100:['Diamants','◆','Aligne les gemmes dans 15 cases et ouvre le coffre bonus.']};
window.ONEScratchMount=(host,{data,busy,pending,token,buy,retry})=>{
 const select=el('div',undefined,'oneScratchChoices');for(const [price,[name,icon]] of Object.entries(games)){const b=el('button',icon+' '+name+' · '+price+' pts');b.type='button';b.disabled=busy||!!pending;b.setAttribute('aria-pressed',String(selected===+price));b.onclick=()=>{selected=+price;window.ONEScratchMount(host,{data,busy,pending,token,buy,retry});};select.append(b);}host.replaceChildren(select);
 const [name,icon,rule]=games[selected],ticket=el('section',undefined,'oneScratchTicket');ticket.dataset.price=selected;ticket.append(el('small','COLLECTION À GRATTER'),el('h3',icon+' '+name),el('p',rule));
 const r=data.scratchTickets?.find(t=>t.stake===selected),key=r?token+':'+r.id:'',done=r&&revealed.has(key),board=el('div',undefined,'oneScratchBoard');
 if(selected===50)ticket.append(el('strong',r?'Numéro chance : '+r.lucky:'Numéro chance : ?','oneLuckyNumber'));
 const gems=['◆','✦','⬟','●','★'],amounts=[selected,selected*2,selected*5,selected*10,selected*50];
 const cells=selected===50?12:selected===100?15:6;board.dataset.cells=cells;
 for(let i=0;i<cells;i++){const cell=el('div',undefined,'oneScratchCell');if(r){if(selected===50)cell.append(el('b',String(r.numbers[i]??'?')),el('small',(r.prizes[i]??0)+' pts'));else if(selected===100){cell.append(el('b',gems[Math.max(0,amounts.indexOf(r.symbols[i]))]||'◆'),el('small',(r.symbols[i]??0)+' pts'));}else cell.append(el('b',(r.symbols[i]??0)+' pts'));}else cell.append(el('b','?'));board.append(cell);}
 ticket.append(board);const status=el('p',r?(done?(r.payout?'Gagné : '+r.payout+' Points ONE':'Ce ticket ne rapporte pas de points.'):'Gratte la surface pour découvrir ton ticket.'):'Choisis ton ticket et commence à gratter.','oneScratchStatus');status.setAttribute('role','status');ticket.append(status);host.append(ticket);
 const reveal=()=>{if(!r||revealed.has(key))return;revealed.add(key);board.removeAttribute('aria-hidden');canvas?.remove();buyButton.disabled=busy||data.balance<selected;status.textContent=r.payout?'Gagné : '+r.payout+' Points ONE':'Ce ticket ne rapporte pas de points.';ticket.classList.toggle('isWinner',r.payout>0);revealButton?.remove();};let canvas=null,revealButton=null;
 if(r&&!done){board.setAttribute('aria-hidden','true');canvas=el('canvas',undefined,'oneScratchCoating');canvas.width=600;canvas.height=360;canvas.setAttribute('aria-hidden','true');board.append(canvas);const ctx=canvas.getContext('2d'),g=ctx.createLinearGradient(0,0,600,360);g.addColorStop(0,'#f4db99');g.addColorStop(.4,'#a5b3d0');g.addColorStop(.65,'#e6edf9');g.addColorStop(1,'#82709f');ctx.fillStyle=g;ctx.fillRect(0,0,600,360);ctx.fillStyle='#ffffff40';for(let x=-360;x<600;x+=24){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+360,360);ctx.strokeStyle='#ffffff40';ctx.stroke();}ctx.fillStyle='#313251';ctx.font='bold 27px system-ui';ctx.textAlign='center';ctx.fillText('ONE · GRATTE ICI',300,185);const visited=new Set();let active=false,last=null;
 const scratch=e=>{if(!active)return;const box=canvas.getBoundingClientRect(),x=(e.clientX-box.left)*600/box.width,y=(e.clientY-box.top)*360/box.height;ctx.globalCompositeOperation='destination-out';ctx.lineWidth=56;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last?.x??x,last?.y??y);ctx.lineTo(x,y);ctx.stroke();last={x,y};visited.add(Math.floor(x/30)+','+Math.floor(y/30));if(visited.size>78){board.removeAttribute('aria-hidden');reveal();}};
 canvas.onpointerdown=e=>{active=true;last=null;canvas.setPointerCapture(e.pointerId);scratch(e);};canvas.onpointermove=scratch;canvas.onpointerup=canvas.onpointercancel=()=>{active=false;last=null;};revealButton=el('button','Révéler le ticket');revealButton.type='button';revealButton.onclick=()=>{board.removeAttribute('aria-hidden');reveal();};host.append(revealButton);}
 const buyButton=el('button',pending?'Retrouver mon ticket':'Acheter · '+selected+' Points ONE','oneScratchBuy');buyButton.type='button';buyButton.disabled=busy||(!pending&&(data.balance<selected||!!r&&!done));buyButton.onclick=()=>pending?retry():buy(selected);host.append(buyButton);
 // Enable the next purchase only once the current ticket has been revealed.
 const update=()=>{if(r&&revealed.has(key)&&!busy)buyButton.disabled=data.balance<selected;};ticket.addEventListener('pointerup',update);revealButton?.addEventListener('click',update);
 host.append(el('p','Gains possibles : ×1 (20 %), ×2 (15 %), ×5 (7 %), ×10 (2 %), ×50 (1 %). Sans gain : 55 %. Les gains comprennent le prix du ticket. Points virtuels sans valeur monétaire.','oneScratchRules'));
};
const s=el('style');s.textContent=`#onePointsPanel .oneScratchChoices{display:grid;gap:8px;margin-bottom:18px}#onePointsPanel .oneScratchChoices button{text-align:left}#onePointsPanel .oneScratchChoices [aria-pressed=true]{border-color:#fbd677;background:#8968bf44}#onePointsPanel .oneScratchTicket{padding:20px 12px;border:2px solid #e3b864;border-radius:22px;text-align:center;background:radial-gradient(ellipse at top,#cc7d284d,transparent),linear-gradient(140deg,#553179,#22133c);box-shadow:inset 0 0 0 5px #ffffff0a,0 12px 28px #0005}#onePointsPanel .oneScratchTicket[data-price="50"]{background:radial-gradient(ellipse at top,#26cfea66,transparent),linear-gradient(140deg,#154d86,#231b52)}#onePointsPanel .oneScratchTicket[data-price="100"]{background:radial-gradient(ellipse at top,#f655b555,transparent),linear-gradient(140deg,#a0277d,#382267)}#onePointsPanel .oneScratchTicket>small{font-size:9px;letter-spacing:3px;color:#ffe3a9}#onePointsPanel .oneScratchTicket h3{font-size:26px;color:#ffde85}#onePointsPanel .oneScratchBoard{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:18px 0;position:relative;overflow:hidden;border-radius:12px;height:180px;background:#170e2c;padding:8px;box-sizing:border-box}#onePointsPanel .oneScratchCell{display:grid;align-content:center;gap:5px;border:1px solid #f4cf7855;border-radius:7px;color:#ffe1a4;background:#ffffff09}#onePointsPanel .oneScratchCell b{font-size:18px}#onePointsPanel .oneScratchCell small{font-size:12px}#onePointsPanel .oneScratchCoating{position:absolute;inset:0;width:100%;height:100%;touch-action:none;cursor:crosshair}#onePointsPanel .oneScratchStatus{min-height:46px;color:#ffeba3}#onePointsPanel .oneScratchBuy{display:block;width:100%;margin:14px 0;background:linear-gradient(#ebbd66,#ac692b);color:#251328;font-weight:bold}#onePointsPanel .oneScratchRules{font-size:11px;margin-top:16px}#onePointsPanel .oneLuckyNumber{display:block;margin-top:12px;color:#ffe298}#onePointsPanel .oneScratchTicket.isWinner{box-shadow:0 0 25px #ebc37566,inset 0 0 0 5px #fff2}`;document.head.append(s);
})();

