(()=>{'use strict';
const API='https://one-comments-api.moulinanthony60.workers.dev',MEDIA='https://one-messages-api.moulinanthony60.workers.dev';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
let query='',known=new Map(),inbox=[],initialized=false,busy=false,timer,account='',typingAt=0,typingTimer,typingPeer='',lastTyping=new Set();
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const thread=()=>document.querySelector('dialog.oneThreadFullscreen[open]');
async function api(base,path,body){const token=window.oneAccountToken?.();if(!token)throw Error('Session absente');const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(9000),cache:'no-store'});if(!r.ok)throw Error('Service indisponible');const data=await r.json();if(token!==window.oneAccountToken?.())throw Error('Le compte a changé');return data}
function time(at){const d=Math.max(0,Date.now()-Number(at));return d<60000?'À l’instant':d<3600000?Math.floor(d/60000)+' min':d<86400000?Math.floor(d/3600000)+' h':Math.floor(d/86400000)+' j';}
function apply(){const root=document.querySelector('.oneChatV8');if(!root)return;const isMessages=!!root.querySelector('[data-social-tab="messages"].active');const rows=[...root.querySelectorAll('.oneV79Row')];let visible=0;for(const row of rows){row.hidden=isMessages&&!norm(row.dataset.onePeerName).includes(norm(query));if(!row.hidden)visible++;const copy=row.querySelector('.copy');if(copy&&row.dataset.chatAt&&Number(row.dataset.chatAt)>0){let stamp=copy.querySelector('.oneChatTime');if(!stamp){stamp=el('small','oneChatTime');copy.append(stamp)}const value=time(row.dataset.chatAt);if(stamp.textContent!==value)stamp.textContent=value}row.classList.toggle('oneChatUnread',Number(row.dataset.chatUnread||0)>0);}
 root.querySelector('.oneChatNoResults').hidden=!isMessages||visible>0||!rows.length;}
function showBanner(person,text,type='message'){const existing=document.querySelector('.oneChatToast');existing?.remove();clearTimeout(timer);const n=el('aside','oneChatToast');n.setAttribute('role','status');const main=el('button','oneToastMain');main.type='button';const avatar=el('span','oneToastAvatar',(person.name||'ONE').slice(0,1).toUpperCase());const copy=el('span');copy.append(el('b','',person.name||'ONE'),el('span','oneToastText '+type,text));main.append(avatar,copy);main.onclick=()=>{n.remove();window.oneShowSpace?.('social');window.oneOpenFriends?.(String(person.id));};const close=el('button','oneToastClose','×');close.type='button';close.setAttribute('aria-label','Fermer la notification');close.onclick=()=>n.remove();n.append(main,close);document.body.append(n);timer=setTimeout(()=>n.remove(),4500);}
function receive(rows,network=true){inbox=rows;if(network){const next=new Map();for(const x of rows){const key=String(x.id),sig=String(x.lastAt||'')+'|'+String(x.lastText||'');next.set(key,sig);if(initialized&&known.get(key)!==sig&&Number(x.unread)>0&&thread()?.dataset.oneV79Id!==key){const media=String(x.lastText||'').includes('one-media')||String(x.lastText||'').includes('ONE_MEDIA')||/^(📸 Photo ONE|🎥 Vidéo ONE)/.test(String(x.lastText||''));showBanner(x,media?'T’a envoyé un média.':'T’a envoyé un message.',media?'media':'message');}}known=next;initialized=true;}apply();}
window.addEventListener('one-chat-inbox',e=>receive(e.detail.rows,e.detail.network));
window.addEventListener('click',e=>{if(e.target.closest('[data-chat-profile]'))document.getElementById('accountBtn')?.click();const search=e.target.closest('[data-chat-search]');if(search){const box=document.querySelector('.oneChatSearch');box.hidden=!box.hidden;if(!box.hidden)box.querySelector('input').focus();else{query='';box.querySelector('input').value='';apply();}}},true);
document.addEventListener('input',e=>{if(e.target.matches('.oneChatSearch input')){query=e.target.value;apply()}const d=e.target.closest('dialog.oneThreadFullscreen');if(d&&e.target.matches('textarea')){const peer=d.dataset.oneV79Id;if(!peer||peer.startsWith('group:'))return;typingPeer=peer;const nonempty=!!e.target.value.trim();if(Date.now()-typingAt>2500||!nonempty){typingAt=Date.now();api(MEDIA,'/typing',{to:peer,active:nonempty}).catch(()=>{});}clearTimeout(typingTimer);typingTimer=setTimeout(()=>api(MEDIA,'/typing',{to:peer,active:false}).catch(()=>{}),3000);}});
async function poll(){if(busy||document.hidden||!window.oneAccountToken?.())return;busy=true;try{const current=String(window.oneAccountLocal?.()?.id||'session');if(current!==account){known.clear();initialized=false;account=current;}const social=document.querySelector('#oneSocialInline');const onMessages=window.oneCurrentSpace?.()==='social'&&!!document.querySelector('[data-social-tab="messages"].active')&&!thread();if(!onMessages){try{const d=await api(API,'/friends/inbox');receive(d.conversations||[])}catch{}}
 try{const d=await api(MEDIA,'/typing');const active=new Set((d.typing||[]).map(x=>String(x.sender)));const currentThread=thread();const peer=inbox.find(x=>String(x.id)===currentThread?.dataset.oneV79Id);const heading=currentThread?.querySelector('.hub-thread-heading');let hint=heading?.querySelector('.oneTypingHint');if(heading){if(!hint){hint=el('small','oneTypingHint','Écrit…');hint.setAttribute('role','status');heading.append(hint);}hint.hidden=!peer||!active.has(String(peer.accountId));}
 for(const x of inbox){if(active.has(String(x.accountId))&&!lastTyping.has(String(x.accountId))&&currentThread?.dataset.oneV79Id!==String(x.id))showBanner(x,'Est en train d’écrire…','typing');}lastTyping=active;
 }catch{}apply();}finally{busy=false;}}
window.addEventListener('one-account-changed',()=>{query='';clearTimeout(typingTimer);typingPeer='';known.clear();inbox=[];initialized=false;lastTyping.clear();document.querySelector('.oneChatToast')?.remove();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();else if(typingPeer)api(MEDIA,'/typing',{to:typingPeer,active:false}).catch(()=>{});});window.addEventListener('one-space-open',()=>{query='';setTimeout(apply,0)});setInterval(poll,2200);
})();

