(()=>{'use strict';
const BASE='https://one-messages-api.moulinanthony60.workers.dev',PEOPLE='https://one-comments-api.moulinanthony60.workers.dev';
const node=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const token=()=>window.oneAccountToken?.()||'';
async function api(base,path,options={}){if(!token())throw Error('Connecte-toi à ONE pour continuer.');const r=await fetch(base+path,{...options,headers:{Authorization:'Bearer '+token(),...options.headers},cache:'no-store',signal:options.signal||AbortSignal.timeout(15000)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||(r.status===404?'Mets à jour le serveur ONE pour activer les publications.':'Service indisponible. Réessaie.'));return d;}
const ids=new WeakMap();
function publish(file,caption,progress,kind){return new Promise((resolve,reject)=>{if(!token())return reject(Error('Connecte-toi à ONE pour publier.'));let keys=ids.get(file);if(!keys){keys={};ids.set(file,keys)}const id=keys[kind]||(keys[kind]=crypto.randomUUID());const x=new XMLHttpRequest();x.open('POST',BASE+'/posts?'+new URLSearchParams({clientId:id,caption,kind}));x.timeout=120000;x.setRequestHeader('Authorization','Bearer '+token());x.setRequestHeader('Content-Type',file.type);x.upload.onprogress=e=>{if(e.lengthComputable)progress('Publication · '+Math.round(e.loaded/e.total*100)+' %');};x.onerror=()=>reject(Error('Connexion interrompue. Réessaie : la publication ne sera pas dupliquée.'));x.ontimeout=()=>reject(Error('Envoi trop long. Vérifie ta connexion puis réessaie.'));x.onload=()=>{let d;try{d=JSON.parse(x.responseText)}catch{return reject(Error('Réponse du serveur indisponible.'))}if(x.status<200||x.status>=300||!d.ok)return reject(Error(d.error||'Publication indisponible. Mets à jour le serveur ONE.'));resolve(d)};x.send(file)});}
window.oneCameraShare=(file,dialog)=>{
 dialog.querySelector('.oneCaptureDestinations')?.remove();const panel=node('section','oneCaptureDestinations');dialog.append(panel);const status=t=>{dialog.querySelector('[role=status]').textContent=t;};
 const button=(text,fn)=>{const b=node('button','',text);b.type='button';b.onclick=fn;return b};
 function back(){panel.remove();status('Vérifie ton contenu avant de le partager sur ONE.');}
 function choose(){panel.replaceChildren(node('h3','','Choisis ta destination'));for(const [title,hint,fn]of [['Publier sur ONE','Dans le fil ONE',publicForm],['Envoyer à mes amis','En message privé',friends],['Ajouter à ma story','Dans Moments · 24 heures',()=>publicForm('story')]]){const b=button('',fn);b.className='oneCaptureChoice';const icon=node('span','oneShareIcon');const path=title==='Publier sur ONE'?'<rect x="4" y="4" width="16" height="16" rx="4"/><path d="m10 8 6 4-6 4z"/>':title==='Envoyer à mes amis'?'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2M16 5a3 3 0 0 1 0 6m2 3a5 5 0 0 1 3 5"/>':'<circle cx="12" cy="12" r="8" stroke-dasharray="5 3"/><path d="M12 7v5l3 2"/>';icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+path+'</svg>';b.append(icon,node('b','',title),node('small','',hint));panel.append(b)}panel.append(button('Changer de photo ou vidéo',()=>window.oneRetakeCapture?.()));status('Choisis qui pourra voir ton contenu.');panel.querySelector('button').focus();}
 function publicForm(kind='post'){if(typeof kind!=='string')kind='post';const story=kind==='story';panel.replaceChildren(node('h3','',story?'Ajouter à ma story':'Publier sur ONE'),node('p','',story?'Visible par les membres ONE dans Moments pendant 24 heures. Tu peux la supprimer avant.':'Cette publication sera visible par les membres ONE. Tu pourras la supprimer depuis le fil.'));const label=node('label','','Légende (facultatif)'),caption=node('textarea');caption.maxLength=1000;caption.rows=3;caption.placeholder='Raconte ce moment…';label.append(caption);panel.append(label);const go=button(story?'Partager ma story':'Publier sur ONE',async()=>{const controls=[...dialog.querySelectorAll('button,input,textarea')];controls.forEach(b=>b.disabled=true);const block=e=>e.preventDefault();dialog.addEventListener('cancel',block);status('Préparation de la publication…');try{await publish(file,caption.value,status,kind);dialog.close();window.toast?.(story?'Story ajoutée dans Moments':'Publication partagée sur ONE');if(story){window.oneShowSpace?.('moments')}else{window.oneShowSpace?.('one');}window.dispatchEvent(new Event('one-posts-updated'));}catch(e){status(e.message)}finally{controls.forEach(b=>b.disabled=false);dialog.removeEventListener('cancel',block)}});go.className='capturePrimary';panel.append(go,button('Retour',choose));caption.focus();status('Le partage a lieu uniquement quand tu appuies sur Publier.');}
 async function friends(){panel.replaceChildren(node('h3','','Envoyer à mes amis'));status('Chargement de tes amis…');const marker={};panel._load=marker;try{const d=await api(PEOPLE,'/friends/state');if(!dialog.open||panel._load!==marker)return;const list=(d.relationships||[]).filter(x=>x.status==='accepted');if(!list.length)panel.append(node('p','','Ajoute un ami dans Discussions pour lui envoyer ton contenu.'));for(const friend of list){const b=button(friend.name||friend.displayName||'Ami ONE',async()=>{if(!window.oneSendMediaToFriend){status('La messagerie se prépare. Réessaie dans un instant.');return}const controls=[...dialog.querySelectorAll('button,input')];controls.forEach(n=>n.disabled=true);const block=e=>e.preventDefault();dialog.addEventListener('cancel',block);status('Préparation de l’envoi…');try{await window.oneSendMediaToFriend(file,{id:String(friend.id),name:friend.name||friend.displayName||'Ami ONE'},{openConversation:false,throwOnError:true,onProgress:status});dialog.close();window.oneOpenFriends?.(String(friend.id));}catch(e){status(e.message+' Le média est conservé : appuie sur ton ami pour réessayer.');}finally{controls.forEach(n=>n.disabled=false);dialog.removeEventListener('cancel',block);}});b.dataset.friend=String(friend.id);panel.append(b)}status('Choisis un ami. Le média privé est supprimé après ouverture.');}catch(e){status(e.message);panel.append(button('Réessayer',friends))}panel.append(button('Retour',()=>{panel._load=null;choose()}));}
 choose();
};
let currentCleanup,currentHost;
window.oneMountNativeFeed=(host,kind='post')=>{
 if(!host?.isConnected)return;currentCleanup?.();currentHost=host;host.replaceChildren();host.className='oneNativeFeed';host.dataset.kind=kind;const heading=node('header'),title=node('h2','',kind==='story'?'Stories':'Le fil ONE'),create=node('button','','＋'),refresh=node('button','','Actualiser');create.setAttribute('aria-label','Créer une publication');create.onclick=()=>window.oneOpenCamera?.();heading.append(title,create,refresh);const intro=node('p','',kind==='story'?'Les stories des membres ONE · visibles 24 h.':'Les photos et vidéos partagées par les membres ONE.'),message=node('p'),list=node('div'),more=node('button','','Voir plus');message.setAttribute('role','status');more.dataset.more='';more.hidden=true;host.append(heading,intro,message,list,more);
 let stopped=false,busy=false,cursor=null;const urls=new Set(),controller=new AbortController();const expiryTimer=setInterval(()=>{for(const item of list.children){if(Number(item.dataset.expires)>0&&Number(item.dataset.expires)<=Date.now()){item.querySelector('video')?.pause();item.remove();}}},15000);const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){observer.unobserve(e.target);loadMedia(e.target)}},{rootMargin:'150px'});
 currentCleanup=()=>{stopped=true;clearInterval(expiryTimer);controller.abort();observer.disconnect();for(const u of urls)URL.revokeObjectURL(u);list.querySelectorAll('video').forEach(v=>v.pause());host.replaceChildren();};
 async function loadMedia(box){if(stopped||!box.isConnected)return;box.replaceChildren(node('p','','Chargement…'));try{const r=await fetch(BASE+'/posts/'+box.dataset.id+'/media',{headers:{Authorization:'Bearer '+token()},signal:controller.signal,cache:'no-store'});if(!r.ok)throw Error('Média indisponible.');const blob=await r.blob();if(stopped||!box.isConnected)return;const url=URL.createObjectURL(blob);urls.add(url);const media=node(box.dataset.mime.startsWith('video/')?'video':'img');media.src=url;if(media.tagName==='VIDEO'){media.controls=true;media.playsInline=true;media.preload='metadata';media.addEventListener('play',()=>list.querySelectorAll('video').forEach(v=>{if(v!==media)v.pause()}))}else media.alt='Publication ONE';media.onerror=()=>{box.replaceChildren(node('p','','Ce format ne peut pas être affiché sur cet appareil.'))};box.replaceChildren(media);}catch(e){if(stopped)return;const retry=node('button','','Réessayer le chargement');retry.onclick=()=>loadMedia(box);box.replaceChildren(retry);}}
 function card(p){const article=node('article','oneNativePost'),head=node('header'),avatar=node('span','onePostAvatar',(p.name||'O').slice(0,1)),identity=node('div'),stamp=node('time','',new Date(p.created).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'}));stamp.dateTime=new Date(p.created).toISOString();identity.append(node('b','',p.name||'Membre ONE'),stamp);head.append(avatar,identity);if(p.mine){const del=node('button','onePostDelete','Supprimer');del.onclick=async()=>{if(del.dataset.confirm!=='true'){del.dataset.confirm='true';del.textContent='Confirmer';setTimeout(()=>{del.dataset.confirm='false';del.textContent='Supprimer'},4000);return}del.disabled=true;try{await api(BASE,'/posts/'+p.id+'/delete',{method:'POST'});article.remove();if(!list.children.length)message.textContent='Aucune publication pour le moment.';}catch(e){message.textContent=e.message;del.disabled=false}};head.append(del)}article.dataset.expires=p.expires||0;const media=node('div','onePostMedia');media.dataset.id=p.id;media.dataset.mime=p.mime;article.append(head,media);if(p.caption)article.append(node('p','',p.caption));list.append(article);observer.observe(media);}
 async function load(reset=false){if(busy||stopped)return;busy=true;refresh.disabled=true;more.disabled=true;message.textContent='Chargement du fil…';try{const params='?'+new URLSearchParams({kind,...(cursor&&!reset?{before:cursor.created,cursor:cursor.id}:{})});const d=await api(BASE,'/posts'+params,{signal:controller.signal});if(stopped||!host.isConnected)return;if(reset){observer.disconnect();list.replaceChildren();for(const u of urls)URL.revokeObjectURL(u);urls.clear();cursor=null}for(const p of d.posts||[])card(p);if(d.posts?.length)cursor=d.posts.at(-1);more.hidden=!d.more;message.textContent=list.children.length?'':'Aucune publication pour le moment. Partage la première !';}catch(e){if(!stopped)message.textContent=e.message;}finally{busy=false;refresh.disabled=false;more.disabled=false}}
 refresh.onclick=()=>load(true);more.onclick=()=>load();load(true);
};
window.addEventListener('one-account-changed',()=>{currentCleanup?.();currentCleanup=null;});window.addEventListener('one-space-open',()=>{setTimeout(()=>{if(currentHost&&!currentHost.isConnected){currentCleanup?.();currentCleanup=null;currentHost=null}mountStories()},0)});
document.addEventListener('visibilitychange',()=>{if(document.hidden)currentHost?.querySelectorAll('video').forEach(v=>v.pause());});
function mountStories(){const moments=document.querySelector('.oneMomentsScreen');if(!moments||moments.querySelector('#oneStories'))return;const host=node('section');host.id='oneStories';host.setAttribute('aria-label','Stories ONE');moments.insertBefore(host,moments.querySelector('.oneMomentsTabs'));window.oneMountNativeFeed(host,'story');}
const shell=document.getElementById('oneFoundation');if(shell)new MutationObserver(()=>{mountStories()}).observe(shell,{childList:true,subtree:true});mountStories();
const waitingFeed=document.getElementById('oneNativeFeed');if(waitingFeed&&!waitingFeed.classList.contains('oneNativeFeed'))window.oneMountNativeFeed(waitingFeed);
})();
