(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-douze.css?v=014117';document.head.append(css);const targetCss=document.createElement('link');targetCss.rel='stylesheet';targetCss.href='ui/douze-target.css?v=117o';document.head.append(targetCss);
 let choice='replace',choiceKey='',previous=null;
 window.ONEDouzeRules='Révèle deux cartes de ta grille. À ton tour, prends la défausse et remplace une carte, ou pioche : garde la carte en échange d’une des tiennes, ou défausse-la puis révèle une carte cachée. Trois cartes identiques dans une colonne sont retirées. Quand un joueur a tout révélé, les autres jouent un dernier tour. Les cartes restantes sont révélées puis comptées. Celui qui termine double ses points de manche s’ils sont positifs et qu’il n’a pas seul le plus petit score. À partir de 100 points cumulés pour un joueur, le plus petit total gagne. Le premier tour revient à la plus forte somme révélée (égalité tirée au sort) ; les manches suivantes commencent par celui qui a terminé la précédente.';
 function syncMic(){document.querySelectorAll('.dzp-seat').forEach(seat=>{const m=window.ONEPartyMedia?.memberStatus?.(seat.dataset.you==='true'?'local':seat.dataset.player),n=seat.querySelector('.dzp-mic');if(n){n.textContent=m?.mic===true?'🎤':m?.mic===false?'🔇':'🎤 ·';n.title=m?.mic===true?'Micro actif':m?.mic===false?'Micro coupé':'État micro indisponible';}});}
 window.addEventListener('one-media-state',syncMic);window.addEventListener('one-game-rendered',syncMic);window.addEventListener('one-account-changed',()=>{previous=null;choiceKey='';});
 window.renderONEDouze=({g,body,busy,command,el,btn,isHost})=>{
  const key=g.id+':'+g.revision;if(choiceKey!==key){choiceKey=key;choice='replace';}
  const old=previous?.id===g.id?previous:null,changed=old?.revision!==g.revision,newRound=!old||old.round!==g.round;
  const me=g.players.find(p=>p.isYou),active=g.status==='playing',setup=active&&g.phase==='setup',ended=['round-end','finished'].includes(g.phase),turn=g.players.find(p=>p.isTurn);
  let pending=false;
  const root=el('section');root.className='dzp-game';root.dataset.phase=g.phase;root.setAttribute('aria-label','Table ONE Douze');body.append(root);
  const feedback=el('p');feedback.className='dzp-feedback';feedback.setAttribute('role','status');
  async function play(action,slot){if(busy||pending)return;pending=true;const touched=slot!==undefined?root.querySelector('.dzp-own [data-slot="'+slot+'"]'):action==='draw'?deck:action==='take-discard'?pile:null;touched?.classList.add('dzp-pending');root.setAttribute('aria-busy','true');root.querySelectorAll('[data-game-control]').forEach(b=>b.disabled=true);try{await command('play','&game='+encodeURIComponent(g.id)+'&revision='+g.revision+'&action='+action+(slot===undefined?'':'&slot='+slot));}finally{pending=false;touched?.classList.remove('dzp-pending');root.removeAttribute('aria-busy');}}
  function card(value,hidden,onClick,label){const n=onClick?btn('',onClick):el('div');n.className='dzp-card';if(onClick){n.addEventListener('pointerdown',e=>{if(n.disabled||e.button!==0)return;n.classList.add('dzp-touch');});for(const type of ['pointerup','pointercancel','pointerleave','blur'])n.addEventListener(type,()=>n.classList.remove('dzp-touch'));}n.dataset.tone=hidden?'back':value<0?'negative':value===0?'blue':value<=4?'green':value<=8?'gold':'red';n.setAttribute('aria-label',label||(hidden?'Carte cachée':String(value)));n.append(el('small',hidden?'✦ ONE':String(value)),el('strong',hidden?'ONE':String(value)),el('small',hidden?'DOUZE':String(value)));return n;}
  const heading=el('header');heading.className='dzp-heading';heading.append(el('span','Manche '+g.round),el('span','Objectif : moins de points'));root.append(heading);
  const stage=el('div');stage.className='dzp-stage';stage.dataset.players=g.players.length;root.append(stage);
  const felt=el('div','ONE');felt.className='dzp-felt-mark';felt.setAttribute('aria-hidden','true');stage.append(felt);
  const columns=[];
  function seat(p,own,pos){const n=el('article');n.className='dzp-seat'+(own?' dzp-own':' dzp-rival')+(p.isTurn?' dzp-current':'')+(p.isWinner?' dzp-winner':'');n.dataset.player=p.accountId;n.dataset.you=String(own);n.style.setProperty('--x',pos[0]+'%');n.style.setProperty('--y',pos[1]+'%');const head=el('header');head.className='dzp-player';const portrait=el('div');portrait.className='dzp-camera';portrait.dataset.cameraSeat=own?'local':p.accountId;const actual=window.oneSocialRoom?.()?.members.find(m=>m.accountId===p.accountId)||{accountId:p.accountId,name:p.name};if(window.ONEUI)portrait.append(ONEUI.avatar(actual));const mic=el('span','🎤 ·');mic.className='dzp-mic';portrait.append(mic);const name=el('b',own?'Toi':p.name);name.title=p.name;const points=el('small',p.total+' pts · '+p.visibleScore+' visibles');points.title='Total : '+p.total+' · cartes révélées : '+p.visibleScore;head.append(portrait,name,points);
   const grid=el('div');grid.className='dzp-grid';grid.setAttribute('aria-label','Grille de '+p.name+' : 4 colonnes de 3 cartes');const before=old?.players.find(x=>x.accountId===p.accountId);let removed=false;
   for(const c of p.grid){const was=before?.grid.find(x=>x.index===c.index),label='Ligne '+(Math.floor(c.index/4)+1)+', colonne '+(c.index%4+1)+' : '+(c.removed?'retirée':c.open?c.value:'cachée');if(c.removed){const empty=el('div');empty.className='dzp-empty';empty.setAttribute('aria-label',label);empty.dataset.slot=c.index;grid.append(empty);if(changed&&!newRound&&was&&!was.removed){columns.push({slot:empty,card:card(was.open?was.value:null,!was.open),player:p.accountId});removed=true;}continue;}
    const item=card(c.open?c.value:null,!c.open,own?()=>play(setup?'reveal':choice,c.index):null,label);item.dataset.slot=c.index;if(own)item.disabled=busy||!active||!(setup?me.flipped<2&&!c.open:g.yourTurn&&g.drawn&&(choice==='replace'||!c.open));if(newRound)item.classList.add('dzp-deal');else if(changed&&was&&!was.removed&&(was.open!==c.open||was.value!==c.value))item.classList.add(was.open?'dzp-replace':'dzp-flip');item.style.setProperty('--delay',(c.index*18)+'ms');grid.append(item);
   }
   if(removed){n.classList.add('dzp-column-won');const tag=el('span','COLONNE !');tag.className='dzp-column-label';n.append(tag);}if(own)n.append(grid,head);else n.append(head,grid);{const count=el('small',setup?p.flipped+'/2 révélées':' ');count.className='dzp-setup-count';count.style.visibility=setup?'visible':'hidden';n.append(count);}stage.append(n);return n;
  }
  const others=g.players.filter(p=>!p.isYou),positions=others.length===1?[[50,0]]:others.length===2?[[16,8],[84,8]]:others.length===3?[[50,0],[14,16],[86,16]]:others.length===4?[[22,0],[78,0],[13,30],[87,30]]:[[50,0],[14,8],[86,8],[13,34],[87,34]];
  others.forEach((p,i)=>seat(p,false,positions[i]||[50,0]));
  const center=el('section');center.className='dzp-center';center.setAttribute('aria-label','Pioche et défausse');const drawAllowed=active&&!setup&&!ended&&g.yourTurn&&g.phase==='turn';
  const deckWrap=el('div'),pileWrap=el('div'),deck=card(null,true,()=>play('draw'),'Prendre la pioche'),pile=card(g.discard,g.discard===null,()=>play('take-discard'),'Prendre la défausse'+(g.discard===null?' vide':' : '+g.discard));deck.disabled=busy||!drawAllowed;pile.disabled=busy||!drawAllowed||g.discard===null;pile.dataset.discard='true';if(changed&&old&&old.discard!==g.discard)pile.classList.add('dzp-to-discard');deckWrap.append(deck,el('b','Pioche'),el('small',g.deckCount+' cartes'));pileWrap.append(pile,el('b','Défausse'));center.append(pileWrap,deckWrap);stage.append(center);
  const instruction=el('div');instruction.className='dzp-turn';instruction.setAttribute('role','status');instruction.append(el('b',setup?'Prépare tes cartes':ended?'Manche terminée':!active?'Partie interrompue':g.yourTurn?'À ton tour':'Tour de '+(turn?.name||'…')),el('span',!active?g.last:setup?(me?.flipped<2?'Révèle '+(2-me.flipped)+' cartes de ta grille.':'En attente des autres joueurs.'):ended?'Les scores sont confirmés.':g.drawn?(choice==='replace'?'Choisis une carte à remplacer.':'Choisis une carte cachée à révéler.'):'Choisis la pioche ou la défausse.'));stage.append(instruction);
  if(g.drawn){const held=el('div');held.className='dzp-held';held.append(el('small',g.drawn.source==='deck'?'Ta pioche · privée':'Carte choisie'),card(g.drawn.value,false));if(changed&&!old?.drawn)held.classList.add('dzp-draw-in');stage.append(held);}
  if(me)seat(me,true,[50,0]);
  const controls=el('div');controls.className='dzp-actions';if(active&&!setup&&!ended){if(g.drawn&&g.yourTurn){const keep=btn('Garder · remplacer',()=>select('replace')),reject=btn('Défausser · révéler',()=>select('discard-reveal'));keep.dataset.action='keep';reject.dataset.action='reject';keep.disabled=busy;reject.disabled=busy||g.drawn.source!=='deck'||!me.grid.some(c=>!c.removed&&!c.open);keep.setAttribute('aria-pressed',String(choice==='replace'));reject.setAttribute('aria-pressed',String(choice==='discard-reveal'));controls.append(keep,reject);}else{const draw=btn('Prendre la pioche',()=>play('draw')),take=btn('Prendre la défausse',()=>play('take-discard'));draw.dataset.action='draw';take.dataset.action='take-discard';draw.disabled=busy||!drawAllowed;take.disabled=busy||!drawAllowed||g.discard===null;controls.append(draw,take);}}
  function select(mode){choice=mode;window.dispatchEvent(new Event('one-game-before-render'));root.remove();window.renderONEDouze({g,body,busy,command,el,btn,isHost});body.insertBefore(body.lastChild,body.querySelector('#oneGameCallDock')||null);window.dispatchEvent(new Event('one-game-rendered'));}
  root.append(controls);if(g.ender&&!ended)root.append(el('p',(g.players.find(p=>p.accountId===g.ender)?.name||'Un joueur')+' a terminé · dernier tour.'));
  if(ended){const result=el('section');result.className='dzp-result';result.setAttribute('aria-label','Résultats');const winners=g.players.filter(p=>p.isWinner).map(p=>p.name);result.append(el('h3',g.phase==='finished'?'🏆 '+winners.join(' et '):'Résultats de la manche '+g.round));const table=el('table'),head=el('tr');['Joueur','Manche','Total'].forEach(x=>head.append(el('th',x)));table.append(head);for(const p of [...g.players].sort((a,b)=>a.total-b.total)){const row=el('tr');if(p.isWinner)row.className='dzp-result-winner';row.append(el('td',p.name),el('td',p.roundScore+(p.doubled?' ×2 inclus':'')),el('td',String(p.total)));table.append(row);}result.append(table);if(g.phase==='round-end'&&active){const next=btn(isHost?'Manche suivante':'L’hôte lance la prochaine manche',()=>play('next-round'));next.disabled=busy||!isHost;result.append(next);}stage.append(result);result.setAttribute('role','region');}
  const tools=el('nav');tools.className='dzp-tools';tools.setAttribute('aria-label','Communication du salon');tools.append(btn('☏ Chat',()=>{window.oneOpenSalon?.();const chat=document.getElementById('onePartyChat');if(chat){chat.hidden=false;chat.scrollIntoView({block:'nearest'});}}));for(const [label,kind]of [['🎤 Micro','mic'],['▣ Caméra','camera']])tools.append(btn(label,async()=>{try{await window.ONEPartyMedia?.toggle?.(kind);}catch(e){feedback.textContent=e.message;}}));tools.append(btn('♧ Salon',()=>window.oneOpenSalon?.()));root.append(feedback);const footer=el('footer');footer.className='dzp-signature';footer.append(el('b','ONE Douze'),el('span','DES JEUX. DES AMIS. UNE SEULE APP.'));root.append(footer);
  // Only animate transitions between public server snapshots. No hidden values inferred.
  if(columns.length&&!matchMedia('(prefers-reduced-motion: reduce)').matches)requestAnimationFrame(()=>{if(!root.isConnected)return;const rr=root.getBoundingClientRect(),target=pile.getBoundingClientRect();for(const item of columns){const rect=item.slot.getBoundingClientRect(),ghost=item.card;ghost.classList.add('dzp-column-ghost');ghost.style.cssText+=';left:'+(rect.left-rr.left)+'px;top:'+(rect.top-rr.top)+'px;width:'+rect.width+'px;height:'+rect.height+'px;--dx:'+(target.left-rect.left)+'px;--dy:'+(target.top-rect.top)+'px';root.append(ghost);ghost.addEventListener('animationend',()=>ghost.remove(),{once:true});}});
  previous=JSON.parse(JSON.stringify(g));syncMic();
 };
})();
