(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev',panel=document.createElement('section');panel.id='onePartyGame';let room=null,data=null,busy=false,loading=false,version=0;
 const avatars={croupier:'La Revenante',renard:'Remy',corbeau:'Agent 09',chasseur:'Le Parasite'};
 const colors={red:'Rouge',blue:'Bleu',green:'Vert',yellow:'Jaune',wild:'Joker'},symbols={skip:'Passe',reverse:'Sens inverse',draw2:'+2',wild:'Joker'};
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-game.css?v=014105';document.head.append(css);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},btn=(text,fn)=>{const b=el('button',text);b.type='button';b.dataset.gameControl='true';b.onclick=fn;return b;};const status=el('p'),body=el('div');status.setAttribute('role','status');body.className='oneGameBody';panel.append(el('h2','ONE Couleurs'),status,body);
 function visible(){return !document.getElementById('oneFoundation')?.hidden&&document.querySelector('[data-one-space="party"]')?.getAttribute('aria-current')==='page';}
 function mount(){if(visible()){const shell=document.getElementById('oneFoundation');if(panel.parentNode!==shell)shell.replaceChildren(panel);if(!data)render();}}window.onePartyGameVisible=visible;
 async function api(action,method='GET',params='',signal){const token=oneAccountToken(),id=room?.id;if(!id)throw Error('Salon fermé.');const response=await fetch(API+'/party/game/'+action+'?room='+encodeURIComponent(id)+params,{method,headers:{Authorization:'Bearer '+token},signal:signal||AbortSignal.timeout(12000)});const result=await response.json().catch(()=>({}));if(room?.id!==id||token!==oneAccountToken())throw Error('Le salon ou le compte a changé.');if(!response.ok||!result.ok)throw Object.assign(Error(result.error||'Jeu indisponible.'),{status:response.status});return result;}
 // Invalidate pre-action polls. A forced read always follows the completed write.
 let readEpoch=0,readTask=null,readAbort=null,openedGame=null;window.oneRefreshPartyGame=()=>load(true);
 async function command(action,params='',question){
  if(busy||question&&!confirm(question))return;
  busy=true;readEpoch++;readAbort?.abort();const own=version;
  panel.setAttribute('aria-busy','true');status.textContent='Confirmation en cours…';
  body.querySelectorAll('button[data-game-control]').forEach(b=>b.disabled=true);
  try{
   await api(action,'POST',params);
   if(own!==version)return;
   const synced=await load(true);
   if(synced)status.textContent='';
   return true;
  }catch(e){if(own===version){if(e.status===409)await window.oneRefreshSalonState?.(true);status.textContent=e.message;await load(true,true);}return false;}
  finally{if(own===version){busy=false;panel.removeAttribute('aria-busy');render();}}
 }
 async function load(force=false,keepError=false){
  if(!room||!force&&busy)return false;
  if(readTask){if(!force)return false;await readTask;if(!room)return false;}
  const own=version,epoch=readEpoch,controller=new AbortController();readAbort=controller;
  const task=(async()=>{try{
   const sentAt=performance.now(),fresh=await api('state','GET','',AbortSignal.any([controller.signal,AbortSignal.timeout(12000)]));
   if(own!==version||epoch!==readEpoch)return false;
   window.dispatchEvent(new CustomEvent('one-game-clock',{detail:{game:fresh.game,receivedAt:performance.now(),rtt:performance.now()-sentAt}}));
   const signature=d=>JSON.stringify(d?.game?{...d,game:{...d.game,serverNow:0,canResolve:undefined}}:d);
   if(fresh.isParticipant!==true)fresh.game=null;const changed=signature(data)!==signature(fresh);const enter=fresh.isParticipant===true&&fresh.activeGame?.status==='playing'&&fresh.game?.status==='playing'&&fresh.game.id!==openedGame;
   if(!fresh.game&&data?.game){full=false;panel.classList.remove('gameFullscreen');document.body.classList.remove('oneGameFullscreen');}
   data=fresh;if(enter){openedGame=fresh.game.id;window.oneCloseSalon?.();window.oneShowSpace?.('party');mount();fullscreen(true);window.ONEGameMenu?.enter(panel,fresh.game);}if(changed&&!busy)render();if(!keepError)status.textContent='';return true;
  }catch(e){if(own===version&&epoch===readEpoch)status.textContent=e.message;return false;}})();
  readTask=task;try{return await task;}finally{if(readTask===task){readTask=null;readAbort=null;}}
 }
 function askStop(){if(panel.querySelector('#oneGameExitConfirm'))return;const box=el('section');box.id='oneGameExitConfirm';box.setAttribute('role','dialog');box.setAttribute('aria-label','Arrêter la partie');const confirm=btn('Confirmer l’arrêt',async()=>{confirm.disabled=true;const ok=await command('reset');if(ok)box.remove();else confirm.disabled=false;});box.append(el('p','Arrêter cette partie pour tous les joueurs ? Le salon restera ouvert.'),confirm,btn('Continuer la partie',()=>box.remove()));panel.append(box);confirm.focus();}
 function returnToGames(){const current=data?.game;if(!current)return;const leave=()=>command('return-lobby','&game='+encodeURIComponent(current.id));if(current.status!=='playing'){leave();return;}if(panel.querySelector('#oneGameExitConfirm'))return;const box=el('section');box.id='oneGameExitConfirm';box.setAttribute('role','dialog');box.setAttribute('aria-label','Retour aux jeux');const confirm=btn('Quitter la partie',async()=>{confirm.disabled=true;if(await leave())box.remove();else confirm.disabled=false;});box.append(el('p','Quitter cette partie et revenir au choix des jeux ? La partie sera arrêtée pour tous. Le salon et le vocal restent ouverts.'),confirm,btn('Continuer à jouer',()=>box.remove()));panel.append(box);confirm.focus();}
 function cardLabel(c){return colors[c.color]+' · '+(symbols[c.value]||c.value);}
 let full=false,joker=null,lastTop='',topUntil=0,lastHand=null;const drawnUntil=new Map();
 function fullscreen(on){full=on;panel.classList.toggle('gameFullscreen',on);document.body.classList.toggle('oneGameFullscreen',on);render();}
 window.onePartyImmersive=fullscreen;
 function graphic(c,interactive=false,fn){const node=interactive?btn('',fn):el('div');node.className='cg-card';node.dataset.color=c.color;node.setAttribute('aria-label',cardLabel(c));const value=symbols[c.value]||c.value,short={skip:'⊘',reverse:'⇄',draw2:'+2',wild:'✦'}[c.value]||c.value;node.append(el('span',short),el('strong',short),el('small',value));return node;}
 function seat(p){const s=el('div');s.className='cg-seat'+(p.isTurn?' current':'')+(p.isWinner?' winner':'');const avatar=el('span',p.name.trim().slice(0,1).toUpperCase()||'?');avatar.className='cg-avatar';const meta=el('div');meta.append(el('b',p.name+(p.isYou?' · toi':'')),el('small',p.isWinner?'Victoire !':p.isTurn?'À son tour':p.count+' cartes'));const face=el('div');face.className='cg-face';face.dataset.cameraSeat=p.isYou?'local':p.accountId||'';face.append(avatar);s.append(face,meta);const backs=el('span');backs.className='cg-backs';backs.setAttribute('aria-label',p.count+' cartes');for(let i=0;i<Math.min(p.count,5);i++)backs.append(el('i'));s.append(backs);return s;}
 function render(){const menuWasOpen=!!body.querySelector('.cg-menu')?.open;panel.classList.toggle('isPoker',data?.game?.kind==='poker');if(!data?.game||!['horror','laugh'].includes(data.game.kind)||!['watch','paused'].includes(data.game.phase))panel.classList.remove('reactionCinema');window.dispatchEvent(new Event('one-game-before-render'));body.replaceChildren();if(!data){panel.classList.remove('hasGame','isBluff','isDouze');if(room)body.append(el('p','Chargement du salon…'));else window.ONEPublicRooms?.catalog(body);window.dispatchEvent(new Event('one-game-rendered'));return;}const g=data.game;panel.classList.toggle('hasGame',!!g);panel.classList.toggle('isBluff',g?.kind==='bluff');panel.classList.toggle('isDouze',g?.kind==='douze');const topbar=el('div');topbar.className='cg-topbar';const brand=el('div');brand.append(el('small','PARTY / JEUX ENTRE AMIS'),el('h2',window.ONEPartyCatalog?.[g?.kind]?.name||(g?.kind==='douze'?'ONE Douze':g?.kind==='bluff'?'ONE Bluff':g?'ONE Couleurs':'Les jeux ONE')));const tools=el('div');tools.className='cg-tools';tools.append(btn(full?'↙ Réduire':'⛶ Plein écran',()=>fullscreen(!full)));if(g&&data.isHost&&g.status==='playing')tools.append(btn('Arrêter',askStop));if(room){tools.append(btn('← Salon',()=>{if(full)fullscreen(false);window.ONEVideoSync?.clear();window.oneOpenSalon?.();}),btn('Quitter le salon',()=>{if(full)fullscreen(false);window.ONEVideoSync?.clear();window.oneAskLeaveSalon?.();}));}if(g){const close=btn('×',returnToGames);close.className='cg-close-game';close.setAttribute('aria-label','Quitter la partie et revenir aux jeux');tools.prepend(close);}const menu=el('details');menu.className='cg-menu';menu.open=menuWasOpen;menu.append(el('summary','☰ Menu'),tools);topbar.append(brand,menu);body.append(topbar);if(g?.pointStake)body.append(el('p','Mise acceptée : '+g.pointStake+' Points ONE par joueur'+(g.kind==='poker'?' · Réserve de poker':' · Pot : '+g.pointStake*g.players.length+' points')));
 if(!g){window.renderONELobby({body,data,room,busy,command,el,btn,avatars,refresh:render});
 }else if(g.kind==='poker'){window.renderONEPartyPoker({g,body,busy,command,el,btn});}else if(window.ONEPartyCatalog?.[g.kind]){window.renderONECollection({g,body,busy,command,el,btn});}else if(g.kind==='douze'){window.renderONEDouze({g,body,busy,command,el,btn,isHost:data.isHost});}else if(g.kind==='bluff'){window.renderONEBluff({g,body,busy,command,el,btn});}else{
  const table=el('div');table.className='cg-table';const surface=el('div');surface.className='cg-surface';surface.setAttribute('aria-hidden','true');surface.append(el('span','ONE'));table.append(surface);const opponents=el('div');opponents.className='cg-opponents';const rivals=g.players.filter(p=>!p.isYou);opponents.dataset.count=rivals.length;for(const p of rivals)opponents.append(seat(p));table.append(opponents);
  const center=el('div');center.className='cg-center';const turn=el('div',g.status==='playing'?(g.yourTurn?'À TOI DE JOUER':(g.players.find(p=>p.isTurn)?.name||'Adversaire')+' JOUE'):g.status==='finished'?'PARTIE TERMINÉE':'PARTIE INTERROMPUE');turn.className='cg-turn'+(g.yourTurn?' yours':'');center.append(turn);
  const stacks=el('div');stacks.className='cg-stacks';const pile=btn('',()=>command('play','&game='+g.id+'&revision='+g.revision+'&action=draw'));pile.className='cg-deck';pile.setAttribute('aria-label','Piocher une carte et passer ton tour');pile.disabled=busy||!g.yourTurn||g.status!=='playing';if(g.pendingDraw)pile.setAttribute('aria-label','Piocher '+g.pendingDraw+' cartes et passer ton tour');pile.append(el('small','ONE'),el('strong','✦'),el('span',g.pendingDraw?'PIOCHER '+g.pendingDraw:'PIOCHER'));const discard=graphic(g.top);discard.classList.add('cg-discard');if(lastTop!==g.top.id){topUntil=Date.now()+350;lastTop=g.top.id;}if(Date.now()<topUntil)discard.classList.add('cg-dealt');stacks.append(pile,discard);center.append(stacks);const color=el('span','Couleur · '+colors[g.color]);color.className='cg-color';color.dataset.color=g.color;center.append(color,el('p',g.last));table.append(center);body.append(table);
  if(g.status==='playing'){
   const area=el('div');area.className='cg-playerArea';const head=el('div');head.className='cg-handHead';head.append(el('b','TA MAIN'),el('span',g.hand.length+' cartes · '+(g.yourTurn?'Touche une carte lumineuse':'Patiente, ton tour arrive')));const me=g.players.find(p=>p.isYou);if(me){const self=seat(me);self.classList.add('cg-self');area.append(self);}area.append(head);
   if(joker&&!g.hand.some(c=>c.id===joker)&&g.yourTurn)joker=null;if(!g.yourTurn)joker=null;
   if(joker){const choices=el('div');choices.className='cg-jokerChoice';choices.append(el('b','Choisis ta couleur'));for(const [key,label]of Object.entries(colors)){if(key==='wild')continue;const pick=btn(label,()=>{const id=joker;joker=null;command('play','&game='+g.id+'&revision='+g.revision+'&action=card&card='+encodeURIComponent(id)+'&color='+key);});pick.dataset.color=key;pick.disabled=busy;choices.append(pick);}choices.append(btn('Annuler',()=>{joker=null;render();}));area.append(choices);}
   const currentIds=new Set(g.hand.map(c=>c.id));if(lastHand)for(const id of currentIds)if(!lastHand.has(id))drawnUntil.set(id,Date.now()+400);lastHand=currentIds;const hand=el('div');hand.className='cg-hand';hand.setAttribute('aria-label','Tes cartes');hand.style.setProperty('--card-count',g.hand.length);for(let i=0;i<g.hand.length;i++){const c=g.hand[i],legal=g.pendingDraw?c.value==='draw2':c.color==='wild'||c.color===g.color||c.value===g.top.value;const b=graphic(c,true,()=>{if(c.color==='wild'){joker=c.id;render();}else command('play','&game='+g.id+'&revision='+g.revision+'&action=card&card='+encodeURIComponent(c.id)+'&color='+g.color);});if((drawnUntil.get(c.id)||0)>Date.now())b.classList.add('cg-drawn');b.disabled=busy||!g.yourTurn||!legal;b.classList.toggle('playable',!b.disabled);const tilt=Math.max(-9,Math.min(9,(i-(g.hand.length-1)/2)*3));b.style.setProperty('--tilt',tilt+'deg');hand.append(b);}area.append(hand);body.append(area);
  }else{const result=el('div');result.className='cg-result';result.append(el('strong',g.status==='finished'?'✦ '+(g.players.find(p=>p.isWinner)?.name||'')+' remporte la partie':'Le groupe a changé.'),el('p','Retrouve le salon pour préparer la prochaine partie.'));body.append(result);}
 }
 if(g&&g.kind!=='poker'&&g.status!=='playing'){const endActions=el('section');endActions.className='cg-end-actions';const ready=g.replayReady||[],me=data.members.find(m=>m.isYou),isReady=ready.includes(me?.accountId);endActions.append(el('h3','Rejouer au même jeu'),el('p',ready.length+'/'+data.members.length+' prêts · La partie redémarre quand tout le monde est prêt.'));const players=el('div');players.className='cg-replay-players';for(const m of data.members)players.append(el('span',m.name+(m.isYou?' · toi':'')+' — '+(ready.includes(m.accountId)?'✓ Prêt':'En attente')));const again=btn(isReady?'✓ Prêt · annuler':'Rejouer · je suis prêt',()=>command('replay','&game='+encodeURIComponent(g.id)+'&ready='+(isReady?'0':'1')));again.disabled=busy;again.className='cg-primary';again.setAttribute('aria-pressed',String(isReady));endActions.append(players,again,btn('Choisir un autre jeu',returnToGames));body.insertBefore(endActions,body.children[1]||null);}
 const callDock=el('div');callDock.id='oneGameCallDock';body.append(callDock);const footer=el('div');footer.className='cg-footer';const rules=el('details');rules.append(el('summary','Règles du jeu'),el('p',window.ONEPartyCatalog?.[g?.kind]?.rules||(g?.kind==='douze'?window.ONEDouzeRules:g?.kind==='bluff'?window.ONEBluffRules:'Sept cartes chacun. Même couleur ou symbole pour jouer. La pioche ajoute une carte et termine le tour. ⊘ passe le joueur suivant ; +2 lance ou augmente la pénalité de deux cartes ; ⇄ inverse le sens (à deux, tu rejoues). ✦ permet de choisir la couleur. Les +2 se cumulent, même de couleurs différentes : ajoute un +2 ou pioche le total et passe ton tour. Le premier sans carte gagne immédiatement, même avec un +2 final. Un départ interrompt la partie.')));if(g)footer.append(rules);footer.append(btn('↻ Actualiser',()=>load(true)));if(g&&data.isHost&&g.status==='playing'){const reset=btn(g.status==='playing'?'Arrêter la partie':'Retour au salon',()=>askStop());reset.disabled=busy;footer.append(reset);}tools.append(footer);if(g)window.ONEGameMenu?.mount({panel,menu,tools,g,room,fullscreen,returnToGames,rules:rules.querySelector('p').textContent});window.dispatchEvent(new Event('one-game-rendered'));
 }

 window.addEventListener('one-party-load-error',e=>{status.textContent=e.detail;});
 window.addEventListener('one-salon-visibility',()=>{if(!visible()&&full)fullscreen(false);mount();if(visible()){render();load();}});
 window.addEventListener('one-party-state',e=>{if(room?.id!==e.detail?.id){if(full)fullscreen(false);openedGame=null;joker=null;lastHand=null;drawnUntil.clear();version++;readEpoch++;panel.removeAttribute('aria-busy');data=null;body.replaceChildren();status.textContent='';busy=false;}room=e.detail;if(room){mount();load();}else{if(full)fullscreen(false);if(visible())mount();else panel.remove();}});window.addEventListener('one-space-open',e=>{if(e.detail!=='party'&&full)fullscreen(false);mount();if(visible())load();});window.addEventListener('one-account-changed',()=>{if(full)fullscreen(false);version++;readEpoch++;busy=false;panel.removeAttribute('aria-busy');room=null;data=null;openedGame=null;panel.remove();});new MutationObserver(()=>{if(full&&document.getElementById('oneFoundation')?.hidden)fullscreen(false);}).observe(document.getElementById('oneFoundation'),{attributes:true,attributeFilter:['hidden']});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&full)fullscreen(false);});setInterval(()=>{if(!document.hidden&&!busy)load();},2000);if(visible()){mount();window.oneRefreshSalonState?.();}
})();

