(()=>{const layout=document.createElement('link');layout.rel='stylesheet';layout.href='ui/salons.css?v=014103';document.head.append(layout);
 const tray=document.createElement('aside');tray.id='oneSalonTray';tray.hidden=true;tray.setAttribute('aria-label','Salons ONE');const trayHead=document.createElement('header'),title=document.createElement('h2'),close=document.createElement('button');title.textContent='Salons ONE';close.textContent='×';close.type='button';close.setAttribute('aria-label','Réduire le salon');trayHead.append(title,close);const shell=document.createElement('div');shell.id='oneSalonBody';tray.append(trayHead,shell);document.body.append(tray);
 window.oneSalonContainer=shell;window.oneSalonIsOpen=()=>!tray.hidden;
 window.oneOpenSalon=()=>{tray.hidden=false;mount();window.dispatchEvent(new Event('one-salon-visibility'));};
 window.oneCloseSalon=()=>{tray.hidden=true;window.dispatchEvent(new Event('one-salon-visibility'));};close.onclick=window.oneCloseSalon;
 const entry=document.createElement('button');entry.type='button';entry.id='oneSalonsToggle';entry.setAttribute('aria-label','Salons');entry.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10 12 3l9 7v10H3zM9 20v-7h6v7" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><span>Salons</span>';entry.onclick=window.oneOpenSalon;document.getElementById('oneNotificationsToggle')?.before(entry);
 const API='https://one-comments-api.moulinanthony60.workers.dev';let revision=0,busy=false,host=null,content=null,status=null,pendingClose=false,lastRoom=null;
 const style=document.createElement('style');style.textContent='.onePartyControls{display:grid;gap:12px}.onePartyControls article{background:#15192b;border:1px solid #39334f;border-radius:14px;padding:14px}.onePartyControls input{box-sizing:border-box;max-width:100%;width:100%;padding:12px;border-radius:10px;background:#0b1020;color:white;border:1px solid #65517f;margin:8px 0}.onePartyControls button{padding:11px;margin:4px;border-radius:10px;border:1px solid #735396;color:white;background:#49306b;font:inherit}.onePartyControls button:disabled{opacity:.5}.onePartyControls p{overflow-wrap:anywhere}.onePartyControls ul{padding-left:20px}.onePartyControls label{display:block}.onePartyControls small{color:#b8afcc}';document.head.append(style);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 function active(){return !tray.hidden;}
 function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
 async function api(path,method='GET'){const token=oneAccountToken();const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000)});const data=await r.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé. Actualise Party.');if(!r.ok||!data.ok)throw Error(data.error||'Party momentanément indisponible.');return data;}
 async function command(path,confirmation){if(busy||confirmation&&!confirm(confirmation))return;busy=true;const node=host,buttons=[...node.querySelectorAll('button')].map(b=>[b,b.disabled]);buttons.forEach(([b])=>b.disabled=true);status.textContent='En cours…';try{const result=await api(path,'POST');if(path==='/party/leave'){lastRoom=null;}if(path==='/party/leave')window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));if(host===node&&active()){await load();status.textContent=path.startsWith('/party/invite')?(result.alreadyPending?'Invitation déjà en attente pour ':'Invitation envoyée à ')+(result.recipient||'ce membre')+'. Le destinataire peut ouvrir la cloche ou actualiser Party.':'Action enregistrée.';}window.dispatchEvent(new Event('one-notifications-refresh'));return true;}catch(e){if(host===node&&active())status.textContent=e.message;return false;}finally{busy=false;if(host===node)buttons.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled;});}}
 function confirmLeave(isHost){if(pendingClose||busy)return;pendingClose=true;const box=el('section');box.className='oneLeaveConfirm';box.setAttribute('role','alert');box.append(el('p',isHost?'Fermer le salon pour tous les membres ? La partie et les invitations seront terminées.':'Quitter ce salon ?'),button(isHost?'Confirmer la fermeture':'Confirmer mon départ',async()=>{if(await command('/party/leave')){pendingClose=false;box.remove();}}),button('Annuler',()=>{pendingClose=false;box.remove();}));content.prepend(box);box.scrollIntoView({block:'nearest'});}
 function mount(){pendingClose=false;if(!active())return;revision++;busy=false;shell.replaceChildren();shell.append(el('p','Ton salon reste ouvert pendant ta navigation dans ONE. Jusqu’à 16 membres.'));host=el('div');host.className='onePartyControls';status=el('p');status.setAttribute('role','status');content=el('div');host.append(button('Actualiser',()=>load()),button('Amis et mon QR code',()=>window.oneOpenFriends?.()),status,content);shell.append(host);load();}
 async function load(){if(!active())return;if(!host?.isConnected){mount();return;}const own=++revision,node=host;if(!oneAccountToken()){window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));content.replaceChildren(el('p','Connecte-toi à ton compte ONE pour créer un salon ou recevoir une invitation.'));status.textContent='';return;}try{const data=await api('/party/state');if(own!==revision||host!==node||!active())return;lastRoom=data.room;content.replaceChildren();status.textContent='';window.dispatchEvent(new CustomEvent('one-party-state',{detail:data.room}));
  if(data.room){const r=data.room,card=el('article');card.append(el('h2',r.name),el('p',r.members.length+'/16 membres inscrits au salon'));const members=el('ul');for(const m of r.members)members.append(el('li',m.name+(m.isYou?' (toi)':'')+(m.isHost?' · créateur':'')));card.append(members);
   card.append(el('p',r.visibility==='public'?'🌐 Salon public · visible dans la recherche':'🔒 Salon privé · sur invitation'));if(r.isHost)window.ONEPublicRooms?.settings(card,r,command);
   if(r.isHost){renderSalonFriends(card,r,own,node);const label=el('label','Code ONE du membre à inviter'),input=el('input');input.placeholder='ABCD-EFGH';input.maxLength=68;label.append(input);card.append(label,el('small','Utilise son code court dans Amis, ou invite-le directement depuis ta liste d’amis.'),button('Inviter',()=>command('/party/invite?recipient='+encodeURIComponent(input.value.trim()))));if(r.invitations.length){const sent=el('ul');for(const i of r.invitations)sent.append(el('li',i.recipient+' · '+(i.status==='accepted'?'acceptée':i.status==='declined'?'refusée':i.expiresAt<Date.now()?'expirée':'en attente')));card.append(el('h3','Invitations créées'),sent);}}
   card.append(button(r.isHost?'Fermer le salon':'Quitter le salon',()=>confirmLeave(r.isHost)));content.append(card);
  }else{const card=el('article'),label=el('label','Nom du salon'),input=el('input');input.maxLength=80;input.placeholder='Soirée jeux';label.append(input);card.append(label);const options=window.ONEPublicRooms?.creation(card);card.append(button('Créer un salon',()=>command('/party/create?name='+encodeURIComponent(input.value.trim())+(options?options():''))));content.append(card);}
  window.ONEPublicRooms?.render(content,{api,command,room:data.room});
  content.append(el('h2','Invitations reçues'));if(!data.invitations.length)content.append(el('p','Aucune invitation en attente.'));for(const invite of data.invitations){const card=el('article');card.append(el('b',invite.name),el('p','Invitation de '+invite.host),el('small','Expire le '+new Date(invite.expiresAt).toLocaleString('fr-FR')),button('Accepter',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/accept')),button('Refuser',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/decline','Refuser cette invitation ?')));content.append(card);}
 }catch(e){if(own===revision&&host===node&&active())status.textContent=e.message;}}

 window.oneAskLeaveSalon=async()=>{window.oneOpenSalon();await load();if(lastRoom)confirmLeave(lastRoom.isHost);};
 async function renderSalonFriends(card,r,own,node){const section=el('section');section.className='oneSalonFriends';section.append(el('h3','Inviter mes amis'),el('p','Chargement…'));card.append(section);try{const data=await api('/friends/state');if(own!==revision||host!==node||!section.isConnected)return;const friends=data.relationships.filter(f=>f.status==='accepted').sort((a,b)=>Number(b.online)-Number(a.online)||a.name.localeCompare(b.name));section.replaceChildren(el('h3','Inviter mes amis'));if(!friends.length){section.append(el('p','Ajoute tes amis depuis Amis pour les retrouver ici.'));return;}const offline=el('details');offline.append(el('summary','Autres amis'));let connected=0;for(const friend of friends){const row=el('div');row.className='oneSalonFriend';const name=el('span',friend.name);if(friend.online){name.className='online';name.setAttribute('aria-label',friend.name+' · en ligne');connected++;}const present=r.members.some(m=>m.accountId===friend.accountId),invited=r.invitations.some(i=>i.recipient===friend.accountId&&i.status==='pending'&&i.expiresAt>Date.now());const b=button(present?'Présent':invited?'Envoyée':'Valider',()=>command('/party/invite?recipient='+encodeURIComponent(friend.accountId||friend.code)));b.setAttribute('aria-label',present?friend.name+' est dans le salon':invited?'Invitation déjà envoyée à '+friend.name:'Inviter '+friend.name);b.disabled=present||invited||r.members.length>=16;row.append(name,b);(friend.online?section:offline).append(row);}if(!connected)section.append(el('p','Aucun ami en ligne pour le moment.'));if(offline.children.length>1)section.append(offline);}catch{section.replaceChildren(el('p','Liste d’amis indisponible pour le moment.'));}}
 let presenceBusy=false;async function presence(){if(presenceBusy||document.hidden||!window.oneAccountToken?.())return;presenceBusy=true;try{await api('/friends/presence','POST');}catch{}finally{presenceBusy=false;}}setInterval(presence,30000);window.addEventListener('one-account-changed',presence);document.addEventListener('visibilitychange',presence);presence();
 window.oneRefreshSalonState=async()=>{if(active()){await load();return;}const token=oneAccountToken();if(!token){window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));return;}try{const data=await api('/party/state');if(token===oneAccountToken())window.dispatchEvent(new CustomEvent('one-party-state',{detail:data.room}));}catch(e){window.dispatchEvent(new CustomEvent('one-party-load-error',{detail:e.message}));}};
 window.addEventListener('one-space-open',e=>{if(e.detail==='party'){window.oneCloseSalon();window.oneRefreshSalonState();}});window.addEventListener('one-account-changed',()=>{revision++;if(active())mount();});window.addEventListener('one-party-refresh',()=>{if(active()&&!pendingClose)load();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&active()&&!busy&&!pendingClose)load();});setInterval(()=>{if(!document.hidden&&active()&&!busy&&!pendingClose&&!host?.querySelector('input:focus,textarea:focus,select:focus'))load();},15000);if(active())mount();
})();
