(()=>{
 const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href='ui/party-lobby.css?v=014103';document.head.append(sheet);
 let selected='bluff',salon='',filter='Tous';
 const games=[{id:'bluff',name:'ONE Bluff',tag:'BLUFF & TENSION',symbol:'♠',desc:'Garde ton sang-froid. Pose tes cartes, trompe tes adversaires et démasque leurs mensonges.',hint:'Cartes cachées · Personnages 3D',cards:['A','K','Q']},{id:'colors',name:'ONE Couleurs',tag:'RAPIDE & MALIN',symbol:'↔',desc:'La bonne couleur, le bon symbole. Débarrasse-toi de tes cartes avant les autres.',hint:'Couleurs · Cartes spéciales',cards:['7','+2','4']},{id:'douze',name:'ONE Douze',tag:'OBSERVATION & STRATÉGIE',symbol:'12',desc:'Révèle ta grille, échange tes cartes et vise le plus petit score.',hint:'12 cartes · Le moins de points',cards:['−2','0','12']}];
 games.forEach(g=>{g.min=2;g.max=4;g.category='Cartes';});for(const [id,g] of Object.entries(window.ONEPartyCatalog||{}).filter(([id])=>!['horror','laugh','blind','mimevoice','mimegesture'].includes(id)))games.push({id,...g,hint:(g.min===g.max?g.min:g.min+'–'+g.max)+' joueurs',category:['trio'].includes(id)?'Cartes':['who','connect','codes','wolf'].includes(id)?'Réflexion':'Ambiance'});
 window.renderONELobby=({body,data,room,busy,command,el,btn,avatars,refresh})=>{
  if(salon!==room.id){salon=room.id;selected=games.some(g=>g.id===room.gameKind)?room.gameKind:'bluff';}const game=games.find(g=>g.id===selected),me=data.members.find(m=>m.isYou),readyCount=data.members.filter(m=>m.ready).length,canStart=data.members.length>=2&&readyCount===data.members.length&&data.members.length>=game.min&&data.members.length<=game.max;
  const lobby=el('div');lobby.className='pl-lobby';const intro=el('header');intro.className='pl-intro';intro.append(el('span','LE SALON ONE'),el('h3','Une table. Vos règles du jeu.'),el('p','Retrouve tes amis, choisis ton jeu et lance la soirée.'));
  const layout=el('div');layout.className='pl-layout';const catalog=el('section');catalog.className='pl-catalog';catalog.append(el('h3','À quoi joue-t-on ?'));const filters=el('div');filters.className='pl-filter';for(const label of ['Tous','Cartes','Réflexion','Ambiance']){const b=btn(label,()=>{filter=label;refresh();});b.setAttribute('aria-pressed',String(filter===label));filters.append(b);}catalog.append(filters);const cards=el('div');cards.className='pl-games';cards.setAttribute('role','group');cards.setAttribute('aria-label','Choisir un jeu');
  for(const g of games.filter(g=>filter==='Tous'||g.category===filter)){const card=btn('',()=>{selected=g.id;refresh();requestAnimationFrame(()=>document.querySelector('#onePartyGame .pl-setup')?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}));});card.className='pl-game';card.dataset.kind=g.id;card.disabled=busy;card.setAttribute('aria-pressed',String(selected===g.id));card.setAttribute('aria-label',g.name);const art=window.ONEGameArt(g.id);const check=el('span',selected===g.id?'✓ Sélectionné':'Découvrir');check.className='pl-selected';card.append(art,el('small',g.tag),el('strong',g.name),el('span',g.hint),check);cards.append(card);}catalog.append(cards);
  const detail=el('div');detail.className='pl-detail';detail.append(el('h4',game.name),el('p',game.desc),el('span',game.min+' à '+game.max+' joueurs · '+(data.isHost?'Tu choisis le jeu pour le groupe.':'Le créateur choisira le jeu au lancement.')));const setup=el('section');setup.className='pl-setup';setup.id='onePartySetup';const selectedCard=el('div');selectedCard.className='pl-selected-game';selectedCard.append(window.ONEGameArt(selected),detail);
  if(selected==='bluff'){const picker=el('div');picker.className='pl-avatars';picker.setAttribute('role','group');picker.setAttribute('aria-label','Ton personnage pour Bluff');const customize=el('details');customize.className='pl-customize';customize.append(el('summary','Choisir mon personnage'));setup.append(customize);for(const [id,name] of Object.entries(avatars)){const b=btn('',()=>command('avatar','&avatar='+id));b.disabled=busy;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String((me?.avatar||'croupier')===id));const img=el('img');img.src='assets/bluff/portraits/'+id+'.png';img.alt='';b.append(img,el('span',name));picker.append(b);}customize.append(picker);}
  const wager=el('section');wager.className='pl-wager';const amount=data.wager?.amount||0;wager.append(el('h3',amount?'Mise : '+amount+' Points ONE par joueur':'Partie gratuite'),el('p',selected==='poker'?'Au poker, cette mise devient ta réserve pour la main. Les mises et les pots sont répartis selon le résultat.':'La mise est réservée au lancement. Le pot revient aux gagnants ; les égalités partagent le pot. Une annulation rembourse chacun.'));if(data.isHost){const select=el('select');select.setAttribute('aria-label','Mise commune Party');for(const n of [0,10,50,100,500]){const o=el('option',n?n+' Points ONE':'Gratuit');o.value=n;select.append(o);}select.value=amount;select.disabled=busy;select.onchange=()=>command('stake','&amount='+select.value);wager.append(select);}wager.append(el('small','Toute modification de la mise annule les confirmations.'));setup.prepend(wager);const group=el('aside');group.className='pl-group';const groupHead=el('div');groupHead.className='pl-group-head';groupHead.append(el('h3','Autour de la table'),el('span',data.members.length+'/16'));group.append(groupHead,el('p',readyCount+' joueur'+(readyCount>1?'s':'')+' prêt'+(readyCount>1?'s':'')));
  for(const m of data.members){const row=el('div');row.className='pl-member';const avatar=el('span',m.name.trim().slice(0,1).toUpperCase()||'?');avatar.className='pl-initial';const meta=el('div');meta.append(el('b',m.name+(m.isYou?' · toi':'')),el('small',m.ready?'Prêt à jouer':'Se prépare…'));row.dataset.ready=String(m.ready);row.append(avatar,meta,el('span',m.ready?'✓':'·'));group.append(row);}const invite=btn('Ouvrir le salon · inviter',()=>window.oneOpenSalon?.());invite.className='pl-invite';group.append(invite);setup.append(group);layout.append(catalog);
  const launch=el('div');launch.className='pl-launch';const context=el('div');context.append(el('b',data.isHost?game.name:'Prêt pour la prochaine partie ?'),el('small',(data.members.length<game.min||data.members.length>game.max)?'Ce jeu demande '+game.min+' à '+game.max+' joueurs.':canStart?'Tout le monde est prêt !':'Chaque joueur doit confirmer qu’il est prêt.'));const actions=el('div');actions.className='pl-actions';const ready=btn(me?.ready?'✓ Prêt · annuler':data.wager?.amount?'Accepter '+data.wager.amount+' points et être prêt':'Je suis prêt',()=>command('ready','&ready='+(me?.ready?'0':'1')+'&stakeVersion='+(data.wager?.version||0)));ready.disabled=busy;ready.setAttribute('aria-pressed',String(!!me?.ready));actions.append(ready);if(data.isHost){const start=btn('Lancer '+game.name+' →',()=>command('start','&kind='+selected));start.className='pl-start';start.disabled=busy||!canStart;actions.append(start);}else actions.append(el('small','Le créateur lance la partie.'));launch.append(context,actions);setup.append(launch);lobby.append(setup,selectedCard,layout);body.append(lobby);
 };
})();
