(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev',panel=document.createElement('section');panel.id='onePartyGame';let room=null,data=null,busy=false,loading=false,version=0;
 const colors={red:'Rouge',blue:'Bleu',green:'Vert',yellow:'Jaune',wild:'Joker'},symbols={skip:'Passe',reverse:'Sens inverse',draw2:'+2',wild:'Joker'};
 const css=document.createElement('style');css.textContent='#onePartyGame{padding:14px;margin:14px 0;border:1px solid #70558b;background:#121729;border-radius:16px}#onePartyGame button,#onePartyGame select{padding:10px;margin:4px;border:1px solid #85679b;border-radius:10px;background:#493268;color:white}#onePartyGame button:disabled{opacity:.45}#onePartyGame .hand{display:flex;flex-wrap:wrap;gap:6px}#onePartyGame .gameCard{min-width:68px;min-height:96px;border:2px solid white;font-weight:bold}#onePartyGame [data-color=red]{background:#9f2234}#onePartyGame [data-color=blue]{background:#184b9e}#onePartyGame [data-color=green]{background:#1b6840}#onePartyGame [data-color=yellow]{background:#e6b92d;color:#17130b}#onePartyGame [data-color=wild]{background:linear-gradient(135deg,#6b207b,#165d87)}';document.head.append(css);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},btn=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};const status=el('p'),body=el('div');status.setAttribute('role','status');panel.append(el('h2','ONE Couleurs'),status,body);
 function visible(){return room&&!document.getElementById('oneFoundation')?.hidden&&document.querySelector('[data-one-space="party"]')?.getAttribute('aria-current')==='page';}
 function mount(){if(visible())document.getElementById('oneFoundation').append(panel);}
 async function api(action,method='GET',params=''){const token=oneAccountToken(),id=room?.id;if(!id)throw Error('Salon fermé.');const response=await fetch(API+'/party/game/'+action+'?room='+encodeURIComponent(id)+params,{method,headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000)});const result=await response.json().catch(()=>({}));if(room?.id!==id||token!==oneAccountToken())throw Error('Le salon ou le compte a changé.');if(!response.ok||!result.ok)throw Error(result.error||'Jeu indisponible.');return result;}
 async function command(action,params='',question){if(busy||question&&!confirm(question))return;busy=true;const own=version;body.querySelectorAll('button').forEach(b=>b.disabled=true);try{await api(action,'POST',params);if(own===version){status.textContent='';await load(true);}}catch(e){if(own===version){status.textContent=e.message;await load(true,true);}}finally{if(own===version){busy=false;render();}}}
 async function load(force=false,keepError=false){if(!room||loading||!force&&!visible())return;loading=true;const own=version;try{const fresh=await api('state');if(own!==version)return;const changed=JSON.stringify(data)!==JSON.stringify(fresh);data=fresh;if(changed)render();if(!keepError)status.textContent='';}catch(e){if(own===version)status.textContent=e.message;}finally{loading=false;}}
 function cardLabel(c){return colors[c.color]+' · '+(symbols[c.value]||c.value);}
 function render(){body.replaceChildren();if(!data)return;const g=data.game;if(!g){body.append(el('p','2 à 4 joueurs · chaque membre doit être prêt.'));const list=el('ul');for(const m of data.members)list.append(el('li',m.name+(m.isYou?' (toi)':'')+' · '+(m.ready?'Prêt':'Pas encore prêt')));body.append(list);const me=data.members.find(m=>m.isYou);const ready=btn(me?.ready?'Je ne suis plus prêt':'Je suis prêt',()=>command('ready','&ready='+(me?.ready?'0':'1')));ready.disabled=busy;body.append(ready);if(data.isHost){const start=btn('Lancer la partie',()=>command('start'));start.disabled=busy||data.members.length<2||data.members.some(m=>!m.ready);body.append(start);}}
  else{body.append(el('p',g.last));const list=el('ul');for(const p of g.players)list.append(el('li',p.name+(p.isYou?' (toi)':'')+' · '+p.count+' cartes'+(p.isTurn?' · À son tour':'')+(p.isWinner?' · Gagnant':'')));body.append(list);
   if(g.status==='playing'){body.append(el('p','Carte au centre : '+cardLabel(g.top)),el('p','Couleur active : '+colors[g.color]),el('strong',g.yourTurn?'À toi de jouer':'En attente du prochain tour'));const choice=el('select');choice.setAttribute('aria-label','Couleur à choisir pour un joker');for(const [value,label]of Object.entries(colors)){if(value==='wild')continue;const o=el('option',label);o.value=value;choice.append(o);}choice.value=g.color;const label=el('label','Couleur du joker ');label.append(choice);body.append(label);const hand=el('div');hand.className='hand';for(const c of g.hand){const b=btn(cardLabel(c),()=>command('play','&game='+g.id+'&revision='+g.revision+'&action=card&card='+encodeURIComponent(c.id)+'&color='+choice.value));b.className='gameCard';b.dataset.color=c.color;b.disabled=busy||!g.yourTurn||!(c.color==='wild'||c.color===g.color||c.value===g.top.value);hand.append(b);}body.append(hand);const draw=btn('Piocher et passer',()=>command('play','&game='+g.id+'&revision='+g.revision+'&action=draw'));draw.disabled=busy||!g.yourTurn;body.append(draw);}
   if(data.isHost){const reset=btn(g.status==='playing'?'Arrêter et revenir au salon':'Retour au salon pour rejouer',()=>command('reset','',g.status==='playing'?'Arrêter la partie pour tous les joueurs ?':null));reset.disabled=busy;body.append(reset);}else if(g.status!=='playing')body.append(el('p','Le créateur peut revenir au salon pour préparer une autre partie.'));
  }
  const rules=el('details');rules.append(el('summary','Règles'),el('p','Sept cartes chacun. Joue une carte de même couleur ou de même symbole que celle au centre. Sinon, pioche une carte et passe ton tour. Passe saute le joueur suivant ; +2 lui fait piocher deux cartes et saute son tour ; Sens inverse change le sens (à deux, tu rejoues). Le joker permet de choisir la couleur. Pas de cumul des +2. Le premier sans carte gagne. Si quelqu’un quitte le salon, la partie est interrompue.'));body.append(rules,btn('Actualiser le jeu',()=>load(true)));
 }
 window.addEventListener('one-party-state',e=>{if(room?.id!==e.detail?.id){version++;data=null;body.replaceChildren();status.textContent='';busy=false;}room=e.detail;if(room){mount();load();}else panel.remove();});window.addEventListener('one-space-open',()=>{mount();if(visible())load();});window.addEventListener('one-account-changed',()=>{version++;room=null;data=null;panel.remove();});setInterval(()=>{if(!document.hidden&&!busy)load();},2000);
})();
