(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-bluff.css?v=014117';document.head.append(css);const finish=document.createElement('link');finish.rel='stylesheet';finish.href='ui/bluff-polish.css?v=117y';document.head.append(finish);
 const ranks={A:'As',K:'Roi',Q:'Dame',J:'Joker'},symbols={A:'♠',K:'♚',Q:'♛',J:'✦'};let selection=new Set(),selectionKey='';
 // Keep counters live even when a stable table or cinematic skips a full render.
 function syncAttemptCounters(g){
  if(g?.kind!=='bluff'||g.rules!=='roulette'||!Array.isArray(g.players))return;
  for(const scene of document.querySelectorAll('#onePartyGame .bluff-scene')){
   if(scene.dataset.stableGame!==String(g.id))continue;
   for(const player of g.players){
    if(!Number.isInteger(player.shots)||player.shots<0||player.shots>6)continue;
    const seat=player.isYou?scene.querySelector('.bf-own'):[...scene.querySelectorAll('.bf-player:not(.bf-own)')].find(n=>n.dataset.owner===String(player.accountId));
    const counter=player.isYou?seat?.querySelector(':scope > small'):seat?.querySelector(':scope > .bf-attempts');
    if(!counter)continue;
    counter.textContent=player.shots+'/6';counter.classList.add('bf-attempts');counter.setAttribute('aria-label','Tentatives : '+player.shots+' sur 6');
   }
  }
 }
 window.addEventListener('one-game-clock',e=>syncAttemptCounters(e.detail?.game));
 window.ONEBluffRules='2 à 4 joueurs. Chaque manche distribue cinq cartes et impose As, Roi ou Dame. Pose une à trois cartes face cachée en prétendant qu’elles correspondent : les jokers sont toujours vrais. Le suivant joue à son tour ou dit « Tu mens ! » pour révéler uniquement la dernière annonce. Si elle est fausse, son auteur tente le barillet ; sinon, l’accusateur. Chaque joueur a six chambres dont une perdante, choisie au début par le serveur. Chaque tentative avance le barillet sans le remélanger. Le tir perdant élimine le personnage. Après chaque accusation, nouvelle distribution. Une main vide oblige à contester à son prochain tour. Le dernier joueur en lice gagne. Un départ du salon interrompt la partie.';
 function handCard(card,selected,disabled,el,click){const b=document.createElement('button');b.type='button';b.className='bluff-card';b.dataset.cardId=card.id;b.dataset.rank=card.rank;b.style.setProperty('--fan',(card.index-(card.total-1)/2)*9+'deg');b.style.setProperty('--rise',Math.abs(card.index-(card.total-1)/2)*4+'px');b.style.zIndex=String(card.index+1);b.setAttribute('aria-label',ranks[card.rank]);b.setAttribute('aria-pressed',String(selected));b.disabled=disabled;b.classList.toggle('selected',selected);b.onclick=click;b.append(el('small',ranks[card.rank]),el('strong',symbols[card.rank]),el('span',card.rank));return b;}
 window.renderONEBluff=({g,body,busy,command,el,btn})=>{
  const key=g.id+':'+g.round+':'+g.yourTurn+':'+g.hand.map(c=>c.id).join(',');if(key!==selectionKey){selection=new Set([...selection].filter(id=>g.hand.some(c=>c.id===id)));selectionKey=key;}
  let scene=body.querySelector('.bluff-scene'),area=body.querySelector('.bluff-controls');
  if(!scene){scene=el('div');scene.className='bluff-scene bf-premium';scene.dataset.stableGame=g.id;scene.setAttribute('aria-label','Table ONE Bluff');const round=el('div');round.className='bluff-round';const status=el('div');status.className='bluff-live-status';const badge=el('div');badge.className='bluff-target';badge.append(el('small'),el('strong'));scene.append(round,status,badge);const tableMark=el('div','ONE');tableMark.className='bf-table-mark';tableMark.setAttribute('aria-hidden','true');scene.append(tableMark);const center=el('div');center.className='bf-center';const deck=el('div','✦\nONE');deck.className='bf-deck';const pending=el('div');pending.className='bf-pending';const announcement=el('b');const turn=el('small');turn.className='bf-turn';const played=el('div');played.className='bf-played-cards';center.append(deck,played,pending,announcement,turn);scene.append(center);const hand=el('div');hand.className='bluff-hand';hand.setAttribute('aria-label','Tes cartes secrètes');scene.append(hand);const self=el('article');self.className='bf-player bf-own';const selfFace=el('div');selfFace.className='gt-portrait';selfFace.dataset.cameraSeat='local';self.append(selfFace,el('b'),el('small'));scene.append(self);area=el('div');area.className='bluff-controls';const actionRow=el('div');actionRow.className='bluff-actions';area.append(el('h3'),el('details'),actionRow);scene.append(area);const chatDock=el('div');chatDock.className='bluff-chat-dock';body.append(scene,chatDock);}else if(area&&area.parentElement!==scene){scene.append(area);}
  scene.classList.toggle('is-your-turn',!!g.yourTurn);scene.classList.toggle('has-reveal',!!g.reveal);scene.querySelector('.bluff-round').textContent='Manche '+String(g.round||1);const badge=scene.querySelector('.bluff-target');badge.querySelector('small').textContent=g.pending?g.pending.name+' annonce :':'La table demande :';badge.querySelector('strong').textContent=g.pending?g.pending.count+' × '+(ranks[g.target]||g.target):(symbols[g.target]||'✦')+' '+(ranks[g.target]||g.target);
  const me=g.players.find(p=>p.isYou),turnPlayer=g.players.find(p=>p.isTurn),live=scene.querySelector('.bluff-live-status');live.textContent=g.status==='finished'?(g.players.find(p=>p.isWinner)?.name||'')+' remporte la partie':g.status==='playing'?(g.yourTurn?'À toi de jouer':(turnPlayer?.name||'')+' joue'):'Partie interrompue';
  window.ONEPremiumTables.bluff(scene,g,el);
  const own=scene.querySelector('.bf-own'),face=own.querySelector('.gt-portrait');own.querySelector(':scope > b').textContent='Toi';own.querySelector(':scope > small').textContent=g.rules==='roulette'?(me?.shots||0)+'/6':'Toi · '+(me?.faults||0)+'/3 erreurs';
  own.querySelector(':scope > small').classList.add('bf-attempts');own.querySelector(':scope > small').setAttribute('aria-label','Tentatives : '+(me?.shots||0)+' sur 6');own.dataset.owner='local';own.dataset.eliminated=String(!!me?.eliminated);if(me?.eliminated){if(!own.dataset.frozen){const frozen=window.ONEPremiumTables.portrait(me,el);face.replaceWith(frozen);own.dataset.frozen='true';}}else if(!face.querySelector('.oneCamBubble')){face.replaceChildren();if(window.ONEUI)face.append(ONEUI.avatar(window.oneSocialRoom?.()?.members?.find(m=>m.accountId===me?.accountId)||me||{name:'Toi'}));else face.append(el('span',me?.name.slice(0,1)||'?'));face.dataset.cameraSeat='local';const mic=el('small','·');mic.className='gt-mic';mic.dataset.owner='local';face.append(mic);}
  const hand=scene.querySelector('.bluff-hand'),existing=new Map([...hand.querySelectorAll('.bluff-card')].map(n=>[n.dataset.cardId,n]));for(const [i,card]of g.hand.entries()){let b=existing.get(card.id);const selected=selection.has(card.id),disabled=busy||!g.yourTurn||(!selected&&selection.size>=3),click=()=>{if(selection.has(card.id))selection.delete(card.id);else if(selection.size<3)selection.add(card.id);syncHand();const playButton=area.querySelector('.bluff-play');if(playButton){playButton.textContent='Jouer cette combinaison';playButton.disabled=busy||!g.yourTurn||!selection.size;}};if(!b){b=handCard({...card,index:i,total:g.hand.length},selected,disabled,el,click);hand.append(b);}else{existing.delete(card.id);b.style.setProperty('--fan',(i-(g.hand.length-1)/2)*9+'deg');b.style.setProperty('--rise',Math.abs(i-(g.hand.length-1)/2)*4+'px');b.style.zIndex=String(i+1);b.setAttribute('aria-label',ranks[card.rank]);b.setAttribute('aria-pressed',String(selected));b.disabled=disabled;b.classList.toggle('selected',selected);b.onclick=click;const values=b.children;values[0].textContent=ranks[card.rank];values[1].textContent=symbols[card.rank];values[2].textContent=card.rank;}}
  for(const node of existing.values())node.remove();
  // Reused cards must follow server order: their fan angles are indexed by that order.
  for(const [i,card] of g.hand.entries()){
   const node=[...hand.children].find(n=>n.dataset.cardId===card.id);
   if(node&&hand.children[i]!==node)hand.insertBefore(node,hand.children[i]||null);
  }
  function syncHand(){for(const b of hand.querySelectorAll('.bluff-card')){const selected=selection.has(b.dataset.cardId);b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));b.disabled=busy||!g.yourTurn||(!selected&&selection.size>=3);}}
  const showActions=()=>{if(area.parentElement!==scene)scene.append(area);area.hidden=false;area.removeAttribute('hidden');area.style.setProperty('position','absolute','important');area.style.setProperty('display','flex','important');area.style.setProperty('left','4%','important');area.style.setProperty('right','3%','important');area.style.setProperty('bottom','8px','important');area.style.setProperty('width','auto','important');area.style.setProperty('height','58px','important');area.style.setProperty('min-height','58px','important');area.style.setProperty('margin','0','important');area.style.setProperty('padding','4px','important');area.style.setProperty('z-index','30','important');area.style.setProperty('background','transparent','important');area.style.setProperty('pointer-events','auto','important');const row=area.querySelector('.bluff-actions');row.hidden=false;row.style.setProperty('display','flex','important');row.style.setProperty('position','relative','important');row.style.setProperty('width','100%','important');row.style.setProperty('height','100%','important');row.style.setProperty('margin','0','important');row.style.setProperty('padding','0','important');row.style.setProperty('gap','8px','important');row.style.setProperty('align-items','center','important');row.style.setProperty('pointer-events','auto','important');const heading=area.querySelector('h3');if(heading)heading.hidden=true;};
  const title=area.querySelector('h3');title.textContent=g.status==='playing'?(g.yourTurn?'À toi de bluffer… ou de dénoncer.':(turnPlayer?.name||'Un joueur')+' joue'):g.status==='finished'?(g.players.find(p=>p.isWinner)?.name||'')+' remporte la partie !':'Partie interrompue';
  const details=area.querySelector('details');details.hidden=!g.reveal;details.replaceChildren();if(g.reveal){const summary=el('summary','Dernière révélation : '+(g.reveal.honest?'annonce vraie':'bluff découvert'));const result=el('p',g.reveal.name+' avait '+g.reveal.cards.map(c=>ranks[c]).join(', ')+' pour une table '+ranks[g.reveal.target]+'. '+g.reveal.penalized+' : '+(g.rules==='roulette'?(g.reveal.eliminated?'éliminé.':'survit ('+g.reveal.shots+'/6).'):g.reveal.faults+'/3 erreurs.'));const review=btn('Voir les cartes sur la table',()=>{window.ONEPremiumTables.proof(scene,g.reveal,el);});review.type='button';details.append(summary,result,review);}
  const actions=area.querySelector('.bluff-actions');actions.replaceChildren();const base='&game='+encodeURIComponent(g.id)+'&revision='+g.revision;
  if(g.status==='playing'){const play=btn('Jouer cette combinaison',async()=>{const cards=[...hand.querySelectorAll('.bluff-card')].filter(b=>selection.has(b.dataset.cardId)).map(b=>({node:b.cloneNode(true),rect:b.getBoundingClientRect()}));const target=scene.querySelector('.bf-center').getBoundingClientRect();const accepted=await command('play',base+'&action=bluff&cards='+encodeURIComponent([...selection].join(',')));if(!accepted||document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(const {node,rect}of cards){node.disabled=true;node.tabIndex=-1;node.setAttribute('aria-hidden','true');node.className='bluff-flying-card';Object.assign(node.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',zIndex:180,pointerEvents:'none'});document.body.append(node);const animation=node.animate([{transform:'translate3d(0,0,0) rotate(0deg)',opacity:1},{transform:'translate3d('+((target.left+target.width/2)-rect.left)+'px,'+((target.top+target.height*.55)-rect.top)+'px,0) scale(.24) rotate(100deg)',opacity:.15}],{duration:480,easing:'ease-in',fill:'forwards'});animation.finished.finally(()=>node.remove());}});play.className='bluff-play';play.disabled=busy||!g.yourTurn||!selection.size;actions.append(play);const accuse=btn('Accuser de bluff',()=>command('play',base+'&action=accuse'));accuse.className='bluff-accuse';accuse.textContent='Accuser de bluff';accuse.disabled=busy||!g.yourTurn||!g.pending;actions.append(accuse);if(g.yourTurn&&!g.hand.length)area.append(el('p','Ta main est vide : conteste la dernière annonce.'));}
  showActions();
  const center=scene.querySelector('.bf-center');center.querySelector('.bf-turn').textContent=g.yourTurn?'À TON TOUR':g.status==='playing'?(turnPlayer?.name||'')+' joue':'';const announcement=center.querySelector('b');announcement.textContent=g.pending?g.pending.name+' · '+g.pending.count+' '+({A:'As',K:'Rois',Q:'Dames'}[g.target]||g.target):g.yourTurn?'À toi de faire parler les cartes':'En attente';const round=scene.querySelector('.bluff-round');round.title='Manche '+(g.round||1);const status=scene.querySelector('.bluff-live-status');status.textContent=g.yourTurn?'À toi · joue ou accuse':(turnPlayer?.name||'')+' joue';
  syncHand();window.ONEBluffSound.effect?.(g,1);window.dispatchEvent(new Event('one-game-rendered'));
 };
})();
