(()=>{
 const sheet=document.createElement('link');sheet.rel='stylesheet';sheet.href='ui/party-lobby.css?v=01476';document.head.append(sheet);
 let selected='bluff',salon='';
 const games=[{id:'bluff',name:'ONE Bluff',tag:'BLUFF & TENSION',symbol:'♠',desc:'Garde ton sang-froid. Pose tes cartes, trompe tes adversaires et démasque leurs mensonges.',hint:'Cartes cachées · Personnages 3D',cards:['A','K','Q']},{id:'colors',name:'ONE Couleurs',tag:'RAPIDE & MALIN',symbol:'↔',desc:'La bonne couleur, le bon symbole. Débarrasse-toi de tes cartes avant les autres.',hint:'Couleurs · Cartes spéciales',cards:['7','+2','4']},{id:'douze',name:'ONE Douze',tag:'OBSERVATION & STRATÉGIE',symbol:'12',desc:'Révèle ta grille, échange tes cartes et vise le plus petit score.',hint:'12 cartes · Le moins de points',cards:['−2','0','12']}];
 window.renderONELobby=({body,data,room,busy,command,el,btn,avatars,refresh})=>{
  if(salon!==room.id){salon=room.id;selected='bluff';}const game=games.find(g=>g.id===selected),me=data.members.find(m=>m.isYou),readyCount=data.members.filter(m=>m.ready).length,canStart=data.members.length>=2&&readyCount===data.members.length;
  const lobby=el('div');lobby.className='pl-lobby';const intro=el('header');intro.className='pl-intro';intro.append(el('span','LE SALON ONE'),el('h3','Une table. Vos règles du jeu.'),el('p','Retrouve tes amis, choisis ton jeu et lance la soirée.'));lobby.append(intro);
  const layout=el('div');layout.className='pl-layout';const catalog=el('section');catalog.className='pl-catalog';catalog.append(el('h3','À quoi joue-t-on ?'));const cards=el('div');cards.className='pl-games';cards.setAttribute('role','group');cards.setAttribute('aria-label','Choisir un jeu');
  for(const g of games){const card=btn('',()=>{selected=g.id;refresh();});card.className='pl-game';card.dataset.kind=g.id;card.disabled=busy;card.setAttribute('aria-pressed',String(selected===g.id));card.setAttribute('aria-label',g.name);const art=el('span');art.className='pl-art';art.setAttribute('aria-hidden','true');for(const [i,value] of g.cards.entries()){const tile=el('i',value);tile.style.setProperty('--i',i);art.append(tile);}const check=el('span',selected===g.id?'✓ Sélectionné':'Découvrir');check.className='pl-selected';card.append(art,el('small',g.tag),el('strong',g.name),el('span',g.hint),check);cards.append(card);}catalog.append(cards);
  const detail=el('div');detail.className='pl-detail';detail.append(el('h4',game.name),el('p',game.desc),el('span','2 à 4 joueurs · '+(data.isHost?'Tu choisis le jeu pour le groupe.':'Le créateur choisira le jeu au lancement.')));catalog.append(detail);
  if(selected==='bluff'){const picker=el('div');picker.className='pl-avatars';picker.setAttribute('role','group');picker.setAttribute('aria-label','Ton personnage pour Bluff');catalog.append(el('h4','Ton personnage pour Bluff'));for(const [id,name] of Object.entries(avatars)){const b=btn('',()=>command('avatar','&avatar='+id));b.disabled=busy;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String((me?.avatar||'croupier')===id));const img=el('img');img.src='assets/bluff/portraits/'+id+'.png';img.alt='';b.append(img,el('span',name));picker.append(b);}catalog.append(picker);}
  const group=el('aside');group.className='pl-group';const groupHead=el('div');groupHead.className='pl-group-head';groupHead.append(el('h3','Autour de la table'),el('span',data.members.length+'/4'));group.append(groupHead,el('p',readyCount+' joueur'+(readyCount>1?'s':'')+' prêt'+(readyCount>1?'s':'')));
  for(const m of data.members){const row=el('div');row.className='pl-member';const avatar=el('span',m.name.trim().slice(0,1).toUpperCase()||'?');avatar.className='pl-initial';const meta=el('div');meta.append(el('b',m.name+(m.isYou?' · toi':'')),el('small',m.ready?'Prêt à jouer':'Se prépare…'));row.dataset.ready=String(m.ready);row.append(avatar,meta,el('span',m.ready?'✓':'·'));group.append(row);}for(let i=data.members.length;i<4;i++){const slot=el('div','+  Place disponible');slot.className='pl-empty';group.append(slot);}const invite=btn('Ouvrir le salon · inviter',()=>window.oneOpenSalon?.());invite.className='pl-invite';group.append(invite);layout.append(catalog,group);lobby.append(layout);
  const launch=el('div');launch.className='pl-launch';const context=el('div');context.append(el('b',data.isHost?game.name:'Prêt pour la prochaine partie ?'),el('small',data.members.length<2?'Invite au moins un ami pour commencer.':canStart?'Tout le monde est prêt !':'Chaque joueur doit confirmer qu’il est prêt.'));const actions=el('div');actions.className='pl-actions';const ready=btn(me?.ready?'✓ Prêt · annuler':'Je suis prêt',()=>command('ready','&ready='+(me?.ready?'0':'1')));ready.disabled=busy;ready.setAttribute('aria-pressed',String(!!me?.ready));actions.append(ready);if(data.isHost){const start=btn('Lancer '+game.name+' →',()=>command('start','&kind='+selected));start.className='pl-start';start.disabled=busy||!canStart;actions.append(start);}else actions.append(el('small','Le créateur lance la partie.'));launch.append(context,actions);lobby.append(launch);body.append(lobby);
 };
})();
