(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-douze.css?v=01476';document.head.append(css);
 let choice='replace',choiceKey='';
 window.ONEDouzeRules='Révèle deux cartes de ta grille. À ton tour, prends la défausse et remplace une carte, ou pioche : garde la carte en échange d’une des tiennes, ou défausse-la puis révèle une carte cachée. Trois cartes identiques dans une colonne sont retirées. Quand un joueur a tout révélé, les autres jouent un dernier tour. Les cartes restantes sont révélées puis comptées. Celui qui termine double ses points de manche s’ils sont positifs et qu’il n’a pas seul le plus petit score. À partir de 100 points cumulés pour un joueur, le plus petit total gagne. Le premier tour revient à la plus forte somme révélée (égalité tirée au sort) ; les manches suivantes commencent par celui qui a terminé la précédente.';
 window.renderONEDouze=({g,body,busy,command,el,btn,isHost})=>{
  const key=g.id+':'+g.revision;if(choiceKey!==key){choiceKey=key;choice='replace';}
  const me=g.players.find(p=>p.isYou),active=g.status==='playing',setup=active&&g.phase==='setup',ended=['round-end','finished'].includes(g.phase);
  const play=(action,slot)=>command('play','&game='+encodeURIComponent(g.id)+'&revision='+g.revision+'&action='+action+(slot===undefined?'':'&slot='+slot));
  const root=el('div');root.className='dz-game';body.append(root);
  const heading=el('div');heading.className='dz-heading';heading.append(el('span','MANCHE '+g.round),el('span','Objectif : le moins de points'));
  const instruction=el('p');instruction.className='dz-instruction';instruction.setAttribute('role','status');
  const turn=g.players.find(p=>p.isTurn);
  instruction.textContent=!active?(g.status==='cancelled'?g.last:'Partie terminée'):setup?(me.flipped<2?'Retourne '+(2-me.flipped)+' carte'+(me.flipped===0?'s':'')+' de ta grille.':'Tes deux cartes sont prêtes. Attendons les autres joueurs.'):ended?'Les points de la manche sont comptés.':g.yourTurn?(g.drawn?'Choisis une carte de ta grille à remplacer.':'À toi : pioche ou prends la défausse.'):(turn?.name||'Un joueur')+' joue…';
  root.append(heading,instruction);
  if(g.ender&&!ended){const ender=g.players.find(p=>p.accountId===g.ender);root.append(el('p',(ender?.name||'Un joueur')+' a terminé : dernier tour pour les autres joueurs.'));}
  function card(value,hidden,onClick,label){const c=onClick?btn('',onClick):el('div');c.className='dz-card';c.dataset.tone=hidden?'back':value<0?'negative':value===0?'zero':value<=4?'low':value<=8?'mid':'high';c.setAttribute('aria-label',label||String(value));c.append(el('small',hidden?'ONE':String(value)),el('strong',hidden?'?':String(value)),el('small',hidden?'DOUZE':String(value)));return c;}
  const rivals=el('div');rivals.className='dz-rivals';
  function grid(p,own){const seat=el('section');seat.className='dz-seat'+(own?' dz-own':'')+(p.isTurn?' dz-current':'');seat.append(el('h3',p.name+(own?' · toi':'')));const scores=el('div');scores.className='dz-scores';const total=el('span');total.append(el('small','TOTAL'),el('b',String(p.total)));const visible=el('span');visible.append(el('small','POINTS VISIBLES'),el('b',String(p.visibleScore)));scores.append(total,visible);seat.append(scores);const board=el('div');board.className='dz-grid';board.setAttribute('aria-label','Grille de '+p.name);for(const c of p.grid){if(c.removed){const empty=el('div','—');empty.className='dz-empty';empty.setAttribute('aria-label','Colonne retirée');board.append(empty);continue;}const label='Ligne '+(Math.floor(c.index/4)+1)+', colonne '+(c.index%4+1)+' : '+(c.open?c.value:'cachée');const b=card(c.value,!c.open,own?()=>play(setup?'reveal':choice,c.index):null,label);if(own)b.disabled=busy||!active||!(setup?me.flipped<2&&!c.open:g.yourTurn&&g.drawn&&(choice==='replace'||!c.open));board.append(b);}seat.append(board);if(setup)seat.append(el('small',p.flipped+'/2 cartes retournées'));return seat;}
  for(const p of g.players.filter(p=>!p.isYou))rivals.append(grid(p,false));root.append(rivals);
  if(active&&!ended&&!setup){const center=el('div');center.className='dz-center';const deck=card(null,true,()=>play('draw'),'Piocher une carte');deck.disabled=busy||!g.yourTurn||g.phase!=='turn';const deckBox=el('div');deckBox.append(el('b','Pioche'),deck,el('small',g.deckCount+' cartes'));const pile=card(g.discard,g.discard===null,()=>play('take-discard'),'Prendre la défausse : '+g.discard);pile.disabled=busy||!g.yourTurn||g.phase!=='turn'||g.discard===null;const pileBox=el('div');pileBox.append(el('b','Défausse'),pile);center.append(deckBox,pileBox);
   if(g.drawn){const held=el('div');held.className='dz-held';held.append(el('b',g.drawn.source==='deck'?'Ta pioche · privée':'Carte choisie'),card(g.drawn.value,false));center.append(held);}root.append(center);
   if(g.drawn&&g.yourTurn){const modes=el('div');modes.className='dz-modes';const keep=btn('Garder et remplacer',()=>select('replace'));const reject=btn('Défausser et révéler',()=>select('discard-reveal'));keep.disabled=busy;reject.disabled=busy||g.drawn.source!=='deck'||!me.grid.some(c=>!c.removed&&!c.open);modes.append(keep,reject);root.append(modes);function select(mode){choice=mode;root.remove();window.renderONEDouze({g,body,busy,command,el,btn,isHost});body.insertBefore(body.lastChild,body.querySelector('#oneGameCallDock')||null);}keep.setAttribute('aria-pressed',String(choice==='replace'));reject.setAttribute('aria-pressed',String(choice==='discard-reveal'));instruction.textContent=choice==='replace'?'Touche une carte de ta grille pour la remplacer.':'Touche une carte cachée : elle sera révélée et ta pioche sera défaussée.';}
  }
  if(me)root.append(grid(me,true));
  if(ended){const result=el('section');result.className='dz-result';const names=g.players.filter(p=>p.isWinner).map(p=>p.name);result.append(el('h3',g.phase==='finished'?(names.join(' et ')+(names.length>1?' remportent':' remporte')+' la partie !'):'Résultat de la manche '+g.round));const table=el('table'),head=el('tr');for(const name of ['Joueur','Manche','Total'])head.append(el('th',name));table.append(head);for(const p of g.players){const tr=el('tr');tr.append(el('td',p.name),el('td',p.roundScore+(p.doubled?' (doublé)':'')),el('td',String(p.total)));table.append(tr);}result.append(table);if(g.phase==='round-end'&&active){const next=btn(isHost?'Manche suivante →':'Le créateur lance la prochaine manche',()=>play('next-round'));next.disabled=busy||!isHost;result.append(next);}root.append(result);}
 };
})();
