(()=>{
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-bluff.css?v=01472';document.head.append(css);
 const ranks={A:'As',K:'Roi',Q:'Dame',J:'Joker'},symbols={A:'♠',K:'♚',Q:'♛',J:'✦'};let selection=new Set(),selectionKey='';
 window.ONEBluffRules='2 à 4 joueurs. Chaque manche distribue cinq cartes et impose As, Roi ou Dame. Pose une à trois cartes face cachée en prétendant qu’elles correspondent : les jokers sont toujours vrais. Le suivant joue à son tour ou dit « Tu mens ! » pour révéler uniquement la dernière annonce. Si elle est fausse, son auteur tente le barillet ; sinon, l’accusateur. Chaque joueur a six chambres dont une perdante, choisie au début par le serveur. Chaque tentative avance le barillet sans le remélanger. Le tir perdant élimine le personnage. Après chaque accusation, nouvelle distribution. Une main vide oblige à contester à son prochain tour. Le dernier joueur en lice gagne. Un départ du salon interrompt la partie.';
 window.renderONEBluff=({g,body,busy,command,el,btn})=>{
  const key=g.id+':'+g.round+':'+g.yourTurn+':'+g.hand.map(c=>c.id).join(',');if(key!==selectionKey){selection=new Set();selectionKey=key;}
  const scene=el('div');scene.className='bluff-scene';const badge=el('div');badge.className='bluff-target';badge.append(el('small','MANCHE '+g.round+' · LA TABLE DEMANDE'),el('strong',symbols[g.target]+' '+ranks[g.target]));scene.append(badge);const sound=el('button','Activer le son');sound.type='button';sound.className='bluff-sound';sound.textContent=window.ONEBluffSound?.enabled()?'Son : activé':'Activer le son';sound.onclick=()=>{const on=window.ONEBluffSound?.toggle();sound.textContent=on?'Son : activé':'Son : coupé';sound.setAttribute('aria-pressed',String(on));};scene.append(sound);body.append(scene);
  window.ONEBluffScene(scene,g.players,g.pending,g);if(g.rules==='roulette'&&g.reveal){const result=el('div');result.className='bluff-shot-result';result.append(el('b',g.reveal.penalized+' · '+(g.reveal.eliminated?'ÉLIMINÉ':'CLIC · EN JEU')),el('small','Tentative '+g.reveal.shots+' / 6'));scene.append(result);}
  if(!scene.querySelector('.bluff-person')){const fallback=el('div');fallback.className='bluff-fallback-players';for(const p of g.players.filter(p=>!p.isYou)){const face=el('div');face.className='cg-face';face.dataset.cameraSeat=p.accountId;face.append(el('span',p.name.slice(0,1)));const label=el('div',p.name+' · '+(p.eliminated?'Éliminé':(p.shots||0)+'/6 tentatives'));label.append(face);fallback.append(label);}scene.append(fallback);}
  const hint=el('span','Glisse sur le décor pour regarder autour');hint.className='bluff-look';scene.append(hint);
  const area=el('div');area.className='bluff-controls';const me=g.players.find(p=>p.isYou);const self=el('div');self.className='bluff-self';const face=el('div');face.className='cg-face';face.dataset.cameraSeat='local';face.append(el('span',me?.name.slice(0,1)||'?'));self.append(face,el('small','Toi · '+(g.rules==='roulette'?(me?.shots||0)+'/6':(me?.faults||0)+'/3 erreurs')));area.append(self);
  const turn=el('h3',g.status==='playing'?(g.yourTurn?'À toi de bluffer… ou de dénoncer.':(g.players.find(p=>p.isTurn)?.name||'Un joueur')+' joue'):g.status==='finished'?(g.players.find(p=>p.isWinner)?.name||'')+' remporte la partie !':'Partie interrompue');area.append(turn);
  if(g.reveal){const r=el('details');r.className='bluff-reveal';r.append(el('summary','Dernière révélation : '+(g.reveal.honest?'annonce vraie':'bluff découvert')),el('p',g.reveal.name+' avait '+g.reveal.cards.map(c=>ranks[c]).join(', ')+' pour une table '+ranks[g.reveal.target]+'. '+g.reveal.penalized+' : '+(g.rules==='roulette'?(g.reveal.eliminated?'éliminé.':'survit ('+g.reveal.shots+'/6).'):g.reveal.faults+'/3 erreurs.')));const review=el('button','Voir les cartes sur la table');review.type='button';review.onclick=()=>{scene.dispatchEvent(new Event('one-review-proof'));scene.scrollIntoView({block:'nearest',behavior:'smooth'});};r.append(review);area.append(r);}
  if(g.status==='playing'){
   if(me?.eliminated)area.append(el('p','Tu es éliminé. Tu peux suivre la fin de la partie.'));
   const hand=el('div');hand.className='bluff-hand';hand.setAttribute('aria-label','Tes cartes secrètes');const cardButtons=[];
   const actions=el('div');actions.className='bluff-actions';const base='&game='+encodeURIComponent(g.id)+'&revision='+g.revision;
   const play=btn('Choisis 1 à 3 cartes',async()=>{const modeled=scene.classList.contains('bluff-model-ready');const cards=cardButtons.filter(([id])=>selection.has(id)).map(([,b])=>({node:b.cloneNode(true),rect:b.getBoundingClientRect()})),target=scene.getBoundingClientRect();const accepted=await command('play',base+'&action=bluff&cards='+encodeURIComponent([...selection].join(',')));if(modeled||!accepted||document.hidden||matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(const {node,rect}of cards){node.disabled=true;node.tabIndex=-1;node.setAttribute('aria-hidden','true');node.className='bluff-flying-card';Object.assign(node.style,{position:'fixed',left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',zIndex:180,pointerEvents:'none'});document.body.append(node);const anim=node.animate([{transform:'translate(0,0) rotate(0deg)',opacity:1},{transform:'translate('+((target.left+target.width/2)-rect.left)+'px,'+((target.top+target.height*.58)-rect.top)+'px) scale(.22) rotate(110deg)',opacity:.2}],{duration:550,easing:'ease-in',fill:'forwards'});anim.finished.finally(()=>node.remove());}});
   const accuse=btn('Tu mens !',()=>command('play',base+'&action=accuse'));accuse.className='bluff-accuse';accuse.disabled=busy||!g.yourTurn||!g.pending;
   function sync(){play.disabled=busy||!g.yourTurn||selection.size===0;play.textContent=selection.size?'Annoncer '+selection.size+' '+ranks[g.target]+(selection.size>1&&g.target!=='A'?'s':''):'Choisis 1 à 3 cartes';for(const [id,b]of cardButtons){b.classList.toggle('selected',selection.has(id));b.setAttribute('aria-pressed',String(selection.has(id)));b.disabled=busy||!g.yourTurn||(!selection.has(id)&&selection.size>=3);}}
   for(const card of g.hand){const b=btn('',()=>{if(selection.has(card.id))selection.delete(card.id);else if(selection.size<3)selection.add(card.id);sync();});b.className='bluff-card';const index=g.hand.indexOf(card)-(g.hand.length-1)/2;b.style.setProperty('--fan',index*10+'deg');b.style.setProperty('--rise',Math.abs(index)*5+'px');b.style.zIndex=String(g.hand.indexOf(card)+1);b.setAttribute('aria-label',ranks[card.rank]);b.append(el('small',ranks[card.rank]),el('strong',symbols[card.rank]),el('span',card.rank));hand.append(b);cardButtons.push([card.id,b]);}
   sync();scene.append(hand);actions.append(play,accuse);area.append(actions);if(g.yourTurn&&!g.hand.length)area.append(el('p','Ta main est vide : conteste la dernière annonce.'));
  }body.append(area);
 };
})();
