(()=>{
 const API='https://one-comments-api.moulinanthony60.workers.dev',panel=document.createElement('section');panel.id='onePartyGame';let room=null,data=null,busy=false,loading=false,version=0;
 const avatars={croupier:'La Revenante',renard:'Remy',corbeau:'Agent 09',chasseur:'Le Parasite'};
 const colors={red:'Rouge',blue:'Bleu',green:'Vert',yellow:'Jaune',wild:'Joker'},symbols={skip:'Passe',reverse:'Sens inverse',draw2:'+2',wild:'Joker'};
 const css=document.createElement('link');css.rel='stylesheet';css.href='ui/party-game.css?v=01475';document.head.append(css);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;},btn=(text,fn)=>{const b=el('button',text);b.type='button';b.dataset.gameControl='true';b.onclick=fn;return b;};const status=el('p'),body=el('div');status.setAttribute('role','status');panel.append(el('h2','ONE Couleurs'),status,body);
 function visible(){return !document.getElementById('oneFoundation')?.hidden&&document.querySelector('[data-one-space="party"]')?.getAttribute('aria-current')==='page';}
 function mount(){if(visible()){const shell=document.getElementById('oneFoundation');if(panel.parentNode!==shell)shell.replaceChildren(panel);if(!data)render();}}window.onePartyGameVisible=visible;
 async function api(action,method='GET',params=''){const token=oneAccountToken(),id=room?.id;if(!id)throw Error('Salon fermé.');const response=await fetch(API+'/party/game/'+action+'?room='+encodeURIComponent(id)+params,{method,headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000)});const result=await response.json().catch(()=>({}));if(room?.id!==id||token!==oneAccountToken())throw Error('Le salon ou le compte a changé.');if(!response.ok||!result.ok)throw Error(result.error||'Jeu indisponible.');return result;}
 async function command(action,params='',question){if(busy||question&&!confirm(question))return;busy=true;const own=version;body.querySelectorAll('button[data-game-control]').forEach(b=>b.disabled=true);try{await api(action,'POST',params);if(own===version){status.textContent='';await load(true);return true;}}catch(e){if(own===version){status.textContent=e.message;await load(true,true);}}finally{if(own===version){busy=false;render();}}}
 async function load(force=false,keepError=false){if(!room||loading||!force&&!visible())return;loading=true;const own=version;try{const fresh=await api('state');if(own!==version)return;const changed=JSON.stringify(data)!==JSON.stringify(fresh);if(fresh.game?.status==='playing'&&fresh.game.id!==data?.game?.id){full=true;panel.classList.add('gameFullscreen');document.body.classList.add('oneGameFullscreen');}data=fresh;if(changed)render();if(!keepError)status.textContent='';}catch(e){if(own===version)status.textContent=e.message;}finally{loading=false;}}
 function cardLabel(c){return colors[c.color]+' · '+(symbols[c.value]||c.value);}
 let full=false,joker=null,lastTop='',topUntil=0,lastHand=null;const drawnUntil=new Map();
 function fullscreen(on){full=on;panel.classList.toggle('gameFullscreen',on);document.body.classList.toggle('oneGameFullscreen',on);render();}
 function graphic(c,interactive=false,fn){const node=interactive?btn('',fn):el('div');node.className='cg-card';node.dataset.color=c.color;node.setAttribute('aria-label',cardLabel(c));const value=symbols[c.value]||c.value,short={skip:'⊘',reverse:'⇄',draw2:'+2',wild:'✦'}[c.value]||c.value;node.append(el('span',short),el('strong',short),el('small',value));return node;}
 function seat(p){const s=el('div');s.className='cg-seat'+(p.isTurn?' current':'')+(p.isWinner?' winner':'');const avatar=el('span',p.name.trim().slice(0,1).toUpperCase()||'?');avatar.className='cg-avatar';const meta=el('div');meta.append(el('b',p.name+(p.isYou?' · toi':'')),el('small',p.isWinner?'Victoire !':p.isTurn?'À son tour':p.count+' cartes'));const face=el('div');face.className='cg-face';face.dataset.cameraSeat=p.isYou?'local':p.accountId||'';face.append(avatar);s.append(face,meta);const backs=el('span');backs.className='cg-backs';backs.setAttribute('aria-label',p.count+' cartes');for(let i=0;i<Math.min(p.count,5);i++)backs.append(el('i'));s.append(backs);return s;}
 function render(){window.dispatchEvent(new Event('one-game-before-render'));body.replaceChildren();if(!data){body.append(el('h2','Les jeux ONE'),el('p',room?'Chargement des jeux…':'Rejoins ou crée un salon pour jouer avec tes amis.'),btn('Ouvrir Salons',()=>window.oneOpenSalon?.()));return;}const g=data.game;panel.classList.toggle('hasGame',!!g);panel.classList.toggle('isBluff',g?.kind==='bluff');panel.classList.toggle('isDouze',g?.kind==='douze');const topbar=el('div');topbar.className='cg-topbar';const brand=el('div');brand.append(el('small','PARTY / JEU DE CARTES'),el('h2',g?.kind==='douze'?'ONE Douze':g?.kind==='bluff'?'ONE Bluff':g?'ONE Couleurs':'Les jeux ONE'));const tools=el('div');tools.className='cg-tools';tools.append(btn(full?'↙ Réduire':'⛶ Plein écran',()=>fullscreen(!full)));topbar.append(brand,tools);body.append(topbar);
 if(!g){const lobby=el('div');lobby.className='cg-lobby';lobby.append(el('span','✦'),el('h3','Couleurs, Bluff ou Douze : à vous de jouer.'),el('p','2 à 4 joueurs · le créateur choisit le jeu après les confirmations'));const list=el('div');list.className='cg-readyList';for(const m of data.members){const p=el('div');p.append(el('b',m.name+(m.isYou?' · toi':'')+' · '+(avatars[m.avatar]||avatars.croupier)),el('span',m.ready?'✓ Prêt':'En attente'));p.dataset.ready=String(m.ready);list.append(p);}lobby.append(list);const me=data.members.find(m=>m.isYou);const picker=el('div');picker.className='cg-avatar-picker';picker.setAttribute('role','group');picker.setAttribute('aria-label','Choisis ton personnage');for(const [id,label]of Object.entries(avatars)){const pick=btn('',()=>command('avatar','&avatar='+id));pick.className='cg-avatar';pick.setAttribute('aria-pressed',String((me?.avatar||'croupier')===id));pick.setAttribute('aria-label',label);pick.disabled=busy;const portrait=el('img');portrait.src='assets/bluff/portraits/'+id+'.png';portrait.alt='';pick.append(portrait,el('b',label));picker.append(pick);}lobby.append(el('h3','Choisis ton personnage'),picker,el('p','Choisis ton personnage, puis confirme que tu es prêt.'));const ready=btn(me?.ready?'Annuler · Prêt':'Je suis prêt',()=>command('ready','&ready='+(me?.ready?'0':'1')));ready.className='cg-primary';ready.disabled=busy;lobby.append(ready);if(data.isHost){const start=btn('Lancer ONE Couleurs →',()=>command('start','&kind=colors'));start.className='cg-primary';start.disabled=busy||data.members.length<2||data.members.some(m=>!m.ready);lobby.append(start);const bluff=btn('Lancer ONE Bluff 3D →',()=>command('start','&kind=bluff'));bluff.className='cg-primary';bluff.disabled=start.disabled;lobby.append(bluff);const douze=btn('Lancer ONE Douze →',()=>command('start','&kind=douze'));douze.className='cg-primary';douze.disabled=start.disabled;lobby.append(douze,el('p','Douze : une grille de 12 cartes, le plus petit score gagne.')); lobby.append(el('p','Bluff : cartes cachées, accusations et barillet virtuel à six chambres.'));}body.append(lobby);
 }else if(g.kind==='douze'){window.renderONEDouze({g,body,busy,command,el,btn,isHost:data.isHost});}else if(g.kind==='bluff'){window.renderONEBluff({g,body,busy,command,el,btn});}else{
  const table=el('div');table.className='cg-table';const surface=el('div');surface.className='cg-surface';surface.setAttribute('aria-hidden','true');surface.append(el('span','ONE'));table.append(surface);const opponents=el('div');opponents.className='cg-opponents';const rivals=g.players.filter(p=>!p.isYou);opponents.dataset.count=rivals.length;for(const p of rivals)opponents.append(seat(p));table.append(opponents);
  const center=el('div');center.className='cg-center';const turn=el('div',g.status==='playing'?(g.yourTurn?'À TOI DE JOUER':(g.players.find(p=>p.isTurn)?.name||'Adversaire')+' JOUE'):g.status==='finished'?'PARTIE TERMINÉE':'PARTIE INTERROMPUE');turn.className='cg-turn'+(g.yourTurn?' yours':'');center.append(turn);
  const stacks=el('div');stacks.className='cg-stacks';const pile=btn('',()=>command('play','&game='+g.id+'&revision='+g.revision+'&action=draw'));pile.className='cg-deck';pile.setAttribute('aria-label','Piocher une carte et passer ton tour');pile.disabled=busy||!g.yourTurn||g.status!=='playing';if(g.pendingDraw)pile.setAttribute('aria-label','Piocher '+g.pendingDraw+' cartes et passer ton tour');pile.append(el('small','ONE'),el('strong','✦'),el('span',g.pendingDraw?'PIOCHER '+g.pendingDraw:'PIOCHER'));const discard=graphic(g.top);discard.classList.add('cg-discard');if(lastTop!==g.top.id){topUntil=Date.now()+350;lastTop=g.top.id;}if(Date.now()<topUntil)discard.classList.add('cg-dealt');stacks.append(pile,discard);center.append(stacks);const color=el('span','Couleur · '+colors[g.color]);color.className='cg-color';color.dataset.color=g.color;center.append(color,el('p',g.last));table.append(center);body.append(table);
  if(g.status==='playing'){
   const area=el('div');area.className='cg-playerArea';const head=el('div');head.className='cg-handHead';head.append(el('b','TA MAIN'),el('span',g.hand.length+' cartes · '+(g.yourTurn?'Touche une carte lumineuse':'Patiente, ton tour arrive')));const me=g.players.find(p=>p.isYou);if(me){const self=seat(me);self.classList.add('cg-self');area.append(self);}area.append(head);
   if(joker&&!g.hand.some(c=>c.id===joker)&&g.yourTurn)joker=null;if(!g.yourTurn)joker=null;
   if(joker){const choices=el('div');choices.className='cg-jokerChoice';choices.append(el('b','Choisis ta couleur'));for(const [key,label]of Object.entries(colors)){if(key==='wild')continue;const pick=btn(label,()=>{const id=joker;joker=null;command('play','&game='+g.id+'&revision='+g.revision+'&action=card&card='+encodeURIComponent(id)+'&color='+key);});pick.dataset.color=key;pick.disabled=busy;choices.append(pick);}choices.append(btn('Annuler',()=>{joker=null;render();}));area.append(choices);}
   const currentIds=new Set(g.hand.map(c=>c.id));if(lastHand)for(const id of currentIds)if(!lastHand.has(id))drawnUntil.set(id,Date.now()+400);lastHand=currentIds;const hand=el('div');hand.className='cg-hand';hand.setAttribute('aria-label','Tes cartes');hand.style.setProperty('--card-count',g.hand.length);for(let i=0;i<g.hand.length;i++){const c=g.hand[i],legal=g.pendingDraw?c.value==='draw2':c.color==='wild'||c.color===g.color||c.value===g.top.value;const b=graphic(c,true,()=>{if(c.color==='wild'){joker=c.id;render();}else command('play','&game='+g.id+'&revision='+g.revision+'&action=card&card='+encodeURIComponent(c.id)+'&color='+g.color);});if((drawnUntil.get(c.id)||0)>Date.now())b.classList.add('cg-drawn');b.disabled=busy||!g.yourTurn||!legal;b.classList.toggle('playable',!b.disabled);const tilt=Math.max(-9,Math.min(9,(i-(g.hand.length-1)/2)*3));b.style.setProperty('--tilt',tilt+'deg');hand.append(b);}area.append(hand);body.append(area);
  }else{const result=el('div');result.className='cg-result';result.append(el('strong',g.status==='finished'?'✦ '+(g.players.find(p=>p.isWinner)?.name||'')+' remporte la partie':'Le groupe a changé.'),el('p','Retrouve le salon pour préparer la prochaine partie.'));body.append(result);}
 }
 if(g&&g.status!=='playing'){const endActions=el('div');endActions.className='cg-end-actions';const again=btn(data.isHost?'Rejouer':'Le créateur peut relancer',()=>command('reset'));again.disabled=busy||!data.isHost;again.className='cg-primary';const back=btn('Retour au salon',()=>{if(full)fullscreen(false);window.oneOpenSalon?.();});endActions.append(again,back);body.append(endActions);}
 const callDock=el('div');callDock.id='oneGameCallDock';body.append(callDock);const footer=el('div');footer.className='cg-footer';const rules=el('details');rules.append(el('summary','Règles du jeu'),el('p',g?.kind==='douze'?window.ONEDouzeRules:g?.kind==='bluff'?window.ONEBluffRules:'Sept cartes chacun. Même couleur ou symbole pour jouer. La pioche ajoute une carte et termine le tour. ⊘ passe le joueur suivant ; +2 lance ou augmente la pénalité de deux cartes ; ⇄ inverse le sens (à deux, tu rejoues). ✦ permet de choisir la couleur. Les +2 se cumulent, même de couleurs différentes : ajoute un +2 ou pioche le total et passe ton tour. Le premier sans carte gagne immédiatement, même avec un +2 final. Un départ interrompt la partie.'));footer.append(rules,btn('↻ Actualiser',()=>load(true)));if(g&&data.isHost&&g.status==='playing'){const reset=btn(g.status==='playing'?'Arrêter la partie':'Retour au salon',()=>command('reset','',g.status==='playing'?'Arrêter la partie pour tous les joueurs ?':null));reset.disabled=busy;footer.append(reset);}body.append(footer);window.dispatchEvent(new Event('one-game-rendered'));
 }

 window.addEventListener('one-party-load-error',e=>{status.textContent=e.detail;});
 window.addEventListener('one-salon-visibility',()=>{if(!visible()&&full)fullscreen(false);mount();if(visible())load();});
 window.addEventListener('one-party-state',e=>{if(room?.id!==e.detail?.id){if(full)fullscreen(false);joker=null;lastHand=null;drawnUntil.clear();version++;data=null;body.replaceChildren();status.textContent='';busy=false;}room=e.detail;if(room){mount();load();}else{if(full)fullscreen(false);if(visible())mount();else panel.remove();}});window.addEventListener('one-space-open',e=>{if(e.detail!=='party'&&full)fullscreen(false);mount();if(visible())load();});window.addEventListener('one-account-changed',()=>{if(full)fullscreen(false);version++;room=null;data=null;panel.remove();});new MutationObserver(()=>{if(full&&document.getElementById('oneFoundation')?.hidden)fullscreen(false);}).observe(document.getElementById('oneFoundation'),{attributes:true,attributeFilter:['hidden']});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&full)fullscreen(false);});setInterval(()=>{if(!document.hidden&&!busy)load();},2000);if(visible()){mount();window.oneRefreshSalonState?.();}
})();
