(()=>{const layout=document.createElement('link');layout.rel='stylesheet';layout.href='ui/salons.css?v=01474';document.head.append(layout);
 const tray=document.createElement('aside');tray.id='oneSalonTray';tray.hidden=true;tray.setAttribute('aria-label','Salons ONE');const trayHead=document.createElement('header'),title=document.createElement('h2'),close=document.createElement('button');title.textContent='Salons ONE';close.textContent='×';close.type='button';close.setAttribute('aria-label','Réduire le salon');trayHead.append(title,close);const shell=document.createElement('div');shell.id='oneSalonBody';tray.append(trayHead,shell);document.body.append(tray);
 window.oneSalonContainer=shell;window.oneSalonIsOpen=()=>!tray.hidden;
 window.oneOpenSalon=()=>{tray.hidden=false;mount();window.dispatchEvent(new Event('one-salon-visibility'));};
 window.oneCloseSalon=()=>{tray.hidden=true;window.dispatchEvent(new Event('one-salon-visibility'));};close.onclick=window.oneCloseSalon;
 const entry=document.createElement('button');entry.type='button';entry.id='oneSalonsToggle';entry.setAttribute('aria-label','Salons');entry.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 10 12 3l9 7v10H3zM9 20v-7h6v7" fill="none" stroke="currentColor" stroke-width="1.7"/></svg><span>Salons</span>';entry.onclick=window.oneOpenSalon;document.getElementById('oneNotificationsToggle')?.before(entry);
 const API='https://one-comments-api.moulinanthony60.workers.dev';let revision=0,busy=false,host=null,content=null,status=null,pendingClose=false;
 const style=document.createElement('style');style.textContent='.onePartyControls{display:grid;gap:12px}.onePartyControls article{background:#15192b;border:1px solid #39334f;border-radius:14px;padding:14px}.onePartyControls input{box-sizing:border-box;max-width:100%;width:100%;padding:12px;border-radius:10px;background:#0b1020;color:white;border:1px solid #65517f;margin:8px 0}.onePartyControls button{padding:11px;margin:4px;border-radius:10px;border:1px solid #735396;color:white;background:#49306b;font:inherit}.onePartyControls button:disabled{opacity:.5}.onePartyControls p{overflow-wrap:anywhere}.onePartyControls ul{padding-left:20px}.onePartyControls label{display:block}.onePartyControls small{color:#b8afcc}';document.head.append(style);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 function active(){return !tray.hidden;}
 function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
 async function api(path,method='GET'){const token=oneAccountToken();const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(12000)});const data=await r.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé. Actualise Party.');if(!r.ok||!data.ok)throw Error(data.error||'Party momentanément indisponible.');return data;}
 async function command(path,confirmation){if(busy||confirmation&&!confirm(confirmation))return;busy=true;const node=host;node.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='En cours…';try{const result=await api(path,'POST');if(path==='/party/leave')window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));if(host===node&&active()){await load();status.textContent=path.startsWith('/party/invite')?(result.alreadyPending?'Invitation déjà en attente pour ':'Invitation envoyée à ')+(result.recipient||'ce membre')+'. Le destinataire peut ouvrir la cloche ou actualiser Party.':'Action enregistrée.';}window.dispatchEvent(new Event('one-notifications-refresh'));}catch(e){if(host===node&&active())status.textContent=e.message;}finally{busy=false;if(host===node)node.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 function confirmLeave(isHost){if(pendingClose||busy)return;pendingClose=true;const box=el('section');box.className='oneLeaveConfirm';box.setAttribute('role','alert');box.append(el('p',isHost?'Fermer le salon pour tous les membres ? La partie et les invitations seront terminées.':'Quitter ce salon ?'),button(isHost?'Confirmer la fermeture':'Confirmer mon départ',async()=>{await command('/party/leave');pendingClose=false;box.remove();}),button('Annuler',()=>{pendingClose=false;box.remove();}));content.prepend(box);box.scrollIntoView({block:'nearest'});}
 function mount(){pendingClose=false;if(!active())return;revision++;busy=false;shell.replaceChildren();shell.append(el('p','Ton salon reste ouvert pendant ta navigation dans ONE. Jusqu’à 4 membres.'));host=el('div');host.className='onePartyControls';status=el('p');status.setAttribute('role','status');content=el('div');host.append(button('Actualiser',()=>load()),button('Amis et mon QR code',()=>window.oneOpenFriends?.()),status,content);shell.append(host);load();}
 async function load(){if(!active())return;if(!host?.isConnected){mount();return;}const own=++revision,node=host;if(!oneAccountToken()){window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));content.replaceChildren(el('p','Connecte-toi à ton compte ONE pour créer un salon ou recevoir une invitation.'));status.textContent='';return;}try{const data=await api('/party/state');if(own!==revision||host!==node||!active())return;content.replaceChildren();status.textContent='';window.dispatchEvent(new CustomEvent('one-party-state',{detail:data.room}));
  if(data.room){const r=data.room,card=el('article');card.append(el('h2',r.name),el('p',r.members.length+'/4 membres inscrits au salon'));const members=el('ul');for(const m of r.members)members.append(el('li',m.name+(m.isYou?' (toi)':'')+(m.isHost?' · créateur':'')));card.append(members);
   if(r.isHost){const label=el('label','Code ONE du membre à inviter'),input=el('input');input.placeholder='ABCD-EFGH';input.maxLength=68;label.append(input);card.append(label,el('small','Utilise son code court dans Amis, ou invite-le directement depuis ta liste d’amis.'),button('Inviter',()=>command('/party/invite?recipient='+encodeURIComponent(input.value.trim()))));if(r.invitations.length){const sent=el('ul');for(const i of r.invitations)sent.append(el('li',i.recipient+' · '+(i.status==='accepted'?'acceptée':i.status==='declined'?'refusée':i.expiresAt<Date.now()?'expirée':'en attente')));card.append(el('h3','Invitations créées'),sent);}}
   card.append(button(r.isHost?'Fermer le salon':'Quitter le salon',()=>confirmLeave(r.isHost)));content.append(card);
  }else{const card=el('article'),label=el('label','Nom du salon'),input=el('input');input.maxLength=80;input.placeholder='Soirée jeux';label.append(input);card.append(label,button('Créer un salon',()=>command('/party/create?name='+encodeURIComponent(input.value.trim()))));content.append(card);}
  content.append(el('h2','Invitations reçues'));if(!data.invitations.length)content.append(el('p','Aucune invitation en attente.'));for(const invite of data.invitations){const card=el('article');card.append(el('b',invite.name),el('p','Invitation de '+invite.host),el('small','Expire le '+new Date(invite.expiresAt).toLocaleString('fr-FR')),button('Accepter',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/accept')),button('Refuser',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/decline','Refuser cette invitation ?')));content.append(card);}
 }catch(e){if(own===revision&&host===node&&active())status.textContent=e.message;}}
 window.oneRefreshSalonState=async()=>{if(active()){await load();return;}const token=oneAccountToken();if(!token){window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));return;}try{const data=await api('/party/state');if(token===oneAccountToken())window.dispatchEvent(new CustomEvent('one-party-state',{detail:data.room}));}catch(e){window.dispatchEvent(new CustomEvent('one-party-load-error',{detail:e.message}));}};
 window.addEventListener('one-space-open',e=>{if(e.detail==='party'){window.oneCloseSalon();window.oneRefreshSalonState();}});window.addEventListener('one-account-changed',()=>{revision++;if(active())mount();});window.addEventListener('one-party-refresh',()=>{if(active()&&!pendingClose)load();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&active()&&!busy&&!pendingClose)load();});setInterval(()=>{if(!document.hidden&&active()&&!busy&&!host?.querySelector('input:focus,textarea:focus'))load();},15000);if(active())mount();
})();
