(()=>{
 const names={bluff:'ONE Bluff',colors:'ONE Couleurs',douze:'ONE Douze',trio:'ONE Trio',codes:'ONE Codes',who:'ONE Qui est-ce ?',connect:'ONE Puissance 4',timer:'ONE Timer',mimevoice:'Mimic Party · Voix',mimegesture:'Mimic Party · Gestes',horror:'ONE Frisson',laugh:'ONE Marrant',blind:'ONE Blind test',wolf:'ONE Loups-garous'};
 for(const id of ['horror','laugh','blind','mimevoice','mimegesture'])delete names[id];
 let chosen='bluff',mode='',query='',filter='',available=true;
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
 function games(value,all=false){const select=el('select');if(all)select.append(new Option('Tous les jeux',''));for(const [id,name]of Object.entries(names))select.append(new Option(name,id));select.value=names[value]?value:(all?'':'bluff');return select;}
 function labelled(text,control){const label=el('label',text);label.append(control);return label;}
 function choices(parent,visibility,kind){const access=el('select');access.append(new Option('Privé · sur invitation','private'),new Option('Public · tout le monde peut rejoindre','public'));access.value=visibility;const game=games(kind);parent.append(labelled('Visibilité du salon',access),labelled('Jeu proposé',game),el('small','Un salon public affiche son nom, le pseudo du créateur et ses places dans la recherche.'));return ()=>new URLSearchParams({visibility:access.value,kind:game.value}).toString();}
 function open(kind,intent){chosen=kind;filter=kind;query='';mode=intent;window.oneOpenSalon?.();}
 window.ONEPublicRooms={
  creation(card){const get=choices(card,'private',chosen);if(mode==='create'){mode='';queueMicrotask(()=>card.scrollIntoView({block:'start'}));}return ()=>'&'+get();},
  settings(card,room,command){const details=el('details');details.className='onePublicSettings';details.append(el('summary','Modifier la visibilité et le jeu proposé'));const get=choices(details,room.visibility,room.gameKind);details.append(button('Enregistrer',()=>command('/party/public-settings?'+get())));card.append(details);},
  render(parent,{api,command,room}){
   const box=el('section');box.className='onePublicSearch';box.append(el('h2','Trouver une partie'));const form=el('form'),input=el('input');input.type='search';input.maxLength=80;input.placeholder='Nom du salon ou du créateur';input.value=query;const select=games(filter,true),check=el('input');check.type='checkbox';check.checked=available;
   const submit=el('button','Rechercher');submit.type='submit';form.append(labelled('Recherche',input),labelled('Jeu',select),labelled('Seulement les salons avec des places, sans partie en cours',check),submit);const result=el('div');result.setAttribute('aria-live','polite');box.append(form,result);parent.append(box);let serial=0;
   async function search(){const own=++serial;query=input.value;filter=select.value;available=check.checked;result.replaceChildren(el('p','Recherche des salons…'));submit.disabled=true;try{const data=await api('/party/public?'+new URLSearchParams({q:query,kind:filter,open:available?'1':'0'}));if(own!==serial||!box.isConnected)return;result.replaceChildren();if(!data.rooms.length)result.append(el('p','Aucun salon public ne correspond. Tu peux créer le tien ou élargir la recherche.'));for(const r of data.rooms){const item=el('article');item.append(el('h3',r.name),el('p',(names[r.kind]||'Jeux ONE')+' · '+r.count+'/'+r.capacity+' joueurs'),el('small','Créé par '+r.host));const state=r.playing?'Partie en cours':r.count>=r.capacity?'Complet':'Places disponibles';item.append(el('p',state));const join=button(room?.id===r.id?'Ton salon':'Rejoindre',async()=>{join.disabled=true;const ok=await command('/party/join-public?room='+encodeURIComponent(r.id));if(ok){window.oneCloseSalon?.();document.querySelector('[data-one-space="party"]')?.click();window.oneRefreshSalonState?.();}else{join.disabled=false;search();}});join.disabled=!!room||r.playing||r.count>=r.capacity;item.append(join);result.append(item);}if(room)result.append(el('p','Quitte ton salon actuel pour en rejoindre un autre.'));if(data.more)result.append(el('p','Les 50 premiers salons sont affichés. Précise ta recherche.'));}catch(e){if(own===serial&&box.isConnected)result.replaceChildren(el('p',e.message));}finally{if(own===serial)submit.disabled=false;}}
   form.onsubmit=e=>{e.preventDefault();search();};input.oninput=()=>query=input.value;select.onchange=()=>{filter=select.value;search();};check.onchange=search;search();if(mode==='join'){mode='';queueMicrotask(()=>box.scrollIntoView({block:'start'}));}
  },
  catalog(body){const lobby=el('section');lobby.className='pl-lobby';const header=el('header');header.className='pl-intro';header.append(el('span','LE SALON ONE'),el('h2','À quoi joue-t-on ?'),el('p','Choisis ton jeu, puis crée un salon ou rejoins une partie.'));const list=el('div');list.className='pl-games';const actions=el('section');actions.className='onePublicChoice';actions.hidden=true;
   for(const [id,name]of Object.entries(names)){const b=button('',()=>{for(const x of list.children)x.setAttribute('aria-pressed','false');b.setAttribute('aria-pressed','true');actions.hidden=false;actions.replaceChildren(el('h3',name),el('p','Comment veux-tu jouer ?'),button('Créer un salon',()=>open(id,'create')),button('Rejoindre un salon',()=>open(id,'join')));actions.scrollIntoView({block:'nearest'});});b.className='pl-game';b.setAttribute('aria-label',name);b.setAttribute('aria-pressed','false');const art=window.ONEGameArt?.(id);if(art)b.append(art);b.append(el('strong',name),el('span','Créer ou rejoindre'));list.append(b);}lobby.append(header,actions,list);body.append(lobby);}
 };
})();
