(()=>{
 const shell=document.getElementById('oneFoundation'),API='https://one-comments-api.moulinanthony60.workers.dev';let revision=0,busy=false,host=null,content=null,status=null;
 const style=document.createElement('style');style.textContent='.onePartyControls{display:grid;gap:12px}.onePartyControls article{background:#15192b;border:1px solid #39334f;border-radius:14px;padding:14px}.onePartyControls input{box-sizing:border-box;max-width:100%;width:100%;padding:12px;border-radius:10px;background:#0b1020;color:white;border:1px solid #65517f;margin:8px 0}.onePartyControls button{padding:11px;margin:4px;border-radius:10px;border:1px solid #735396;color:white;background:#49306b;font:inherit}.onePartyControls button:disabled{opacity:.5}.onePartyControls p{overflow-wrap:anywhere}.onePartyControls ul{padding-left:20px}.onePartyControls label{display:block}.onePartyControls small{color:#b8afcc}';document.head.append(style);
 const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
 function active(){return !shell.hidden&&document.querySelector('[data-one-space="party"]')?.getAttribute('aria-current')==='page';}
 function button(text,fn){const b=el('button',text);b.type='button';b.onclick=fn;return b;}
 async function api(path,method='GET'){const token=oneAccountToken();const r=await fetch(API+path,{method,headers:{Authorization:'Bearer '+token}});const data=await r.json().catch(()=>({}));if(token!==oneAccountToken())throw Error('Le compte a changé. Actualise Party.');if(!r.ok||!data.ok)throw Error(data.error||'Party momentanément indisponible.');return data;}
 async function command(path,confirmation){if(busy||confirmation&&!confirm(confirmation))return;busy=true;const node=host;node.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='En cours…';try{await api(path,'POST');if(path==='/party/leave')window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));if(host===node&&active()){await load();status.textContent='Action enregistrée.';}window.dispatchEvent(new Event('one-notifications-refresh'));}catch(e){if(host===node&&active())status.textContent=e.message;}finally{busy=false;if(host===node)node.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 function mount(){if(!active())return;revision++;busy=false;shell.replaceChildren();shell.append(el('h1','Party'),el('p','Prépare un groupe de quatre membres maximum. Les jeux seront ajoutés ensuite.'));host=el('div');host.className='onePartyControls';status=el('p');status.setAttribute('role','status');content=el('div');host.append(button('Actualiser',()=>load()),button('Amis et mon QR code',()=>window.oneOpenFriends?.()),status,content);shell.append(host);load();}
 async function load(){if(!active())return;if(!host?.isConnected){mount();return;}const own=++revision,node=host;if(!oneAccountToken()){window.dispatchEvent(new CustomEvent('one-party-state',{detail:null}));content.replaceChildren(el('p','Connecte-toi à ton compte ONE pour créer un salon ou recevoir une invitation.'));status.textContent='';return;}try{const data=await api('/party/state');if(own!==revision||host!==node||!active())return;content.replaceChildren();status.textContent='';window.dispatchEvent(new CustomEvent('one-party-state',{detail:data.room}));
  if(data.room){const r=data.room,card=el('article');card.append(el('h2',r.name),el('p',r.members.length+'/4 membres inscrits au salon'));const members=el('ul');for(const m of r.members)members.append(el('li',m.name+(m.isYou?' (toi)':'')+(m.isHost?' · créateur':'')));card.append(members);
   if(r.isHost){const label=el('label','Code ONE du membre à inviter'),input=el('input');input.placeholder='ABCD-EFGH';input.maxLength=68;label.append(input);card.append(label,el('small','Utilise son code court dans Amis, ou invite-le directement depuis ta liste d’amis.'),button('Inviter',()=>command('/party/invite?recipient='+encodeURIComponent(input.value.trim()))));if(r.invitations.length){const sent=el('ul');for(const i of r.invitations)sent.append(el('li',i.recipient+' · '+(i.status==='accepted'?'acceptée':i.status==='declined'?'refusée':i.expiresAt<Date.now()?'expirée':'en attente')));card.append(el('h3','Invitations créées'),sent);}}
   card.append(button(r.isHost?'Fermer le salon':'Quitter le salon',()=>command('/party/leave',r.isHost?'Fermer ce salon pour tous les membres et annuler ses invitations ?':'Quitter ce salon ?')));content.append(card);
  }else{const card=el('article'),label=el('label','Nom du salon'),input=el('input');input.maxLength=80;input.placeholder='Soirée jeux';label.append(input);card.append(label,button('Créer un salon',()=>command('/party/create?name='+encodeURIComponent(input.value.trim()))));content.append(card);}
  content.append(el('h2','Invitations reçues'));if(!data.invitations.length)content.append(el('p','Aucune invitation en attente.'));for(const invite of data.invitations){const card=el('article');card.append(el('b',invite.name),el('p','Invitation de '+invite.host),el('small','Expire le '+new Date(invite.expiresAt).toLocaleString('fr-FR')),button('Accepter',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/accept')),button('Refuser',()=>command('/party/invitations/'+encodeURIComponent(invite.id)+'/decline','Refuser cette invitation ?')));content.append(card);}
 }catch(e){if(own===revision&&host===node&&active())status.textContent=e.message;}}
 window.addEventListener('one-space-open',e=>{if(e.detail==='party')mount();else revision++;});window.addEventListener('one-account-changed',()=>{revision++;if(active())mount();});window.addEventListener('one-party-refresh',()=>{if(active())load();});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&active()&&!busy)load();});setInterval(()=>{if(!document.hidden&&active()&&!busy&&!host?.contains(document.activeElement))load();},15000);if(active())mount();
})();
