/* Shared presentation; existing API contracts are unchanged. */
(()=>{
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,cls='os-button')=>{const n=el('button',text,cls);n.type='button';n.onclick=fn;return n;};
 async function api(path,method='GET',body){const token=window.oneAccountToken?.();if(!token)throw Error('Connecte-toi à ONE pour continuer.');const r=await fetch('https://one-comments-api.moulinanthony60.workers.dev'+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const d=await r.json().catch(()=>({}));if(token!==window.oneAccountToken?.())throw Error('Le compte a changé.');if(!r.ok||!d.ok)throw Error(d.error||'Connexion indisponible. Réessaie.');return d;}
 function icon(kind){const src=document.querySelector('[data-one-space="'+kind+'"] .symbol svg')||document.querySelector('#chips [data-filter="'+kind+'"] svg');if(src)return src.cloneNode(true);return el('span',({one:'▶',together:'♧',party:'✦',youtube:'▶',tiktok:'♪',twitch:'▣',music:'♫'})[kind]||'✦','os-symbol');}
 function avatar(m){const a=el('span',(m.name||'ONE').trim().slice(0,2).toUpperCase(),'os-avatar');a.setAttribute('aria-hidden','true');if(typeof m.avatarUrl==='string'){try{const u=new URL(m.avatarUrl,location.href);if(u.protocol==='https:'){const i=el('img');i.src=u.href;i.alt='';i.loading='lazy';i.onerror=()=>i.remove();a.append(i);}}catch{}}return a;}
 function dialog(title){const d=el('dialog',undefined,'oneModDialog os-dialog'),h=el('header'),focus=document.activeElement;h.append(el('h2',title),button('×',()=>d.close(),'os-close'));h.lastChild.setAttribute('aria-label','Fermer');d.append(h);d.addEventListener('close',()=>{d.remove();if(focus?.isConnected)focus.focus();},{once:true});document.body.append(d);d.showModal();return d;}
 function qr(parent,value,label){try{const q=qrcode(0,'M');q.addData(value);q.make();const c=el('canvas',undefined,'os-qr'),size=q.getModuleCount(),scale=5;c.width=c.height=(size+8)*scale;c.setAttribute('role','img');c.setAttribute('aria-label',label);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#151027';for(let y=0;y<size;y++)for(let z=0;z<size;z++)if(q.isDark(y,z))x.fillRect((z+4)*scale,(y+4)*scale,scale,scale);parent.append(c);}catch{parent.append(el('p','QR indisponible. Utilise le lien à copier.'));}}
 async function copy(value,status){try{await navigator.clipboard.writeText(value);status.textContent='Copié.';}catch{status.textContent='À copier : '+value;}}
 function tile(kind,fn){const labels={one:['ONE','Vidéos & créations'],together:['Together','Regarder ensemble'],party:['Party','Jouer ensemble']};const b=button('',fn,'os-tile');b.dataset.kind=kind;b.append(icon(kind),el('b',labels[kind][0]),el('small',labels[kind][1]));return b;}
 const games=()=>[{id:'bluff',name:'ONE Bluff',min:2,max:4,category:'Cartes'},{id:'colors',name:'ONE Couleurs',min:2,max:4,category:'Cartes'},{id:'douze',name:'ONE Douze',min:2,max:4,category:'Cartes'},...Object.entries(window.ONEPartyCatalog||{}).filter(([id])=>!['horror','laugh','blind','mimevoice','mimegesture'].includes(id)).map(([id,g])=>({id,...g,category:['poker','trio'].includes(id)?'Cartes':'Ambiance'}))];
 // Fail closed: room-wide readiness is not consent to a particular activity.
 function activity(parent,{kind='party',game,room}={}){const box=el('section',undefined,'os-activity'),title=kind==='together'?'Together'+(game?' · '+game:''):(game?.name||'Une partie ONE');box.append(el('span','PARCOURS EN PRÉPARATION','os-eyebrow'),el('h3',title),el('p','Rejoindre une activité te rendra prêt pour celle-ci. Les autres membres resteront libres dans ONE.'),el('b','Minimum : '+(kind==='party'?(game?.min||2):2)+' participants'),el('p','Aucune acceptation enregistrée pour cette activité.','os-muted'));const roster=el('div',undefined,'os-participants');roster.setAttribute('aria-label','Participants ayant accepté');box.append(roster);const actions=el('div',undefined,'os-actions'),join=button('Rejoindre = prêt',null,'os-primary');join.disabled=true;actions.append(join);if(room?.isHost){const start=button('Lancer '+(kind==='party'?'la partie':'Together'),null,'os-primary');start.disabled=true;actions.append(start);}box.append(actions,el('p','Pas encore disponible : la sélection des participants doit être ajoutée au service des salons.','os-blocked'));parent.append(box);return box;}
 window.ONEUI={el,button,api,icon,avatar,dialog,qr,copy,tile,games,activity};
})();
