(()=>{
 'use strict';const {el,button,api}=ONEUI,root=window.ONEAccountUI?.alerts;if(!root)return;
 root.append(el('div','✦','hub-alert-art'),el('h3','ONE te prévient'),el('p','Amis, salons et créateurs : choisis les nouvelles qui comptent pour toi.','hub-muted'));
 const status=el('p',undefined,'hub-push-status');status.setAttribute('role','status');const enable=button('Activer sur ce téléphone',activate),disable=button('Désactiver sur cet appareil',deactivate),test=button('Envoyer une notification de test',testPush);enable.className='hub-primary hub-wide';const choices=el('div',undefined,'hub-alert-choices'),inputs={};
 for(const [key,title,desc]of [['friends','Amis et invitations','Demandes d’amis et invitations aux salons.'],['messages','Messages','Conversations privées et messages de tes salons.'],['creators','Tes créateurs','Nouvelles vidéos YouTube et débuts de live Twitch.']]){const label=el('label'),text=el('span'),input=el('input');input.type='checkbox';input.checked=true;input.setAttribute('aria-label',title);text.append(el('b',title),el('small',desc));label.append(text,input);choices.append(label);inputs[key]=input;input.onchange=saveSettings;}
 const details=el('p',undefined,'hub-muted');root.append(status,enable,disable,test,choices,details);let config=null,sub=null,busy=false,epoch=0,owner=window.oneAccountLocal?.()?.id,syncTimer=null,lastSyncKey='';
 const supported=()=>window.isSecureContext&&'Notification'in window&&'serviceWorker'in navigator&&'PushManager'in window;
 const fromBase64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));
 async function registration(){return Promise.race([navigator.serviceWorker.ready,new Promise((_,reject)=>setTimeout(()=>reject(Error('Recharge ONE pour terminer sa mise à jour.')),10000))]);}
 function paint(){enable.hidden=!!sub;disable.hidden=test.hidden=!sub;enable.disabled=busy||!config?.configured||!supported();disable.disabled=test.disabled=busy;for(const input of Object.values(inputs))input.disabled=busy||!config;}
 async function refresh(){const own=++epoch,token=window.oneAccountToken?.();if(!token){config=null;sub=null;status.textContent='Connecte-toi à ONE pour gérer tes notifications.';paint();return;}try{const next=await api('/push/config');if(own!==epoch)return;config=next;for(const [key,input]of Object.entries(inputs))input.checked=!!config.settings[key];sub=supported()?(await navigator.serviceWorker.getRegistration())?.pushManager?await(await navigator.serviceWorker.getRegistration()).pushManager.getSubscription():null:null;if(own!==epoch)return;if(sub){const check=await api('/push/status','POST',{endpoint:sub.endpoint});if(own!==epoch)return;if(!check.registered)sub=null;}
  status.textContent=!supported()?(/iPhone|iPad|iPod/.test(navigator.userAgent)?'Sur iPhone : ajoute ONE à l’écran d’accueil depuis Safari, puis ouvre ONE depuis son icône pour activer les notifications.':'Ce navigateur ne permet pas les notifications téléphone. Essaie une version récente de Chrome, Edge, Firefox ou Safari.') : Notification.permission==='denied'?'Notifications bloquées : autorise ONE dans les réglages du navigateur.':!config.configured?'L’activation des notifications téléphone attend la configuration du serveur ONE.':sub?'Notifications activées sur cet appareil.':'Active les notifications même quand tu quittes ONE.';
  details.textContent='YouTube : nouvelles vidéos. Twitch : '+(config.creators.twitch?'débuts de live.':'connexion serveur à configurer.')+' TikTok et créations ONE : alertes disponibles après raccordement de leurs services.';syncCreators().catch(()=>{});
 }catch(e){if(own===epoch)status.textContent=e.message;}finally{paint();}}
 async function activate(){if(busy||!config?.configured||!supported())return;busy=true;paint();const token=window.oneAccountToken?.();try{const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Tu pourras activer les notifications plus tard dans ces réglages.');const reg=await registration();sub=await reg.pushManager.getSubscription()||await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:fromBase64(config.publicKey)});if(token!==window.oneAccountToken?.()){await sub.unsubscribe();sub=null;return;}await api('/push/subscribe','POST',{subscription:sub.toJSON()});reg.active?.postMessage({type:'ONE_PUSH_ACCOUNT',accountId:window.oneAccountLocal?.()?.id||''});await syncCreators().catch(()=>{});status.textContent='Notifications activées sur cet appareil.';}catch(e){try{await sub?.unsubscribe();}catch{}sub=null;status.textContent=e.message;}finally{busy=false;paint();}}
 async function deactivate(){if(busy)return;busy=true;paint();try{await detach();status.textContent='Notifications désactivées sur cet appareil.';}catch(e){status.textContent=e.message;}finally{busy=false;paint();}}
 async function detach(){if(!('serviceWorker'in navigator))return;const reg=await navigator.serviceWorker.getRegistration();reg?.active?.postMessage({type:'ONE_PUSH_ACCOUNT',accountId:''});const existing=await reg?.pushManager?.getSubscription();if(existing){try{await api('/push/unsubscribe','POST',{endpoint:existing.endpoint});}finally{await existing.unsubscribe();sub=null;}}}
 async function testPush(){if(busy||!sub)return;busy=true;paint();try{await api('/push/test','POST',{endpoint:sub.endpoint});status.textContent='Test envoyé au téléphone. Vérifie ses notifications.';}catch(e){status.textContent=e.message;}finally{busy=false;paint();}}
 async function saveSettings(){try{await api('/push/settings','POST',Object.fromEntries(Object.entries(inputs).map(([k,input])=>[k,input.checked])));status.textContent='Tes préférences sont enregistrées.';if(inputs.creators.checked)await syncCreators();}catch(e){status.textContent=e.message;}}
 async function syncCreators(){if(!window.oneAccountToken?.()||!inputs.creators.checked)return;let creators=[];try{const keys=JSON.parse(localStorage.getItem('one_followed_creators_v18_1')||'[]'),meta=JSON.parse(localStorage.getItem('one_followed_creator_meta_v18_23')||'{}');creators=keys.map(k=>meta[k]).filter(Boolean).slice(0,100);}catch{}const key=window.oneAccountToken?.()+JSON.stringify(creators);if(key===lastSyncKey)return;await api('/social/creators/sync','POST',{creators});lastSyncKey=key;}
 window.addEventListener('one-followed-creators-changed',()=>{clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCreators().catch(()=>{}),800);});
 const logout=document.getElementById('oneLogout'),previous=logout?.onclick;if(logout)logout.onclick=async e=>{try{await detach();}catch{}return previous?.call(logout,e);};
 window.addEventListener('one-account-changed',async()=>{const token=window.oneAccountToken?.(),id=window.oneAccountLocal?.()?.id;if(owner!==id){epoch++;owner=id;lastSyncKey='';config=null;sub=null;if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();reg?.active?.postMessage({type:'ONE_PUSH_ACCOUNT',accountId:''});await(await reg?.pushManager?.getSubscription())?.unsubscribe();}}refresh();});
 window.ONEPush={refresh,detach};document.getElementById('accountBtn')?.addEventListener('click',refresh);refresh();
 navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='ONE_NOTIFICATION_OPEN')openAlert(e.data.url);});
 function openAlert(href){const url=new URL(href,location.href),kind=url.searchParams.get('one_alert'),thread=url.searchParams.get('thread');if(!kind)return;const modal=document.getElementById('accountModal');modal?.classList.remove('show');if(['creator_video','creator_live'].includes(kind)){if(thread){try{const external=new URL(thread);if(external.protocol==='https:'&&['www.youtube.com','www.twitch.tv'].includes(external.hostname))location.assign(external.href);}catch{}}}else if(kind==='message')window.oneOpenFriends?.(thread);else if(['group_message','group_saved'].includes(kind))window.oneOpenFriends?.('group:'+thread);else if(kind==='group_invite')window.oneOpenFriends?.({tab:'groups'});else if(kind==='friend')window.oneOpenFriends?.({tab:'invitations'});else document.getElementById('oneNotificationsToggle')?.click();}
 const initial=new URL(location.href);if(initial.searchParams.has('one_alert')){const href=initial.href;initial.searchParams.delete('one_alert');initial.searchParams.delete('thread');history.replaceState(history.state,'',initial);setTimeout(()=>openAlert(href),500);}
})();


