/* Frontend content preparation; no shared playback or publication is fabricated. */
(()=>{
 const {el,button,icon,avatar,dialog}=ONEUI;const previews=[];let selected=null,source='one',activeMedia=[];
 const sources=[['one','ONE'],['tiktok','TikTok'],['youtube','YouTube'],['twitch','Twitch'],['music','Musique']];
 function chooseNative(onChoose){const d=dialog('Choisir une création ONE');d.append(el('p','Créations locales de cette session. La publication du Feed ONE n’est pas encore reliée.','os-muted'));for(const item of previews){const b=button(item.title,()=>{d.close();onChoose(item);},'os-button os-wide');d.append(b);}const file=el('input');file.type='file';file.accept='video/*';file.setAttribute('aria-label','Prévisualiser une vidéo locale');const label=el('label','Ajouter une vidéo locale à prévisualiser');label.append(file);d.append(label);file.onchange=()=>{const f=file.files?.[0];if(!f)return;if(!f.type.startsWith('video/')){d.append(el('p','Choisis un fichier vidéo.'));return;}const item={id:crypto.randomUUID(),title:f.name,creator:'Toi',url:URL.createObjectURL(f),file:f,source:'one',local:true};previews.push(item);d.close();onChoose(item);};if(!previews.length)d.append(el('p','Aucune création disponible pour le moment.'));
 }
 function watch(item){selected=item;source=item.source;window.oneShowSpace?.('together');}
 function parseLink(value,kind){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('Utilise un lien HTTPS de la source sélectionnée.');let embed=null;
  if(kind==='youtube'){let id;if(u.hostname==='youtu.be')id=u.pathname.slice(1);else if(['youtube.com','www.youtube.com','m.youtube.com'].includes(u.hostname))id=u.searchParams.get('v')||u.pathname.match(/^\/(?:shorts|embed)\/([\w-]+)/)?.[1];if(!/^[\w-]{11}$/.test(id||''))throw Error('Lien YouTube non reconnu.');embed='https://www.youtube-nocookie.com/embed/'+id;}
  else if(kind==='twitch'){if(!['twitch.tv','www.twitch.tv','m.twitch.tv'].includes(u.hostname)||!/^\/[\w]{2,25}\/?$/.test(u.pathname))throw Error('Utilise le lien d’une chaîne Twitch.');embed='https://player.twitch.tv/?channel='+encodeURIComponent(u.pathname.replaceAll('/',''))+'&parent='+encodeURIComponent(location.hostname)+'&autoplay=false';}
  else if(kind==='tiktok'){if(!['tiktok.com','www.tiktok.com','m.tiktok.com','vm.tiktok.com','vt.tiktok.com'].includes(u.hostname))throw Error('Utilise un lien TikTok.');const id=u.pathname.match(/\/video\/(\d+)/)?.[1];if(id)embed='https://www.tiktok.com/player/v1/'+id;}
  return {id:crypto.randomUUID(),title:u.hostname+u.pathname,source:kind,url:u.href,embed,local:false};
 }
 function contentLink(){const d=dialog('Choisir le contenu'),label=el('label','Lien '+(sources.find(s=>s[0]===source)?.[1]||'')),input=el('input');input.type='url';input.placeholder='https://…';label.append(input);const status=el('p');status.setAttribute('role','status');d.append(label,button('Préparer ce contenu',()=>{try{selected=parseLink(input.value.trim(),source);d.close();const shell=document.getElementById('oneFoundation');renderTogether(shell);}catch(e){status.textContent=e.message;}},'os-primary'),status);}
 function choose(){if(source==='one')chooseNative(item=>{selected=item;renderTogether(document.getElementById('oneFoundation'));});else contentLink();}
 function renderPreview(parent,item){parent.replaceChildren();if(!item){parent.append(icon(source),el('h2','Choisis votre prochain moment'),el('p','Prépare une vidéo ou un lien à regarder ensemble.'));return;}if(item.local){const video=el('video');video.src=item.url;video.controls=true;video.playsInline=true;video.preload='metadata';video.setAttribute('aria-label',item.title);parent.append(video);activeMedia.push(video);}else if(item.embed){const frame=el('iframe');frame.src=item.embed;frame.title='Aperçu personnel · '+item.title;frame.allow='fullscreen; encrypted-media; picture-in-picture';frame.referrerPolicy='strict-origin-when-cross-origin';frame.allowFullscreen=true;parent.append(frame);activeMedia.push(frame);}else{parent.append(icon(item.source),el('h2','Lien sélectionné'),el('p','Ce contenu ne propose pas de lecteur intégré ici.'));const a=el('a','Ouvrir la source');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.className='os-button';parent.append(a);}}
 function stopPreview(){for(const node of activeMedia){if(node.tagName==='VIDEO')node.pause();else node.remove();}activeMedia=[];document.querySelectorAll('.os-watch-player video,.os-native-video').forEach(v=>v.pause());document.querySelectorAll('.os-watch-player iframe').forEach(f=>f.remove());}
 function roomMembers(target){window.dispatchEvent(new Event('one-salon-before-render'));target.replaceChildren();const room=window.oneSocialRoom?.();if(room){for(const m of room.members)target.append(ONEUI.player(m));}else target.append(button('Créer ou rejoindre un salon',()=>window.oneOpenSalon?.(),'os-primary'));window.dispatchEvent(new Event('one-salon-rendered'));}
 function renderTogether(shell){stopPreview();window.ONETogether.render(shell,selected);}
 function renderFeed(shell){stopPreview();shell.replaceChildren();const host=el('section');host.id='oneNativeFeed';host.setAttribute('aria-label','Publications ONE');shell.append(host);if(window.oneMountNativeFeed)window.oneMountNativeFeed(host);else host.textContent='Le fil se prépare. Réessaie dans un instant.';}
 document.getElementById('chips')?.addEventListener('click',stopPreview,true);window.ONEContent={renderTogether,renderFeed,watchWithSalon:watch,parseLink};
 
 window.addEventListener('one-space-open',e=>{if(e.detail!=='together'&&e.detail!=='one')stopPreview();});
 window.addEventListener('one-account-changed',()=>{stopPreview();for(const item of previews)URL.revokeObjectURL(item.url);previews.length=0;selected=null;source='one';if(window.oneCurrentSpace?.()==='together')renderTogether(document.getElementById('oneFoundation'));if(window.oneCurrentSpace?.()==='one')renderFeed(document.getElementById('oneFoundation'));});
 window.addEventListener('pagehide',()=>{stopPreview();for(const item of previews)URL.revokeObjectURL(item.url);});
})();



