(()=>{
 const {el,button,tile,icon,avatar,activity,games}=ONEUI;const css=el('link');css.rel='stylesheet';css.href='ui/social.css?v=014106';document.head.append(css);
 let room=window.oneSocialRoom?.()||null,filter='Tous',selected='bluff';
 const capsule=button('',()=>window.oneOpenSalon?.(),'os-capsule');capsule.hidden=true;capsule.id='oneRoomCapsule';document.querySelector('.topbar .brandrow').after(capsule);
 function syncRoom(){capsule.hidden=!room;capsule.replaceChildren();if(room){capsule.append(el('span','● Salon · '+room.members.length));const faces=el('span',undefined,'os-mini-avatars');room.members.slice(0,3).forEach(m=>faces.append(avatar(m)));capsule.append(faces);capsule.setAttribute('aria-label',room.name+', '+room.members.length+' membres. Ouvrir le salon.');}const banner=document.getElementById('oneRoomBanner');if(banner){banner.replaceChildren();banner.hidden=!room;if(room){banner.append(el('b','Toujours ensemble'),el('p','Tu es dans le salon « '+room.name+' ». Navigue librement avec ton groupe.'),button('Voir le salon',()=>window.oneOpenSalon?.()));}}}
 function home(shell){shell.replaceChildren();const hero=el('section',undefined,'os-home-hero');hero.append(el('span','À PLUSIEURS, PARTOUT DANS ONE','os-eyebrow'),el('h1','Les mêmes moments.\nEnsemble.'),el('p','Ton salon, tes amis et les contenus que vous aimez.'),button('Ouvrir les salons',()=>window.oneOpenSalon?.(),'os-primary'));shell.append(hero);const banner=el('section',undefined,'os-room-banner');banner.id='oneRoomBanner';shell.append(banner);const strip=el('div',undefined,'os-home-links');strip.append(button('♧ Amis ONE',()=>window.oneOpenFriends?.()),button('＋ Créer une vidéo',()=>window.openOneStudio?.()));shell.append(strip,el('p','UNE SEULE APPLICATION. TOUS VOS MOMENTS.','os-home-signature'));syncRoom();}
 function nativeFeed(shell){shell.replaceChildren();const h=el('div',undefined,'os-page-head');h.append(el('h1','Feed ONE'),button('＋ Créer',()=>window.openOneStudio?.(),'os-primary'));shell.append(h);const tabs=el('nav',undefined,'os-tabs');tabs.setAttribute('aria-label','Rubriques du Feed ONE');const empty=el('section',undefined,'os-feed-empty');for(const text of ['Pour toi','Abonnements','Découvrir']){const b=button(text,()=>{for(const c of tabs.children)c.setAttribute('aria-pressed',String(c===b));empty.querySelector('p').textContent=text==='Abonnements'?'Les créations des comptes que tu suivras apparaîtront ici.':'Les vidéos publiées dans ONE apparaîtront ici.';});b.setAttribute('aria-pressed',String(text==='Pour toi'));tabs.append(b);}empty.append(icon('one'),el('h2','Vos histoires commencent ici.'),el('p','Les vidéos publiées dans ONE apparaîtront ici.'),el('small','La publication du feed natif n’est pas encore disponible.'),button('Préparer une création',()=>window.openOneStudio?.(),'os-primary'));shell.append(tabs,empty);}
 function together(shell){shell.replaceChildren();shell.append(el('span','LE MÊME SALON, LES MÊMES MOMENTS','os-eyebrow'),el('h1','Together'));const cover=el('section',undefined,'os-together-cover');cover.append(icon('together'),el('h2','Regarder ensemble'),el('p','Retrouve ton groupe autour de vos contenus préférés.'));shell.append(cover);let source='YouTube';const platforms=el('div',undefined,'os-platforms'),proposal=el('div');for(const [id,name]of [['tiktok','TikTok'],['youtube','YouTube'],['twitch','Twitch'],['music','Musique']]){const b=button('',()=>{source=name;for(const x of platforms.children)x.setAttribute('aria-pressed',String(x===b));proposal.replaceChildren();activity(proposal,{kind:'together',game:source,room});});b.append(icon(id),el('span',name));b.setAttribute('aria-pressed',String(id==='youtube'));platforms.append(b);}shell.append(platforms);if(!room)shell.append(button('Créer ou rejoindre un salon',()=>window.oneOpenSalon?.(),'os-primary os-wide'));activity(proposal,{kind:'together',game:source,room});shell.append(proposal,button('Continuer à regarder librement',()=>document.querySelector('#chips [data-filter="'+({TikTok:'tiktok',YouTube:'youtube',Twitch:'twitch',Musique:'music'})[source]+'"]').click()));}
 function partyCatalog(parent,currentRoom=room){const box=el('section',undefined,'os-party-catalog');box.append(el('span','DES JEUX, UN SEUL GROUPE','os-eyebrow'),el('h2','Party'),el('p','Choisis ce que tu aimerais proposer à ton salon.','os-muted'));const tabs=el('nav',undefined,'os-tabs');tabs.setAttribute('aria-label','Catégories des jeux');const list=el('div',undefined,'os-game-grid'),detail=el('div');function select(){detail.replaceChildren();const game=games().find(g=>g.id===selected)||games()[0];detail.append(el('h3',game.name),el('p',game.desc||'Retrouve tes amis autour de la table.'));if(!currentRoom)detail.append(button('Créer ou rejoindre un salon',()=>window.oneOpenSalon?.(),'os-primary'));activity(detail,{game,room:currentRoom});}function draw(){list.replaceChildren();for(const g of games().filter(g=>filter==='Tous'||g.category===filter)){const b=button('',()=>{selected=g.id;draw();select();},'os-game-card');b.setAttribute('aria-pressed',String(g.id===selected));b.append(window.ONEGameArt(g.id),el('b',g.name),el('small',g.min+'–'+g.max+' joueurs'));list.append(b);}}for(const name of ['Tous','Cartes','Ambiance']){const b=button(name,()=>{filter=name;for(const t of tabs.children)t.setAttribute('aria-pressed',String(t===b));draw();});b.setAttribute('aria-pressed',String(filter===name));tabs.append(b);}box.append(tabs,list,detail);parent.append(box);draw();select();}
 // Only the pre-game lobby changes. Existing running-game renderers remain intact.
 window.renderONELobby=({body,room})=>partyCatalog(body,room);
 if(window.ONEPublicRooms)window.ONEPublicRooms.catalog=body=>partyCatalog(body,null);
 function render(space){document.body.dataset.oneSocialSpace=space||'';const shell=document.getElementById('oneFoundation');if(!shell||shell.hidden)return;if(space==='home')home(shell);if(space==='one')nativeFeed(shell);if(space==='together')together(shell);if(space==='social'){shell.replaceChildren(el('h1','Amis ONE'),button('Retrouver mes amis',()=>window.oneOpenFriends?.(),'os-primary'));}}
 window.addEventListener('one-space-open',e=>render(e.detail));window.addEventListener('one-party-state',e=>{room=e.detail;syncRoom();});window.addEventListener('one-account-changed',()=>{room=null;syncRoom();document.querySelectorAll('.os-dialog').forEach(d=>d.close());});render(window.oneCurrentSpace?.());syncRoom();
})();
