(()=>{
 'use strict';
 const {el,button,api,avatar}=ONEUI;
 const note=(parent,text)=>parent.append(el('p',text,'hub-muted'));
 function faceGroup(group){const box=el('span',undefined,'hub-faces');for(const m of group.members.filter(m=>m.status==='accepted').slice(0,3))box.append(avatar(m));if(!box.childNodes.length)box.append(el('span','♧'));return box;}
 function renderGroups(content,options){const {state,status,onMessage,onClose,isCurrent}=options;let busy=false;
  const intro=el('section',undefined,'hub-group-intro');intro.append(el('small','VOS RENDEZ-VOUS ONE'),el('h3','Un groupe. Toujours au même endroit.'),el('p','Retrouve tes amis, vos séances et votre conversation. Une seule invitation, puis chacun revient quand il veut.'));
  const actions=el('div',undefined,'hub-actions'),list=el('div',undefined,'hub-group-list');content.append(intro,actions,list);
  const create=button('＋ Nouveau salon',()=>editor());create.className='hub-primary';actions.append(create);
  const room=window.oneSocialRoom?.();if(room?.isHost&&!room.savedGroupId)actions.append(button('☆ Enregistrer le salon actuel',()=>editor(null,room)));
  async function run(path,body,done){if(busy)return;busy=true;status.textContent='Enregistrement…';try{const result=await api(path,'POST',body);if(!isCurrent())return;status.textContent='';await done?.(result);if(isCurrent())await load();window.dispatchEvent(new Event('one-notifications-refresh'));await window.oneRefreshSalonState?.(true);}catch(e){if(isCurrent())status.textContent=e.message;}finally{busy=false;}}
  async function load(){list.replaceChildren(el('p','Chargement des salons…','hub-muted'));try{const data=await api('/social/groups');if(!isCurrent())return;list.replaceChildren();if(!data.groups.length)note(list,'Aucun salon enregistré. Crée ton premier rendez-vous entre amis.');for(const g of data.groups){const card=el('article',undefined,'hub-group-card'),head=el('div',undefined,'hub-group-heading'),who=el('div');who.append(el('h3',g.name),el('small',g.status==='pending'?'Invitation à accepter une seule fois':g.activeCount?g.activeCount+' membre(s) dans le salon':'Prêt pour votre prochaine séance'));head.append(faceGroup(g),who);card.append(head,el('p',g.members.filter(m=>m.status==='accepted').map(m=>m.name).join(' · '),'hub-member-names'));
    const row=el('div',undefined,'hub-actions');if(g.status==='pending'){row.append(button('Accepter',()=>run('/social/groups/'+g.id+'/accept',null),'hub-primary'),button('Refuser',()=>run('/social/groups/'+g.id+'/decline',null)));}
    else{const join=button(g.activeCount?'Rejoindre':'Ouvrir le salon',()=>run('/social/groups/'+g.id+'/join',null,async()=>{await window.oneRefreshSalonState?.(true);onClose();window.oneOpenSalon?.();}));join.className='hub-primary';const messages=button('Messages'+(g.unread?' · '+g.unread:''),()=>onMessage(g.id));row.append(join,messages);const more=el('details',undefined,'hub-group-more');more.append(el('summary','Gérer le salon'));const tools=el('div',undefined,'hub-actions');if(g.isOwner){tools.append(button('Modifier / inviter',()=>editor(g)),button('Supprimer',()=>confirmRemove(g,true)));}else tools.append(button('Quitter ce groupe',()=>confirmRemove(g,false)));more.append(tools);card.append(more);}
    card.append(row);list.append(card);}
   }catch(e){if(isCurrent()){list.replaceChildren(el('p',e.message,'hub-muted'),button('Réessayer',load));}}}
  function confirmRemove(group,owner){const box=ONEUI.dialog(owner?'Supprimer ce salon enregistré ?':'Quitter ce groupe ?');note(box,owner?'Le salon, sa conversation et la séance en cours seront supprimés pour les membres.':'Tu perdras l’accès à ce salon enregistré et à sa conversation. Une nouvelle invitation sera nécessaire pour revenir.');const yes=button(owner?'Supprimer le salon':'Quitter le groupe',async()=>{yes.disabled=true;box.close();await run('/social/groups/'+group.id+'/'+(owner?'delete':'leave'));});box.append(yes,button('Annuler',()=>box.close()));}
  function editor(group=null,activeRoom=null){const form=el('form',undefined,'hub-group-editor'),title=el('h3',group?'Modifier '+group.name:activeRoom?'Conserver ce salon':'Créer un salon entre amis'),label=el('label','Nom du salon'),name=el('input');name.required=true;name.maxLength=80;name.value=group?.name||activeRoom?.name||'';name.placeholder='Les soirées du vendredi';label.append(name);form.append(title,label);const choices=el('div',undefined,'hub-friend-choices');
   if(activeRoom)note(form,'Les membres présents retrouveront ce salon dans Amis → Salons. Votre conversation sera conservée.');else{note(form,group?'Ajoute des amis : ils recevront une invitation unique.':'Sélectionne tes amis. Après acceptation, ils pourront revenir sans nouvelle invitation.');for(const friend of state.relationships.filter(f=>f.status==='accepted'&&!group?.members.some(m=>m.accountId===f.accountId))){const l=el('label',undefined,'hub-friend-choice'),c=el('input');c.type='checkbox';c.value=friend.accountId;l.append(c,avatar(friend),el('span',friend.name));choices.append(l);}form.append(choices);}
   const row=el('div',undefined,'hub-actions'),save=button(group?'Enregistrer':'Créer le salon'),cancel=button('Annuler',()=>form.remove());save.type='submit';save.className='hub-primary';row.append(save,cancel);const feedback=el('p');feedback.setAttribute('role','status');form.append(row,feedback);list.before(form);create.disabled=true;cancel.addEventListener('click',()=>create.disabled=false);name.focus();
   form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const members=[...choices.querySelectorAll('input:checked')].map(c=>c.value);if(members.length+(group?.members.length||1)>16){feedback.textContent='Maximum 16 membres par salon.';return;}save.disabled=true;try{if(group){await api('/social/groups/'+group.id+'/rename','POST',{name:name.value.trim()});for(const accountId of members)await api('/social/groups/'+group.id+'/invite','POST',{accountId});}else await api('/social/groups/create','POST',{name:name.value.trim(),members,...(activeRoom?{roomId:activeRoom.id}:{})});if(!isCurrent())return;form.remove();create.disabled=false;await load();await window.oneRefreshSalonState?.(true);window.dispatchEvent(new Event('one-notifications-refresh'));}catch(e){feedback.textContent=e.message;}finally{save.disabled=false;}};
  }
  load();
 }
 function renderConversation(content,thread,{isCurrent,onBack,drafts,status}){const group=thread.startsWith('group:'),id=thread.slice(thread.indexOf(':')+1),endpoint=group?'/social/groups/'+id+'/messages':'/party/chat?room='+encodeURIComponent(id),room=window.oneSocialRoom?.();let loading=false,signature='',pending=null,readThrough=0;
  content.append(button('← Toutes les conversations',onBack));const header=el('div',undefined,'hub-thread-heading'),title=el('h3',group?'Conversation du salon':room?.name||'Salon en cours');header.append(el('span','♧','hub-thread-symbol'),title);content.append(header);if(!group)note(content,'Messages du salon en cours. Enregistre le salon pour conserver la conversation.');
  const log=el('div',undefined,'friend-message-log hub-group-log');log.setAttribute('role','log');log.setAttribute('aria-label','Messages du salon');const form=el('form',undefined,'hub-compose'),input=el('textarea');input.rows=2;input.maxLength=1000;input.placeholder='Écrire au salon…';input.setAttribute('aria-label','Message au salon');input.value=drafts.get(thread)||'';const send=button('Envoyer');send.type='submit';send.className='hub-primary';form.append(input,send);content.append(log,form);input.oninput=()=>{drafts.set(thread,input.value);pending=null;};
  async function poll(){if(!isCurrent()||loading||document.hidden)return;loading=true;try{const result=await api(endpoint);if(!isCurrent())return;const key=JSON.stringify(result.messages);if(key!==signature){const near=log.scrollHeight-log.scrollTop-log.clientHeight<60;log.replaceChildren();for(const m of result.messages){const row=el('article',undefined,m.isYou?'mine':'theirs'),author=el('div',undefined,'hub-message-author');author.append(avatar({accountId:m.accountId,name:m.author,avatarUrl:m.avatarUrl}),el('small',(m.isYou?'Toi':m.author)+' · '+new Date(m.createdAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})));row.append(author,el('p',m.text));log.append(row);}if(!result.messages.length)note(log,'Votre conversation commence ici.');if(near||!signature)log.scrollTop=log.scrollHeight;signature=key;}const through=result.messages.at(-1)?.createdAt;if(group&&through>readThrough){await api('/social/groups/'+id+'/read?through='+through,'POST');readThrough=through;window.dispatchEvent(new Event('one-notifications-refresh'));}}catch(e){if(isCurrent())status.textContent=e.message;}finally{loading=false;}}
  form.onsubmit=async e=>{e.preventDefault();if(send.disabled||!input.value.trim())return;const draft=input.value;pending=pending?.text===draft.trim()?pending:{id:crypto.randomUUID(),text:draft.trim()};send.disabled=true;try{await api(endpoint,'POST',pending);if(!isCurrent())return;if(input.value===draft){input.value='';drafts.delete(thread);}pending=null;status.textContent='';await poll();}catch(e){if(isCurrent())status.textContent=e.message;}finally{send.disabled=false;}};
  if(group)api('/social/groups').then(data=>{if(isCurrent()){const g=data.groups.find(g=>g.id===id);if(g)title.textContent=g.name;}}).catch(()=>{});poll();return setInterval(poll,4000);
 }
 window.ONEHub={renderGroups,renderConversation,faceGroup};
})();
