/* Shared presentation; existing API contracts are unchanged. */
(()=>{
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,cls='os-button')=>{const n=el('button',text,cls);n.type='button';n.onclick=fn;return n;};
 async function api(path,method='GET',body){const token=window.oneAccountToken?.();if(!token)throw Error('Connecte-toi à ONE pour continuer.');const r=await fetch('https://one-comments-api.moulinanthony60.workers.dev'+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(12000)});const d=await r.json().catch(()=>({}));if(token!==window.oneAccountToken?.())throw Error('Le compte a changé.');if(!r.ok||!d.ok)throw Error(d.error||'Connexion indisponible. Réessaie.');return d;}
 function icon(kind){const src=document.querySelector('[data-one-space="'+kind+'"] .symbol svg')||document.querySelector('#chips [data-filter="'+kind+'"] svg');if(src)return src.cloneNode(true);return el('span',({one:'▶',together:'♧',party:'✦',youtube:'▶',tiktok:'♪',twitch:'▣',music:'♫'})[kind]||'✦','os-symbol');}
 function avatar(m){const a=el('span',undefined,'os-avatar');a.setAttribute('aria-hidden','true');const hue=[...(m.accountId||m.name||'ONE')].reduce((n,c)=>n+c.charCodeAt(0),0)%70;a.style.setProperty('--avatar-hue',hue+'deg');a.innerHTML='<svg viewBox="0 0 80 100" class="os-avatar-default"><defs><linearGradient id="av" x2="1" y2="1"><stop stop-color="#c9a5ff"/><stop offset="1" stop-color="#655deb"/></linearGradient></defs><circle cx="40" cy="32" r="17" fill="url(#av)"/><path d="M9 96V77a31 31 0 0 1 62 0v19Z" fill="url(#av)"/><path d="M29 28q11-14 22 0" stroke="#e8d8ff" stroke-width="2" fill="none"/></svg>';if(typeof m.avatarUrl==='string'){try{const u=new URL(m.avatarUrl,location.href);if(u.protocol==='https:'){const i=el('img');i.src=u.href;i.alt='';i.loading='lazy';i.onerror=()=>i.remove();a.append(i);}}catch{}}return a;}
 function dialog(title){const d=el('dialog',undefined,'oneModDialog os-dialog'),h=el('header'),focus=document.activeElement;h.append(el('h2',title),button('×',()=>d.close(),'os-close'));h.lastChild.setAttribute('aria-label','Fermer');d.append(h);d.addEventListener('close',()=>{d.remove();if(focus?.isConnected)focus.focus();},{once:true});document.body.append(d);d.showModal();return d;}
 function qr(parent,value,label){try{const q=qrcode(0,'M');q.addData(value);q.make();const c=el('canvas',undefined,'os-qr'),size=q.getModuleCount(),scale=5;c.width=c.height=(size+8)*scale;c.setAttribute('role','img');c.setAttribute('aria-label',label);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#151027';for(let y=0;y<size;y++)for(let z=0;z<size;z++)if(q.isDark(y,z))x.fillRect((z+4)*scale,(y+4)*scale,scale,scale);parent.append(c);}catch{parent.append(el('p','QR indisponible. Utilise le lien à copier.'));}}
 async function copy(value,status){try{await navigator.clipboard.writeText(value);status.textContent='Copié.';}catch{status.textContent='À copier : '+value;}}
 function tile(kind,fn){const labels={one:['ONE','Vidéos & créations'],together:['Together','Regarder ensemble'],party:['Party','Jouer ensemble']};const b=button('',fn,'os-tile');b.dataset.kind=kind;b.append(icon(kind),el('b',labels[kind][0]),el('small',labels[kind][1]));return b;}
 const games=()=>[{id:'bluff',name:'ONE Bluff',min:2,max:4,category:'Cartes'},{id:'colors',name:'ONE Couleurs',min:2,max:4,category:'Cartes'},{id:'douze',name:'ONE Douze',min:2,max:4,category:'Cartes'},...Object.entries(window.ONEPartyCatalog||{}).filter(([id])=>!['horror','laugh','blind','mimevoice','mimegesture'].includes(id)).map(([id,g])=>({id,...g,category:['poker','trio'].includes(id)?'Cartes':'Ambiance'}))];
 let draft=null,roomId=null;
 function clearDraft(){draft=null;window.dispatchEvent(new Event('one-activity-draft'));}
 window.addEventListener('one-account-changed',()=>{roomId=null;clearDraft();});
 window.addEventListener('one-party-state',e=>{const id=e.detail?.id||null;if(id!==roomId){roomId=id;clearDraft();}});
 function activity(parent,{game,room,kind='party'}={}){const box=el('section',undefined,'os-activity os-proposal');box.append(el('span','PROPOSITION LOCALE · NON ENVOYÉE','os-eyebrow'),el('h3',game?.name||'Together'),el('p','Proposé par 👑 '+(room?.members.find(m=>m.isHost)?.name||'l’hôte')),el('b','Minimum : '+(game?.min||2)+' joueurs'));const rows=el('div',undefined,'os-ready-list');for(const m of room?.members||[]){const row=el('div');row.append(avatar(m),el('b',(m.isHost?'👑 ':'')+m.name));if(m.isHost)row.append(el('small','Prêt à l’envoi*'));else{const ready=button('Prêt',null);ready.disabled=true;row.append(ready);}rows.append(row);}box.append(rows,el('p','0 acceptation confirmée · les autres membres restent libres dans ONE.','os-muted'));const launch=button('LANCER '+(game?.name||'TOGETHER').toUpperCase(),null,'os-primary os-wide');launch.disabled=true;box.append(launch,el('p','* À l’envoi, l’hôte sera automatiquement prêt. L’envoi, les réponses et le lancement attendent l’évolution du service. Aucun membre n’a été averti.','os-blocked'),button('Annuler cette préparation',clearDraft));parent.append(box);return box;}
 function propose(game){const room=window.oneSocialRoom?.(),token=window.oneAccountToken?.(),d=dialog(game.name);d.append(el('p',game.min+'–'+game.max+' joueurs'),el('h3','Proposer '+game.name+' à ton salon ?'));const note=el('p','Préparation locale uniquement : l’envoi aux membres n’est pas encore disponible.','os-muted');const send=button('Proposer au salon',()=>{const fresh=window.oneSocialRoom?.();if(!fresh?.isHost||fresh.id!==room?.id||token!==window.oneAccountToken?.()){note.textContent='Le salon ou le compte a changé.';return;}draft={roomId:fresh.id,game:{...game}};d.close();window.oneOpenSalon?.();window.dispatchEvent(new Event('one-activity-draft'));},'os-primary');send.disabled=!room?.isHost;d.append(note);if(!room)d.append(button('Créer ou rejoindre un salon',()=>{d.close();window.oneOpenSalon?.();}));else if(!room.isHost)d.append(el('p','Seul l’hôte peut proposer une activité.'));d.append(send,button('Annuler',()=>d.close()));}
 function player(m){const row=el('article',undefined,'os-member');row.dataset.member=m.isYou?'local':m.accountId;const face=el('div',undefined,'os-face');face.dataset.cameraSeat=row.dataset.member;face.append(avatar(m));const presence=el('span',undefined,'os-presence');presence.title='Membre du salon · présence instantanée non fournie';face.append(presence);const mic=el('span','🎤 —','os-member-mic');mic.setAttribute('aria-label','État micro inconnu');face.append(mic);if(m.isHost)face.append(el('span','👑','os-crown'));row.append(face,el('b',m.name),el('small',m.isHost?'Hôte · dans le salon':'Dans le salon'));return row;}
 function syncMedia(){for(const row of document.querySelectorAll('.os-member[data-member]')){const state=window.ONEPartyMedia?.memberStatus?.(row.dataset.member),mic=row.querySelector('.os-member-mic'),dot=row.querySelector('.os-presence');if(mic){mic.textContent=state?.mic===true?'🎤':state?.mic===false?'🔇':'🎤 —';mic.setAttribute('aria-label',state?.mic===true?'Micro actif':state?.mic===false?'Micro coupé':'État micro inconnu');}if(dot){dot.dataset.online=String(!!state?.connected);dot.title=state?.connected?'Dans l’appel':'Membre du salon · présence instantanée non fournie';}}}
 window.addEventListener('one-media-state',syncMedia);window.addEventListener('one-salon-rendered',syncMedia);
 window.ONEUI={el,button,api,icon,avatar,dialog,qr,copy,tile,games,activity,propose,player,syncMedia,activityDraft:()=>draft};
})();
