import * as THREE from './three.module.js';
let active=null; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function box(scene,x,y,z,w,h,d,color=0x242329){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.9}));m.position.set(x,y,z);scene.add(m);return m}
function open(){close();const shell=document.createElement('section');shell.className='three17-shell';shell.innerHTML=`<div class="three17-stage"><div class="three17-hud"><div class="three17-top"><div class="three17-clock">03:17</div><div class="three17-objective">🔒 SORTIE VERROUILLÉE<br><b>Éléments trouvés : <span data-count>0</span>/3</b></div></div><button class="three17-exit" type="button">← Lobby</button><div class="three17-cross"></div><div class="three17-stick"><div class="three17-knob"></div></div><div class="three17-look"></div><div class="three17-actions"><button class="three17-btn flash" type="button">🔦</button><button class="three17-btn interact" type="button">AGIR</button></div><div class="three17-msg"></div></div><div class="three17-start"><div class="three17-card"><h1>3:17 FOUR</h1><div class="time">03:17</div><p>Trouvez les 3 éléments et ouvrez la porte principale.</p><button type="button">ENTRER DANS LA MAISON</button></div></div><div class="three17-win"><div><h1>VOUS ÊTES SORTI</h1><p>Prototype 3:17 FOUR · objectif terminé</p><button class="three17-btn" type="button">OK</button></div></div></div>`;document.body.append(shell);
 const stage=shell.querySelector('.three17-stage'),scene=new THREE.Scene();scene.background=new THREE.Color(0x0d0d12);scene.fog=new THREE.Fog(0x0d0d12,11,28);const camera=new THREE.PerspectiveCamera(68,1,.05,45);let yaw=Math.PI,pitch=0,px=0,pz=6.8;
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,20),new THREE.MeshStandardMaterial({color:0x2b292d,roughness:1}));floor.rotation.x=-Math.PI/2;scene.add(floor);box(scene,0,1.5,-10,18,3,.25);box(scene,-9,1.5,0,.25,3,20);box(scene,9,1.5,0,.25,3,20);box(scene,0,1.5,10,18,3,.25);
 // Interior: corridor + rooms, with openings.
 [[-4.5,-4,9,.18],[4.5,-4,9,.18],[-4.5,3,9,.18],[4.5,3,9,.18],[-4.5,-.5,.18,7],[4.5,-.5,.18,7]].forEach(([x,z,w,d])=>box(scene,x,1.5,z,w,3,d,0x28272c));
 // furniture
 box(scene,-6.5,.45,-6.8,3,.9,1.1,0x353039);box(scene,6.3,.45,-6.4,2.6,.9,1.2,0x302c28);box(scene,-6,.7,5.8,2.5,1.4,1,0x29242a);box(scene,6,.45,5.8,2.8,.9,1.4,0x25272a);box(scene,0,3.05,0,18,.12,20,0x1b1a1e);box(scene,-6.8,.38,-1.4,2.8,.75,1.2,0x493e43);box(scene,6.5,.45,-1.7,2.5,.9,1.1,0x3d3833);box(scene,6.8,.95,6.9,1.8,1.9,.55,0x343038);
 scene.add(new THREE.HemisphereLight(0xaeb8d8,0x251d24,1.15));const moon=new THREE.DirectionalLight(0xb7c8ef,1.25);moon.position.set(2,6,3);scene.add(moon);const flashlight=new THREE.SpotLight(0xf3f6ff,65,18,.58,.55,1.15);const target=new THREE.Object3D();scene.add(flashlight,target);flashlight.target=target;const fillLight=new THREE.PointLight(0xdde8ff,3.5,5,1.7);scene.add(fillLight);let flashOn=true;
 const items=[];function item(x,z,label,color){const g=new THREE.Mesh(new THREE.BoxGeometry(.28,.28,.28),new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:1.2}));g.position.set(x,.45,z);g.userData={type:'item',label,taken:false};scene.add(g);items.push(g)}item(-6.8,-7.4,'Clé ancienne',0xd6b34a);item(6.8,-7.2,'Fusible',0x5db4ff);item(-6.5,6.8,'Sceau',0xb36cff);
 const exitDoor=box(scene,0,1.25,9.82,2.1,2.5,.28,0x332925);exitDoor.userData={type:'exit'};
 const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.35));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.65;stage.prepend(renderer.domElement);
 const keys={x:0,y:0};let drag=null,look=null,lx=0,ly=0,last=performance.now(),raf=0,count=0,msgTimer=0;const ray=new THREE.Raycaster();
 function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(stage);resize();
 function message(t){const m=shell.querySelector('.three17-msg');m.textContent=t;m.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>m.classList.remove('show'),1500)}
 function blocked(nx,nz){if(nx<-8.55||nx>8.55||nz<-9.5||nz>9.5)return true; // simplified room wall collisions
  if(Math.abs(nz+4)<.32 && Math.abs(nx)>1.15)return true;if(Math.abs(nz-3)<.32 && Math.abs(nx)>1.15)return true;if(Math.abs(nx+4.5)<.32 && nz>-3.7&&nz<2.7 && Math.abs(nz+.5)>1)return true;if(Math.abs(nx-4.5)<.32 && nz>-3.7&&nz<2.7 && Math.abs(nz+.5)>1)return true;return false}
 function interact(){ray.setFromCamera(new THREE.Vector2(0,0),camera);const hits=ray.intersectObjects([...items,exitDoor],false).filter(h=>h.distance<2.2);if(!hits.length){message('Rien à utiliser ici');return}const o=hits[0].object;if(o.userData.type==='item'&&!o.userData.taken){o.userData.taken=true;o.visible=false;count++;shell.querySelector('[data-count]').textContent=count;message('✓ '+o.userData.label+' récupéré');return}if(o.userData.type==='exit'){if(count<3)message(`Il manque ${3-count} élément${3-count>1?'s':''}`);else shell.querySelector('.three17-win').classList.add('show')}}
 function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;/* Le joystick utilise directement les axes REELS de la camera. Ainsi haut/bas/gauche/droite restent synchronises avec le regard, quelle que soit la rotation. */const forward=new THREE.Vector3();camera.getWorldDirection(forward);forward.y=0;if(forward.lengthSq()<.0001)forward.set(0,0,-1);forward.normalize();const right=new THREE.Vector3(-forward.z,0,forward.x);const forwardInput=-keys.y,strafeInput=keys.x,spd=2.5;const moveX=(forward.x*forwardInput+right.x*strafeInput)*spd*dt;const moveZ=(forward.z*forwardInput+right.z*strafeInput)*spd*dt;const nx=px+moveX,nz=pz+moveZ;if(!blocked(nx,pz))px=nx;if(!blocked(px,nz))pz=nz;camera.position.set(px,1.62,pz);flashlight.visible=flashOn;fillLight.visible=flashOn;flashlight.position.copy(camera.position);fillLight.position.copy(camera.position);const dir=new THREE.Vector3();camera.getWorldDirection(dir);target.position.copy(camera.position).add(dir.multiplyScalar(5));target.updateMatrixWorld();items.forEach(i=>{if(i.visible)i.rotation.y+=dt*1.6});renderer.render(scene,camera);raf=requestAnimationFrame(frame)}raf=requestAnimationFrame(frame);
 const stick=shell.querySelector('.three17-stick'),knob=shell.querySelector('.three17-knob');function sm(e){e.preventDefault();const b=stick.getBoundingClientRect(),dx=e.clientX-(b.left+b.width/2),dy=e.clientY-(b.top+b.height/2),d=Math.hypot(dx,dy)||1,m=Math.min(38,d),nx=dx/d,ny=dy/d;keys.x=nx*(m/38);keys.y=ny*(m/38);knob.style.transform=`translate(${nx*m}px,${ny*m}px)`}stick.addEventListener('pointerdown',e=>{e.preventDefault();drag=e.pointerId;try{stick.setPointerCapture(drag)}catch(_){}sm(e)},{passive:false});stick.addEventListener('pointermove',e=>{if(e.pointerId===drag)sm(e)},{passive:false});function se(e){if(e.pointerId!==drag)return;e.preventDefault();drag=null;keys.x=keys.y=0;knob.style.transform=''}stick.addEventListener('pointerup',se,{passive:false});stick.addEventListener('pointercancel',se,{passive:false});stick.addEventListener('lostpointercapture',()=>{drag=null;keys.x=keys.y=0;knob.style.transform=''})
 const lookz=shell.querySelector('.three17-look');lookz.addEventListener('pointerdown',e=>{look=e.pointerId;lx=e.clientX;ly=e.clientY;lookz.setPointerCapture(look)});lookz.addEventListener('pointermove',e=>{if(e.pointerId!==look)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=clamp(pitch-dy*.004,-.8,.7)});lookz.addEventListener('pointerup',e=>{if(e.pointerId===look)look=null});
 shell.querySelector('.interact').onclick=interact;shell.querySelector('.flash').onclick=()=>{flashOn=!flashOn;message(flashOn?'Lampe allumée':'Lampe éteinte')};shell.querySelector('.three17-exit').onclick=close;shell.querySelector('.three17-start button').onclick=()=>shell.querySelector('.three17-start').remove();shell.querySelector('.three17-win button').onclick=close;active={shell,renderer,ro,raf};
}
function close(){if(!active)return;cancelAnimationFrame(active.raf);active.ro.disconnect();active.renderer.dispose();active.shell.remove();active=null}window.ONEThree17={open,close};window.addEventListener('pagehide',close);
