import * as THREE from './three.module.js';
let active=null; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function box(scene,x,y,z,w,h,d,color=0x242329){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:.9}));m.position.set(x,y,z);scene.add(m);return m}
function open(){close();const shell=document.createElement('section');shell.className='three17-shell';shell.innerHTML=`<div class="three17-stage"><div class="three17-hud"><div class="three17-top"><div class="three17-clock">03:17</div><div class="three17-objective">🔒 SORTIE VERROUILLÉE<br><b>Éléments trouvés : <span data-count>0</span>/3</b><br><small data-floor>REZ-DE-CHAUSSÉE</small></div></div><button class="three17-exit" type="button">← Lobby</button><div class="three17-cross"></div><div class="three17-stick"><div class="three17-knob"></div></div><div class="three17-look"></div><div class="three17-actions"><button class="three17-btn flash" type="button">🔦</button><button class="three17-btn interact" type="button">AGIR</button></div><div class="three17-msg"></div></div><div class="three17-start"><div class="three17-card"><h1>3:17 FOUR</h1><div class="time">03:17</div><p>Explorez la maison, le sous-sol et l’étage.<br>Trouvez les 3 éléments.</p><button type="button">ENTRER DANS LA MAISON</button></div></div><div class="three17-win"><div><h1>VOUS ÊTES SORTI</h1><p>Prototype 3:17 FOUR · objectif terminé</p><button class="three17-btn" type="button">OK</button></div></div></div>`;document.body.append(shell);
 const stage=shell.querySelector('.three17-stage'),scene=new THREE.Scene();scene.background=new THREE.Color(0x0d0d12);scene.fog=new THREE.Fog(0x0d0d12,11,28);const camera=new THREE.PerspectiveCamera(68,1,.05,45);let yaw=Math.PI,pitch=0,px=0,pz=7.4,floorId=0; const floorY={0:0,1:3.35,'-1':-3.35},floorName={0:'REZ-DE-CHAUSSÉE',1:'ÉTAGE','-1':'SOUS-SOL'};
 const interactables=[],items=[];
 function slab(y,c=0x2b292d){box(scene,0,y-.08,0,18,.16,20,c);box(scene,0,y+3.05,0,18,.12,20,0x17171c)}
 function outer(y){box(scene,0,y+1.5,-10,18,3,.25);box(scene,-9,y+1.5,0,.25,3,20);box(scene,9,y+1.5,0,.25,3,20);box(scene,0,y+1.5,10,18,3,.25)}
 function door(x,y,z,rot=0,label='Porte'){const d=box(scene,x,y+1.25,z,2.15,2.5,.16,0x3a2d28);d.rotation.y=rot;d.userData={type:'door',label,open:false};interactables.push(d);return d}
 function stair(x,y,z,toFloor,toX,toZ,label){for(let i=0;i<7;i++)box(scene,x,y+.12+i*.12,z-i*.34,2.1,.24,.42,0x353239);const s=new THREE.Object3D();s.position.set(x,y+1,z);s.userData={type:'stairs',toFloor,toX,toZ,label};scene.add(s);interactables.push(s)}
 function item(x,y,z,label,color){const g=box(scene,x,y+.42,z,.3,.3,.3,color);g.material.emissive=new THREE.Color(color);g.material.emissiveIntensity=1.25;g.userData={type:'item',label,taken:false};items.push(g);interactables.push(g)}
 // RDC : salon, cuisine, salle à manger et couloir central
 slab(0);outer(0);box(scene,0,1.5,-3.7,7.6,3,.22);box(scene,-6.2,1.5,-3.7,5.6,3,.22);box(scene,6.2,1.5,-3.7,5.6,3,.22);box(scene,0,1.5,3.2,7.6,3,.22);box(scene,-6.2,1.5,3.2,5.6,3,.22);box(scene,6.2,1.5,3.2,5.6,3,.22);box(scene,-4.5,1.5,-.2,.22,3,4.5);box(scene,-4.5,1.5,2.4,.22,3,1.4);box(scene,4.5,1.5,-.2,.22,3,4.5);box(scene,4.5,1.5,2.4,.22,3,1.4);
 door(0,0,-3.7,0,'Porte du salon');door(-4.5,0,1.55,Math.PI/2,'Porte cuisine');door(4.5,0,1.55,Math.PI/2,'Porte salle à manger');
 box(scene,-6.5,.45,-6.7,3.5,.9,1.1,0x443840);box(scene,-5.8,.25,-5.2,1.8,.5,1,0x4c4038);box(scene,7.7,.5,-7.4,1.4,1,4,0x3d3a35);box(scene,5.8,.5,-5.8,2.8,1,1.15,0x49443c);box(scene,6.3,.42,6.3,3.4,.84,1.5,0x3d332e);box(scene,-6.5,.9,6.7,2.5,1.8,.65,0x302d31);
 const exitDoor=door(0,0,9.82,0,'Porte principale');exitDoor.userData.type='exit';stair(-2.2,0,7.0,1,-2.2,6.2,'Monter à l’étage');stair(2.3,0,7.0,-1,2.3,6.2,'Descendre au sous-sol');
 // ÉTAGE : couloir, trois chambres, salle de bain, débarras
 slab(3.35,0x26252a);outer(3.35);box(scene,0,4.85,0,.22,3,20);box(scene,-4.5,4.85,-3.2,9,3,.22);box(scene,-4.5,4.85,3.2,9,3,.22);box(scene,4.5,4.85,-3.2,9,3,.22);box(scene,4.5,4.85,3.2,9,3,.22);
 door(0,3.35,-5.8,Math.PI/2,'Chambre 1');door(-4.5,3.35,-3.2,0,'Chambre 2');door(-4.5,3.35,3.2,0,'Chambre 3');door(4.5,3.35,-3.2,0,'Salle de bain');door(4.5,3.35,3.2,0,'Débarras');box(scene,-6.6,3.72,-6.4,3.2,.72,3.8,0x413940);box(scene,6.6,3.68,-6.6,3.1,.65,1.45,0x686970);box(scene,-6.4,4.35,6.9,1.4,2,.7,0x2f2d32);box(scene,6.6,3.72,6.5,3.2,.72,3.7,0x3b353a);stair(-2.2,3.35,7.0,0,-2.2,6.2,'Redescendre au rez-de-chaussée');
 // SOUS-SOL : couloir béton, chaufferie, stockage et pièce condamnée
 slab(-3.35,0x202126);outer(-3.35);box(scene,-3.2,-1.85,0,.22,3,20);box(scene,3.2,-1.85,0,.22,3,20);box(scene,-6.1,-1.85,-2.4,5.8,3,.22);box(scene,-6.1,-1.85,2.8,5.8,3,.22);box(scene,6.1,-1.85,-2.4,5.8,3,.22);door(-3.2,-3.35,-5.5,Math.PI/2,'Chaufferie');door(3.2,-3.35,2.4,Math.PI/2,'Stockage');door(-6.1,-3.35,2.8,0,'Pièce condamnée');box(scene,-6.2,-2.55,-6.6,2.2,1.6,1.4,0x37383b);box(scene,6.2,-2.75,5.8,3.4,1.1,1.2,0x343238);box(scene,6.4,-2.35,-5.7,1.5,2,.8,0x2c2d30);stair(2.3,-3.35,7.0,0,2.3,6.2,'Remonter au rez-de-chaussée');
 item(-7,0,-7.4,'Clé ancienne',0xd6b34a);item(6.7,-3.35,-6.1,'Fusible',0x5db4ff);item(-6.5,3.35,6.7,'Sceau',0xb36cff);
 scene.add(new THREE.HemisphereLight(0xaeb8d8,0x251d24,1.15));const moon=new THREE.DirectionalLight(0xb7c8ef,1.25);moon.position.set(2,6,3);scene.add(moon);const flashlight=new THREE.SpotLight(0xf3f6ff,65,18,.58,.55,1.15);const target=new THREE.Object3D();scene.add(flashlight,target);flashlight.target=target;const fillLight=new THREE.PointLight(0xdde8ff,3.5,5,1.7);scene.add(fillLight);let flashOn=true;
 const renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance',alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.15));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.65;stage.prepend(renderer.domElement);
 const keys={x:0,y:0};let drag=null,look=null,lx=0,ly=0,last=performance.now(),raf=0,count=0,msgTimer=0,lastRender=0;const FRAME_MS=1000/45;const ray=new THREE.Raycaster();
 function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix()}const ro=new ResizeObserver(resize);ro.observe(stage);resize();
 function message(t){const m=shell.querySelector('.three17-msg');m.textContent=t;m.classList.add('show');clearTimeout(msgTimer);msgTimer=setTimeout(()=>m.classList.remove('show'),1500)}
 function blocked(nx,nz){if(nx<-8.55||nx>8.55||nz<-9.5||nz>9.5)return true; // simplified room wall collisions
  if(Math.abs(nz+4)<.32 && Math.abs(nx)>1.15)return true;if(Math.abs(nz-3)<.32 && Math.abs(nx)>1.15)return true;if(Math.abs(nx+4.5)<.32 && nz>-3.7&&nz<2.7 && Math.abs(nz+.5)>1)return true;if(Math.abs(nx-4.5)<.32 && nz>-3.7&&nz<2.7 && Math.abs(nz+.5)>1)return true;return false}
 function nearestInteractable(){let best=null,bd=2.4;for(const o of interactables){if(o.userData.taken)continue;const d=Math.hypot(o.position.x-px,o.position.z-pz),dy=Math.abs(o.position.y-(floorY[floorId]+1));if(d<bd&&dy<2){best=o;bd=d}}return best}
 function interact(){const o=nearestInteractable();if(!o){message('Rien à utiliser ici');return}const u=o.userData;if(u.type==='item'){u.taken=true;o.visible=false;count++;shell.querySelector('[data-count]').textContent=count;message('✓ '+u.label+' récupéré');return}if(u.type==='stairs'){floorId=u.toFloor;px=u.toX;pz=u.toZ;const f=shell.querySelector('[data-floor]');if(f)f.textContent=floorName[floorId];message(u.label);return}if(u.type==='door'){u.open=!u.open;o.visible=!u.open;message(u.open?'Porte ouverte':'Porte fermée');return}if(u.type==='exit'){if(count<3)message(`Il manque ${3-count} élément${3-count>1?'s':''}`);else shell.querySelector('.three17-win').classList.add('show')}}
 function frame(now){raf=requestAnimationFrame(frame);if(document.hidden||now-lastRender<FRAME_MS)return;lastRender=now;const dt=Math.min(.05,(now-last)/1000);last=now;camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;/* Le joystick utilise directement les axes REELS de la camera. Ainsi haut/bas/gauche/droite restent synchronises avec le regard, quelle que soit la rotation. */const forwardInput=-keys.y,strafeInput=keys.x,spd=2.5;/* Même formule que le joystick du lobby 3D validé sur mobile. */const sin=Math.sin(yaw),cos=Math.cos(yaw);const moveX=(-sin*forwardInput+cos*strafeInput)*spd*dt;const moveZ=(-cos*forwardInput-sin*strafeInput)*spd*dt;const nx=px+moveX,nz=pz+moveZ;if(!blocked(nx,pz))px=nx;if(!blocked(px,nz))pz=nz;camera.position.set(px,floorY[floorId]+1.62,pz);flashlight.visible=flashOn;fillLight.visible=flashOn;flashlight.position.copy(camera.position);fillLight.position.copy(camera.position);const dir=new THREE.Vector3();camera.getWorldDirection(dir);target.position.copy(camera.position).add(dir.multiplyScalar(5));target.updateMatrixWorld();items.forEach(i=>{if(i.visible)i.rotation.y+=dt*1.6});renderer.render(scene,camera);}raf=requestAnimationFrame(frame);
 const stick=shell.querySelector('.three17-stick'),knob=shell.querySelector('.three17-knob');function sm(e){const b=stick.getBoundingClientRect(),dx=e.clientX-(b.left+b.width/2),dy=e.clientY-(b.top+b.height/2),d=Math.hypot(dx,dy)||1,m=Math.min(38,d),nx=dx/d,ny=dy/d;keys.x=nx*(m/38);keys.y=ny*(m/38);knob.style.transform=`translate(${nx*m}px,${ny*m}px)`}stick.addEventListener('pointerdown',e=>{drag=e.pointerId;stick.setPointerCapture(drag);sm(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===drag)sm(e)});function se(e){if(e.pointerId!==drag)return;drag=null;keys.x=keys.y=0;knob.style.transform=''}stick.addEventListener('pointerup',se);stick.addEventListener('pointercancel',se)
 const lookz=shell.querySelector('.three17-look');lookz.addEventListener('pointerdown',e=>{look=e.pointerId;lx=e.clientX;ly=e.clientY;lookz.setPointerCapture(look)});lookz.addEventListener('pointermove',e=>{if(e.pointerId!==look)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=clamp(pitch-dy*.004,-.8,.7)});lookz.addEventListener('pointerup',e=>{if(e.pointerId===look)look=null});
 // V9 multitouch: actions fire on their OWN pointerdown, independently of joystick/camera pointers.
 const uiButtons=[...shell.querySelectorAll('button')];uiButtons.forEach(btn=>{btn.style.touchAction='manipulation';btn.addEventListener('pointerdown',e=>e.stopPropagation());btn.addEventListener('pointerup',e=>e.stopPropagation());});
 function press(el,fn){el.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();fn(e)},{passive:false})}
 press(shell.querySelector('.interact'),()=>interact());
 press(shell.querySelector('.flash'),()=>{flashOn=!flashOn;message(flashOn?'Lampe allumée':'Lampe éteinte')});
 press(shell.querySelector('.three17-exit'),()=>close());
 press(shell.querySelector('.three17-start button'),()=>shell.querySelector('.three17-start')?.remove());
 press(shell.querySelector('.three17-win button'),()=>close());active={shell,renderer,ro,raf};
}
function close(){if(!active)return;cancelAnimationFrame(active.raf);active.ro.disconnect();active.renderer.dispose();active.shell.remove();active=null}window.ONEThree17={open,close};window.addEventListener('pagehide',close);
