(()=>{
 const feed=document.getElementById('vfeed'),exit=document.getElementById('closeVFeed');let minimized=false,drag=null,native=false;function clearHistory(){if(history.state?.oneTikTokView){const s={...history.state};delete s.oneTikTokView;history.replaceState(s,'');}}
 const bar=document.createElement('div');bar.id='oneTikTokMiniBar';bar.hidden=true;bar.innerHTML='<span>⠿ TikTok</span><button aria-label="Agrandir TikTok">⛶</button><button aria-label="Fermer TikTok">×</button>';document.body.appendChild(bar);
 function layout(){const r=feed.getBoundingClientRect();bar.style.cssText='left:'+r.left+'px;top:'+Math.max(0,r.top-32)+'px;width:'+r.width+'px';}
 function reset(){clearHistory();minimized=false;feed.classList.remove('oneTikTokMini');for(const key of ['--tt-width','--tt-height','--tt-left','--tt-top','--tt-scale'])feed.style.removeProperty(key);bar.hidden=true;}
 function shrink(){if(minimized||verticalFeedMode!=='tiktok'||!feed.classList.contains('show'))return;const r=feed.getBoundingClientRect(),scale=Math.min(190/r.width,(innerHeight-150)/r.height,.6);v17Observer?.disconnect();feed.style.setProperty('--tt-width',r.width+'px');feed.style.setProperty('--tt-height',r.height+'px');feed.style.setProperty('--tt-scale',scale);feed.style.setProperty('--tt-left',Math.max(0,innerWidth-r.width*scale-12)+'px');feed.style.setProperty('--tt-top',Math.max(34,innerHeight-r.height*scale-85)+'px');clearHistory();minimized=true;feed.classList.add('oneTikTokMini');document.body.style.overflow='';bar.hidden=false;layout();}
 const previous=exit.onclick;exit.onclick=e=>{if(verticalFeedMode==='tiktok'&&!minimized){shrink();return;}reset();previous?.call(exit,e);};
 const buttons=bar.querySelectorAll('button');buttons[0].onclick=()=>{const active=document.querySelector('.vslide[data-active="1"]');reset();document.body.style.overflow='hidden';if(active)document.getElementById('vfeedScroller').scrollTop=active.offsetTop;v17SetupObserver();history.pushState({...history.state,oneTikTokView:true},'');};buttons[1].onclick=e=>{reset();previous?.call(exit,e);};
 bar.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;const r=feed.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};bar.setPointerCapture(e.pointerId);e.preventDefault();});bar.addEventListener('pointermove',e=>{if(!drag)return;const r=feed.getBoundingClientRect();feed.style.setProperty('--tt-left',Math.max(0,Math.min(innerWidth-r.width,e.clientX-drag.x))+'px');feed.style.setProperty('--tt-top',Math.max(32,Math.min(innerHeight-r.height,e.clientY-drag.y))+'px');layout();});for(const name of ['pointerup','pointercancel','lostpointercapture'])bar.addEventListener(name,()=>drag=null);
 new MutationObserver(()=>{if(minimized&&!feed.classList.contains('show'))reset();}).observe(feed,{attributes:true,attributeFilter:['class']});
 const open=openVerticalFeed;openVerticalFeed=function(mode){const result=open.apply(this,arguments);if(verticalFeedMode==='tiktok')history.pushState({...history.state,oneTikTokView:true},'');return result;};window.addEventListener('popstate',e=>{if(feed.classList.contains('show')&&verticalFeedMode==='tiktok'&&!minimized){e.stopImmediatePropagation();shrink();}},true);
document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement){native=verticalFeedMode==='tiktok'&&feed.classList.contains('show');return;}if(native){native=false;shrink();}});
})();
