(()=>{
 let media=null,login='',expanded=false,native=false,drag=null;
 const bar=document.createElement('div');bar.id='oneTwMiniBar';bar.hidden=true;bar.innerHTML='<span>⠿ Live Twitch</span><button type="button" aria-label="Agrandir le live">⛶</button><button type="button" aria-label="Fermer le live">×</button>';document.body.appendChild(bar);
 function layout(){if(!media)return;const r=media.getBoundingClientRect();bar.style.left=r.left+'px';bar.style.top=(r.top-34)+'px';bar.style.width=r.width+'px';}
 function mini(){if(!media?.isConnected)return;media.closest('.card,.oneChannelHub,.vfeed')?.classList.add('oneTwMiniHost');expanded=false;media.classList.add('oneTwMini');document.getElementById('oneChatClose').click();document.dispatchEvent(new Event('oneExitLiveView'));media.classList.remove('oneLandscapeMedia');bar.hidden=false;layout();window.oneResumeTwitchView?.(media);}
 function clear(){if(!media)return;media.closest('.card,.oneChannelHub,.vfeed')?.classList.remove('oneTwMiniHost');media.classList.remove('oneTwMini');media.style.removeProperty('--mini-left');media.style.removeProperty('--mini-top');bar.hidden=true;}
 const original=window.oneOpenChat;window.oneOpenChat=(channel,preferred)=>{if(media?.classList.contains('oneTwMini'))clear();original(channel,preferred);media=document.querySelector('.oneSplitMedia');if(!media)return;login=channel;expanded=true;};
 document.getElementById('oneExitLiveView').addEventListener('click',e=>{const current=document.querySelector('.oneSplitMedia,.oneLandscapeMedia');if(!current)return;try{const u=new URL(current.querySelector('iframe')?.src);if(u.hostname!=='player.twitch.tv')return;login=u.searchParams.get('channel')||login;}catch{return;}media=current;e.stopImmediatePropagation();mini();},true);
 const buttons=bar.querySelectorAll('button');buttons[0].onclick=()=>{const m=media;clear();window.oneOpenChat(login,m);};buttons[1].onclick=()=>{if(media)media.dataset.oneMiniClosed='1';try{window.oneGetTwitchPlayer?.(media)?.pause();window.oneGetTwitchPlayer?.(media)?.setMuted(true);}catch{}clear();media=null;expanded=false;};
 bar.addEventListener('pointerdown',e=>{if(e.target.closest('button')||!media)return;const r=media.getBoundingClientRect();drag={x:e.clientX-r.left,y:e.clientY-r.top};bar.setPointerCapture(e.pointerId);e.preventDefault();});bar.addEventListener('pointermove',e=>{if(!drag||!media)return;const r=media.getBoundingClientRect();media.style.setProperty('--mini-left',Math.max(0,Math.min(innerWidth-r.width,e.clientX-drag.x))+'px');media.style.setProperty('--mini-top',Math.max(34,Math.min(innerHeight-r.height,e.clientY-drag.y))+'px');layout();});for(const evt of ['pointerup','pointercancel','lostpointercapture'])bar.addEventListener(evt,()=>drag=null);window.addEventListener('resize',layout);document.getElementById('oneChatClose').addEventListener('click',()=>{if(!media?.classList.contains('oneTwMini'))expanded=false;});
})();
